### ISSUE TITLE
[RA2] Ch1 - Cloud Native Principle -- Highlight make high-impact changes frequently and predictably

### ISSUE THREAD

**Issue by nickolaev** [cntt-n/CNTT#1004]
I think a really important one was omitted here. Namely "make high-impact changes frequently". That is a crucial change to the overall lifecycle management model we have today in the NFV. Being able to have reliable CI/CD pipelines, well-defined staging environments and robust deployment models (A/B, Blue-green, Canary) is a gamechanger for the next-gen NFV implementations.

**Comment by CsatariGergely** [comment]
We use the CNCF Cloud Native definition as a basis and this is not mentioned there...

**Comment by nickolaev** [comment]
Second paragraph, second sentence [here](https://github.com/cncf/toc/blob/master/DEFINITION.md) reads:
 _Combined with robust automation, they allow engineers to **make high-impact changes frequently** and predictably with minimal toil._

**Comment by peterwoerndle** [comment]
I agree with @CsatariGergely to keep using the CNCF Cloud Native definition and complement it with the CNCF TUG definition for a Cloud Native Network Function. This ensures that we keep in sync with the larger community in CNCF.

**Comment by nickolaev** [comment]
There is some misunderstanding here. Let me try to clarify.
What is quoted in [1.3.1 Cloud Native Principles](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter01.md#131-cloud-native-principles) is an exact copy of [CNCF Cloud Native Definition v1.0](https://github.com/cncf/toc/blob/master/DEFINITION.md) and it clearly states:
"_... they allow engineers to make high-impact changes frequently and predictably ..._". This almost directly translates to having CI/CD practices and implementing various deployment strategies.

**Comment by xmulligan** [comment]
@nickolaev the cloud native definition already lists it and is included. do you have a PR of how you would like to highlight it?

**Comment by tomkivlin** [comment]
@nickolaev - are you talking about updating the bullets in [rows 55-68](https://github.com/cntt-n/CNTT/blame/master/doc/ref_arch/kubernetes/chapters/chapter01.md#L55-L68)?  I need to do an update to this chapter anyway following the TUG whitepaper changing to GitHub so could incorporate if you agree.

**Comment by nickolaev** [comment]
@tomkivlin yes, the bullets are the first place to be updated. Then, of course, this should flow through the document in the relevant sections. I would imagine that the major part to implement this requirement is in the CNF itself, yet I believe the infrastructure should provide means to implement CI/CD, various deployment models etc.
One of the impacts here may be in 4.7, as the service meshes are generally considered one of the enablers of the deployment models.
