### ISSUE TITLE
[RM] Define backward compatibility policy/strategy for CNTT

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#1008]
In discussions on the exceptions framework and how it would be implemented in practice, the topic of backwards compatibility came up.  Assumptions were being made about its use, but it is not explicitly documented or addressed in the RM or at a Governance or Technical Steering level.

This issue is to create a proposal on what the backward compatibility strategy is for CNTT.  Once agreed to in the RM level, the proposal will be presented to the Tech Steering (and governance) levels if necessary for ratification.  

This issue is also related to issue #1009 about backward compatibility strategy.

**Comment by kedmison** [comment]
When looking at a compatibility strategy, one should look at the interface(s) being considered and the 'perspective' of the interface; that is, the consumer or provider of the interface, and if there is a perspective on which of consumer or provider would be migrating first.

From a CNTT perspective, a backwards compatibility policy should apply to the NFVI; that is, a NFVI of version 'x' should be compatible the interfaces provided by NFVI version x-1 (up to some agreed-upon number of previous versions)

As a starting point for discussion, I think we should consider that this covers 
- the NFVI interfaces (explicit and implied) that are used by VNFs
Are there others that should be covered here?

Explicit interfaces are intended to refer to the actual APIs that are provided.
Implicit interfaces are intended to refer to configuration or convention that, while it may not be a formal part of an explicit API, is necessary for getting consistent behavior from an explicit API.  This includes definitions of objects, tags and the like that may be used as parameters for explicit APIs.

Do others have comments or perspectives on this definition and scope prior to working on a PR to contribute a change for this?

**Comment by kedmison** [comment]
Additional thoughts: 
- This would touch installation and lifecycle management, in that the NFVI would need to be capable of deploying, healing, and managing resources supporting workloads defined by CNTT version n-1, until such time as there are no deployed VNFs requiring services from CNTT spec version n-1.

**Comment by kedmison** [comment]
This comment contains the proposed text that will be sent to TSC/Gov on the topic of backward compatibility.  Comments are welcome, and I will edit this text to reflect the comments that are made.



### Problem statement: What backwards compatibility do we need to see?
* Current direction is to release a new RM/RA/RI/RC lineup, and have VNFs and NFVI certified against that.  
* This does not account for the fact that NFVI often has to be updated while maintaining support for already-deployed VNFs.
* A newly upgraded NFVI is thus in the situation of needing to support VNFs that are compliant to the current version of the CNTT specifications, as well as the previous version of CNTT specifications.
* Profiles may change between releases.  The exceptions framework that has been defined clearly illustrates the need to revise the profile specifications over time (in this case, in order to move away from the use of an exception technology to a preferred alternative)
* Addressing this drives requirements through the entire CNTT suite, touching RM, RA, RI, RC and so should therefore be considered by TSC or Gov.   Examples include: 
  * NFVI release 'n' needing to provision additional hosts to support a VNF compliant to Release 'n-1'
  * NFVI release 'n' needing to deploy Release 'n-1' workloads only on hosts supporting Release 'n-1'
  * NFVI release 'n' needing to deploy Release 'n' workloads only to hosts supporting Release 'n'

### Ask of TSC/Gov: Please provide guidance on backwards compatibility story, in the following areas:
  * Should a backwards compatibility policy be stated at the RM level and flowed through to the RA/RI/RC documents?
  * what interfaces should be documented by the backwards compatibility policy?
    * NFVI-VNF interface (Vn-Nf) (this would include the workload profile definitions)
    * NFVI-VNFM interface (Vi-Vnfm)
  * how many releases back should the backwards compatibility policy apply, by default?

From this, the RM workstream will:
* Document backwards-compatibility requirements
* Determine how to differentiate the profile definitions of Release 'n' from those of Release 'n+1'
* Trigger discussions with RA/RI/RC as needed

**Comment by pgoyal01** [comment]
@kedmison Thanks for capturing the need for the policy. May I suggest that instead of NFVI we consider use cases at a more granular level. For example,
1. Support for multi-generations of physical infrastructure.
    - Even within the same Data Center, multi-generations of hardware may exist. This can happen because of augments and/or hardware refresh cycles
    - The implication of introducing new server types, for example, is that host profiles may have to be added and changes to host aggregates made. While the removing of server types may be the deletion of host profiles.
      - Depending upon the nature of the new server types introduced, the impacts can be to the interfaces Vi-Ha, Vn-Nf and Nf-Vi ([RM 6.2 NFVI APIs](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter06.md#62-nfvi-apis))
    - Depending upon the nature of how flavors (RA-1) have been defined, new flavors may have to be introduced. If an operator chooses not to specify flavors but uses parameters to create instances these instance create calls may or may not get affected.

2. Introduction of new Orchestration & Management Service (for example, a new OpenStack release):
    - When introducing a new CNTT OpenStack release, it is incumbent upon CNTT to identify impacts
    - Some changes may require actions similar to those listed above.
    - In other cases, as listed in the OpenStack ensuring [API Interoperability](https://specs.openstack.org/openstack/api-wg/guidelines/api_interoperability.html) document, incompatibilities will result
    - Some changes can be accommodated by VNF Guidelines; for example, VNF support for listed versions of OpenStack.

Critique?

**Comment by kedmison** [comment]
@pgoyal01 Thanks for the thoughtful comments.  

I had considered the NFVI/VNF boundary as one of the interfaces at which a backwards compatibility commitment was being considered.  A decision about backwards compatibility at one of these interfaces winds up cascading into several areas, including some of the ones you have highlighted (e.g. host profiles).  It is good to highlight this as a related factor.

I'll update the above comment with this.

As for item 2: This is a very good point; there may be some dependencies/incompatibilities that are outside of our control, or that merit highlighting and contrasting compared to previous release.  Do you think this needs to be expressed in the 'ask' to TSC, or can we identify this as a work item in RM?

**Comment by pgoyal01** [comment]
@kedmison "... or can we identify this as a work item in RM" -- We can identify it as work items in RM and RAs. Should the TSC be aware of this though?

**Comment by kedmison** [comment]
@pgoyal01 Fair point; I was thinking the RM/RAs had some autonomy on deciding their work items, but since we are identifying related work items, it makes sense to include that in the set.

**Comment by kedmison** [comment]
apparently if I do the assignments too fast it unassigns people...

**Comment by ASawwaf** [comment]
@pgoyal01 thanks for ur comments, I like it :)

regarding point Support for multi-generations of physical infrastructure. , I totally agree and there is no harm to have multiple CPU , HW configuration, under same NFVi 

So actually there is no backward compatibility, we just need to highlight what @pgoyal01  mention only expansion here that if we SRIOV, the VNF itself required to develop any new drivers in case of new NIC is adopted 

for 2nd point regarding API ( Vi-Ha, Vn-Nf and Nf-Vi ) , I need to highlight that as per ETSI NFV architecture there is a difference between 
1- Main NFV reference point ( Or-Vi , Or-Vnfm,vi-vnfm ,..) , interfaces between main building block and there is IFA and SOL for each those interfaces ( which cover information and solution / API specification ) 
2 - Execution reference point (Vi-Ha, Vn-Nf and Nf-Vi ) , from the name it execution interfaces which consume ( compute, network and storage ) , there is no IFA or SOL for this ref.point 

if we see on ETSI Release evolution, we will find that for Main NFV reference point, there is always updates Harding the IFA/SOL But for an Execution reference point (Vi-Ha, Vn-Nf and Nf-Vi ) there is bo update the draft is fressed since 2015/2016 

Fact  is no change over (Vi-Ha, Vn-Nf and Nf-Vi ) , So i believe there is no backward compatibility for this API

The 3rd point, I believe we should cover OS backward compatibility as discussed in other issue# xx

@kedmison @pgoyal01 @rabi-abdel does it make sense ?

**Comment by rabi-abdel** [comment]
**Decisions:** 
- Any CNTT deployed cloud (NFVI) should be able to contain NFVI of a CNTT profile (B, NI) (!=hardware) that belongs to different CNTT releases (with different exceptions allowed). The number of CNTT releases supported by a given cloud should not be more than the latest **3** CNTT releases. This information needs to be written in RM as a policy. **RI/RC  will need to allow this to happen.**
