### ISSUE TITLE
[RM] Define forward compatibility policy/strategy for CNTT

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#1009]
In discussions on the exceptions framework and how it would be implemented in practice, the topic of forward compatibility came up.  Assumptions were being made about its use, but it is not explicitly documented or addressed in the RM or at a Governance or Technical Steering level.

This issue is to create a proposal on what the forward compatibility strategy is for CNTT.  Once agreed to in the RM level, the proposal will be presented to the Tech Steering (and governance) levels if necessary for ratification.  

This issue is also related to issue #1008 about backward compatibility strategy.

**Comment by kedmison** [comment]
When looking at a compatibility strategy, one should look at the interface(s) being considered and the 'perspective' of the interface; that is, the consumer or provider of the interface, and if there is a perspective on which of consumer or provider would be migrating first.

From a CNTT perspective, a backwards compatibility policy should apply to the NFVI; that is, a NFVI of version 'x' should be compatible the interfaces provided by NFVI version x-1 (up to some agreed-upon number of previous versions)

As a starting point for discussion, I think we should consider that this covers 
- the NFVI interfaces (explicit and implied) that are used by VNFs
Are there others that should be covered here?

Explicit interfaces are intended to refer to the actual APIs that are provided.
Implicit interfaces are intended to refer to configuration or convention that, while it may not be a formal part of an explicit API, is necessary for getting consistent behavior from an explicit API.  This includes definitions of objects, tags and the like that may be used as parameters for explicit APIs.

Do others have comments or perspectives on this definition and scope prior to working on a PR to contribute a change for this?

**Comment by kedmison** [comment]
Can we expect the VNF validation process to be sufficient in covering the validation that VNFs compliant to CNTT release 'x' can be run on a NFVI compliant to CNTT release 'x+1', assuming the NFVI is implementing backwards compatibility as per #1008?  What gaps may exist in this assumption?

**Comment by kedmison** [comment]
apparently if I do the assignments too fast it unassigns people...

**Comment by petorre** [comment]
> What gaps may exist in this assumption?

Depends on how much are apps coupled with the infrastructure+platform underneath and difference from X to X+1 release.
As differences between releases could be in RM Profiles, RA APIs, Exceptions, Certification and level of HW+SW details defined (generic Metrics or specific HW+SW configs), VNF Validated for X would not work on X+1 if:
1. Profile or APIs: Changed enough.
2. Exceptions: VNF must use (typically to reach required latency) Infrastructure Exception X.A not available in X+1. But it would work if VNF would optionally use Exception X.B (typically to run more cost effective). Similar like for Infrastructure can be for Platform services.
3. Certification and level of HW+SW details: X+1 HW+SW changes enough to create impact on NFVI performance characteristics or non-resilient VNF.

In PR #789 I propose generic framework of it with terminology.
