### ISSUE TITLE
[RA-1 Ch08] Discovery/Negotiation off VNF/NFVI capabilities

### ISSUE THREAD

**Issue by sukhdevkapur** [cntt-n/CNTT#1015]
During Prague meeting, we discussed that discovery and negotiations of the NFVI/VNF capabilities. We discussed various options: 
1) This is needed - everybody mostly agreed
2) Should this be done at the HW procurement time and should be part of RFI/RFQ process? 
3) Should this be done statically at the time of deployment of the VNF
4) If we do it dynamically through a negotiation protocol, isn't it too late? While this may be very useful and desirable, but, this will take a lot of effort to develop and will not fit into the release for this year
5) Should we look into what ONAP has in terms of resource discovery and see if we can add additional capabilities to that framework

Please add if I missed any other pertinent discussion points. 
I have tagged it for RA2 Chapter 8 as well - because this is applicable to both reference architectures.

**Comment by mf4716** [comment]
@sukhdevkapur , thank you for capturing this discussion item.  

Additionally, I'd add 2.a or 3.a, that being, auto-discovery would be a great utility post-delivery of the RI-x env.  Once the h/w is delivered, configured, and software deployed, the discovery capability would be used to confirm features and capabilities exposed by the platform - i.e. part of the RI/RC validation.  

Alternatively, the utility could be used in troubleshooting integration issues.  Bottom line, there is value in an automated auto-discovery utility.

**Comment by pgoyal01** [comment]
@sukhdevkapur @mf4716 Please review the OpenStack Placement service and APIs.

**Comment by sukhdevkapur** [comment]
We will be discussing and addressing this in the Networking Focus Group. Based upon the outcome of decision, this issue will addressed appropriately.

**Comment by pgoyal01** [comment]
As moved to RM, closing this issue as per Metering of July 27, 2020.
