### ISSUE TITLE
[RA-1 RA-2] Hardware Acceleration Support/APIs

### ISSUE THREAD

**Issue by sukhdevkapur** [cntt-n/CNTT#1017]
Should we define the specific  requirements for acceleration hardware? 
What level of detailed specification we want?  For example:
1) SmartNIC offload
2) DPDK
3) SRIOV

Do we want to go into the details of FPGA, GPU, etc? 

I am assigning both RA1 and RA2 as both need to address this gap.

**Comment by pgoyal01** [comment]
@sukhdevkapur OpenStack [Cyborg](https://docs.openstack.org/cyborg/latest/) project was recently overhauled including the architecture. It includes for example, 

*Definition Breakdown*
General Management Framework: 
- Resource Discovery 
- Life Cycle Management

Accelerators: 
- Software: dpdk/spdk, pmem, … 
- Hardware: FPGA, GPU, ARM SoC, NVMe SSD, CCIX based Caches, …

**Comment by ASawwaf** [comment]
@sukhdevkapur , For SRIOV , it will be covered in expectation scopes

**Comment by sukhdevkapur** [comment]
We will be discussing and addressing this in the Networking Focus Group. Based upon the outcome of decision, this issue will addressed appropriately.

**Comment by pgoyal01** [comment]
As moved to RM, closing this issue as per Metering of July 27, 2020.
