### ISSUE TITLE
[RA2]: Centralisation of control

### ISSUE THREAD

**Issue by fkautz** [cntt-n/CNTT#1020]
Centralization of control in a K8s cluster should be ok. However, we should be careful of the wording. 

Kubernetes is an emergent architecture. Desired outcome is posted into apiserver, and the system attempts to converge to a desired state. Likewise, many K8s components, CNI SDNs, and applications living on K8s share similar properties. This is antithetical to some top down control patterns where details are pushed from the top rather than emerging from the bottom. The desired state of a cluster is "centralized", but the realization is emergent. 

I recommend we follow a similar pattern. Allow for centralization of declarative configuration but whether it is top down control or emergent is an implementation detail. I'd like to make sure things are worded to allow for either. Before I work through the whole spec, I'd like to get other's thoughts on this topic and wording.

**Comment by tomkivlin** [comment]
@fkautz can you highlight which content the issue relates to please? Chapters, sections, snippets etc.

**Comment by tomkivlin** [comment]
Following discussion:
This is about configuration management approach as it applies to deployments of all shapes and sizes - centralised, edge, air-gapped, etc.

@fkautz to highlight chapters/sections that refer to centralised config mgmt. and see if any wording suggestion can be made accordingly
Also - suggest you sign up to the Edge workstream, as some of the considerations can be driven through there into wording changes too: https://wiki.lfnetworking.org/display/LN/CNTT+Workstream+Signup#CNTTWorkstreamSignup-EdgeWS(EDGE)

**Comment by fkautz** [comment]
This is going to require a bit of time to read through and make some recommendations. I'll do this over the next week.

**Comment by tomkivlin** [comment]
@fkautz - could you advise if a PR is imminent? The Baldy deadline is this Friday, so if not we can move to the Backlog to deal with it as part of the next release.

**Comment by tomkivlin** [comment]
Closed due to inactivity.
