### ISSUE TITLE
[RI-1] baldy.ri1.5: Add new chapter to include hardware delivery verification requirement

### ISSUE THREAD

**Issue by fuqiao123** [cntt-n/CNTT#1021]
1. add a new chapter to include hardware delivery verification requirement. referencing this page:
https://wiki.lfnetworking.org/pages/viewpage.action?pageId=27525908

2. update description file to include hardware verification data model

**Comment by ChilionChan** [comment]
Hi all, just provide a draft commit for this issue, welcome your comments.

**Comment by ChilionChan** [comment]
@fuqiao123 could you help to involve more, thanks.
