### ISSUE TITLE
There is no automatic checking on the changes

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1023]
At the moment we have no tools to check if the changes in the documentation are okay from syntax point of view. In ideal case we would need to run an .md linter with agreed rules and a link checker on the changes before they are merged.

**Comment by rabi-abdel** [comment]
do you have a recommendation @CsatariGergely which tools/plugin to use? will you be happy to look at this?

**Comment by CsatariGergely** [comment]
@rabi-abdel let's not close this yet. We would need a linter, some link checker and a way to run them automatically for every commit for the final solution.
