### ISSUE TITLE
[RC-1 Ch01] Broken Link

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1026]
Please fix link to CNTT Terminology in [1.1.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter01.md#111-terminology) -- the error portion of the URL is teh extra "ref_cert/lfn/chapters" n the path

https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/ref_model/chapters/glossary.md

**Comment by mf4716** [comment]
Addressed (fixed) with PR #1030 .  Awaiting PR approval.
