### ISSUE TITLE
[RM Ch08] 8.3.1. Entry/Exit Criteria

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1027]
Issue #1: 8.3.1 under Exit Criteria Typo - 1. Certification tenants should be "tenets"

Issue #2: 2. Operational Considerations -- isn't this list covered in the first statement under 1. Certification tenets: All Test Cases have a status of Passed, Failed, N/A, or Out-scoped.

**Comment by kedmison** [comment]
@pgoyal01 What would you consider doing for issue 2?   Should the expression 'verified to be working as expected', and similar, be removed?   This would remove the implied override of the criteria in 'Certification Tenets'.    
I would still find it good to list several of the capabilities that are being tested, to give a high level view of the scope.  If desired, we could add a note that this is a non-exhaustive list of RC criteria.

**Comment by pgoyal01** [comment]
@kedmison In the statement, "I would still find it good to list several of the capabilities that are being tested, ..." you are asking for the definition of the scope of the test cases. Shouldn't those be covered under either requirements or a separate section.

You should also review the "End User Considerations" to validate that these are really "Exit Criteria"

**Comment by kedmison** [comment]
Closing as Chapter 8 content has now moved to RI and RC workstreams.
