### ISSUE TITLE
[RM Ch08] 8.3.1. - 3. End User Consideration

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1028]
If these are requirements then they should be included there not add criteria for test exit that are not required.

**Comment by ASawwaf** [comment]
@pgoyal01 @rabi-abdel , I think this PR not as CH08 is / will be moved 

shall we close it

**Comment by pgoyal01** [comment]
@ASawwaf I was trying to point out issues with some of the content. Now that the content has been moved, yes we can close this issue or edit and transfer to where the content has been moved.

**Comment by ASawwaf** [comment]
@pgoyal01 Thanks
@kedmison it is ready to close

**Comment by kedmison** [comment]
Closing as Chapter 8 content has now moved to RI and RC workstreams.
