### ISSUE TITLE
[RC-1 Ch02] VNF Profile(s)

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1029]
In RC CH02 and elsewhere, replace VNF Profiles with NFVI Profiles.

For example, in RC 2.3, "VNF performance profiles, for which NFVI validations will support and be verified against, are defined as basic, network intensive, and compute intensive. Details for each of these profiles can be found in chapter 2.3."

should be
NFVI performance profiles, for which NFVI validations will support and be verified against, are defined as basic, network intensive, and compute intensive. Details for each of these profiles can be found in Reference Model chapter 2.3."

RE: Compute flavors: S, M, L: while Figure 4-2 refers to S, M and L flavors, the actual required flavors are defined in  RM [4.2.1.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4211-predefined-compute-flavours)

**Comment by deebhatia** [comment]
Q 1. What would be a VNF profile if the type of workload isn't?
Q2. Shouldn't NFVI profile X be that profile which will support VNF workload X? RC2.5 bullet 1.

**Comment by pgoyal01** [comment]
@deebhatia [RM Ch02](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter02.md#23-nfvi-profiles) introduces NFVI Profiles by workload types and these are then further explored in RM Chapter 03 and 04 including the concept of CNTT pre-defined flavors, and software and hardware profiles.  There isn't a 1:1 relationship between VNF workloads and the profiles. 

In OpenStack, as you know, the create instance (server) command accepts either an already created flavor or specification of CPU, RAM and disk. If a VNF profile doesn't match the existing flavors then the latter approach in the create command may be used.

**Comment by deebhatia** [comment]
Okay. I misinterpreted that VNF workloads and the profiles are 1:1. Thanks for the clarification.

**Comment by mf4716** [comment]
@deebhatia are you able to volunteer for this one?

**Comment by deebhatia** [comment]
> @deebhatia are you able to volunteer for this one?

Sure.

**Comment by mf4716** [comment]
Thank you @deebhatia
