### ISSUE TITLE
[TSC] Document Technical Releasing Process

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#1033]
- we would like to document the process of releasing CNTT
  - deadlines for contributions.
  - deadlines for proofreading.
  - etc.

**Comment by jbeltranatl** [comment]
@rabi-abdel suggest this also include definition of the scope (of Technical Releases)...

**Comment by rabi-abdel** [comment]
> @rabi-abdel suggest this also include definition of the scope (of Technical Releases)...

Yes, I will do that. thanks @jbeltranatl
