### ISSUE TITLE
[RC-1] Reflect Backward compatibility support in RI

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1036]
**Decisions:** 
- Any CNTT deployed cloud (NFVI) should be able to contain NFVI of a CNTT profile (B, NI) (!=hardware) that belongs to different CNTT releases (with different exceptions allowed). The number of CNTT releases supported by a given cloud should not be more than the latest **3** CNTT releases. This information needs to be written in RM as a policy. **RI/RC  will need to allow this to happen.**

_Originally posted by @rabi-abdel in https://github.com/cntt-n/CNTT/issues/1008#issuecomment-582394877_

**Comment by mf4716** [comment]
@rabi-abdel , is the intent here to include the info in our Framework, or Intro, documents?  Hasn't been picked up, or reviewed since creation, so wanted to confirm still applicable and potential location for info.

**Comment by fuqiao123** [comment]
I think this is just an issue RC need to make sure to accomplish. Don't think there are any obstacle for accomplishing this for the current framework of RC. Will confirm with the team on Apr.1st call and close this issue

**Comment by fuqiao123** [comment]
will close this one as it is a reminder and RC can natually support this.
