### ISSUE TITLE
[tooling]: Consider dropping actions/labeler for the fork and pr model

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1040]
We are using the actions/labeler GitHub action to do automatic labelling, but this prevents us from using the fork and PR model. (See more about this in the issue of [actions/labeler](https://github.com/actions/labeler/issues/12#event-3010934809))
With this current ways of working every PR have to be done from a branch in cntt-n/CNTT. The drawback of this are that to create a pr one needs a write access to the repo to be able to create the branch. This leads to not needed administration and makes onboarding difficult.

**Comment by gkunz** [comment]
+1 
I made the same discovery recently while trying to figure out why the labeler action fails on my PRs. While the labeler is very convenient, it is also very confusing to see it fail on PRs which follow the default GitHub workflow model.

**Comment by rabiabdel** [comment]
Makes sense. Happy to remove it and we can think about alternatives. Good points @CsatariGergely

**Comment by rabiabdel** [comment]
Would you mind @CsatariGergely removing it as an officer for tooling and automation ? You should have the right permissions.
