### ISSUE TITLE
[RI-1] baldy.ri1.1: General cleanup for RI doc

### ISSUE THREAD

**Issue by fuqiao123** [cntt-n/CNTT#1041]

**Comment by jayacha** [comment]
@fuqiao123 can we close this? we can further discusson the call tomorrow

**Comment by fuqiao123** [comment]
> @fuqiao123 can we close this? once some one can go through the document and make sure there are no gaps

Hi, Raja. Yes. I actually spend some time go through chp0-chp4, making sure it allign with each other. And those PRs have been merged. If we can have someone help go through the rest of the doc, then we can certainly close this.

**Comment by jayacha** [comment]
Recommended to close based on the current review and we have general issue for cookbook which will be reviewed.
