### ISSUE TITLE
[RI-1] baldy.ri1.7 Implement Profiles within OPNFV Installers and consume CNTT metadata

### ISSUE THREAD

**Issue by fuqiao123** [cntt-n/CNTT#1043]
This issue is created to follow the discussion and progress of the following work:
1. information model discussion and creation in OPNFV
2. information model translate into PDF 2.0
3. implement PDF 2.0 within OPNFV installers

**Comment by jayacha** [comment]
Based on the discussion, suggesting to take this in to the weekly Technical discussion call.

**Comment by jayacha** [comment]
@fuqiao123 , will check with her when she get back from vacation.

**Comment by jayacha** [comment]
This issue has no interest and has been idle. recommendation is to close on the next call on May 13th.

**Comment by pgoyal01** [comment]
@lylavoie @opensource-tnbt I see that the PDF specifications exist in [RI1 Chapter 6](https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter06.md). But couldn't find anything related to installers?

@jaycha had recommended that the issue be closed in May 2020. 

Can either of you please close -- it can always be reopened? Thanks.
