### ISSUE TITLE
[RA1 RA2] Express conditional requirements for implementations based on SW/HW profiles

### ISSUE THREAD

**Issue by peterwoerndle** [cntt-n/CNTT#1048]
In the discussions on #1014 we came across the issue that we'd like to have a mandatory requirement on the architecture but a conditional requirement on the implementation. In the RA2 call we concluded that we need some way to communicate that information to RI2 as part of the RA2 text. I'd therefore like to have a discussion on the following "pattern" to describe these kind of requirements.

> The architecture **must** support _capability xyz_.
> An implementation following the architecture **may** provide _capability xyz_ based on the applied HW or SW profile.

We can have a leading statement that if no conditionality is given, an implementation has to follow the architectural requirements. If possible we should also refer to the profile definition handling the conditionality.

**Comment by pgoyal01** [comment]
This should be two different issues so that we can work the RA1 and RA2 stream independently.

**Comment by tomkivlin** [comment]
@pgoyal01 if #1130 gets merged then that will deal with it for RA2, and so I'll remove RA2 from this Issue.

**Comment by tomkivlin** [comment]
Re-opened and removed from RA2 so now only RA2 specific.  For RA1 info, #1130 has been our solution in RA2.

**Comment by pgoyal01** [comment]
@tomkivlin Thanks. If there is a similar need in RA-1 we will follow the RA-2 practice.

**Comment by pgoyal01** [comment]
Issue being closed
