### ISSUE TITLE
[RA-1 Ch02] Document how resource autoscaling should be supported by Openstack

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#1052]
Referring to this discussion https://github.com/cntt-n/CNTT/pull/1046#discussion_r376489794, it is yet to be decided how autoscaling should be supported by architecture. 
1. Heat
2. Senlin + Prometheus

**Comment by pgoyal01** [comment]
Meeting of June 8, 2020, discussion to review requirements and also the mechanism for doing so. Assigned to @iangardner22

**Comment by iangardner22** [comment]
@deebhatia would you kindly reach out to me to discuss this please.   You should already have my email address but if not let me know by commenting.   

I was just wondering how we want to address this one.

Are we considering just the heat engine autoscaling which can be triggered by ceilometer (unreliable) or via an application (VNFM) calling the webhook (preferred)

Thanks a lot

**Comment by deebhatia** [comment]
Hi @iangardner22, it is open to discussion what should be the approach. It is okay from my side for the application (VNFm) to call such webhooks. 
Some queries which should be addressed:
1. Is this to be generic VNFm or a specialised VNFm or can be anything?
2. How VNFm should register the webhooks?
3. What are the policies for triggering webhooks? 
  The input of the policy can be either application aspect events/conditions (e.g. subscriber capabilities ,call loss rate) or non-application aspect events/conditions (e.g. CPU usage).

**Comment by iangardner22** [comment]
Thanks @deebhatia 

1. I think this can be *any* application.   Typically it would be a VNFM
2. When the initial heat stack is created then the webhook URLs can be defined as Outputs: and picked up from that by the application.   How they register would be application dependent I guess.   One option would be to recommend a standard resource name in heat that can be reliably queried by any application.
3. I don't think we can recommend ceilometer as a trigger so I would suggest these triggers are completely VNF dependent and we don't get involved in this.

Another option is to allow the VNFM to fire up resources outside of a heat stack.   This would move the stack LCM to the VNFM - again application dependent and not sure we really mind.

Any thoughts from RA-1 colleagues??? @pgoyal01 @rabi-abdel @karinesevilla @samuelhellec @sukhdevkapur

**Comment by iangardner22** [comment]
Once we agree I think a short paragraph is all that is needed to capture the approach.  Suggest this fits in Ch4.

**Comment by pgoyal01** [comment]
@deebhatia Can you let us know if you will be working this issue and when. This is important to take a decision on next steps. Thanks.

**Comment by deebhatia** [comment]
Hi @pgoyal01, I won't able to pick it up at the moment. I will remove myself from the assignees. 
Thanks

**Comment by iangardner22** [comment]
@pgoyal01 is this something we can just update ourselves?  I am struggling for time but will try to join the call today.

**Comment by pgoyal01** [comment]
@tomkivlin @CsatariGergely @peterwoerndle can you guys suggest how to handle the issue of auto-scaling in an OSTK environment. Please see questions and comments in the above discussions.

**Comment by tomkivlin** [comment]
@pgoyal01 I thought the ETSI MANO architecture dealt with this through the direct/indirect mode where NFVO controls the scaling of nodes either directly with the VIM (i.e. asks for a different replica count or new machines), or indirectly via the VNFM, where the VNFM asks for a grant to change the replica count/create new machines and then instructs the VIM to make it so?

Or have I misunderstood the question?  

For CNFs, the approach that I've seen make most sense is for the NFVO to own the dimensions of an autoscaling _thing_ (e.g. Horizontal Pod Autoscaler for Kubernetes) and then the NFVO, or the VNFM (if there is one anymore), will apply that HPA configuration to Kubernetes which then manages the autoscaling (thereby making the closed loop as small as possible, generally a good thing).  

i.e. NFVO owns min/max/desired/metrics to track/scaling triggers/etc. as part of the VNF descriptor and higher-level service descriptor and translates that into Kubernetes configuration.  I don't know the HEAT ASG concept well enough, nor how capable VNFs are to be scaled in such a way, to say whether that approach would be suitable for OpenStack.

**Comment by pgoyal01** [comment]
req.gen.scl.01 | Scalability | The Architecture should support policy driven auto-scaling.
-- | -- | --

**Comment by tomkivlin** [comment]
@pgoyal01 "The Architecture" suggests that you're looking for OpenStack services to support that capability (given the scope of RA1) - i.e. you're not looking for e.g. an NFVO or VNFM to own that capability.  Is that right?

**Comment by pgoyal01** [comment]
@tomkivlin Correct -- that is what the requirement is asking for. Now, if we decide that this is not easily achieved using OpenStack services, we would have to mark it as a Gap with the annotation that currently, this capability is provided by the VNFM but not natively by the Architecture. @iangardner22 Thoughts?

**Comment by iangardner22** [comment]
@tomkivlin @pgoyal01 if we want OpenStack Heat to manage autoscaling instead of VNFM then we can define Heat ASGs that can trigger based on ceilometer (not pretty as we know ceilometer is deprecated and I've not looked at it since) or based on a web-hook (i.e. VNFM or other external program initiates scale based on some application telemetry that is manages).   Also please note if you delete a VM manually from my tests Heat ASG doesn't recover!   I'd prefer we had a VNF provider define what they use today rather than trying to guess.   @kedmison - do you have any experience you could share here where one of your VNFs uses Heat ASG?  Thanks

**Comment by iangardner22** [comment]
Additionally I saw mention of senlin above... this is operating at a different level (i.e. physical hardware) and not the virtual resources that I believe this requirement is targeting...   let me know if I am wrong @tomkivlin @pgoyal01

**Comment by iangardner22** [comment]
As you wrote @pgoyal01 - senlin could offer another way to do this... originally I thought senlin was concerned only with physical compute nodes but it now can handle clusters of VMs...  quite nice but I wouldn't feel comfortable to write this up without using it and that isn't going to be possible in the short-term sorry.

**Comment by iangardner22** [comment]
@pgoyal01 @sukhdevkapur @karinesevilla @tomkivlin @ildikov - the proposed paragraph will read as follows - please confirm with a +1 if this meets your expectations and I will raise a PR to get it implemented.

@ildikov - are you able to confirm what the official scaling roadmap is please... In mitaka (and queens) I used asg's in a demo heat template and successfully triggered a scale-up/down based on CPU usage but it seems this has now taken two paths - one is AWS based scaling and the other is senlin - would you kindly recommend the best path here please.

The proposed paragraph:
> **Autoscaling**
> With regards to resource autoscaling it is recommended that the NFVO/VNFM manages the policy and triggers a scale-up or scale-down action based on application telemetry, an event, AI, or ML etc.  While the use of ceilometer / aodh is possible to trigger a scaling operation based on resource utilisation, without application context this may not provide the granularity or reaction time required for the application.  It is therefore suggested OpenStack autoscaling is triggered via a web-hook by the NFVO/VNFM and defined in the heat autoscaling group. 
> 
> For more information please see;
> https://docs.openstack.org/senlin/latest/scenarios/autoscaling_heat.html
> 
> Please note: physical compute node autoscaling is out of scope.

**Comment by pgoyal01** [comment]
@iangardner22 Can you take care of this so that we can complete prior to Sept 14.
