### ISSUE TITLE
[RA1 Ch04] Develop content about the allocation of host cores to OpenStack services

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1053]
Following PR #1046, to fulfill requirement "req.inf.com.08', content is needed in chapter 4 about the allocation of host cores/threads to non-tenant workloads, especially OpenStack services

**Comment by pgoyal01** [comment]
@karinesevilla Should we create a section on configuring "physical hosts" and make this (reserving certain cores for host services (OS< OSTK, ...)?

**Comment by karinesevilla** [comment]
@pgoyal01 I am not sure we need a new section, we can add this content into 4.2.2.5 "Compute Nodes"

**Comment by pgoyal01** [comment]
@karinesevilla So the content would look something like this:

The [RA-1 2.3.2 Infrastructure Requirements](https://github.com/cntt-n/CNTT/blob/pgoyal01-patch-2/doc/ref_arch/openstack/chapters/chapter02.md#232-infrastructure-requirements) req.inf.com.08 requires the allocation of "certain number of host cores/threads to non-tenant workloads such as for OpenStack services." A number ("n") of random cores can be reserved for host services (including OpenStack services) by specifying the following in nova.conf:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reserved_host_cpus = n
where n is any positive integer.
If we wish to dedicate specific cores for host processing we need to consider two different use cases:
1. Require dedicated cores for Guest resources
2. No dedicated cores are required for Guest resources 

For #1, we will need to specify both the cpu_shared_set and cpu_dedicated_set configurations, while for #2 only the  cpu_shared_set configuration would need to be specified. The cores and their sibling threads dedicated to the host services are those that do no exist in either of the cpu_shared_set and cpu_dedicated_set configurations. 

Let us consider a compute host with 20 cores and SMT enabled (let us disregard NUMA) and the following parameters have been specified
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cpu_shared_set = 18-39
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cpu_dedicated_set = 2-7,10-17
This implies that the two physical cores '0' and '8' and their sibling threads are dedicated to the host services, while 7 cores and their sibling threads are dedicated to Guest instances (these dedicated cores cannot be over allocated), and 11 cores and their sibling threads are available for Guest instances (and can be over allocated as per the specified cpu_allocation_ratio in nova.conf.
>Please note that in this example the cores and sibling threads are numbered consecutively but this is not usually the case.
