### ISSUE TITLE
[RC1 - Ch01] Clarify Conformance Categories (NFVI & VNFs)

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#1056]
Define Conformance, and Related Categories.  Replace Certification with Conformance within the RC documentation.  

Addressed with PR #1283 .

See initial comment below by @mf4716 .

**Comment by mf4716** [comment]
To All - 

Analysis / research performed to more narrowly define Conformance:

Presumably, we have consensus from CNTT to use Conformance to describe the output of the RC-1 team.  

Therefore, let’s start with a definition of Conformance, and descriptive paragraph to replace the opening RC-1 Ch1 Introductory paragraph.  **NOTE**:  Conformance vs compliance is not defined in CVC and previously was debated without conclusion (reference https://wiki.lfnetworking.org/pages/viewpage.action?pageId=10551934)

**By definition,** “Conformance testing, also known as compliance testing, is a methodology used in engineering to ensure that a product, process, computer program or system meets a defined set of standards. These standards are commonly defined by large, independent entities such as the Institute of Electrical and Electronics Engineers (IEEE), the World Wide Web Consortium (W3C) or the European Telecommunications Standards Institute (ETSI)” (retrieved from https://searchsoftwarequality.techtarget.com/definition/conformance-testing, Conformance Testing, on 3/9/2020).

**As described in**, “Conformance Testing (Compliance Testing) - Complete Guide” (retrieved from https://www.guru99.com/conformance-testing.html on 3/9/2020), Conformance testing will:
-	Confirm the fulfillment of system requirements (e.g. Model, Architecture, Configuration, Profile, and Instance requirements)
-	Confirm the accuracy and completeness of documentation (e.g. Runbooks, Cookbooks, Traceability of Requirements)
-	Performa an evaluation of design, development, and delivery (e.g. Implementation, Functional, Interoperability, and Non-Functional)

**Compliance**, on the other hand, is a state of being, and often implies alignment and adherence to some legal standard, or overarching requirement that legal authorities can use legal channels to ensure alignment to standards are met, or to hold others accountable to standards.  The use of Compliance for CNTT RX-x purposes will be used to signal that all Conformance tests have been designed and executed to evaluate alignment, docuementation, implementation, and interoperability of CNTT requirements for a specified reference architecture, relative to a single reference model.  For additional reading, please refer to “Compliance Vs. Conformance” (https://visionintegrity.ca/compliance-vs-conformance/).

Below, please find two RC-1 Introductory Chapter 1 paragraphs (https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter01.md), written as “before” and “after” using the above definition of Conformance for context:

"**Before**” – i.e. as currently published

For the purposes of this chapter, NFVI+VNF testing will be performed for Conformances indicating a measured performance of the adherence to, and demonstrated proficiency with, all aspects of software delivery including but not limited to planning, logistics for communication, and testing of installed, or implemented, NFVI. Similarily, VNFs will be checked for Compliance and Validations against the RM and RA requirements ensuring VNF instantiation, stability, and successful removal of the VNF from the implementation of the stated architecture. The additional VNF testing will verify that the developed VNF meets prescribed RM/RA infrastructure standards.
In summary, NFVI+VNF testing will be performed for Verification and Validation purposes.
•	Verification will be used to indicate conformance to design requirement specifications. Activities involved Reviews and Walk-Throughs to ensure the NFVI is delivered per implementation specifications.
•	Validations is used to indicate testing performed to confirm the actual output of a product meets the expected, or desired outcome, or behaviour.

**All Terms utilized throughout this chapter are intended to align with CVC definitions, and their use through CVC documentation, guidelines, and standards.**

“**After**” – i.e. slight modification using the Conformance definition mentioned earlier:

NFVI+VNF testing will be performed to evaluate Conformance (i.e. adherence) to, and demonstrated proficiency with, all aspects of software delivery.  More specifically, Conformance includes:
-	Verified implementations of NFVI+VNF match expected design requirements
-	Clearly stated guidelines for test, badging, and lifecycle management 
-	Inclusion of Operational run-books for 3rd party supplier instantiation and validations of NFVI+VNF0
-	Evidence, through test results (FR/NFR), confirming delivered code matches design and client expectations
-	Interoperability testing of Reference VNFs ensuring integration stability, including the successful removal of the VNF from the target architecture

**In summary**, NFVI+VNF Conformance testing will be performed for Verification and Validation purposes.
•	Verification will be used to indicate conformance to design requirement specifications. Activities involved Reviews and Walk-Throughs to ensure the NFVI is delivered per implementation specifications.
•	Validations is used to indicate testing performed to confirm the actual output of a product meets the expected, or desired outcome, or behavior.

**All Terms utilized throughout this chapter are intended to align with CVC definitions, and their use through CVC documentation, guidelines, and standards.**

**Comment by tomkivlin** [comment]
Really good analysis, thanks @mf4716
