### ISSUE TITLE
[RA2] CNF deployment into dedicated vs. shared Kubernetes clusters

### ISSUE THREAD

**Issue by samulikuusela** [cntt-n/CNTT#1059]
Background:
This came up in RA2 security context, but it is a broader topic. Included is all the information discussed so far in RA2 security. The topic was discussed briefly in Prague F2F as well.

Introduction:
The challenge: if an operator allocates a dedicated K8s cluster for every CNF from every vendor, the number of K8s clusters perhaps becomes too big (or does it really, if there is a good multi-cluster mgmt?). If this is the case, some level of aggregation of CNFs into shared K8s clusters needs to be done. This will not be problem-free and would cause increased OPEX.

Examples of problems if deploying multiple CNFs together in same K8s cluster (= CNFs which have not been planned and verified to co-exist in same cluster):
1) ingress controller, like Contour
2) logging framework, like ELK stack
3) service mesh, like Istio
These are commonly used concepts that are **global in a K8s cluster**. AT the time of CNF development, CNF integrates with a specific product & version, defines the configuration. The interfaces are typically proprietary.

Thus, if multiple CNFs would be attempted to be deployed in one cluster, it causes eg following problems:
- Version conflicts: CNF A uses version 1.1, CNF B uses version 1.2 (of eg. Istio)
- Configuration conflicts: CNF A vs. CNF B
- Problematic life cycle mgmt: SW upgrades within a K8s cluster becomes problematic due to version dependencies

Additionally, the security related challenge is increased risk of failure of isolation between the CNFs, because isolation relies fully on SW based mechanisms.

How to solve the above challenge?
No good solution was identified in Prague F2F, in the short discussion.

**Comment by tomkivlin** [comment]
From VF2F: an appendix to be created with some guidance about the approach of sharing k8s clusters or not.  From that, we can start to identify potential gaps to include in chapter08.md.

**Comment by peterwoerndle** [comment]
@xmulligan Did you start to draft something related to this? Are you planning to look in general into handling of cluster-wide resources or will you mainly describe the shared vs. dedicated cluster implications?

**Comment by xmulligan** [comment]
@peterwoerndle I was mainly going to focus on shared vs dedicated. Do you want to do intra cluster?

**Comment by peterwoerndle** [comment]
@xmulligan I thought of putting something together regarding "Kubernetes extensions". Something which can be installed/deployed on a Kubernetes cluster with a cluster-wide scope e.g. CRDs and how to handle those extensions.

**Comment by xmulligan** [comment]
@peterwoerndle check out my pull request and make a new one for the parts you think I don't address

**Comment by xmulligan** [comment]
@tomkivlin I think this can be closed since my PR is merged or is there anything else you think we should cover?

**Comment by tomkivlin** [comment]
The linked PR is the gap, was there another? I think the original point was to identify the resources that are cluster scoped and therefore may add to the need for separate clusters between "tenants".
