### ISSUE TITLE
[RI-2] Meeting Slot for RI-2 WS

### ISSUE THREAD

**Issue by rihabbanday** [cntt-n/CNTT#1061]
Since R1-2 workstream has been approved now, we should start a meeting series to discuss the roadmap and associated steps as listed in https://etherpad.opnfv.org/p/RI2.

**Comment by tomkivlin** [comment]
Has the WS been accepted? I've not seen any comms from the Governance meeting yet.

**Comment by rihabbanday** [comment]
The WS got approved in today's steering [meeting](https://wiki.lfnetworking.org/display/LN/2020-02-12+-+%5BCNTT+-+Technical+Steering%5D+-+Meeting+Agenda+and+Minutes), don't know if there is an additional step in getting it accepted - a newbie here :)

**Comment by tomkivlin** [comment]
Ah OK yes I've just seen in the minutes. I will get a Doodle Poll set up.

**Comment by tomkivlin** [comment]
Here's a Doodle Poll: https://doodle.com/poll/45iuub3wecqsq6ef

**Comment by rabiabdel** [comment]
Final approval will be given during governance meeting tomorrow. But doodle pool is a good idea to be sent now anyway .

**Comment by SaadUllahSheikh** [comment]
@tomkivlin @rabi-abdel  I have added information in Etherpad on tools and Deployment scenario two most important as a operator things it .
Just one observation do u think we should cover so many deployment scenarios  e.g Airship , Baremetal3 and Akraino ICN looks the only best place to start with and currently many Telco's thing this as way forward .

**Comment by tomkivlin** [comment]
@SaadUllahSheikh I don't think any of those are necessarily the right answer for the *reference* implementation. That's not to say they aren't useful to operators or able to become certified, but for me the reference implementation should be just that and no more. Given Kubernetes has a reference installer already (kubeadm) my preference / suggestion would be to use that or one of the Kubernetes owned wrappers of kubeadm such as kubespray. That way we stay as aligned as possible to the core project (Kubernetes) andeave other projects and products to certify as compliant vendor implementations.

**Comment by rihabbanday** [comment]
So as per current Doodle stats, Wednesday@15:00 UTC seems to be the most convenient time slot for the meeting series.

**Comment by tomkivlin** [comment]
@rihabbanday confirmed.  I have updated the meeting schedule wiki: https://github.com/cntt-n/CNTT/wiki/Meetings
