### ISSUE TITLE
[RA-1] Impacts of Parking Compute Intensive Profile in RM

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1066]
[RM] Park Compute Intensive Issue #973 and the related PR #1063 and PR #1064 impact RA-1 Ch 02 and Ch 04.

[RA-1 Ch02] Edit requirements that call out "compute intensive":  req.inf.com.04, req.inf.com.07

before working may need PR #1046 to be merged

[RA-1 Ch 04] Edit 
    - [4.2.2.5. Compute Nodes](https://github.com/cntt-n/CNTT/blob/Park-compute-intensive/doc/ref_arch/openstack/chapters/chapter04.md#4225-compute-nodes) -- Two tables
   - [4.4.1. Support for Profiles and T-shirt instance types](https://github.com/cntt-n/CNTT/blob/Park-compute-intensive/doc/ref_arch/openstack/chapters/chapter04.md#441-support-for-profiles-and-t-shirt-instance-types)
    - [4.5.1. Cloud Topology Considerations](https://github.com/cntt-n/CNTT/blob/Park-compute-intensive/doc/ref_arch/openstack/chapters/chapter04.md#451-cloud-topology-considerations) -- multiple occurrences within text

**Comment by rabiabdel** [comment]
@pgoyal01 I am happy to include those changes to the existing PR. Let me know

**Comment by pgoyal01** [comment]
@rabi-abdel Sure.

FYI: There is an open PR #1046 for RA-1 Ch02 -- 3 approvals have been made. I could make the the change to the req.inf.com.04, req.inf.com.07 but would necessitate another round of Approvals.
