### ISSUE TITLE
[RA2 Ch02] requirements for virtual CPU, memory, and disk capabilities

### ISSUE THREAD

**Issue by gkunz** [cntt-n/CNTT#1068]
Currently, the descriptions of requirements e.nfvi.res.cap.001, e.nfvi.res.cap.002, and e.nfvi.res.cap.003 in chapter 2 [1] state _max_ values for virtual CPU, memory and disk resources allocated to a pod. Phrasing these as maximum values is misleading as they should not define a hard upper bound.

[1] https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter02.md#224-instance-capabilities-mapping

**Comment by gkunz** [comment]
Well, _min_ is not entirely correct. Instead I propose the following:

| e.nfvi.res.cap.001 | Max number of vCPU that can be assigned to a single pod by the NFVI | at least 16<sup>1)</sup> | Y |
| e.nfvi.res.cap.002 | Max memory in MB that can be assigned to a single pod by the NFVI | at least 32 GB<sup>1)</sup> | Y |
| e.nfvi.res.cap.003 | Max storage in GB that can be assigned to a single pod by the NFVI | at least 320 GB<sup>1)</sup> | Y |

**Comment by deebhatia** [comment]
@gkunz These values are being used from the biggest flavour defined in [RM 4.2.1.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4211-predefined-compute-flavours) and these are per [VNFC](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#416-vim-capabilities). Isn't the at-least restrictions you are suggesting too big?

**Comment by gkunz** [comment]
@deebhatia right, I noticed after creating the issue that simply inverting _max_ to _min_ does not make sense either. You are right that these values should not be the minimum values, but they should also not be the maximum values as currently stated. Hence my proposal for adding an "at least" to the value, stating that the "_maximum_ value for X should be at least Y". This means, the value can be smaller than the maximum, but the maximum is also not hard limited by a single value (as currently stated), i.e., a vendor implementation can certainly support more than the currently stated values.
