### ISSUE TITLE
[RA1]Clarify SFC, Cyborg, Barbican or Telemetry API

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1076]
A few "should" requirements obscure the common CNTT API and the related testing (RC).
I would rather suggest "must" or no requirement for the next services (SFC, Cyborg, Barbican, Telemetry, etc.):
- req.asr.mon.01
- req.inf.ntw.04
- req.sec.zon.02

In this state, I would have considered that we do complete the API (major/minimal versions and capabilities) and we do add the related testing in IaaS verification (most of them are already covered). But at the end of the day the testing shouldn't be part of RC as they are optional.

**Comment by collivier** [comment]
CC: @mf4716 who aggregated all requirements for RC

**Comment by pgoyal01** [comment]
RA-1 Ch02 Requirements will be split into Requirements and Recommendations and Recommendations are not testable.

**Comment by collivier** [comment]
As discussed last Monday, only Barbican has to be added (versions and features) to RA1 Chapter 5.
SFC should be removed from the requirements and Telemetry will be kept as asis and untestable.

**Comment by collivier** [comment]
@rabiabdel one additional change is needed for Barbican.
