### ISSUE TITLE
[RA1][RC1]Check mandatory Neutron extensions

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1106]
A few Neutron extensions may be linked to the reference implementation:
- availability_zone
- l3_agent_scheduler
- l3-ha
- dvr
- l3-flavors
- fip-port-details
- floatingip-pools
- filter-validation
- extraroute-atomic

A straightforward proposal is to double check them via OVN.

**Comment by collivier** [comment]
availability_zone is supported by OVN
https://docs.openstack.org/networking-ovn/latest/admin/features.html

neutron_tempest_plugin.api.admin.test_agent_availability_zone.AgentAvailabilityZoneTestCase.test_agents_availability_zone is linked to
- AGENT_TYPE_DHCP = 'DHCP agent'
- AGENT_TYPE_L3 = 'L3 agent'

**Comment by ASawwaf** [comment]
@collivier , Can you elaborate more on what is scope of this issue?

**Comment by collivier** [comment]
2 are out of Pike:
-floatingip-pools: https://github.com/openstack/neutron/commit/4e3fb3191927e07b37fe0937102dc17334e906d1#diff-6cdd456e9b1cad4a23c219ecef1ecdae
- extraroute-atomic:
https://github.com/openstack/neutron/commit/b3eda71638973836c68dca90da9e017b285a642c#diff-25237435a98c84c53fbb8ae0b1c82c00

For the time being, only the next extension may change:
l3_agent_scheduler
l3-ha
dvr
l3-flavors
fip-port-details
filter-validation

**Comment by collivier** [comment]
@ASawwaf : I'm double checking a few mandatory extensions which may force the implementation of 
Neutron. The first list has to be double checked via a few reference impl.

**Comment by collivier** [comment]
@ASawwaf It's not so simple because I'm also working from OpenStack master to OpenStack pike dealing with testing logic. I'm adding comments to ease writing test case list at the end.
+ https://bugs.launchpad.net/neutron/+bug/1863707

**Comment by collivier** [comment]
@ASawwaf I will create the opposite thread later. dns integration could be added as mandatory.

**Comment by collivier** [comment]
port-mac-address-regenerate, filter-validation and  fip-port-details were introduced in Rocky (oldest OPNFV release: Hunter)
https://github.com/openstack/neutron/commit/2b1d8ea4a202f24c1b485ccebdbf831c505a4e6a
https://github.com/openstack/neutron/commit/8f3a066b20b7ffafec95a618d60e40727504f37c
https://github.com/openstack/neutron/commit/c760d4f26f4b4753c80269437d2cd0b8f63dbc7c
