### ISSUE TITLE
[RA-1 Ch07] Create LCM TOC

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1116]
RA-1 LCM TOC

Is this LCM of NFVI and VIM? Or just, NFVI or VIM?

Preliminary Ideas:
- Provisioning
    - OpenStack Services
    - Tenants
    - 
- Configuration Management
    - Desired state management of OpenStack Services
    - Configuring and maintaining Tenants
    - Configuring compute node profiles

- Logging, Monitoring and Analytics (LMA)
    (move from RA-1 Ch 04 and supplement with additional content)

**What else needs to be covered? What from the above is not required?**

**Comment by pgoyal01** [comment]
Issue #369 existed but is being closed as the current issue has some suggested content.

**Comment by ASawwaf** [comment]
@pgoyal01 @rabi-abdel , I tried personally to get an answers before for what you mention above with no luck :(

https://github.com/cntt-n/CNTT/issues/663

**Comment by pgoyal01** [comment]
@ASawwaf So maybe we create the minimum topics that would be required. For example, RA-2 Ch07, has an outline that consists of the following:

1. Kubernetes Cluster Lifecycle Management: Desired state configuration management drives lifecycle management Include the lifecycle management of associated objects (e.g. secrets)

1. Monitoring Kubernetes Clusters: instead we can have the more encompassing LMA (logging, monitoring and analytics) 9use some of the content from RA-1 Ch04 but expand)

1. Kubernetes Cluster Maintenance: Upgrades, adding new services, etc. (to me this is already part of the clutsre Lifecycle Management)

1. End-to-end Lifecycle Management Interfaces and Integration: e.g. NFVI lifecycle management e.g. e2e network service lifecycle management e.g. integration with LCM of non cloud native workloads (not sure about this)
