### ISSUE TITLE
[RM Ch04] Units for CPU metrics

### ISSUE THREAD

**Issue by peterwoerndle** [cntt-n/CNTT#1125]
The current version of the document does not specify the unit of measurement for CPU usage and CPU utilization which makes those statements having the same description and thus be ambiguous. As per the reference document ([ETSI GS NFV TST008](https://www.etsi.org/deliver/etsi_gs/NFV-TST/001_099/008/03.02.01_60/gs_nfv-tst008v030201p.pdf)) usage should be reported in nanoseconds and utilization in percent.

> **6.5 Units of measure**
Processor usage results shall be reported as time in nanoseconds, and utilization shall be reported as the ratio of total time in one or more execution contexts to the total time in the measurement interval, expressed as a percentage. 

A change in the RM will need to be followed up by changes in the the RA documents.

**Comment by ASawwaf** [comment]
https://github.com/cntt-n/CNTT/pull/1161#pullrequestreview-363082567

I think this issue covers your @peterwoerndle @CsatariGergely @rabi-abdel @kedmison
