### ISSUE TITLE
[RM Ch04] CPU overbooking

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1126]
Section 4.1.4.2 Table 4.6, the definition of "CPU overbooking" is missing and the capability is expressed with the ratio 1:N rather than N:1 as commonly used and defined in chapter 5 5.1.1
@kedmison  I propose to use the definition and wording of chapter 5 and modify the chapter 4 as follow:
- rename "CPU overbooking" by "CPU allocatio ratio"
- def: Number of virtual cores per physical core
- unit: N:1
Impact for tables 4.6 and 4.24

**Comment by kedmison** [comment]
Thanks, this is a good catch.  Please make a PR.
