### ISSUE TITLE
[RA 2] req.kcm.09 - The Architecture **should** prevent workloads from starving other workloads of guaranteed resources.

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#1132]
In PR #1121 , `req.kcm.09` The Architecture **should** prevent workloads from starving other workloads of guaranteed resources.

The requirement should be a **must**.

**Comment by CsatariGergely** [comment]
This issue was created as a consequence of my false advice. The comment should be resolved in #1121 (sorry again).
