### ISSUE TITLE
[RA2 Ch2] Improve traceability from RA2 to RM

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1137]
references, values, etc.

**Comment by tomkivlin** [comment]
@ramkri123 @CsatariGergely  let's suggest things here before raising a PR

**Comment by tomkivlin** [comment]
My suggestion to this is two-fold.

Firstly, for the tables in section 2.2, we should add a column that lists the RA2 requirement that links to the RM requirement, and then also a column for the chapter/section/arch spec (see #1186) to capture the full mapping.  This is then just helpful for checking how the "Y" is achieved. e.g. 


Attribute | Description | Value | Supported | RA2 Requirement | RA2 Spec
-- | -- | -- | -- | -- | --
e.nfvi.res.cap.005 | Total instance (persistent) storage (GB) | 300 GB | Y | `req.inf.stg.07` | [Section 4.5](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter04.md#45-storage-components)



Secondly, for the tables in section 2.3, we should add a column that lists the RM requirements the RA2 requirement is addressing (this is useful to check that an RA2 requirement is actually needed and useful - i.e. if there is no RM requirement it is linked to, why do we need it?). e.g. 

Ref # | Sub-Category | Description | RM Requirement
-- | -- | -- | -- 
`req.inf.stg.07` | Storage | The Architecture must support persistent storage for Pods. | `e.nfvi.res.cap.005`

What do you think?

**Comment by tomkivlin** [comment]
Also need to consider how to ensure updates to the RM are reflected in RA2.  From #639 
> BTW RA-2 Ch02, Section 2.2.4 has more entries than the current RM 4.2.5.

**Comment by CsatariGergely** [comment]
I'm okay with the suggestion of @tomkivlin in his previous [comment](https://github.com/cntt-n/CNTT/issues/1137#issuecomment-594482340). 
Some additional questions:
* Do we really need to have an RA2 requirement to map the RM requirements? Can't we just use the RM requirements?
* I'm not sure how can we keep the consistency to the RM requirements. We have some options, but I'm not sure if they are good
  * We can add a comment to the RM tables asking future contributors to cover RA-s also when they change the attributes
   * We can introduce a pr template where contributors need to indicate if the attribute names are changing
   * We can introduce a label to indicate if the attribute names are changing

**Comment by tomkivlin** [comment]
@CsatariGergely - I wonder whether we can massively simplify things, as per your question.

Chapter02 provides a link to the various RM chapters/sections that describe the RM requirements. Ideally, there is nothing or very little extra that needs adding here.  So, similar to the suggestion in #1338, we have:

- Chapter02: link to RM requirements, very few RA2-specific requirements
- Chapter03: description of the functional blocks and interfaces, no specification
- Chapter04: describe the specifications i.e. the specific choices and configurations that deliver the capabilities/interfaces (ch03) and the requirements (ch02) - this is where things like CNI, persistent volumes, etc. would be declared

If you agree, let's discuss tomorrow in the call how best to approach this quite big change.
