### ISSUE TITLE
[RM] Introduce availability zones to Reference Model

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#1160]
Availability zones are a common construct provided to allow workloads to create a more highly available application on top of an infrastructure.  They communicate important information about shared failure domains for infrastructure.  

Availability zones, as a construct, are available in OpenStack and in Kubernetes. 

In the absence of multiple availability zones, workloads rely on anti-affinity.  For large distributed workloads, this can create issues in requiring a large number of infrastructure hosts, thus creating inefficiency in the host hardware allocation.  

Introducing availability zones would allow for 
- VNF vendors to create better availability strategies for their VNFs
- NFVI operators to push VNF vendors to minimize sprawl across the infrastructure

**Comment by pgoyal01** [comment]
@kedmison are you suggesting adding a requirement around Availability Zones (AZs)? (I think you are referring to AZs in the context of hosts (nova AZs) and not network/storage). I hope you agree that AZs do not negate the need for anti-affinity and that the use of AZs as an anti-affinity mechanism is rare. Would the use as an anti-affinity mechanism require a large number of AZs? Please remember that with AZs, as operators, we are dividing our resources into separate resource pools with implications on capacity availability as the utilisation across these pools is unlikely to be the same. 

Typically, operators use AZs as failure domains-- enable workloads to achieve higher levels of availability as a mitigation against single points of failure. This latter aspect is highly operator environment dependent (racks with single or redundant ToR switches, set of racks connected to one power sources and the rest connected to another power source, etc.).  To guard against single points of failure, operators may implement 2 (based on needed redundancy) or 3 for quorum based workloads (databases, clusters, ...). AZs may also be used as a availability mechanism in certain maintenance activities (as in allowing rolling updates).

**Comment by kedmison** [comment]
@pgoyal01 we are aligned on the context of AZ.  I am referring to using AZs as a way for the operator to indicate acceptable failure domain separation, yes.  The operator could choose to only separate the compute nodes into availability zones, and not the storage or the networking.  Or they could choose to separate all 3.  In the absence of AZ definitions, VNF vendors have to look for other options to leverage, and anti-affinity is one of the sole remaining tools, albeit one with drawbacks.

**Comment by ASawwaf** [comment]
@kedmison @pgoyal01 , I think Host Agg  will be the right way to address what @kedmison mention

**Comment by pgoyal01** [comment]
@ASawwaf Agree host aggregates can address some of what is asked for but host aggregates are invisible to the users and so the VNF specification would need to capture the requirement for the cloud operator to choose the best possible mechanism to support the need.
