### ISSUE TITLE
[RM Ch05] Park Compute intensive in §5.1 and §5.2

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#1180]
### Occurences
1. Figure 5-3 depicts a high level view of the Basic, Network Intensive and **Compute Intensive** Instance Types.
2. This section will detail NFVI SW profiles and associated configurations for the 3 types of NFVI instances: Basic, Network intensive, and **Compute intensive**.

**Comment by rabi-abdel** [comment]
@deebhatia please make sure you assign the right Projects (in this case it is RM) so it can be picked up by Project.

**Comment by deebhatia** [comment]
> @deebhatia please make sure you assign the right Projects (in this case it is RM) so it can be picked up by Project.

I was facing some issues yesterday in attaching projects and labels. Thanks for attaching them.
