### ISSUE TITLE
[RA2 Ch02] OS kernel and resource isolation requirements

### ISSUE THREAD

**Issue by rihabbanday** [cntt-n/CNTT#1204]
I think we need to be more specific on the requirements

`req.sec.gen.04 `| General | The Architecture should provide Operating System kernel isolation.
`req.sec.gen.05 `| General | The Architecture must provide compute resources isolation.

Does Operating System kernel isolation here refer to using kata containers, containers in VM, etc?

Does Compute Resource isolation here refer to isolation provided by the standard container runtime?

**Comment by CsatariGergely** [comment]
I think `req.sec.gen.04` requires katacontainers or similar where the kernel of the containers/pod is isolated form the host and other containers/pods.
`req.sec.gen.05` I believe is a bit more than what standard container runtime provides as it does not provide isolation from noisy neighbours, like other pods in the same host or other processes not visible for the infrastructure.
