### ISSUE TITLE
[RM Ch04] Address Comments by @Mark Shostak on a merged PR

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#1206]
@karinesevilla Hi Karine, When you say Number of virtual cores per physical core. are you referring to number of Threads (or Processes or VMs) scheduled per physical core? 

Consider including "overbooking" in the comments section; it's an easy way to help people understand the parameter, and still have the more technical definition from above which is more precise, but not as intuitive IMHO.

_Originally posted by @markshostak in https://github.com/cntt-n/CNTT/pull/1187#issuecomment-591420554_

**Comment by pgoyal01** [comment]
@rabi-abdel Operating systems report "Processors" or "Logical Processors" (logical and virtual are synonymous). As you know when speaking of "threads" there are "physical" and "emulator" threads. 

But if we look for usage of terms logical cores and physical cores are very common terms. May I suggest that we use "logical (virtual) cores".

**Comment by kedmison** [comment]
I think we should take the topic of processor vs core vs thread vs vcpu vs. cpu separately; this will likely touch many documents across RM, RA, RI, RC from what I can see.
