### ISSUE TITLE
[RA-2 CH01] LCM is out of scope -- but required

### ISSUE THREAD

**Issue by nickchase** [cntt-n/CNTT#1207]
Chapter 1 says that 'For the avoidance of doubt, the following is considered to be out of scope:  Kubernetes cluster lifecycle management: reason being, it is not considered to be "visible" to a CNF and so should not be included.'

However, multiple locations say things like "req.inf.ntw.09 | Network | The Architecture must support API driven life-cycle management (LCM) of the infrastructure that allows repeatable, scalable and standardised handling of K8s clusters. LCM use cases to cover are: instantiation, termination, upgrade, scaling, and healing."

So is it in scope or not?

**Comment by fkautz** [comment]
I don't see a conflict here, but perhaps the wording can be improved.

There is the life-cycle of the cluster and life-cycle of the workload. The workload does not need to be aware of the life-cycle of the cluster. Interestingly, the workload often doesn't need to be aware of its own life-cycle, though being aware of its own life-cycle may sometimes be necessary based on the type of workload being run.

I would argue that for now, the LCM of the cluster as a whole should probably be out of scope while the LCM of the CNFs should probably be in scope.

Anyone else have thoughts on this?

**Comment by tomkivlin** [comment]
> I would argue that for now, the LCM of the cluster as a whole should probably be out of scope while the LCM of the CNFs should probably be in scope.

@fkautz that's exactly what we're trying to achieve, yes.  

@nickchase - I think you've probably highlighted a requirement that needs re-wording or removing :). Happy if you want to create a PR that deal with that and resolve this issue?

**Comment by ulikleber** [comment]
I agree that LCM of the cluster is out of scope for CNTT. However the reasoning is not correct. Many things that are not visible to the CNF/VNF are in scope for CNTT. 
A complete NFV-MANO solution would need to provide LCM for the kubernetes clusters it is using to deploy its CNFs. But as CNTT doesn't describe the NFVO and VNFM parts, the management of the cluster(s) in my view is not in scope, while the VIM and the LCM of containers is in scope.

**Comment by nickchase** [comment]
OK, so I'm sitting down to do this and I actually think I disagree with the fundamental issue. How can you ensure that the CNF has the resources that it needs to execute its workload if you can't control the lifecycle of those resources?  I do agree that cluster LCM should not be visible to the workload, but I think that the original requirement should be something more along the lines of:

 'For the avoidance of doubt, following is considered to be out of scope: The method of Kubernetes cluster lifecycle management: reason being, it is not considered to be "visible" to a CNF and so should not be included, except to specify that the following capabilities must be available: resource instantiation, termination, upgrade, scaling, and healing.'

**Comment by ASawwaf** [comment]
@fkautz @tomkivlin @nickchase 
I have a different/Opposite  opinion :) which matches @nickchase , the LCM for VNF/CNF is out of scope from day one as it is MANO ( VNF-M/CNF-M) function which responsible for LCM ( instantiate, Terminate, scale,..) But what we cover the LCM on the NFVi which is VIM function for resources allocation,...

So +1 with @nickchase

**Comment by tomkivlin** [comment]
Hi all - I've added to the agenda for today's Tech Steering call: https://wiki.lfnetworking.org/display/LN/2020-03-10+TSC+Meeting+Agenda+and+Minutes

**Comment by rabi-abdel** [comment]
@tomkivlin as discussed, feel free to create a PR to clarify the scope and add it to the tech document under scope (https://github.com/cntt-n/CNTT/tree/master/doc/tech#2.0)

**Comment by tomkivlin** [comment]
Being addressed in #1247
