### ISSUE TITLE
[ALL]: NFVI Profile =? Instance Type

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1209]
RM Chapter 1.4 introduces the definition of NFVI Software and NFVI Hardware profiles along with Instance Type (in Figure 1-1). For me Instance Type is the NFVI Software Profile and NFVI Hardware profile together. In other parts of the document, like in Chapter 4.2 there are mentions of NFVI Profile, which describes the term better. Instance Type, Instance and NFVI * Profile-s are mixed in the whole document. 

I would propose to 
* Rename Instance Type to NFVI Profile in the whole document
* Add a definition of NFVI Profile to Chapter 1.1

**Comment by rabi-abdel** [comment]
This is very valid point @CsatariGergely, are you happy to start a PR for it? 

p.s. Please make sure to add RM project to issue :)

**Comment by ASawwaf** [comment]
@rabi-abdel moreover, there is an unclear border ( Definition ) between :
Instance Type
NFVI Profile
Profile
T-Size 
Flavor

**Comment by CsatariGergely** [comment]
Yes, we are happy to start a pr about this.

**Comment by pgoyal01** [comment]
Currently, NFVI Software profile is being used as the configuration of, say, the software (hypervisor, VIM) in support of instance types. If we are going to use NFVI Software Profile in the manner as suggested then I suggest we change NFVI hardware profile to NFVI host profile (to cover both hardware and software configurations),

**Comment by CsatariGergely** [comment]
The idea is to use NFVI Profile as the software and hardware profile and remove "instance types" as this is used in inconsistent way. We would still keep NFVI Software and NFVI Hardware profiles.

**Comment by kedmison** [comment]
@rabi-abdel In [a comment in issue 1210](https://github.com/cntt-n/CNTT/pull/1210#discussion_r389301164) makes a very good point about following the naming changes through to all the other documents.  Can we convert this Issue to an 'All' issue and then use it to update the rest of the document set?

**Comment by rabiabdel** [comment]
> @rabi-abdel In [a comment in issue 1210](https://github.com/cntt-n/CNTT/pull/1210#discussion_r389301164) makes a very good point about following the naming changes through to all the other documents. Can we convert this Issue to an 'All' issue and then use it to update the rest of the document set?

@kedmison i agree. i see this issue is assigned to @CsatariGergely please feel free to create a PR that expands across all specs to change the term as discussed here. don't worry about #1264 as we can always resolve the conflict before merging.

**Comment by pgoyal01** [comment]
@rabi-abdel @kedmison The issue with using the terminology NFVI SW Profile and NFVI HW Profile in, say, RA-1 is that the terms do not exist in OpenStack. 
How do we classify Flavor Geometry (the vCPU, RAM, etc. sizing)? or the Flavor Capabilities (CPU Allocation Ratio, CPU Pinning, NUMA, etc.)? Host profiles?

**Comment by kedmison** [comment]
Openstack and Kubernetes will have different terminologies for these sorts of things so having RM terminology that aligns with Openstack will make it less obvious for RA2.

Yes, I do think we need to draw a clear line to to the terminology of RM.

Can we say that the CNTT NFVI Profile is described as mapping to the Flavour Capabilities, and then the different geometries included in the RM are then used to create a set of Flavours?
