### ISSUE TITLE
[Chapter 1] Clarify that CNFs run on an app orchestration layer, not directly on infra (NFVI/VIM)

### ISSUE THREAD

**Issue by fzdarsky** [cntt-n/CNTT#122]
Problem:
Various sections (terminology, architecture, infrastructure abstraction) use VNFs and CNFs interchangeably, describing them as "just different workloads of an NFVI". Consequently, functionality for enabling and managing containers is wrongly allocated to the NFVI/VIM.

VNFs and CNFs work on different abstraction-levels, though:
VNFs are (groups of) VMs and build on infrastructure-level abstractions (machine, network, disk / block storage) which is what NFVIs/VIMs provide.
CNFs are processes build on OS-level abstractions (process groups, network sockets, file sockets, ...) which is what an OS + container runtime + container orchestration platform layer _on top_ of an infrastructure layer provides.

Proposed fix:
We need to a) remove any statements suggesting CNFs (like VNFs) would run / consume resources / be managed by the NFVIs/VIMs directly and b) introduce an application orchestration layer on top of the NFVIs/VIMs that runs CNFs and decouples them from infrastructure resources.

Consequences if not fixed:
* confusion of which functionality belongs into infra vs app layer and consequently, which services need to be exposed by NFVI/VIM and which not
* misalignment with industry standard practice (public cloud, OpenStack vs Kubernetes, ...) of cleanly separating infra and app layers
* losing benefit of running same container/app orchestration platform on different NFVIs/VIMs technologies and ability to "swap out" / mix-and-match

**Comment by xavier-grall** [comment]
We should remain aligned with ETSI definitions/specifications, so CNF being only a possible implementation of VNF, the current VNF/CNF-related definitions should be preserved.
However, concerning VIM and regarding ETSI NFV IFA029, it should also be noticed that it only manages VM-related components (especially for VM-based VNF), while CISM (Container Infrastructure Service Management) manages container-related components (for container-based VNF): maybe something to precise/desambigaite about that in chapter 1 ?

**Comment by ulikleber** [comment]
I fully agree to remain aligned with ETSI. I would like to clarify the above wording a bit. 
When CISM as defined in IFA029 manages the containers for a container-based VNF, there is still the NFVO in place managing the whole VNF and using the VNFM to trigger life-cycle operations. 
From the Network Service consumer point of view, the NFVO manages the VNF even when deep inside there are containers and a CISM doing the management on the level of the containers.

**Comment by xavier-grall** [comment]
OK for NFVO role, but after reading carefully IFA029, it is not so clear for CISM vs VIM since 2 options are currently "left for normative work to provide a unified target architecture"  : CISM embedded in the VIM (option 1) and CISM as a stand-alone functional block (option 3)...

**Comment by fzdarsky** [comment]
@xavier-grall there is no CNF definition in ETSI NFV! The ETSI NFV terminology doc (NFV004, page 15) defines VNFs as "implementation of an NF that can be deployed on a Network Function Virtualisation Infrastructure (NFVI)", which doesn't work for CNFs.

Means, if we want to be explicit about VMs vs containers we need to come up with _some_ name even at the risk of differing from ETSI NFV. I never liked "CNF" and would have preferred "Containerized VNF", but "CNF" seems more common in the industry these days.

**Comment by fzdarsky** [comment]
@ulikleber I think we need to be precise on using terminology. It's not the NFVO that's "manages the VNF", it's the VNFM. And if IFA029 assumes Kubernetes only managed containers and their infrastructure, it's missing the point that Kubernetes is a VNFM (cf Operator pattern)!

After reading IFA029 carefully, especially section 7.2.4 with the 4 options of how to map CISM into the ETSI MANO architecture, none of the 4 options map to how Kubernetes is being deployed and used to manage CNFs today. I'm sure ETSI NFV plans to address that in some future WI, but this just shows that we cannot dogmatically rely on ETSI NFV for this activity.

**Comment by pgoyal01** [comment]
@fzdarsky: From ETSI GS NFV 003 V1.4.1 (2018-08)

**virtualisation container**: partition of a compute node that provides an isolated virtualised computation environment
NOTE: Examples of virtualisation container includes virtual machine and OS container.

**Virtualised Network Function Component (VNFC)**: internal component of a VNF providing a VNF Provider a defined sub-set of that VNF's functionality, with the main characteristic that a single instance of this component maps 1:1 against a single **Virtualisation Container**

**Virtualised Network Function Component (VNFC) Instance**: instance of a VNFC deployed in a specific **Virtualisation Container** instance. It has a lifecycle dependency with its parent VNF instance

**Comment by fzdarsky** [comment]
@pgoyal01 I know, those are mostly my definitions :)

Again: There is no name/definition in ETSI NFV to express a containerized VNF as opposed to a VM-based VNF. It's all blurred behind a single term. IIUC, the author of Chapter 1 meant to have terms to be able to distinguish the two, thus introducing the new term "CNFs". I haven't seen an alternative proposal that manages to square this circle (compatibility with ETSI NFV terminology).

The issue raised here is not about naming, though. It's about recognizing that VNFs and CNFs are not interchangeable, neither from infra perspective (CNFs cannot run on NFVIs/VIMs like VNFs) nor from MANO perspective (CNFs are orchestrated and managed differently), and proposing fixes accordingly.

**Comment by pgoyal01** [comment]
@fzdarsky I just pointed out that some of the terminology does attempt to cover containers. No one is arguing that VNFs or CNFs are interchangeable; there are also different deployment scenarios based on considerations such as isolation.   W.r.t. IFA029 -- it is still a work in progress -- and the authors do present various options and in their discussions on CISM/CIS discuss how containers are being used today. Is Kubernetes a VNFM or only a VIM -- does Kubernetes deal with containers or the VNF workloads hosted in the containers?

**Comment by ulikleber** [comment]
I am happy to hear that the intent is not to say that a CNF is not a VNF. However the acronym "CNF" really makes people think we want to point out that a CNF would not be a VNF. 
(however the proposal in #123 didn't allow a VNF to use containers, but maybe hat was not the idea of it)
To make some progress here, I would like to propose the acronym C-VNF for containerized VNF. If necessary we can also use V-VNF for VNFs using VMs.
According to IFA029, NFVO and VNFM manage V-VNFs and C-VNFs. The relation of C-VNFs to the NFVI is different from V-VNFs. But they should still run on top of an NFVI. Assuming that an operator wants to deploy a large variety of VNFs, there will be both, C-VNFs and V-VNFs. A NS will contain both, C-VNFs and V-VNFs and they should be able to run on the same set of hardware.

**Comment by xavier-grall** [comment]
It seems we all agree that we need to clearly distinguish VM-based and container-based VNF, so we need words/definitions for that purpose:
- VNF vs CNF remains ambiguous (since VNF can be container-based from the ETSI perspective)
- V-VNF vs C-VNF seems a relevant proposal (and even, it would be interesting CNTT-originated acronyms ;-)
Regarding Kubernetes as a VNFM vs VIM/CISM, I do not have any opinion for now, but it also needs to be clarified.

**Comment by pgoyal01** [comment]
Let us agree to use VNF as generic, V-VNF and C-VNF as specific VM-based and Containerised- VNFs respectively.
For now, let us agree that Kubernetes is a VIM for Containers; we can always revise this position if we see that k8s orchestrates and manages C-VNFs and not just the containers.

**Comment by xavier-grall** [comment]
@pgoyal01 - I fully agree with that position, so V- and C-VNF should be defined in chapter 1
here is a proposal for that:
[PR proposal](https://github.com/xavier-grall/CNTT/commit/6438ad13eef15bf3424a7214b19fa303620c5c8a)
opinion ?

**Comment by bfcohen** [comment]
Added a bit of wording to cover this.  Chapter 01 is high level enough that all this detail belongs in the upcoming container architecture document.

**Comment by bfcohen** [comment]
Should be closed.
