### ISSUE TITLE
[Chapter 3] Change name of chapter to NFVI Components or Abstraction

### ISSUE THREAD

**Issue by bfcohen** [cntt-n/CNTT#124]
Based on feedback from the group, the suggest is to rename Chapter 3 to NFVI Components or Abstraction, which is more description than the term model.

**Comment by pgoyal01** [comment]
NFVI abstraction - Ch 3.1; we don’t get into all components as intent was to abstract away the detail. The metrics don’t belong with the abstraction - maybe specifications.

If not splitting chapter them NFVI Astraction and Specifications

Best regards
Pankaj

Sent from my iPhone

On Jul 24, 2019, at 4:27 PM, bfcohen <notifications@github.com<mailto:notifications@github.com>> wrote:


Based on feedback from the group, the suggest is to rename Chapter 3 to NFVI Components or Abstraction, which is more description than the term model.

**Comment by BernardTsai-DT** [comment]
Has this been now addressed properly by splitting up the Chapter 3 into the Modelling part and the NFVI abstraction part?

**Comment by BernardTsai-DT** [comment]
@rabi-abdel Can we close this issue since we have already restructured the chapters of the reference model?
