### ISSUE TITLE
[RI2] Lab requirements

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1241]
Lab requirements:
- what do we need from the lab (the place we're deploying the RI at any point in time)

**Comment by xmulligan** [comment]
should we support hardware and network provisioning ahead of time or should we expect it from an admin ahead of time?

What is our starting point for provisioning and configuration?

How much should we rely upon open source?

**Comment by tomkivlin** [comment]
Need to identify requirements from RM/RA2 that impact on hardware provisioning and configuration.

**Comment by tomkivlin** [comment]
CNF Testbed team (Watson, Taylor, Michael, Denver) to look at this and update the spreadsheet with the info that we need to check against the installers.

**Comment by michaelspedersen** [comment]
To my knowledge, BIOS and bootloader configuration will have to be done outside of the installer. 

BIOS settings depend on the hardware in the system, and also what the purpose of the setup is (deterministic/max performance, power consumption etc.)

For SR-IOV, we will need VT-d enabled. I have noticed on some of the servers provided by Packet.com, that we use for the CNF Testbed, that in addition SR-IOV needs to be enabled for the PCI device (x710 NIC) explicitly. I dont' think any of this can be configured through an installer. If anything it would be beneficial with a pre-deploy validation check, which could utilize something like `dmidecode` to check how the system has been configured prior to running the installer.

The bootloader ideally gets configured prior to running any installer. For the CNF Testbed we do it after installing, which can work as well (but of course requires a reboot following the update). 

My opinion here is to keep these parts separated from the installer comparison. Maybe the Vulk team (Watson, Taylor and Denver) has another view on things, but we can follow-up on that.

**Comment by tomkivlin** [comment]
> To my knowledge, BIOS and bootloader configuration will have to be done outside of the installer.
> 
> BIOS settings depend on the hardware in the system, and also what the purpose of the setup is (deterministic/max performance, power consumption etc.)
> 
> For SR-IOV, we will need VT-d enabled. I have noticed on some of the servers provided by Packet.com, that we use for the CNF Testbed, that in addition SR-IOV needs to be enabled for the PCI device (x710 NIC) explicitly. I dont' think any of this can be configured through an installer. If anything it would be beneficial with a pre-deploy validation check, which could utilize something like `dmidecode` to check how the system has been configured prior to running the installer.
> 
> The bootloader ideally gets configured prior to running any installer. For the CNF Testbed we do it after installing, which can work as well (but of course requires a reboot following the update).
> 
> My opinion here is to keep these parts separated from the installer comparison. Maybe the Vulk team (Watson, Taylor and Denver) has another view on things, but we can follow-up on that.

Thanks for this information, very useful. I'm OK with them being kept separate from the installer comparison.  It feels like there are two approaches to this:
1. the infrastructure API has capabilities to include these settings when provisioning a machine (i.e. can the Packet API pass these settings in when provisioning a machine?)
1. if the infra API can't do it, is it something that needs to be built into an image-build stage with e.g. Packer?

Something to review on the call today.

**Comment by tomkivlin** [comment]
Have done a diagram to help me understand/explain.  I agree that bootloader / BIOS settings will be managed elsewhere but I would like to understand the options there, and whether the installer can/should orchestrate the infra/imaging/etc. tooling.

<p><img src="https://wiki.lfnetworking.org/rest/gliffy/1.0/embeddedDiagrams/9f780d63-a3fc-4b14-b348-08cb3c508012.png"/></p>

**Comment by tomkivlin** [comment]
@tomkivlin to update diagram based on meeting 01/04

**Comment by tomkivlin** [comment]
PR to be created once #1528 is complete.
