### ISSUE TITLE
[RI2] Kubernetes installer requirements

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1242]
"k8s" LCM requirements:
- what do we want from an installer? (e.g. e2e LCM, 2-stage, etc.)?
- what impact does this have on the lab we're using?

**Comment by rihabbanday** [comment]
The requirement on the installer in RA2 states that it should be listed in the [Kubernetes Distributions and Platforms document](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es/edit#gid=0). I feel kubeadm or kubespray could be good candidates if we are looking for an installer providing LCM functionality. But that also depends on the definition & scope of LCM functionality that we are targeting.

**Comment by nickchase** [comment]
I think we need to define what we mean by "LCM", however, as there seems to be some disconnect.  See https://github.com/cntt-n/CNTT/issues/1207.  Is it out of scope?  In scope?

**Comment by tomkivlin** [comment]
> I think we need to define what we mean by "LCM", however, as there seems to be some disconnect. See #1207. Is it out of scope? In scope?

It's out of scope in terms of what the conformance tests will test for (i.e. we won't have any tests targeting the installer itself).  This issue is about choosing an installer to install a Kubernetes cluster, for the testing of that cluster (not the installer).

**Comment by nickchase** [comment]
That makes perfect sense, thanks, @tomkivlin .

**Comment by xmulligan** [comment]
Should we consider including kubeadm and cluster-api?
There is both a packet and bare metal provider

**Comment by xmulligan** [comment]
How complete should the installer be and how much life cycle management should it be able to do?

**Comment by xmulligan** [comment]
https://wiki.lfnetworking.org/display/LN/Kubernetes+Installer+Comparison

First take at creating a comparision chart, would be great to have feedback on what other features we should consider or if there are other installers we should look into

**Comment by ASawwaf** [comment]
@xmulligan shall we include Cluster API

**Comment by xmulligan** [comment]
@ASawwaf sure do you want to do the initial assessment? However, do you think it is an installer by itself or more just a node manager?

**Comment by ASawwaf** [comment]
@xmulligan , I think it is cluster installer and manager which  can be used for creation, configuration, and management of K8s Cluster

**Comment by rabi-abdel** [comment]
by @Taylor : https://docs.google.com/spreadsheets/d/12EWZVvlumktXoywvmlYPR_DrU34e7Gk_rSED3VyCG4o/edit#gid=0

**Comment by pgoyal01** [comment]
Can we use Confluence? Google docs is inaccessible from some of the companies?

**Comment by xmulligan** [comment]
refer to #1374 for further discussion
