### ISSUE TITLE
[RI2] Kubernetes (+ add-ons) configuration requirements

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1243]
"k8s" requirements:
- what config parameters to choose etc. to conform to the RA spec (should be able to pull through from RA, identify gaps if not in RA)

**Comment by xmulligan** [comment]
Step 1. create a list of the config parameters to go through
Step 2. choose which option to implement in the RI

**Comment by xmulligan** [comment]
possibly convert to confluence?

https://docs.google.com/spreadsheets/d/12EWZVvlumktXoywvmlYPR_DrU34e7Gk_rSED3VyCG4o/edit#gid=0

**Comment by tomkivlin** [comment]
PR needed to add content to ch02 and ch04. After #1527 and #1529 are closed.

**Comment by tomkivlin** [comment]
Kuberef/BMRA version already added in previous PRs (to 4.3). Airship and other details will be added in new PRs.
