### ISSUE TITLE
[TSC]: Allow issue self assignement

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1254]
I think we should not wait until WS leads assign issues to people, but people should be able to assign issues to themselves.

**Comment by rabiabdel** [comment]
i have no issue with the proposal. let us discuss in next TS meeting and get this approved if we have consensus on this.

**Comment by CsatariGergely** [comment]
03.11 TS meeting is too early for me due to some travels. Let's discuss on the week after. 

.. and can you assign this ticket to me? :)

**Comment by rabi-abdel** [comment]
> 03.11 TS meeting is too early for me due to some travels. Let's discuss on the week after.
> 
> .. and can you assign this ticket to me? :)

We can still discuss it next week too. 
:) yes off course.

**Comment by rabi-abdel** [comment]
@CsatariGergely would like to propose text change in form of PR for this to be reviewed in TSM call next week? if we can get the text agreed, it can be a quick approval.
