### ISSUE TITLE
[RC1 - Ch1.8] baldy.rc1.1:  Add Results Collation Process

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#1258]
Supports: baldy.rc1.1 General Cleanup

Purpose: Conduct discussions & document outcome in RC1 Ch1.8 ("Results Collation & Presentation") for establishing a common repo for test results collation and results presentation which:

- supports a badging program
-  enables CNTT RIRC deliveries for Baldy
- serves as a common results platform for OPNFV test projects & the friendly RI-1 trial partners

Update TOC to align with document sections.

**Comment by mf4716** [comment]
Initial call conducted 3/5.

Follow-up touch-point 3/16.

•	Goals: Discussed Goals of:
o	needing to change compression format from *zip to *gz.  Low effort to implement, and can be done.
o	needing to identify the right structure of output data which supports OVP Portal requirements.  

•	Options considered for aligning to the right structure include:
•	create a translator which takes test result output from projects and translates to Portal structure
•	modify the Functest/Xtesting output to align to Portal format
•	modify the Portal to align to Functest/Xtesting structure and format

•	Mentioned that OVP Portal was designed to store artifacts indefinitely for traceability purposes

•	Question was asked if Dovetail Portal supports the OPNFV test database and structure.  Answer:  No, it does not.  Something that could be looked into.

•	Live review of Functest output was done by Lincoln.  Identified at least one change for relative paths which Cedric agreed to make.  
o	All changes to be applied / needed will be communicated via Gerrit.  We can review/approve there.

•	Next steps
o	Cedric to make initial relative path change.  Team will monitor/approve via Gerrit.
o	Lincoln & Kanag to perform a deeper dive into the Functest output to identify any other changes possibly needed on the Portal side, or Functest side.  
o	Team agreed to work issues via offline means (email, Gerrit, etc).

**Comment by prabhubalan** [comment]
General clean-up done for the Chapter 01 in RC1, please refer #1451. Closing this issue after discussed with Rabi and Fu Qiao
