### ISSUE TITLE
[RM Ch09]: html tables

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1278]
Ch09 contains some tables in html and not in md notation. The reason that these tables contain complex structures, like merged cells what is not possible to describe in md. Using html on the other hand can result in errors when the md is compiled to something else than html, like to pdf. 

Let's decide if we are okay with the html notation or we should change them to md.

**Comment by kedmison** [comment]
They should be in markdown notation.

**Comment by kedmison** [comment]
I did some more reading.  The tables here use a rowspan attribute, and there is no support for this in Github-flavored md notation.  So, a decision must be made: either the tables either stay in HTML format to preserve their rowspan usage, or are structurally altered and can then use markdown.

**Comment by kedmison** [comment]
for the following reasons:
* the tables use rowspan to group rows together
* github supports (and whitelists table html markup, including rowspan and colspan)
* github markdown does not support rowspan

the usage of HTML tables  in chapter 9 is should be considered acceptable.
