### ISSUE TITLE
[RA Ch2] New Items for RA2 2.3.2

### ISSUE THREAD

**Issue by SaadUllahSheikh** [cntt-n/CNTT#1279]
I have noticed few items/points not included in Infra Requirements and want to propose below in 2.3.2 , please support check . 

1. Cloud storage CNI should meet the conformance requirements i.e Application Latency , IOPS requirements not only pass/fail

2. local volume dynamic provisioning must be supported

3.K3S support for Edge deployments should be supported

4. local volume  live migration should be be supported

5. Storage acceleration must be handled on NFVI with Kubernetes only manage control path 

6. Cloud Storage QOS must be supported

**Comment by CsatariGergely** [comment]
1. Latency and IOPS requirements must be inherited from the RM.
2. Didn't we had some discussion about these already?
3. If K3s can be compliant with the requirements of RA2, than it is supported
4. Isn't this a storage backend feature? What is behind the _live_ requirement?
5. RA2 deals with the Kubernetes layer only. If nothing is needed from this layer, than we do not have requirements.
6. What exactly do you mean on this?

**Comment by SaadUllahSheikh** [comment]
@CsatariGergely  @tomkivlin  sorry for late inputs as i was reviewing others docs in CNTT and also kubernetes so ensure requirement is clear , Do check below my inputs for your queries 

1. Latency and IOPS requirements must be inherited from the RM.
**-->i will check corresponding items in RM and if needed will raise there****

2. Didn't we had some discussion about these already?
**-->in RA2  i can not find local volume dynamic provision , currently i  find its all done manual and **-->every time there is new host need to update config for all ******

3. If K3s can be compliant with the requirements of RA2, than it is supported
**-->can we confirm if it is included in RA2 because i can not find items related to it so kindly just confirm it ******

4.Isn't this a storage backend feature? What is behind the live requirement?
**-->Although live migration is backend feature but the CNF has a requirements e.g move its use data , network , service IP along this part is not included . As we all know issues of Live migration with SRIOV even in Openstack so we need include items in CNF world as well ******

5. RA2 deals with the Kubernetes layer only. If nothing is needed from this layer, than we do not have requirements.
--> This item is related to new features in Container ready storage and specifically  Dell/EMC islion which uses data sets from K8S to implement it . In simple the data plane decision is not done on the data path but K8S is participating in this decision so our suggestion is to include it in a way saying that any items related to Storage acceleration must be handled on backend layer with Kubernetes only manage control path


6. What exactly do you mean on this?
--> Although currently K8S supports provisional storage priority class while attaching the Storage with PoD/Cluster using CSI detailed QOS marking like DSCP ,  Traffic Class , VLAN etc are missing . It will impact realization of E2E QOS so we suggest to include it same like servers NFVI handling it

**Comment by petorre** [comment]
> * If K3s can be compliant with the requirements of RA2, than it is supported
>   **-->can we confirm if it is included in RA2 because i can not find items related to it so kindly just confirm it ******

New Edge-focused workstream is about to start, to check all existing documentation and more.

**Comment by tomkivlin** [comment]
From VF2F: @tomkivlin to update once PR for restructure is in place.

**Comment by tomkivlin** [comment]
Closed due to inactivity.
