### ISSUE TITLE
What does req.gen.rsl.02 mean?

### ISSUE THREAD

**Issue by YuPengZTE** [cntt-n/CNTT#1286]
In [RA2](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter02.md), ```req.gen.rsl.02: The architecture should support elastic Kubernetes Service components are not subject to req.gen.rsl.01.```
Does it refer to [ backing-services in The Twelve Factors](https://12factor.net/backing-services) or [VNF Common Service in ETSI GR NFV-IFA 029 V3.3.1](https://www.etsi.org/deliver/etsi_gr/NFV-IFA/001_099/029/03.03.01_60/gr_nfv-ifa029v030301p.pdf#page=13&zoom=100,0,0)?

If not, what does it mean?

Thanks for your answer.

**Comment by CsatariGergely** [comment]
Humm interresting `req.gen.rsl.02` is  "The Architecture should support **resilient** Kubernetes service components that are not subject to req.gen.rsl.01.". So it is about resilient components and not elastic. 
This means that `req.gen.rsl.01` requires all combernetes components to be resilient what are needed to run the workloads uniterrupted whatever happens and optionally the architecture can contain other resilient Kubernetes components to make the architecture more roboust.

**Comment by YuPengZTE** [comment]
Thanks @CsatariGergely .

 I see: 
```req.gen.rsl.01``` is about workloads,
```req.gen.rsl.02``` is not about workloads, e.g. root cause analysis components.
