### ISSUE TITLE
[RA-1 Terminology] Create Terminology Chapter

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1309]
Relabel RA-1 Abbreviations to Terminology and capture content (terms and abbreviations).

**Comment by ASawwaf** [comment]
@pgoyal01 , Is it different between glossary

**Comment by pgoyal01** [comment]
@ASawwaf Some terms are not defined in the OpenStack Glossary and the Reference Model Glossary or require a mapping between the RM terms and OpenStack terms.

**Comment by pgoyal01** [comment]
Based on discussion in PR #1322 label changed to "won't address" (will not be worked on. @rabiabdel to identify where the RA_1 specific Terminology can be added.
