### ISSUE TITLE
[RA-1 Ch03]: 3.4.2.2. Network ( Network Diagram ) 

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1311]
3.4.2.2. Network
The recommended network architecture is spine and leaf topology; however, for small sites, a legacy topology (access/aggregation switches) can be set up.

my recommendation, to remove "however, for small sites, a legacy topology (access/aggregation switches) can be set up."

**Comment by walterkozlowski** [comment]
Hi Ahmed.  I agree we can remove "however, for small sites, a legacy topology (access/aggregation switches) can be set up." It does not add any value.  Is there plaything else you wantme to do with this?

**Comment by ASawwaf** [comment]
Thanks @walterkozlowski  , I will create PR to remove it 
if no objection from our Colleagues 
@pgoyal01  ?

**Comment by pgoyal01** [comment]
@ASawwaf No objection. Thanks.
