### ISSUE TITLE
[RA-1 Ch02] Make Object Storage mandatory

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1313]
req.inf.stg.02 -- make this a "must" | Make Object Storage mandatory
Add a note that the some operators may choose not to implement.

Add conditional notes to some other requirements.

**Comment by deebhatia** [comment]
If RM says it as [optional](https://github.com/cntt-n/CNTT/pull/1285), can we really make a requirement in RA mandatory with a footnote exception?

**Comment by ASawwaf** [comment]
@pgoyal01 , I think , this subject is closed in RM and we decide to make should 
am i right

**Comment by pgoyal01** [comment]
@ASawwaf The RM doesn't take any position.  Object Storage is referenced in RM [5.1.5 Platform Services](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#515-platform-services) in Table 5-7.

|.conf | Feature | Type | Description |
|-- | -- | -- | --|
| nfvi.svc.stg.001 | Object Storage | Yes/No | Object Storage Service (e.g S3-compatible) |

For RA-1, we may need to make this a "must" requirement but with a qualifier a la conditional.

Suggest the following language -- please critique:

**Current:**
| req.inf.stg.02 | Storage | The Architecture **should** provide Object storage for VM Instances. | OpenStack Swift Service (RA-1 4.3.1.4 "Swift") |
|-- | -- | -- | --|

**Proposed:**
| req.inf.stg.02 | Storage | The Architecture **must** provide Object storage for VM Instances. Operators may choose not to implement Object Storage but must be cognizant of the risk of "Compliant VNFs" failing in their environment.  | OpenStack Swift Service (RA-1 4.3.1.4 "Swift") |
|-- | -- | -- | --|

**Comment by ASawwaf** [comment]
@pgoyal01 , I like the proposed clause, However, as far as I know, there is no VNF request an Object storage 

BTW , I am ok with the proposed one
