### ISSUE TITLE
[RC-1 Ch03] Tests for earlier versions or deprecated APIs

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1314]
Test for deprecated or earlier versions APIs/services should be excluded in conformance tests.
The supported API versions are listed in RA-1 Chapter 05.

Examples of deprecated or earlier versions of APIs:
nova-network 
3.3.4.1. Identity - Keystone:: Keystone API v2
3.3.4.2 Image - Glance API v1

**Comment by fuqiao123** [comment]
According to discussion on May 13, the issue are covered in current version of RC.
