### ISSUE TITLE
[RM-Appendix A]What does "vGPUs" mean?

### ISSUE THREAD

**Issue by YuPengZTE** [cntt-n/CNTT#1316]
What does "vGPUs" mean, In ```A textbook example of a capability that transgresses this principle, is SR-IOV. Other, less notable, yet very important examples include vGPUs and other acceleration hardware, such as FPGA``` of [A.5 Hardware-Dependent Coding Policies](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/appendix-a.md#a5-hardware-dependent-coding-policies) and [7.1.2 Hardware-Dependent Coding](https://github.com/cntt-n/CNTT/blob/master/doc/tech/policies.md#712-hardware-dependent-coding)?

vGPUs are not hardware, it is better to delete "v".

P.S.
In Kubernetes, virtual GPU can be provided by sharing, such as [gpushare-device-plugin](https://github.com/AliyunContainerService/gpushare-device-plugin) and [gpushare-scheduler-extender](https://github.com/AliyunContainerService/gpushare-scheduler-extender); In OpenStack, virtual GPU can be provided by passthrough.

**Comment by ASawwaf** [comment]
@YuPengZTE ,We Just refer to GPU as one of special requirements beside HW acceleration to be considered in our roadmap

**Comment by YuPengZTE** [comment]
@ASawwaf, I see, and I fix it with https://github.com/cntt-n/CNTT/pull/1324 and https://github.com/cntt-n/CNTT/pull/1323.
Please check them, thanks.

**Comment by YuPengZTE** [comment]
In order to record more discussions, I reopened this issue.

For some previous discussions, please see https://github.com/cntt-n/CNTT/pull/1324
