### ISSUE TITLE
[Tech Approach]- Fix Figure 1-3: Network Layering

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1321]
@kedmison @rabi-abdel @TFredberg 

Could you plz support to fix the link for "Figure 1-3: Network Layering"

**Comment by rabi-abdel** [comment]
@ASawwaf there is no figure in RM Ch01 called 1-3. was it the scope figure?

Rabi

**Comment by ASawwaf** [comment]
https://github.com/cntt-n/CNTT/blob/master/doc/tech/approach.md 

it was in approach and it is fixed now ( Tomass Figure )

**Comment by ASawwaf** [comment]
@rabi-abdel, it fixed right now we can close it

**Comment by walterkozlowski** [comment]
Closing the issue as it has been fixed
