### ISSUE TITLE
[RM CH01 ] Introduction -1.3 Principles 

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1335]
"if one member wanted to use Ceph, and another member wanted to use Swift "

https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter01.md 

we are comparing CEPH with swift , which from my POV , misleading, we need to remove it

**Comment by SaadUllahSheikh** [comment]
@ASawwaf  my suggestion is to keep architecture language as vendor agnostic as possible  e.g Ceph is a represntative of SDS , Swift in Object storage , vSAN is an HCI Stroage .

Architecture should be also to fork to handle any thing that is strictly based on a specific vendor offering aligning in principle that is based on technologies and not vendors .

**Comment by pgoyal01** [comment]
Not sure why I have been assigned this. For one, I would never write this. Secondly, RAs should discuss technology choices within the main body. In any case the example is wrong as we all know that Ceph supports Swift APIs.
