### ISSUE TITLE
[RA2 Ch02-04]: Separate requirements, functional capabilities and solutions 

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1338]
RA2 meeting on 2020.03.19 agreed to implement @tomkivlin -s suggestion from [issue 1112](https://github.com/cntt-n/CNTT/issues/1112#issuecomment-601162790):
- Ch02 - document requirements, avoid those that define a specific choice
- Ch03 - describe functional capabilities and interfaces - maybe with examples such as CNI/NSM but avoid if possible
- Ch04 - articulate the specifications - i.e. the specific choices and configurations that deliver the capabilities/interfaces (ch03) and the requirements (ch02)

Which should mean CNI is removed from ch02, the networking model is described in ch03 and then the specific interfaces (CNI, eBPF, etc.) and networking solutions (Calico, DANM, Multus, NSM) can be described in ch04. This may also mean ch05 is not required as the interface specs are all in ch04.

**Comment by tomkivlin** [comment]
@CsatariGergely good stuff, thanks.  As you've self-assigned, are you working on a PR?  I will, if not.
