### ISSUE TITLE
[RA2]: Investigate if we would like to enforce Kubernetes Ingress and Egress Policies

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1340]

**Comment by CsatariGergely** [comment]
The primary interface should use them, the question if we would like to enforce this for the secondary interfaces. 
Scope are the protocols Kubernetes already supports on the primary interface (TCP, UDP, SCTP).

**Comment by tomkivlin** [comment]
as per #1341

**Comment by CsatariGergely** [comment]
To fulfill this requirement upstream Kubernetes would need to support multiple pod interfaces.

**Comment by tomkivlin** [comment]
> To fulfill this requirement upstream Kubernetes would need to support multiple pod interfaces.

So - is this a requirement we want to add (and if so, why?), and therefore document as a gap?

**Comment by CsatariGergely** [comment]
> 
> 
> > To fulfill this requirement upstream Kubernetes would need to support multiple pod interfaces.
> 
> So - is this a requirement we want to add (and if so, why?), and therefore document as a gap?

I would rather document this as a gap of Kubernetes. I also have doubts that Kubernetes community would be ever motivated to merge a change like this.
