### ISSUE TITLE
[RA2]: investigate if we would like to use Kubernetes Load Balancing

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1341]

**Comment by CsatariGergely** [comment]
The primary interface should use them, the question if we would like to enforce this for the secondary interfaces. 
Scope are the protocols Kubernetes already supports on the primary interface (TCP, UDP, SCTP).

**Comment by tomkivlin** [comment]
From FV2V: created from a comment in weekly meeting.
@CsatariGergely to clarify requirement, possible solutions and/or gaps to include in chapter08.md

**Comment by CsatariGergely** [comment]
To fulfill this requirement upstream Kubernetes would need to support multiple pod interfaces.

**Comment by CsatariGergely** [comment]
I suggest to conclude, that Kubernetes Load Balancing can not be used in case of multiple pod interfaces are required, but can be used for Pods with a single interface.

**Comment by tomkivlin** [comment]
@CsatariGergely to clarify, we're talking here about which scenario?
1. Load balancing between primary interfaces of multiple pods (i.e. interface1 on each of pod1, pod2, pod3)
1. Load balancing between secondary interfaces of multiple pods (i.e. interface2 on each of pod1, pod2, pod3)
1. Load balancing between any interface of any pod (i.e. interface1 on each of pod1, pod2 and interface2 on pod3)

**Comment by CsatariGergely** [comment]
3. what includes also 1. and 2.. Kubernetes supports only 1 at the moment.

**Comment by tomkivlin** [comment]
> 1. what includes also 1. and 2.. Kubernetes supports only 1 at the moment.

Cool - thought so but wanted to check.  So do we want to create a gap in chapter 6 to log this (and close the issue)?  Or just close it because we're happy for the software vendors to either bring their own load balancing or assume the use of external load balancing?  I'm thinking we should document it somewhere.
