### ISSUE TITLE
[Chapter 1] Rewording suggestion for 1.3

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#136]
@petar.torre@intel.com suggested the following text for 1.3

All NFVI APIs must ensure Interoperability (multi-vendor, components substitution), drive Simplification, and come from Open Communities and Standards Development Organizations. Through such APIs will NFVI resources be discovered/monitored by management entities, configured on behalf of VNFs and consumed by VNFs.

**Comment by bfcohen** [comment]
Seems reasonable.

**Comment by bfcohen** [comment]
Added to Chapter 01.
