### ISSUE TITLE
[RI2] Create a table for RI-2 Installer features derived from RA-2 requirements

### ISSUE THREAD

**Issue by trevgc** [cntt-n/CNTT#1374]
Table will be a working document to list RA-2 requirements and map to features that we need from an installer for RI-2
- Flag which are MVP requirements (what is needed in N months to target next release)
- Link to the table on Wiki https://wiki.lfnetworking.org/display/LN/Table+for+RI-2+Installer+feature+list+derived+from+RA-2+requirements

An installer comparison chart will then show if an installer can fulfill the requirements of RA-2 
- Can it deploy and configure with features installed and configured correctly in a CI/CD environment including test tools?
- Can the environment be brought up in a vendor environment?
- Can the environment be brought up in a public Cloud environment?
- Reference CNF test bed Kubernetes installer comparison https://wiki.lfnetworking.org/display/LN/Kubernetes+Installer+Comparison
	
Describe / define stages of standing up RI-2 and map against tools
  1. Node provisioning
  2. Kubernetes install
  3. Application provisioning
	
Related tickets
[RI2] Kubernetes installer requirements #1242 <https://github.com/cntt-n/CNTT/issues/1242> 
[RI2] Lab requirements #1241 <https://github.com/cntt-n/CNTT/issues/1241> 
[RI2] Kubernetes LCM Automation #1244 <https://github.com/cntt-n/CNTT/issues/1244>

**Comment by rihabbanday** [comment]
I have created a table & slowly started to add requirements (for now only the k8s installer one).

So far the only requirement that I have seen on the application provisioner is "The reference architecture must support the usage of a Kubernetes Application package manager using the Kubernetes API-s, like Helm v3." May be we should have separate tables for capturing the requirements for the node installer & application provisioner .

**Comment by xmulligan** [comment]
I think applicaiton provisioning is outside the scope of the RA and RI. The RA just says it should be supported, not that it is included.

**Comment by xmulligan** [comment]
https://docs.google.com/spreadsheets/d/12EWZVvlumktXoywvmlYPR_DrU34e7Gk_rSED3VyCG4o/edit#gid=0

**Comment by pgoyal01** [comment]
@xmulligan The above Google docs is for RA-2 Requirements

**Comment by xmulligan** [comment]
@pgoyal01 yes the intent was to use that document to see which requirements need to be fulfilled by the installer

**Comment by tomkivlin** [comment]
From RI2 meeting 30/9: a Kuberef/BMRA based RI2 is already in development (see chapter04) and an Airship one is likely to be developed.  Each will use their own built in installer and so discussions at this level are no longer needed and we should focus on traceability between RA2 requirements/specification and RI2 configuration artefacts.
