### ISSUE TITLE
[RA2 Ch4]: Remove not open source CNI plugin

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1378]
#1370 was prematurely merged and added the not open source NSX Container Plugin to RA2. This should be removed.

**Comment by YuPengZTE** [comment]
Yes, we have no way to evaluate the not open-source plugins from different dimensions, and we should evaluate more open-source plugins which are mentioned in [Networking and Network Policy](https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy)
