### ISSUE TITLE
[Chapter 1] Disambiguate VNF vs CNF terminology

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#139]
Hi Beth:
Please address this PR.
https://github.com/cntt-n/CNTT/pull/123

**Comment by xavier-grall** [comment]
Note that PR #193 address the same issue than PR #123, but with a different approach

**Comment by pgoyal01** [comment]
related to #198 and #203

**Comment by bfcohen** [comment]
Discussed endlessly in other Issues.  Taken care of in the Chapter 01 rewrite.
