### ISSUE TITLE
[RA-1 Ch06] Image Security

### ISSUE THREAD

**Issue by yeelinglam** [cntt-n/CNTT#1395]
OpenStack Reference - https://docs.openstack.org/security-guide/instance-management/security-services-for-instances.html#trusted-images/

**Comment by yeelinglam** [comment]
@rabi-abdel - I used the template and it assigned to you by default without option to re-assign.  Could that be changed?  Thanks!

**Comment by rabiabdel** [comment]
I need to figure out how to configure this since we moved to GITHUB teams. Let me try. I am assigning it to you for now.

**Comment by rabi-abdel** [comment]
@yeelinglam it should be resolved now, please let me know if you still can not self-assign or add labels, etc

**Comment by yeelinglam** [comment]
@rabi-abdel - thanks and will do!
