### ISSUE TITLE
[Chapter 5] How the NFVI software profile is a set of virtual resources 

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#140]
In 5.1
"A NFVI SW profile is a set of virtual resources with specific behaviour, capabilities and metrics."

Needs rewording

**Comment by karinesevilla** [comment]
The sentence is wrong. It can be replaced by 
"A NFVI SW profile is a set of features, capabilities and metrics offered by an NFVI SW layer"
