### ISSUE TITLE
[RA01 Ch03] Change NFVI to Cloud Infrastructure

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1403]
@pgoyal01 @rabi-abdel , Change the title of  Ch03 from "NFVI + VIM Architecture" to 
" Cloud Infrastructure Architecture - OpenStack " 

and add into the introduction, 
This CNTT Reference Architecture (RA-1) aims to provide an OpenStack distribution agnostic reference architecture which include NFVi layer ( VIM + NFVi )

**Comment by ASawwaf** [comment]
i am ready to open PR for it

**Comment by pgoyal01** [comment]
@ASawwaf Changed to include all changes to NFVI (all occurrences)
