### ISSUE TITLE
[RC1 Ch2.7.2.] Dead link to the "current test cases selected by CNTT"

### ISSUE THREAD

**Issue by herrib** [cntt-n/CNTT#1406]
https://cntt-n.github.io/CNTT/doc/ref_cert/lfn/chapters/chapter02.html#2.7.2

'2.7.2 Test case requirements:
It’s worth mentioning that current test cases selected by CNTT (https://cntt-n.github.io/CNTT/doc/ref_cert/lfn/chapters/chapter09.html) already leverages on Xtesting which is a simple framework to assemble sparse test cases and to accelerate the adoption of CI/CD best practices.'

The link to the test cases refers an html page which does not exist...

**Comment by collivier** [comment]
@herrib Thank you. Well catch! The content was moved by @rabi-abdel during a key refactoring and we forget a few links. Ideally CNTT should run linkcheck as for Xtesting and Functest.

**Comment by pgoyal01** [comment]
Please change WSxx to the work stream name. Thanks
