### ISSUE TITLE
[Tech Glossary] Cloud Infrastructure

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1407]
Cloud Infrastructure: A generic term covering NFVI and **CaaS** capabilities - essentially the infrastructure on which a Workload can be executed.

and later CaaS is defined as:
CaaS: Container-as-a-Service. A complete set of technologies to enable the management of containerised software, including a Kubernetes cluster, container networking, storage, routing, service mesh, etc.

The definition of "cloud infrastructure" needs to be modified to include RA-1. May I suggest the following change:

Cloud Infrastructure: A generic term covering NFVI and **IaaS/CaaS** capabilities - essentially the infrastructure on which a Workload can be executed.

**Comment by rabi-abdel** [comment]
@pgoyal01 please review and update
