### ISSUE TITLE
[Question] What difference should we do in the model between Datacenter and edge computing ?

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#141]
One of the feedback of former chapter 6 was as follow :

"can we add HW hardening to edge cloud items ?" 

We suggest to extend the feedback to a wider perimeter and clearly define what are the differences that we see between Edge Computing and Datacenter if there are any.

Any opinions are most welcome on the topic as this issue might be general for all the Reference Model.

**Comment by rabi-abdel** [comment]
There will be addressed under General (FAQ) prepared.

**Comment by rabi-abdel** [comment]
we need to address it for the Panel

**Comment by rabi-abdel** [comment]
close as being address in FAQ
