### ISSUE TITLE
[RA1 Ch3] Change Horizon to optinal service

### ISSUE THREAD

**Issue by shawnlee1976** [cntt-n/CNTT#1417]
Ch3.3.1.3 requires Horizon as a required service. However, most venders have built their own GUI to provide same functions of Horizon and more enhancements. I suggest that the architecture must provide a GUI for user(like required in Ch2) but Horizon should be an optianl choice. It's not a must-have service on control nodes.

**Comment by pgoyal01** [comment]
@shawnlee1976 When you say "most vendors" can you specify the nature of the vendors? The Telco cloud operators all require Horizon. For various functions including operations, Tenants (or projects) utilise Horizon.

**Comment by shawnlee1976** [comment]
Umm.. yes， “most venders” are not accurate words, however some venders such as huawei and zte have their own GUIs which are not Horizon-based services. I do agree that a GUI service should be a required service in the architecture. It should  meet the requirements of operations, tenants, and etc. Just like the Horizon has provided. I just suggest that this GUI should not have to be the Horizon. Any GUI service that meets the requirements should be accepted.

**Comment by pgoyal01** [comment]
@shawnlee1976 We are listing OpenStack services -- Horizon is an OpenStack service.  I hope that you can see that we in CNTT are not in a position to specify requirements for OpenStack services.  IMHO, Vendors with alternate GUIs should get their GUIs approved by OpenStack as a replacement for Horizon; make them part of OpenStack services.

The problem with listing alternate GUI is how RI and RC will get affected.

**Comment by collivier** [comment]
Horizon testing is not part yet of RC (see Functest tempest_horizon) but it's possibly a mistake.
If the results here is that Horizon is mandatory, I will push the appropriate changes in Functest CNTT containers and RC. If it's optional, it will be kept as part of IaaS verification which also runs on RI verification (RI is verified twice: IaaS verification + CNTT Conformance).

**Comment by shawnlee1976** [comment]
I'd like to withdraw this issue. It's better to keep the status quo. Thank you all for joining this discussion.

**Comment by pgoyal01** [comment]
@shawnlee1976 Thanks.

Closing Issue.

**Comment by collivier** [comment]
@pgoyal01 It means that Horizon is mandatory then I do backport horizon testing in RC if doable, right?

**Comment by pgoyal01** [comment]
@collivier Yes -- perform Horizon testing if doable. Thanks
