### ISSUE TITLE
[TSC CONTRIBUTING] Remove requirement to always require an Issue when creating a PR

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1420]
Specifically referring to [L53-L55](https://github.com/cntt-n/CNTT/blame/master/CONTRIBUTING.md#L53-L55):

> - PRs must only be created when there is an issue present and a decision to create a PR is made. A PR must reference the issue it is resolving in the description field.
>  - using GitHub predefined keyword "**Fixes Issue#**" will automatically close the issue which the PR is resolving when it is merged.
>- A PR for an issues must only be created by the contributor assigned to the issue by the respective WSL.

I would propose that for minor editorial changes such as typos, correcting table/figure numbers, correcting broken links etc. that a PR can and should be raised without an Issue being needed.  Proposed change being something like:

> - **PRs dealing with minor editorial changes can be raised without a corresponding Issue, but must be labelled as "**Minor**".  Otherwise,** _PRs must only be created when there is an issue present and a decision to create a PR is made. A PR must reference the issue it is resolving in the description field._
>  - _using GitHub predefined keyword "**Fixes Issue#**" will automatically close the issue which the PR is resolving when it is merged._
> - _A PR for an issues must only be created by the contributor assigned to the issue by the respective WSL._

**Comment by CsatariGergely** [comment]
I like the idea.
