### ISSUE TITLE
[RM Ch05] Storage part to be reviewed

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#143]
Lots of feedback on that topic 

•	Network attached storage
•	Tenant vs storage networking
•	In memory storage vs physical HDD/SSD => different characteristics and use

we need to strengthen this part.

**Comment by karinesevilla** [comment]
PR to be created

**Comment by rabiabdel** [comment]
lack of contribution.

**Comment by CsatariGergely** [comment]
Scope is Ch 5.4.2

**Comment by pgoyal01** [comment]
@samuelhellec would you like to pursue this Issue further and create a PR to make the changes. Thanks

**Comment by walterkozlowski** [comment]
Closed as part of the RM cleanup
