### ISSUE TITLE
[RM Ch08] Chapter 8 references and images are not consistent

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1439]
- There are some images just referred as url-s. There should be turned into proper links or images.
- The reference list does not always contain the link to the referenced documents
- The reference list does not contain the latest versions of the ETSI NFV documents
- The reference list contains 'raw' links in stead of linking from the title of the documents

**Comment by markshostak** [comment]
@CsatariGergely Hi Gergely, The majority (>90%) of the RMCH-8 content is about to be moved/removed. I'd suggest we close this Issue, and revisit after the dust settles, if required. Will that work for you? Have a safe weekend! -Mark

**Comment by CsatariGergely** [comment]
Do we already know which part will be moved and which will be removed? It is still meaningfull to update the part what is not removed.

**Comment by CsatariGergely** [comment]
Oke, all of RM Ch08 is gone now. I think we can close this issue.
