### ISSUE TITLE
[Chapter 5] Network part to be reviewed

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#144]
feedback 

- Entire HW Host Profile (Network) needs to be reviewed. 
- Define what networking and tenant needs are intra vs. inter.=> linked to chapter 3 with definition of tenants
- Table of NIC configuration specify that prot speed is physical
- Number of PCI slot to be reviewed

we need to strengthen this part.

**Comment by karinesevilla** [comment]
PR to be created

**Comment by karinesevilla** [comment]
PR #276 approved and modifications merged the 09/12
