### ISSUE TITLE
[Chapter 5] What does exactly support of flavours mean? Can we add a bit of clarification here?

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#145]
good question 

maybe we have to removed that row from the table 5.1?

**Comment by pgoyal01** [comment]
Flavours are artifacts used by consumers of NFVI  resources -- used to create an execution environment instance. But for the execution environment instance to be created actual physical resources with certain capabilities need to exist or another way of saying "support for flavours." I think the intent of the ask here is to elaborate on what "support" means.

**Comment by samuelhellec** [comment]
we agree with your interpretation. So what could "support" mean ?

**Comment by karinesevilla** [comment]
This intent was to ensure the support of the flavours defined in Chapter 4.
It can be removed.

**Comment by pgoyal01** [comment]
Per @karinesevilla close the issue.
