### ISSUE TITLE
[RA-1 Ch3,4] Provide a table for the possible network flows

### ISSUE THREAD

**Issue by iangardner22** [cntt-n/CNTT#1454]
Provide network flow diagram or table covering how traffic is managed depending on network type:
(we need a network guru to add the correct flows if I get any of this wrong)

Same Tenant Kernel OVS. Traffic uses gre/vxlan and flows from compute to compute and compute to controller
Neutron NAT. Traffic flows from the compute node to the controller and is NAT'd via Floating IP

Provider VLAN. Traffic flows directly to/from the compute node hosting the VM via OVS
Provider VLAN DPDK. Traffic flows directly to/from the compute node hosting the VM via OVS-DPDK
Provider VLAN SRIOV. ...

Differences if we use CVR / DVR

As I say need a guru to validate and add other paths and I'd prefer is you own the PR please :-)

**Comment by pgoyal01** [comment]
@iangardner22 is it more than what is described in [Open vSwitch: Self-service networks](https://docs.openstack.org/ocata/networking-guide/deploy-ovs-selfservice.html)

**Comment by iangardner22** [comment]
> @iangardner22 is it more than what is described in [Open vSwitch: Self-service networks](https://docs.openstack.org/ocata/networking-guide/deploy-ovs-selfservice.html)

Yes this covers a lot of it I agree.  I guess that may be missing SRIOV / DPDK but I think the principles are the same.

**Comment by zhouhuijing** [comment]
I understand that your requirement is to add the packet processing of dpdk and sriov into the diagrams of  https://docs.openstack.org/ocata/networking-guide/deploy-ovs-selfservice.html . And, we also need DVR scenario, including SDN and non-sdn. If my understanding is correct, I think I can try.

**Comment by iangardner22** [comment]
> I understand that your requirement is to add the packet processing of dpdk and sriov into the diagrams of https://docs.openstack.org/ocata/networking-guide/deploy-ovs-selfservice.html . And, we also need DVR scenario, including SDN and non-sdn. If my understanding is correct, I think I can try.

Yes this would be cool.  Thanks!

**Comment by zhouhuijing** [comment]
shawnlee1976 will help me draw these diagrams. Can you send me your email for our further discussion?

**Comment by pgoyal01** [comment]
@zhouhuijing Thanks. Are you asking for @iangardner22 email?

**Comment by iangardner22** [comment]
@zhouhuijing - I can be reached firstname<dot>lastname@vodafone.com  (I won't put my email address here :-) )

**Comment by pgoyal01** [comment]
Major effort required including coordination with Network FG work.

**Comment by pgoyal01** [comment]
Meeting of June 15, 2020, it was decided to wait until the networking model is finalised (Issues #1572 and 1573).

@walterkozlowski to raise it in the RM meeting

**Comment by pgoyal01** [comment]
Closed as per decision of RA1 meeting on October 05, 2020,
