### ISSUE TITLE
[RM ChA] De-Dupe RM and Tech Content

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#1459]
@rabi-abdel Per request, this Issue is to de-dupe RM Appendix A, Section 5, from Tech Section "Policies". Let me know if you want to align on what content should go to which document.

**Comment by rabi-abdel** [comment]
@markshostak Yes, will like to address this as soon as possible. Can this be discussed during RM meeting? or we can have a quick 1:1 to align on this.

**Comment by wmk-admin** [comment]
Closed in PRs #1922, #1923, #1925
