### ISSUE TITLE
[Chapter 5] CPU part to be reviewed

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#146]
feedbacks 

- Be clearer about what is the speed unit of execution, speed, standard metrics, etc. similar have technology to define KPIs.
- How does chip architecture get accomodated. Can we do it from operational model, then down from there.
- CPU architectue is missing from the Compute profile
- Would like to see CPU speed as part of model/profile. and speed of architecture. e.g. m4, m5, c5...
- Simultaneous MultiThreading (SMT/HT) is hardware specific, maybe we need to make it optional or remove it?

During the F2F we said that CPU architecture should be parking lot however some CPU characteristic (eg speed)  should be present .

we need to strengthen this part.

**Comment by pgoyal01** [comment]
Do we need this level of detail in Reference Layers 0-4 (previous Reference Model and Reference Architecture)? Can we specifya minimum clock speed but anything beyond that is likely impractical given the likely variances within our organizations. AWS is one of a few cloud companies that creates new instance types (flavours) based on the underlying hardware technology.  Public cloud service providers, in general, have created hundreds of flavours -- many times quite confusing.  Do we anticipate that our internal clouds will benefit from creating chip technology specific flavours or would they benefit from abstracting away from the chip level details. The latter would result in a more "homogeneous" view of the physical servers and much more operationally efficient.

**Comment by ASawwaf** [comment]
form my POV  , no need to create a flavour based on underneath CPU specification except if there is a big change in CPU arch. or in case of new technologies like FPGA and GPU

**Comment by karinesevilla** [comment]
My opinion on these points:
-	For CPU architecture: I think the reference model document isn’t the right place for that
-	For CPU frequency: It can be added in table 5.13 Compute resources, but doing so we will need to add minimum values for each profiles

**Comment by karinesevilla** [comment]
PR #309 approved the 09/19
