### ISSUE TITLE
[RM Ch05.1.5] Possible typo in the Title of table , also contents  need update with below points

### ISSUE THREAD

**Issue by SaadUllahSheikh** [cntt-n/CNTT#1465]
Table 5-7: Virtual Networking Acceleration features ---->Table 5-7: Cloud Infrastructure Platform services.

Also suggest to add following in this table as minimum requirements 
1. Database as a service e.g Cassandra 
2. Queue e.g Rabbit MQ
3. LB and HA Proxy

**Comment by pgoyal01** [comment]
@rabi-abdel PR #1558 fixed this issue and is already merged. This issue #1465 needs to be closed

**Comment by rabi-abdel** [comment]
> @rabi-abdel PR #1558 fixed this issue and is already merged. This issue #1465 needs to be closed

noted. thanks @pgoyal01
