### ISSUE TITLE
[RI1][RC1] Add tempest_horizon in CNTT

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1472]
Horizon is mandatory in CNTT and then must be covered by Functest tempest_horizon.
The test was backported to Hunter and then must be listed in RC and executed into RI.
https://gerrit.opnfv.org/gerrit/c/functest/+/69932

**Comment by collivier** [comment]
@pgoyal01 conforming with our previous discussions.

**Comment by jayacha** [comment]
@collivier work is completed, updting the section in RC
