### ISSUE TITLE
[RA2 Ch02] Specify Workload Requirements

### ISSUE THREAD

**Issue by xmulligan** [cntt-n/CNTT#1496]
RA needs to specify CNF requirements to be tested in RC2

From April virtual meeting:

**CNF artefact compliance**
- is CNF Conformance looking to test CNF and the platform?  what's the scope and direction?
   - main scope is cloud native principles and capabilities of the platform/CNF - no functional testing of the CNF or platform otherwise
   - available now is the workload test - the framework can run both, main focussed on trying to map requirements from CNTT to Kubernetes conformance tests and then identifying gaps to fill with new tests
   - these gaps is where we can decide whether to add into CNF Conformance or something else that's a better fit
   - idea is to cover everything from platform through to workload from a cloud native capabilities perspective

**CNF functionality**
- gaps in the definition of these requirements - where should they live?
   - testing 3gpp spec? - feels out of scope for RC2
   - testing cloud native behaviours? need to write this down - maybe best for CNF Conformance to test?
   - testing conformance with CNTT e.g. abstracted interfaces, using the interfaces specified in RM/RA2? - where should we make these explicit, needs to be in CNTT, either RA2 or RC2.
   - RA2 should define the specification, RC2 should define how to test conformance to that specification

**Comment by taylor** [comment]
There is a cross-community collaborative effort to gather the requirements for running Cloud native workloads which can be used by everyone (eg. RA-2, RC-2, OVP-2, CNF Conformance)
- Spreadsheet gathering requirement ideas, test tracing, etc https://docs.google.com/spreadsheets/d/1TxrrCDKQEzca_snuIXMAcz4GCHj9b99-Obnhs20rCB0/edit#gid=2002882762
- Intro slides: https://docs.google.com/presentation/d/1rTUDacKW96IUJYt-QckITmxwRUD1l8pFZe1xCqyK6yo/edit?ts=5f1f18cd#slide=id.g8d1cd95f5e_1_184

**Comment by taylor** [comment]
Cross-posting a comment from https://github.com/cntt-n/CNTT/pull/1793#pullrequestreview-448093640 here:

> Ideally all layers of a workload would be implemented using cloud native principles from the smallest component all the way up. In the end your workload is a composition of of all the network service end points. If every network service end point is implemented cloud natively then the entire workload would be cloud native.
> 
> Regarding the definition specifically, a CNF is a cloud native application, specifically one that focuses on providing some type of network service (eg. nat, packet inspection, ipsec). A cloud native application, by definition, is developed following cloud native principles. One of those principles is that the application uses discrete, reusable components, with their dependencies packaged with them. In other words microservices. As the building blocks if they do not follow cloud native principles (eg. immutability, declarative APIs) then the application likewise will fail in some or all of those areas.

As far as RA-2 workload requirements are concerned, while a cloud native property/principle can be explicitly spelled out for a specific requirement, more importantly is to ensure all requirements can be implemented using cloud native principles.

**Comment by pgoyal01** [comment]
One thing we need to be careful about is specifying what workloads needs are from the Platform/Cloud infrastructure. For the design and characteristics of CNF at one time, I think, we were going to create an Appendix that would act as a Guide to CNF Vendors.

**Comment by taylor** [comment]
@pgoyal01, if we bump requirements for the workload (and their service components they are composed of) to an appendix we will need to bump the RC-2 workload requirements as well (if they follow other testing where it maps to RA-2).

Wherever it happens, having requirements, implementation, and testing for cloud native workloads would be beneficial to Telcos IMO.

**Comment by pgoyal01** [comment]
@taylor Understood -- I am not asking all workload requirements to be moved. What I am suggesting is that there are workload requirements w.r.t. what is needed to be supported by the platform and there are the workload design requirements (microservices, loosely coupled, etc.) and that the latter may not be in scope of RA-2. How would we test for some of these workload design requirements. Would we use cyclomatic measures, instead of testing, to quantify the degree of coupling between components and the cohesion within a component?

**Comment by tomkivlin** [comment]
CNF requirements activity has been running, looking at collating requirements from multiple sources: https://docs.google.com/spreadsheets/d/1TxrrCDKQEzca_snuIXMAcz4GCHj9b99-Obnhs20rCB0/edit#gid=39883758

Meeting minutes (meetings are each Tuesday at 9am PT): https://docs.google.com/document/d/1eStYtBIoAvz8kh8k2NtvTnjfKZ_6km9HVzCEBt4s0tY/edit#heading=h.tqki8edcltqu

**Comment by tomkivlin** [comment]
Likely to move this to backlog - to confirm next week.

**Comment by tomkivlin** [comment]
Clear position agreed between CNTT and CNCF:  RA2 shoudl only deal with requirements that workloads have in order to interoperate with an RA2-compliant platform. Cloud native best practices and the requirements relating to those will be handled in either the CNCF TUG or CNF Working Group.

**Comment by tomkivlin** [comment]
Given the above, I would argue that RA2 doesn't have any requirements relating to workloads that need documenting in ch02.  Instead, the requirements for the workloads need to take the form of architecture specifications that we document in ch04, section 4.9.  Please disagree here if you think that's wrong - will give a week before closing if there is no problem.

**Comment by xmulligan** [comment]
closing per Tom's comment above
