### ISSUE TITLE
[RA-2 Ch04] 4.5 CNI Plugins

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1499]
[4.5 CNI Plugins](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter04.md#45-cni-plugins) refers to DANM for meta plugin in the text implicitly implying it to be the preferred meta plugin. I don't believe that to be the intent but we should correct any perceptions.

IMO, from a requirements perspective, we should only evaluate features that should be performed by a meta plugin; not compare extraneous features that a particular meta plugin may or may not support. 

With that in mind may I suggest that we evaluate the need for the following requirements to be part of a meta-plugin evaluation:

| Requirement | Requirement Description |
|----------|-----------|
| req.inf.ntw.02 | The Architecture must support intra-node communications, such as between agents on a node and all pods on that node |
| req.inf.ntw.03 | The Architecture must support inter-node communications without NAT, such as communications between pods on a node with all other pods on all nodes |
| req.inf.ntw.04 | The Architecture must support low latency and high throughput traffic needs. |
| req.inf.ntw.10 | The networking solution should be configurable in an automated manner using openly published API definitions. |
| req.inf.ntw.11 | The networking solution should be able to be centrally administrated and configured. |
| req.inf.ntw.14 | The Architecture must support capabilities for integrating SDN controllers. |
| req.inf.ntw.15 | The Architecture should support Service Mesh Interface (SMI). |
|  | Cluster wide IP address management |

**Comment by CsatariGergely** [comment]
The metaplugin has affect an almost all networking features, therefore a full analyzis of the requirements is needed. The table proposed in #1532  marks the non relevant features, like SFC as "Non relevant", there fore #1532 should close this issue.
