### ISSUE TITLE
[RA-1 Ch4] Change the sizing rules of control nodes

### ISSUE THREAD

**Issue by licayun** [cntt-n/CNTT#1501]
For some edge cloud there are only a few of compute nodes. Three control nodes are a little wasteful for such an environment. 
And For Large-scale cloud there more thhan 1000 compute nodes.Four control nodes are some shortcomings for such cloud
So I suggest that we set principles but not strict restrictions for numbers of control nodes

**Comment by pgoyal01** [comment]
@licayun Can you please list out the changes that you want made? This issue has been open for a while without any further prgress.

**Comment by pgoyal01** [comment]
Meeting of August 3, 2020, decided to close. If this concern is raised again a new issue shall be opened.
