### ISSUE TITLE
[RM  Ch07] Strong separation between tenants

### ISSUE THREAD

**Issue by tianliangma** [cntt-n/CNTT#1503]
7.4.3 Platform security requirements "Strong separation between tenants - ensuring network, data, and runtime process isolation between tenants"

 In addition to the above, it should also contain   CPU running core isolation and memory isolation  between tenants

**Comment by karinesevilla** [comment]
Now in section 7.3.3
Enhance the description (7.3.3) per @tianliangma comment and add a link to requirements in 7.11.3.
Rephrase or improve requirements in 7.11.3 and 7.11.4 if necessary
