### ISSUE TITLE
[Chapter 3] Need and Information Model

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#151]
**Comment from Paris Meeting: Chapter 03 Infrastructure Abstraction - GAPS (Day 1):** 

related to the Etherpad issue "Discovery of Resources"

**Comment by BernardTsai-DT** [comment]
Would you have further details clarifying the issue?

**Comment by pgoyal01** [comment]
@BernardTsai-DT this issue is from the Etherpad list -- a couple of folks felt that a model chapter needed an Information Model.  In the RM, this could be restricted to the objects exposed to the identified Actors; viz., not get into an Information Model, say, for a VIM.

**Comment by BernardTsai-DT** [comment]
@pgoyal01: In the context of this issue I would intend to detail the missing architecture agnostic substructure of the software and physical resources layer.

**Comment by BernardTsai-DT** [comment]
@pgoyal01: How about structuring Chapter 3 in the following was:

Chapter 3: Overview of design principles and the layers
Section 3.1 Virtual Infrastructure Layer
Section 3.2. Software Layer
Section 3.3 Physical Infrastructure Layer

In these layers we would detail the elements of each layer in an abstract manner.

**Comment by pgoyal01** [comment]
@BernardTsai-DT That works. Should the overview be titled, "Overview of the Design Principles and the NFVI Reference Model?"

**Comment by BernardTsai-DT** [comment]
@pgoyal01 That would be a suitable title but since it is in the introduction of the Chapter 3 I would simply write and explain this in the text.

**Comment by BernardTsai-DT** [comment]
Have created a new branch: Chapter-3---Information-model for this issue to capture proposals

**Comment by BernardTsai-DT** [comment]
@pgoyal01: How about adjusting the model overview diagram slightly to account for your thoughts regarding the software layer 
![Model Overview](https://user-images.githubusercontent.com/52318123/63416025-f7528280-c3fe-11e9-8376-e1acfcbe7e2f.png)

**Comment by BernardTsai-DT** [comment]
The different domains could be detailed in the following architecture blueprint neutral way:

**3.1 Virtual Resources**
![Model Virtual Resources](https://user-images.githubusercontent.com/52318123/63423873-81094c80-c40d-11e9-857c-7a5020d83c88.png)

**3.2 Management Software**
![Model Management Software](https://user-images.githubusercontent.com/52318123/63423914-94b4b300-c40d-11e9-8111-cbb001cbe42b.png)

**3.3 Physical Resources**
![Model Physical Resources](https://user-images.githubusercontent.com/52318123/63423934-9ed6b180-c40d-11e9-849b-e7df8949fc02.png)

**Comment by pgoyal01** [comment]
@BernardTsai-DT These look great

**Comment by pgoyal01** [comment]
Closing #151 as already addressed in the Content (see also comments above).
