### ISSUE TITLE
[RA2 Ch4]: Fixing of mistyped values in CNI comparision table

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1522]
In #1379 I [mistyped the value of the last entry of the CNI comparision table](https://github.com/cntt-n/CNTT/pull/1379/files#diff-54288da3967ac685c0ef740b131abd0aL123). Also the number of these requirements and a title of the table is missing.

**Comment by tomkivlin** [comment]
Fixed in #1532.
