### ISSUE TITLE
[Chapter 10: Gaps] conflict between "standards/open" and "interoperable" 

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#153]
Recognize that there maybe a conflict between "standards/open" and "interoperable" 
Add as an action item to Chapter 11: Gaps

**Comment by tomkivlin** [comment]
@rabi-abdel should this have chapter 11 as a label, not chapter 9?

**Comment by rabi-abdel** [comment]
Fixed to Chapter 10

**Comment by rabi-abdel** [comment]
Not sure what that issue is :) will close
