### ISSUE TITLE
[RA-2 Ch04] Shall requirements listed in Ch04 moved to Ch02?

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1538]
There are requirements listed as bullets points in Ch04 for each of the components, shall they be more structured (i.e. added into a table or moved to Ch02)?

@tomkivlin @CsatariGergely

**Comment by tomkivlin** [comment]
@rabi-abdel yes, but I think this is covered by #1525?

**Comment by tomkivlin** [comment]
Confirmed it is.
