### ISSUE TITLE
[RM Ch01] Language

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1542]
"open source implementations that have an open governance model"

I think the intent here is to say that the "open source implementations" should be from sources with an "open governance model" but that is not what it says.

**Comment by walterkozlowski** [comment]
@pgoyal01 can you point to the offending sentence please?  I cannot find it.

**Comment by pgoyal01** [comment]
@walterkozlowski Sorry about that but there is a merge since I opened the issue and maybe the sentence was deleted. Closing the issue.
