### ISSUE TITLE
[RM Ch04] Information about how to incorporate NFVI acceleration technology

### ISSUE THREAD

**Issue by bfcohen** [cntt-n/CNTT#155]
The following issues belong in CH2-4: VNF drivers and where they live. How to expose hardware? Lose benefits of SRIOV? Etc.
Defining acceleration interfaces.
How exactly will ref model and ref arch certifications work?
Exposition of acceleration technologies to VNFs?
Acceleration embedded into VNFs or into NFVI?
Comment RH: VNFs suppliers will not support all the acceleration technos offered by NFVI, VNFS care about what NFVI is
Certification? OVP NFVI certifcation program, expand OVP to CNTT objectives

**Comment by wmk-admin** [comment]
Closed in PRs #1922, #1923, #1925
