### ISSUE TITLE
[RM Ch07, RA1 Ch02] Alignement with ONAP security requirements

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1552]
Per discussion during CNTT-ONAP joint session, April's Virtual conference
References to ONAP securtity requirements, mainly about workloads can be added in chapter 6

**Comment by pgoyal01** [comment]
Collected ONAP Security Requirements and ONAP VNF Security Requirements. Will create a wiki page for common review before making changes to RM and RA_1 Security Requirements.

**Comment by karinesevilla** [comment]
RM security requirements must be reviewed first.
ONAP security requirements analysis has been identified to enhance security requirements. Refer to issue#366

**Comment by pgoyal01** [comment]
Links: https://wiki.lfnetworking.org/display/LN/RM+and+RA-1%3A+ONAP+Security+Requirements and https://wiki.lfnetworking.org/pages/viewpage.action?pageId=34607866
