### ISSUE TITLE
[Chapter 03] Reference Model

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#156]
Currently includes RL-0 Reference Model
RL-2 Reference Architecture -- first version based on OpenStack

IMHO, there is wide gap between the RL-0 abstract model and the RL-2 OpenStack based High Level Reference Architecture. Suggest a cloud-technology agnostic RL-1 model.

**Comment by BernardTsai-DT** [comment]
I was wondering if we should differentiate between the model for the virtual infrastructure resources a NFVI is providing and the management component. I had the impression that 3.1 was more related to the abstraction of the resources whereas the model you have shared was more focussing on the management component. Or did I get something wrong here?

**Comment by pgoyal01** [comment]
@BernardTsai-DT Totally Agree. Question is how do we include RL-1 related materials and incorporate them with whet were originally just RL-0 materials.

**Comment by pgoyal01** [comment]
Closing #156 as the issue is addressed in the content.
