### ISSUE TITLE
[RA-1 Ch03/04] Network Edge

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1573]
Incorporate Network Edge

**Comment by bfcohen** [comment]
What changes need to be made in Chapter 2,3 and 4 to support the Edge requirements.  These are hopefully expansions of the existing work to include any new or modified requirements that are needed for edge.  WAN, network constraints, HW constraints, etc.

**Comment by pgoyal01** [comment]
@ASawwaf created wiki page to gather all inputs: https://wiki.lfnetworking.org/display/LN/CNTT+Edge+-+RA01+%28+OpenStack+%29+Architecture+-+Scenario

**Comment by pgoyal01** [comment]
In Edge WS meeting of September 8, 2020, it was decided to move this for work to Backlog for work in the next release.
