### ISSUE TITLE
[Chapter 8] Assess Open Stack and OPNFV Test Harnesses

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#158]
**Specific Action**
-	JB - Action - are tests that legitimately belong in OpenStack, or stay in OPNFV?

**Comment by kagreenwell** [comment]
FuncTest (OPNFV) project incorporates OpenStack Tempest (API validation) and Rally (performance benchmarking) as part of their test suite. I do not believe there is a need to choose one or the other.

**Comment by mf4716** [comment]
This is just clarification, as you mentioned, that OPNFV draws other projects for test verification.  Anything that belongs to a product/project for testing downloads and incorporates what is needed for that verification effort. Assigned to Jonathan Beltran for confirmation/closure.

**Comment by jbeltranatl** [comment]
I believe the clarification of this comment is simply that we (CNTT test solutions) should not recreate wheels that already exist in other project. In practice I don't personally know what pencils out to, but I suspect that other entities (i.e. ONAP) test scripts that we need to leverage for a Common NFVI certification should stay, live, breath, and be cared for still in ONAP. Therefore, the Common NFVI has those particular scripts/process/platform/etc. has an upstream dependency that needs to be tracked and cared for in the SDLC--which I believe is typical of other open source project dependency approach. Make sense?

**Comment by mf4716** [comment]
Agree.  We're aligned.  We'll add as a principle.  Closing.
