### ISSUE TITLE
[RM Ch05] 5.1.4 Security

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1583]
5.1.4 Security
Comment: To be worked on.

what is the content that should be there

**Comment by CsatariGergely** [comment]
5.1.4 is empty. Security if discussed in Ch7 of RM. All consolidated requirements are in 7.11. @ASawwaf can you clarify what should be changed in 5.1.4 or in 7.11?

**Comment by pgoyal01** [comment]
@ASawwaf already addressed this. The current content of 5.14 currently has "Please see the [RM Security Chapter](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md) and, in particular, the [Consolidated Requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#711-consolidated-security-requirements) section."

@walterkozlowski I suggest that we close this Issue as it has already been addressed. Thanks

**Comment by walterkozlowski** [comment]
@ASawwaf already addressed this. The current content of 5.14 currently has "Please see the RM Security Chapter and, in particular, the Consolidated Requirements section."
