### ISSUE TITLE
[RC1 Ch01] Provide Verification Process, including Life Cycle Management

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#159]
**Specific Action**
-	JB - Action - Verification will show which validation it passed, lifecycle management, etc. -- need to clean up relationship between CNTT, ONAP, etc.
-	JB - Action - need to define where the test cases would live? What is the handover between CNTT and OPNFV.

**Comment by mf4716** [comment]
Updated.

- CNTT-RI project (or related project once approved) will be responsible for extraction and implementation of test cases into CVC / OPNFV.  Existing test projects will have related RI test cases, unless not applicable or technically possible.  Then, physical RI test cases/harnesses will reside within the CNTT-RI (or related CNTT project) project.
- Ch 8 has a section for test results, and another for life cycle management currently a WIP.

**Comment by mf4716** [comment]
@rabi-abdel - please confirm if you can own this item and close per recent CNTT>OPNFV>CVC and project proposal discussions

**Comment by mf4716** [comment]
See my comments below.  Please confirm a) your assistance on this item, b) status, and c) next steps.

@rabi-abdel @rabiabdel - are you still reviewing/analyzing?

@kagreenwell - are you assisting, or working on this in parallel? 

**The Action:** "Verification will show which validation it passed..clean up relationship between CNTT, ONAP, etc." **--> @mf4716 comment:** Dovetail test results will show test results.  CNTT will execute VVP test suites for interopability validations.  ONAP will continue BAU for orchestration+VNF validations.  ONAP will be invoked via the OVP Ecosystem if desired after CNTT validations.

The Action - need to define where the test cases would live? What is the handover between CNTT and OPNFV. --> @mf4716 comment.  Test cases will reside in a) preexisting OPNFV test suites, and/or b) specific to an onboarded Test Project.

**Comment by kagreenwell** [comment]
I see LF/CVC project "VNFSDK" as an input for us. We rely on VNFSDK to provide an ONAP certified package. We take that package and test using OVP. In this way a VNF will earn two badges (ONAP + OPNFV VNF).

Agree that test cases should reside in existing OPNFV test suites. CNTT should not own any test cases/suites. We should be making recommendations to other OPNFV test projects. If desired, CNTT can contribute test cases to those projects where gaps exist.

**Comment by mf4716** [comment]
@kagreenwell - can you work to close this out with Rabi?  Also, identify where in our document(s) we need to make updates/modifications (Please)?  FYI --- VNFSDK is Tosca validations, for which we are subscribing we will perform, but not a prereq, or input, to provide an ONAP certified package.  At least not from an NFVI perspective.

**Comment by rabi-abdel** [comment]
@mf4716 @kagreenwell yes I am happy to take this item. once the overall lifecycle is agreed on, I am happy to add the diagram to the chapter.

**Comment by rabi-abdel** [comment]
PR will be created for next Thursday Meeting

**Comment by rabi-abdel** [comment]
Hello All, I have added few diagrams to the CNTT-RI repository:
https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter01.md

which sets some of the framework for this content. I don't think it belongs to Chapter 8 in RM.
if you are OK whit the above, we can close this issue.
@mf4716 @kagreenwell

**Comment by kagreenwell** [comment]
Between this additional content and the various mentions of how we interoperate with other organizations already mentioned in the chapter, I am satisfied.

**Comment by mf4716** [comment]
@rabiabdel - status?  and, did you mean to change the label from Ch 8 to Ch 1?  If Ch 1, we can edit the title and change to ch 1

**Comment by mf4716** [comment]
Confirmed w/ Rabi, not required for Botrange, and should be Ch 1.  Removed the Botrange label and updated the title from Ch 8 to Ch 1.

**Comment by mf4716** [comment]
@rabi-abdel - please confirm status for this item.  Thanks

**Comment by rabi-abdel** [comment]
@mf4716 I think this issue can be closed now as it has been resolved. do you agree?

**Comment by mf4716** [comment]
@rabi-abdel - we cannot close until we move the diagrams/content from RI / RM to RC1 Ch01.

**Comment by mf4716** [comment]
@rabi-abdel - is this complete?

**Comment by mf4716** [comment]
@rabi-abdel - is this complete?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@rabi-abdel still applicable?  quite old

**Comment by fuqiao123** [comment]
I will close this one since it is very old and all the subjects have been accomplished already.
