### ISSUE TITLE
[RM Issues Logging] Logging issues for Baraque release

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1598]
Based on the roadmap discussed for Baraque release:
https://wiki.lfnetworking.org/display/LN/CNTT+Baraque

Please do the following:
- Go through all backlog issues in your Project (RM).
- Identify the issues that are needed for Baraque release:
  - remove the 'backlog" label.
  - assign M3 Milestone to them.
- Create any additional issues that are needed for Baraque release and assign the correct project (RM) and correct Milestone to them.

**Comment by kedmison** [comment]
In progress; 20 issues reviewed with RM team and moved to M3 as per https://wiki.lfnetworking.org/display/LN/2020-05-27+-+%5BCNTT+-+RM+Workstream+Master%5D+Agenda+and+Meeting+Minutes

Still remaining to review: issues proposed for outright closing, and issues proposed to not address in Baraque release.
