### ISSUE TITLE
[Chapter 8] Add Degrees of Passing to Verification Process

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#160]
**Specific Action**
-	JB - Action - need to consider degrees of 'passing', clarify conformance vs. performance. Need to analyze upstream reuse vs. new.
- Ensure clarification of:
: JB implementations to be certified not the model and ref arch (they are documents/artifacts)
: JB reference implementetion needs to pass all tests

**Comment by kagreenwell** [comment]
Functional testing should not have levels/degrees of pass/fail. They are boolean. A decision needs to be made on performance test cases as to how data is presented after completion. Are we going to present hard numbers of test results? Are we going to set a baseline performance value per test and report pass/fail against that number?

**Comment by mf4716** [comment]
My thoughts - 

**Functional testing:** Agree.  P/F based on assertions used.  

**Perf testing:**   Baseline perf tests is desired for comparisons purposes against the Non-functional Requirements (NFRs).  NFRs should be the P/F criteria - e.g. resource util, response times, latency, sustained TPS, delta from baseline metrics, etc.

**Comment by mf4716** [comment]
Closed.  Included/added two relevant sections to address the issue:

- Section 8.7.3 includes exit criteria which reads, "All Test Cases have a status of “Passed”, “Failed”, “N/A” or “Out-scoped”...All Severity 1 and Severity 2 issues are resolved.

- Section 8.8 reads: Test suites will be categorized as functional or performance based. Results reporting will be communicated as a boolean (pass/fail). The pass/fail determination for performance-based test cases will be made by comparing results against a baseline. Example performance-based metrics include, but are not limited to: resource utilization, response times, latency, and sustained throughput per second (TPS).
