### ISSUE TITLE
[RC02 Ch05] initial content of CNF requirements

### ISSUE THREAD

**Issue by xmulligan** [cntt-n/CNTT#1615]
For Baraque Release Planning https://wiki.lfnetworking.org/display/LN/CNTT+Baraque

Badging/Reporting Requirements.
Framework Requirements.
Categories of testing.

**Comment by xmulligan** [comment]
on hold until there is progress on #1496

**Comment by taylor** [comment]
RA-2 #1853 is also relevant and needs progress
