### ISSUE TITLE
[RC02 Ch03] initial content of Kubernetes Traceability Matrix

### ISSUE THREAD

**Issue by xmulligan** [cntt-n/CNTT#1616]
For Baraque Release Planning https://wiki.lfnetworking.org/display/LN/CNTT+Baraque

Reference to CNTT Req (RM, RA-2).
Category (Conformance, Benchmarking).
Type: Performance, Functional, etc.
High Level Test Case Definition.
Criteria (May, Should, Must, Info).
Covered in the industry (Yes/No)
Reference to Test Project/Name covering it.

https://cntt-n.github.io/CNTT/doc/ref_cert/RC2/chapters/chapter03.html

**Comment by taylor** [comment]
Changed `Reference to CNTT Req (RM, RA-1)` to `Reference to CNTT Req (RM, RA-12)`

**Comment by taylor** [comment]
There is no other RC chapters with an example structure.  The Openstack RC also has no structure.

We could start with something from RA-2 Chp4 https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter04.md

**Comment by taylor** [comment]
Example


|Ref|Specification|Details|Requirement Trace|
|---|---|---|---|
|`ra2.ch.001`||||
|`ra2.ch.002`||||
|`ra2.ch.003`||||

**Comment by taylor** [comment]
Suggestion use chapter 2 for requirements.  Example https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter02.md#221-cloud-infrastructure-software-profile-capabilities

**Comment by taylor** [comment]
The structure of RC-1 ([chapter 3]( https://cntt-n.github.io/CNTT/doc/ref_cert/RC1/chapters/chapter03.html))is not a perfect fit by any means but it's a start.   The TOC can be worked out based on RA-2 sources like
- [RA-2 Chapter 2](https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter02.html)
- [RA-2 Chapter 3](https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter03.html)
- [RA-3 Chapter 4](https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter04.html)

and anything from the RM.

The test mapping / content layout for RC-1 chapter 3 (openstack platform test traceability) is not like what was suggested for the RC-2 chapter 3 as far as I can tell.  Specifically the main mapping from tests (names specifically) to requirements (not by id) is at the very end in one table with two columns: https://cntt-n.github.io/CNTT/doc/ref_cert/RC1/chapters/chapter03.html#3.4.  

The rest of the content in RC-1 Chapter 3 mainly focuses how an entire set of tests covers an *area* of requirements from a high-level.  What should be excluded it tested is listed.  

There was a section (which is now commented out) under 3.3.1 Architecture and OpenStack Requirements which had an extensive mapping.  

IMO, it does not seem like this layout and majority of the type of content shown is a good fit for RC-2.

The intro to https://cntt-n.github.io/CNTT/doc/ref_cert/RC1/chapters/chapter03.html#3.3.4 does look like a good starter for RC-2 communicating that the test suites being used cover many items.  Eg. K8s Conformance will cover a large number of requirements.
