### ISSUE TITLE
[RA1- Ch02] APIs: requirements for all OpenStack Mandatory Services APIs

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1621]
In section 2.3.4 "Interfaces & APIs requirements", we should add a dedicated requirement for each OpenStack mandatory service. Currently, only "Horizon" and "Placement" have a dedicated requirement and req.int.api.01 is too generic to cover all the other services

**Comment by pgoyal01** [comment]
Opened to make changes
