### ISSUE TITLE
[RM ] Table numbers are inconsistent

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1625]

**Comment by pgoyal01** [comment]
@CsatariGergely As part of fixing Issue #816 - Consistency, PR #1756 corrects the following Table issues in Chapter 04:

Duplicate Table number 4-12: Renumbered second Table 4-12 "Predefined Compute Flavours" to Table 4-13; existing Table 4-13 and 4-14 renumbered as Table 4-14 and 4-15, respectively'; there was no Table 4-15.

Renumbered Table 4-19 to 4-17.

**Comment by walterkozlowski** [comment]
Fixed
