### ISSUE TITLE
[RM Ch08] Include VNF Requirements and Analysis

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#163]
Specific Action
- Action - add VNFs that are being certified in ONAP (link to ONAP requirements somewhere in model)
- Action - what is the acceptable packet loss in the model?
- Action - Connect work done on alarm correlations w/ONAP OMS? PTL synergies with CNTT) for Service Assurance

**Comment by walterkozlowski** [comment]
Chapter 8 removed from RM
