### ISSUE TITLE
[RA2 Ch04] Define configuration parameters of CNI plugins

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1637]
As it was discussed in the [RA2 meeting on 2020.05.28](https://wiki.lfnetworking.org/display/LN/2020-05-28+-+%5BCNTT+-+RA2%5D+-+Meeting+Agenda+and+Minutes) RA2 should specify the CNI plugin parameters what are mandatory to set for an RA2 compliant infrastructure.

**Comment by tomkivlin** [comment]
Some suggested write-up for networking:
[RA2-Ch4-Networking-Specs-2020-07-17.docx](https://github.com/cntt-n/CNTT/files/4938945/RA2-Ch4-Networking-Specs-2020-07-17.docx)

_Originally posted by @pgoyal01 in https://github.com/cntt-n/CNTT/pull/1805#issuecomment-660207366_
