### ISSUE TITLE
[Chapter 8] Update Environment Guidelines to include +1

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#164]
**Specific Action**
- JB - consider environmental requirements +1

**Comment by kagreenwell** [comment]
Im not sure what the ask here is? Is this just referring to the RI? If so, I think we could probably close this as it will be covered by default as we expand the RI.

**Comment by mf4716** [comment]
The question has a few parts:  1) Who is responsible for setup/maintenance of labs?  Believe the answer is OPNFV will facilitate this need (need Bin to verify; added as assigner).  2) Do we need labs to support an N+1, or multiple versions of RI (assume different OPNFV releases)?  Need Rabin/Bin to confirm how many labs can be used, or secured, by one particular team, and for how long.  We may need a practice which support N and N+1 type lab arrangements, but presumably not indefinitely.  Perhaps this is ad-hoc, on demand, and labs can be used for a finite period.  (Assigning Rabi/Bin to help.)

**Comment by mf4716** [comment]
Emailed Bin Hu for clarification to questions.  Then, will need to insert this info into the Ch 8 Annex to ensure we have a location to retain the info.

**Comment by hubenjamin** [comment]
1) Who is responsible for setup/maintenance of labs?

In the past, individual companies that donated a lab would be responsible for setup and maintenance of the lab. e.g. Intel is responsible for setting up and maintaining Intel's community lab. They would then share the lab information in the wiki https://wiki.opnfv.org/display/pharos/Community+Labs, including:
- where the lab is
- how many physical pods and virtual pods are available
- contact person
- and other details on the left-hand column.
Use Intel as an example, their details are described in https://wiki.opnfv.org/display/pharos/Intel+Hosting, including lab policy and how to apply for VPN access. The child page https://wiki.opnfv.org/display/pharos/Intel+Lab also gives detail of each pod and lab topology.

The lab resource availability and process of using the lab is quite straightforward.

2) Do we need labs to support an N+1, or multiple versions of RI (assume different OPNFV releases)?

In CNTT case, the "lab" concept could one physical Pod or multiple Pods in a community lab. Still use Intel as example, you can apply for 3 Pods, Pod 1 can be "CNTT Lab 1", Pod 2+3 can be "CNTT Lab 2", etc. subject to the availability of Pods. Each "Lab" can be used for different purpose, e.g. "CNTT Lab 1" (Pod 1) for RI-1, "CNTT Lab 2" (Pod 2+3) for RI-2 etc.

All you need to do is to identify how many hardware you need, then you will know how many Pods you need. Then apply for use of Pods according to your need.

If you have special hardware or topology requirement, e.g. special NIC or hardware accelerator or you want 8 servers in one Pod that is different from default settings in a lab, talk to lab owner directly, and they will see if they can make special setup for you or not.

3) How many labs can be used, or secured, by one particular team, and for how long?

As long as you need and resource available, you can have as many as you want. But if you are given a Pod, but it is barely used, Lab owner will take it back and assign to the team that needs it and uses it more frequently.

**Comment by mf4716** [comment]
@mf4716 - put in RI.  Generate PR and close.

**Comment by mf4716** [comment]
Updated CNTT-RI Ch2 - created section 2.5 Lab Use Guidelines, and inserted content from the issue log re: considerations for lab use, support, and needing N+1 labs; created a PR, requesting approval and merge
