### ISSUE TITLE
[Tech Glossary] Add carrier grade

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#1646]
Add carrier grade definition to the Glossary

**Comment by petorre** [comment]
Like `Carrier Grade is a system or a component that is extremely reliable, well tested and proven in its capabilities. Carrier grade systems are designed and tested to meet or exceed "five nines" high availability, and provide very fast fault recovery.` following https://en.wikipedia.org/wiki/Carrier_grade ?

**Comment by walterkozlowski** [comment]
Fixed in PR # 1706
