### ISSUE TITLE
[RC1, RC2] Assess Need (and Add) for KPI & Benchmark Tables, including Conformance 

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#166]
Specific Action
- Action - what is the acceptable packet loss in the model? ch03 to define, mapping in ch04
JB Clarify about KPIs, benchmarking, other parameters, options, extensions, methods in the KPI area in which chapters?
Metrics and Benchmarking: ETSI NFV TST009 
- Include information on how to view Conformance (to standards, functional and perf benchmarks)

**Comment by kagreenwell** [comment]
5 9s is the typical telco expectation for service. If this is the case, packet loss for performance testing must be capped at 0.001%.

Common network function performance testing includes RFC2544, RFC6349, and RFC6985. VoIP related applications would include some SIP testing (concurrent calls, calls/second, etc). 
Is there a need to include VNF specific requirements that are dependent on the app? (Im thinking in terms of VoIP applications requiring various iterations of testing for common codecs, transcoding, SIP only vs. SIP+RTP).

**Comment by rabi-abdel** [comment]
@hubenjamin

**Comment by CsatariGergely** [comment]
Ch08 were removed. SLA requirements are defined in Ch03 and Ch04. 
This is more like an RC1 and RC2 issue.

**Comment by walterkozlowski** [comment]
Resolved by the previous actions
