### ISSUE TITLE
[RM Overall] GSMA feedback for cleaning up

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#1667]
we received feedback from GSMA about RM which requires review and action.
[GMSA feedback](https://wiki.lfnetworking.org/download/attachments/38863167/rm_baldy_prd_draft.docx?api=v2)

In anticipation of the next steps in the process for the publication of the CNTT RM as a GSMA PRD being put in place, I have been looking into how to convert the baldy version of the RM into a document format that could be sent through the GSMA approval process. Mostly that seems to go rather well, even if some manual steps are required, but that was to be expected and once the first version is published the effort required for subsequent updates will probably be fine.
 
Having gone through the document though, I noticed a number of things that were odd and may require discussion:
-          Clear editorial issues
-          Some maturity issues that may lead to remarks when sending the document for GSMA approval (e.g. a section with just the standard “lorem ipsum”-place holder text will probably not make it through)
-          Some parts that I couldn’t make sense of (some lines in table 6-3 look really odd for example) on which some guidance would be welcome.
-          Some questions that may save time in doing the conversion, e.g. whether there’s some reference or abbreviation list living somewhere that I have missed.
-          Some questions on what to do with references to other CNTT documents such as the glossary that may or may not be appropriate to keep as references in a standalone GSMA version of the RM. So a decision would be required on whether to include also that content in the PRD or to leave that as a reference.
 
See the comments in attached for a detailed overview. While input on specific comments would definitely welcome, my main question is what would be the best way to move this forward. Some of those issues could be addressed in Github already now for example or they could be fed back in bulk together with all other potential changes during the approval phase (i.e. in the feedback step that was discussed during the presentation in the LFN virtual event). Similarly some of the discussions that need to be had could take place in the GSMA NG subgroup that should be set up because they would be specific to the document on GSMA side or we could have them in the CNTT RM group. Do you have a view on that?

**Comment by walterkozlowski** [comment]
I think we can fix most of these issues now in github.
During this process we can identify any ones that are candidates for the "bulk fix" at time of approval.
And yes, in parallel we need to discuss with the GSMA NG subgroup about their expectation regarding the way this material needs to be presented within GSMA documentation body.  @rabi-abdel, is Tom the right person to talk about organizing such a discussion?

**Comment by CsatariGergely** [comment]
I can help fix some of these in GitHub. I think for the typos and errors we should just file a pr while for the non-trivial changes we should create issues. By bulk, do you mean that we create pr-s with the scope of more WS-es?

**Comment by rabi-abdel** [comment]
@walterkozlowski yes, it will be tom (tpelt@gsma.com) . I suggest getting him to talk us though his feedback either in a TSM call or in smaller meeting.
