### ISSUE TITLE
[Chapter 3] Add use cases to Model

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#167]
This relates to #156 about the need to add RL-1 (technology agnostic) reference model description including use cases that explain how the reference architectures should be operated upon from various actors perspective (VNF Developer, Cloud Service Provider, Cloud Service Consumer).

**Comment by BernardTsai-DT** [comment]
Would it be good to reshape the **chapter 3 Abstraction** in the following way:
3.1. Layer 0 Model
3.2. Layer 0 Resources 
3.2. Layer 0 Management (incl. use-cases) 

I had the impression that the model in RL-1 was more referring to the management aspects. But maybe I am mistaken here.

**Comment by walterkozlowski** [comment]
Yes, it is mostly about Management and Operations, I think.  So we could do the way you propose..
The question is whether this is Layer 0 or rather Layer 1.  That’s what probably we should  discuss.

**Comment by pgoyal01** [comment]
Bernard,

Agree with you and Walter.

The content I provided can be labeled RL-1 VIM Model or NFVI Software Layer HL Components or NFVI Management and Operations.

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by pgoyal01** [comment]
Closing #167 as addressed in Section 3.3
