### ISSUE TITLE
[RM Ch07] Security chapter Clean up & re-arrangement 

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1676]
Work on Security chapter Clean up & re-arrangement

**Comment by pgoyal01** [comment]
For each Section change a PR will be opened.

Suggested Reorg:
•	[7.1 Introduction](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.1)                                                            rewrite
•	[7.2 Principles and Guidelines](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.2)                                         delete 
    o	[7.2.1 Overarching Objectives and Goals](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.2.1)
    o	[7.2.2 Verification Methodologies](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.2.2)
    o	[7.2.3 Governance](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.2.3)
•	[7.3 Common standards](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.3)                                        exchange with 7.4 (this section becomes 7.4) 
    o	[7.3.1 Potential attack vectors](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.3.1)
    o	[7.3.2 Testing demarcation points](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.3.2)
•	[7.4 Security Scope](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4)                                               exchange with 7.3 (this section becomes 7.3) 
    o	[7.4.1 In-scope and Out-of-Scope definition](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4.1)
    o	[7.4.2 Security requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4.2)                        rename Security Domains; edit certification from Fig
    o	[7.4.3 Platform security requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4.3)           move under 7.5
    o	[7.4.4 Workload security requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4.4)         move under 7.6
    o	[7.4.5 Certification/validation requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.4.5)           no content -- delete
•	[7.5 Platform Security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.5) 
    o	[7.5.1 General Platform Security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.5.1)
    o	[7.5.2 Platform ‘back-end’ access security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.5.2)
    o	[7.5.3 Platform ‘front-end’ access security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.5.3)
•	[7.6 Workload Security - Vendor Responsibility ](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6)
    o	[7.6.1 Software Hardening](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.1)
    o	[7.6.2 Port Protection](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.2)
    o	[7.6.3 Software Code Quality](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.3)
    o	[7.6.4 Alerting and Monitoring](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.4)
    o	[7.6.5 Logging](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.5)
    o	[7.6.6 VNF images](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.6)
    o	[7.6.7 Identity and Access Management](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.7)
    o	[7.6.8 CVEs and Vulnerability Management](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.8)
    o	[7.6.9 Encryption suite supports](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.9)
    o	[7.6.10 Password complexity support](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.10)
    o	[7.6.11 Customized Banner](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.6.11)
•	[7.7 Workload Security- Operator Responsibility](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.7)
    o	[7.7.1 Remote Attestation/openCIT](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.7.1)
    o	[7.7.2 VNF Image Scanning / Signing](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.7.2)
•	[7.8 VNF Vendors responsibility](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.8)                   align TOC title with actual section title
•	[7.9 Cloud Infrastructure Vendors responsibility](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9)   Relabel to measurement related 
    o	[7.9.1 Networking Security Zoning](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.1)              belongs in 7.5
    o	[7.9.2 Encryption](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.2)                                        belongs in 7.5
    o	[7.9.3 Platform Patching](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.3)                             belongs in 7.5
    o	[7.9.4 Boot Integrity Measurement (TPM)](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.4)
    o	[7.9.5 Runtime Integrity Measurement (TPM)](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.5)
    o	[7.9.6 Cloud Infrastructure & Cloud Infrastructure Manager](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.9.6)            belongs in 7.5
•	[7.10 Certification requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.10)                  very light content and doesn’t align -- rewrite
•	[7.11 Consolidated Security requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11) 
    o	[7.11.1 System Hardening](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.1)
    o	[7.11.2 Platform Access](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.2)
    o	[7.11.3 Confidentiality and Integrity](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.3)
    o	[7.11.4 Workload Security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.4)
    o	[7.11.5 Image Security](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.5)
    o	[7.11.6 Security LCM](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.6)
    o	[7.11.7 Monitoring and Security Audit](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.7)
    o	[7.11.8 Compliance with Standards](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.8)
    o	[7.11.9 References](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#7.11.9)

The reorg/rewrite should also ensure that all requirements are captured in 7.11 including recommendations from a review of the [ONAP Security Requirements](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=34607866).

**Comment by ASawwaf** [comment]
@pgoyal01  , i belive 7.9 completely should be under 7.5 

are you ok with this @pgoyal01 @karinesevilla

**Comment by pgoyal01** [comment]
@ASawwaf As you can see most subsections move under 7.5 but the main section ans sub-sections remain in 7.5. The title of 7.5 will then need to be changed. 

Please see my TOC in one of the above comments.

**Comment by ASawwaf** [comment]
@pgoyal01 Yes , this based on your TOC , but it is not reflected 

Can you lead in this

**Comment by wmk-admin** [comment]
The clean-up has been done along these lines.  If there are any further requirements we will need to create new specific Issues/PRs
