### ISSUE TITLE
[Chapter 5] RL-1 cloud technologic agnostic model for SW and HW

### ISSUE THREAD

**Issue by samuelhellec** [cntt-n/CNTT#170]
review the proposal of @pgoyal01

**Comment by pgoyal01** [comment]
Will including the VIM model (cloud technology agnostic) alter the purpose for Chapter 5? Should the VIM model be part of Chapter 3 as suggested in the Issue #167

**Comment by samuelhellec** [comment]
this issue is to see how we can move forward with your proposal of NFVI Software Services in your document RL1-Model-Arch-2019-08-02 v2.docx.

the add of the vim section was a suggestion from rabi and I created a separate issue for that one #169

**Comment by karinesevilla** [comment]
Done: VIM section and content have been added in chapter 4 , PR #226
