### ISSUE TITLE
[RM Ch05] backwards& Forward compatibility

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#1720]
https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4272-backwards-compatibility

move the backwards& Forward compatibility from RM CH04 to : 
1- RM CH01 intro
2- RM new chapter
3- High level above RM , in ToC

**Comment by CsatariGergely** [comment]
@ASawwaf what is the problem with the current location?
Are 1, 2 and 3 different options?

**Comment by ASawwaf** [comment]
@CsatariGergely , yup different options 
i belive it should be in higher level to be catchy

**Comment by wmk-admin** [comment]
I am leaving this in BACKLOG for now.  The whole Anuket release process needs to be clarified and the RM will be part of it.  This will have impact on the back, forward compatibility as well.

**Comment by walterkozlowski** [comment]
Closed as agree at the RM Meeting on 10 March 2021.  A new issue will be raised by @walterkozlowski to address general compatibility remarks to Introduction of RM
