### ISSUE TITLE
[RC2] Add a new testcase based on K8s e2e tests as mandatory

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1743]
The proposal is to include K8s e2e tests as integrated by Functest which already fulfills the test case integration requirements.
It's already in-used in OPNFV gating (see XCI verification and Functest gates).

For the time writing, the in-used regexes are the ones proposed by K8s conformance.
The test entry file will be simply adapted to match the ongoing work led by @taylor.

It's worth mentioning that CNTT requirement testing will be a super set of the current CNTT conformance as discussed during our last event.

**Comment by collivier** [comment]
I will put it on my agenda but of course any help is more than welcome to release my Baraque schedule.

**Comment by taylor** [comment]
There are a large set of e2e tests.  We can either use a subset (eg. individual or groups) or run the entire e2e tests.

Whatever the case we need to map CNTT RA2 requirements to the tests to provide traceability on coverage.  

At a high-level we are mapping what K8s builtin functionality meets different CNTT RA2 requirements.  The K8s e2e tests are validating the K8s functionality.
