### ISSUE TITLE
[RC2] Add mandatory CNF-based test cases (see RC1)

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1746]
Conforming to [RC1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter03.md#3.3.8) the proposal is to onboard and test CNF as part of CNTT Conformance.

Running opensource CNFs is a key technical solution to ensure that the platforms meet Network Functions Virtualization/CNTT requirements. Functest already offers one VNF test case which automatically onboard and test an opensource IMS.
The second test case leveraging Helm is under development.

**Comment by collivier** [comment]
I put it on my agenda but of course any help is more than welcome to release my Baraque schedule.

**Comment by xmulligan** [comment]
can we have a list of the test cases?

**Comment by taylor** [comment]
@collivier please update the description to communicate this is for testing a sample workload and what that entails.  Eg. "onboarding" and integration testing.

**Comment by xmulligan** [comment]
on hold until there is progress on #1496 and #1853
