### ISSUE TITLE
[RM Ch07] Modification of tables for security requirements + Ref with prefix

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#1758]
Section 7.11 Consolidated Security Requirements
1- Following the model of capabilities tables, the requirements tables are composed of 4 columns:
"Ref", "Requirement", "Unit", "Definition"
In the case of requirements the columns "Unit" and "Definition" have no interest.
My proposal is to remove the "Unit" column and change "Definition" by "Note" :
"Ref", "Requirement", "Note"

2- In RA#1, for references, we've had the prefix "req" to identify requirements, I propose to do the same for security requirements.
sec.gen.001 will become req.sec.gen.01

**Comment by walterkozlowski** [comment]
Closed by PR #1766
