### ISSUE TITLE
[RA2 Ch4] Define which Well-Known Labels, Annotations and Taints should RA2 mandate

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1761]
Kubernetes have a list of [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/). RA2 should discuss which one of these are mandatory and which one is optional.

List of non deprecated Well-Known Labels, Annotations and Taints:
- kubernetes.io/arch
- kubernetes.io/os
- kubernetes.io/hostname 
- node.kubernetes.io/instance-type
- topology.kubernetes.io/region
- topology.kubernetes.io/zone

**Comment by CsatariGergely** [comment]
Now as I read about these more I've just realized that these are set by Kubernetes, so we do not need to define which ones are mandatory to set. 
I propose to close this issue, @tomkivlin what do you think?

**Comment by tomkivlin** [comment]
@CsatariGergely yes agreed, I hadn't realised that. Closed.
