### ISSUE TITLE
[RA2 Ch4] Is there a need for different node labels for the different Cloud Infrastructure Profiles?

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1762]
RA2 should describe if a Kubernetes cluster should have different node labels for the different hosts supporting different CNTT Cloud Infrastructure Profiles.

**Comment by gkunz** [comment]
Assuming there might be more profiles over time (e.g., compute intensive [AI/ML]), I'd go for the second approach, allowing profiles to be overlapping and nodes meeting the requirements of multiple profiles to be used flexibly with regards to the workload running on them.
