### ISSUE TITLE
[RA-1 Ch08] Remove Gaps (8.2) that were moved to RM Ch 10

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1768]
4 [RA-1 Section 8.2](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter08.md#82-the-gaps) Gaps were moved to [RM Ch 10.3](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter10.md#103-gaps) -- this requires deletion of these 4 moved Gaps from RA-1 Ch 8.2

**Comment by walterkozlowski** [comment]
Fixed in PR #1769
