### ISSUE TITLE
[RA] Question Regarding Prescriptive VM Sizing

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#179]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-8. Per initial triage, it applies to the RA.
- JB-8: Why do we have exact numbers for the VM sizing in a Model? These numbers are subjective like the 300GB volume if it s volume.

Original triage notes:
- JB - work this in Ref Arch discussion.

**Comment by rabi-abdel** [comment]
Not sure what to do with it.
