### ISSUE TITLE
[RI-2 Ch1] Add section about host provisioning

### ISSUE THREAD

**Issue by gkunz** [cntt-n/CNTT#1791]
Add a high-level description of the role of host provisioning  in RI-2: bare-metal provisioning, bare-metal cloud infra provider, IaaS provider.

**Comment by tomkivlin** [comment]
Here: https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri2/chapters/chapter01.md#141-host-provisioning

Use-case description of where/how RI2 can be deployed in various infrastructure scenarios?  Packet/OpenStack/OPNFV/AWS/etc.
