### ISSUE TITLE
[Chapter 3] NEW: Incorporation of Resource Pooling Construct

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#180]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-12. Per initial triage, it applies to original Chapter 3.
- JB-12: Where are the Resource Pools for theses resources? As an SLA can be delivered only if we have Pools, Profiles and Policies to apply those. I see 1:1 mapping of Flavor resources and node (server).

Original triage notes:
- JB - Categorize resources in to profiles also. This may fit better in Tenant section. Doc currently not clear where control is, where it is guaranteed. There is ambiguity in nomenclature usage in doc: resource pools, tenants, etc. Create Issue.

**Comment by BernardTsai-DT** [comment]
Section 1.2 Terminology defines the terms NFVI, resource pool and tenants (represents an isolated and independently manageable elastic pool of virtual compute, storage and network resources).
In simple words:
* the NFVI maintains a set of resource pools for the virtual compute, network and storage resources
* a tenant may obtain resources from these resource pools  

Question is: are we missing here anything which should be added to the definition?

**Comment by pgoyal01** [comment]
Closing Issue #180 as already taken care of.
