### ISSUE TITLE
[TSC] Finalise, Confirm, Transition plans and Guidelines.

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#1822]
Open Discussion:

**Comment by walterkozlowski** [comment]
@cntt-n/tsc, do we know what this issues is really about?  There is no description so this can be interpreted  in many different ways.  @scottsteinbrueck, I propose to put this on the TSC agenda and after discussion either amend or close this issue

**Comment by scottsteinbrueck** [comment]
@walterkozlowski agree with close, will raise at TSC Meeting on 8/12/2020
