### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by herrib** [cntt-n/CNTT#1824]
Hello,

When browsing the documentation (https://cntt-n.github.io/CNTT/doc/ref_cert/) the link towards the "test cases selected by CNTT" (https://cntt-n.github.io/CNTT/doc/ref_cert/chapter03.md) is dead (it drives to a 404 error).

Could you please fix this bug (or alternatively, indicate the proper link to access the test cases)?

Thank you in advance,

**Comment by rabi-abdel** [comment]
Thank you @herrib will fix them
