### ISSUE TITLE
[RA-2 Ch02.2.1] Errors in Table 2-1

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#1829]
@tomkivlin, there are some errors in this table which were caused by errors in RM requirements table.  These errors in RM have been now fixed (mainly by @pgoyal01), look in
https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md
See Table 4-17 there.  

Please correct in RA by aligning to the corrected Table 4-17 in RM

**Comment by tomkivlin** [comment]
Thanks @walterkozlowski, @pgoyal01 - were these corrections in the RM applied to the stable/baldy branch as well, or just master?

**Comment by pgoyal01** [comment]
@tomkivlin I think it was decided that Cedric will roll applicable changes to the Baldy version also. 

@collivier Can PR #1756 be rolled into the Baldy version? Thanks

**Comment by tomkivlin** [comment]
@pgoyal01 thanks - I'll prepare a PR to do so for RA2 as well then.
