### ISSUE TITLE
[RM Ch03] Bonding, ACP, redundency need to be defined

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#183]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-21. This may apply to multiple tables across the RM specifying Capabilities.
- JB-21: Bonding, ACP, redundancy need to be defined

Original triage notes:
- JB - need to be defined at model level. Create Issue.

**Comment by markshostak** [comment]
Note: This is not a gating issue for Botrange, therefore I'm removing the BotR label.
As of now, there are no instances of Bonding or ACP in RM CH-3, 4 or 5. There are 2 instances of redundancy, briefly used in RM CH-3. Handing to Bernard/RM CH-3, to triage and determine if further action is required.

**Comment by markshostak** [comment]
Corrected Issue title and JB reference number...

**Comment by TFredberg** [comment]
Closed since resiliency methods are not in scope for the Reference Model as agreed on the RM meeting Aug 5th 2020.
