### ISSUE TITLE
[RA1-Ch8] Update Chapter 8 

### ISSUE THREAD

**Issue by sukhdevkapur** [cntt-n/CNTT#1836]
@sukhdevkapur is the following description acceptable -- please edit as appropriate and this problem description should drive the write-up in PR #1837 :

OpenStack support for multi-cloud deployments beyond regions: Currently OpenStack supports independent multiple deployments (regions), for example, as in Region A, Region B and Region C where each of the three deployments are independent except for authentication and authorization (Identity: Keystone) and Dashboard (Horizon). But other OSTK services don't know about other regions and how to coordinate with each other.

**Comment by walterkozlowski** [comment]
closed by PR #1837
