### ISSUE TITLE
[Chapter 3] Need availability attributes

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#184]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-25. Per initial triage, this applies to original Chapters 3, 4 and 9, hence this issue will be replicated against each of those targets. Individual Issues can be broken off if/when further investigation warrants.
- JB-25: Need availability attributes (uptime, similar language as used for applications) BFC: Also add to chapter 9 Operations

Original triage notes:
- JB Ch 3, 4, & 9 discussion.; JB - Create Issue to add in Ch. 9.

**Comment by pgoyal01** [comment]
@BernardTsai-DT @rabi-abdel Don't believe that this belongs in the RM Chapter 03. Suggest we close as duplicates of this issue per @markshostak are assigned for handling in other chapters.
