### ISSUE TITLE
[RM Ch9.2] 9.2 Configuration and Lifecycle Management

### ISSUE THREAD

**Issue by sb1975** [cntt-n/CNTT#1840]
I saw we wanted to ensure the target state described in a CNF manifest. This can be achieved by using Kubernetes Operators and the latest GitOps trend in community.

**Comment by tomkivlin** [comment]
@sb1975 do you mean RA2 for this?? There is no chapter 9 in RA2?

**Comment by sb1975** [comment]
> @sb1975 do you mean RA2 for this?? There is no chapter 9 in RA2?

Yeah , sorry about that. I meant RM.
https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter09.md

**Comment by walterkozlowski** [comment]
@tomkivlin, @sb1975 - I reassign this to RA2, as RM is not technology specific

**Comment by tomkivlin** [comment]
> @tomkivlin, @sb1975 - I reassign this to RA2, as RM is not technology specific

@walterkozlowski lifecycle management isn't in scope of RA2.  I will close this (it can be reopened if needed).
