### ISSUE TITLE
[TSC] Fix vulnerability in pillow

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1843]
https://github.com/cntt-n/CNTT/blob/master/requirements.txt:

```
pillow==5.4.1
```

Vulnerabilities found, suggest updating requirements.txt to:

```
pillow>=7.1.0
```

See: https://github.com/cntt-n/CNTT/network/alert/requirements.txt/Pillow/open

**Comment by pgoyal01** [comment]
@tomkivlin Will you be creating a PR to fix?

**Comment by scottsteinbrueck** [comment]
@pgoyal01 @tomkivlin I will make this change.  Thank you.

**Comment by scottsteinbrueck** [comment]
@pgoyal01 @tomkivlin Fixed.
