### ISSUE TITLE
[Chapter 4] Need availability attributes

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#185]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-25. Per initial triage, this applies to original Chapters 3, 4 and 9, hence this issue will be replicated against each of those targets. Individual Issues can be broken off if/when further investigation warrants.
- JB-25: Need availability attributes (uptime, similar language as used for applications) BFC: Also add to chapter 9 Operations

Original triage notes:
- JB Ch 3, 4, & 9 discussion.; JB - Create Issue to add in Ch. 9.

**Comment by rabi-abdel** [comment]
duplicate with similar issue
