### ISSUE TITLE
[RA2 Ch04]: Create 4.9 Kubernetes workloads in the new structure

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1853]

**Comment by CsatariGergely** [comment]
RA2 meeting 2020.08.06: Workload requirements are missing from Chapter 2. We should add them there first. @CsatariGergely to open a ticket about this.

**Comment by taylor** [comment]
See [RA2 Ch02] Specify Workload Requirements #1496

**Comment by tomkivlin** [comment]
Closing as 4.9 is now included in ch04 by some other PR that didn't reference this issue.
