### ISSUE TITLE
Common - Approach needed at all?

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#1859]
Do we need Approach document at all? It is not keeping up to date and creating confusion.

**Comment by walterkozlowski** [comment]
https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/approach.md

**Comment by ulikleber** [comment]
Agree. Is there anything we did not cover in RM by now?

**Comment by pgoyal01** [comment]
@walterkozlowski No but only once all content moved to RM.

For example, the following moved under  [Chapter00.md](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/chapter00.md):

- [Networking Scope](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/approach.md#networking-scope) moved under [Functional Scope](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/chapter00.md#functional-scope)

- [Networking Principles & Strategy](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/approach.md#networking-principles--strategy) moved after [Architectural Principles](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/chapter00.md#architectural-principles)

while
- [Network Layering and Concepts](https://github.com/cntt-n/CNTT/blob/4e496175e6f54f1b85d6f605bf07054690bca0e1/doc/common/approach.md#5.1.3) moved under RM Chapter 3 and/o4 RM Chapter 4

**Comment by walterkozlowski** [comment]
All contents of Approach document moved to Chapter 3.1 Modelling and Chapter 4.3 Networking except the following list. Recommendation deprecate Approach, after reviewing the list and creating necessary Issues. 

Specific topics to be included in the Networking Scope

To address the concern areas detailed above the specific topics listed below will be covered under Networking.

Editor's Note: The list below does not pretend to be complete. It will be a subject to modifications as a result of the community discussion.
Network connectivity for L3 tenants, GWs, SDS, etc
Spine-Leaf Architecture ( 3 Tier or 5 Tier CLOS architecture )
Automation of the programmable newtorking fabric
Variety of Underlay protocols that can be used as a transport layer within the physical fabric
Variety of Overlay protocols
SDN integration with Infrastructure Management
SR-IOV workload interworking
DPDK workload interworking
Service Function Chaining (SFC ) and how it can be achieved
New networking realisation technologies ( SmartNIC , FPGA ,..)
Inter K8s POD connectivity and CNI
Networking aspects of migration from IaaS to CaaS (from the VNF paradigm to the CNF paradigm)
Coexistence of IaaS and CaaS and protracted parallel operations
Version controlled catalog of APIs, and their respective spans of control, capabilities and purpose, to facilitate predictable integration with a wide selection of fabric implementations

**Comment by walterkozlowski** [comment]
As per the decision of the RM stream meeting on Wed 11 Aug, this document needs to be deprecated.
