### ISSUE TITLE
[RM Ch03] Need More Metrics

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#186]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-25. Per initial triage, this applies to original Chapters 3, 4 and 9, hence this issue will be replicated against each of those targets. Individual Issues can be broken off if/when further investigation warrants.
- JB-25: Need availability attributes (uptime, similar language as used for applications) BFC: Also add to chapter 9 Operations

Original triage notes:
- JB Ch 3, 4, & 9 discussion.; JB - Create Issue to add in Ch. 9.

**Comment by pgoyal01** [comment]
@tomkivlin @kedmison before closing can we delete [4.1.5.2 Internal Availability/Reliability Measurements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4152-internal-availabilityreliability-measurements) with its MTBF, recovery time etc. specifications?

**Comment by tomkivlin** [comment]
@pgoyal01 I agree - those are deployment-specific metrics for each operator (each deployment in each operator) and so I don't think they are needed in the RM or any RA/RI documents.

**Comment by iangardner22** [comment]
I agree to close this but just one comment do we capture somewhere that the infrastructure needs to provide the telemetry system behind these metrics to let the Operator decide on what good looks like? i.e. capability to measure but not metric

**Comment by kedmison** [comment]
If we go with @pgoyal01's suggestion of removing 4.1.5.2, the net effect would be to effectively remove Section 4.1.5 (internal metrics) entirely.  I'm just highlighting that.

It seems like these particular metrics have not been propagated any further into the document set.  I am thus inclined to agree with @pgoyal01 and remove the section 4.1.5 entirely.
