### ISSUE TITLE
[RM Ch10] 10.3.2 Load Balance

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1860]
RM 10.3.2 Support Load Balance of VNF/CNFs

What about the OSTK LBaaS - Octavia? If this is beyond Octavia then the description should include what Octavia can and cannot do.

**Comment by walterkozlowski** [comment]
@qabpea, can you please create a PR to close this issue, thanks. We are closing this release now!

**Comment by walterkozlowski** [comment]
These updates have already done, approved and merged
