### ISSUE TITLE
[RM Ch10] 10.3.4 Packet Acceleration Request (e.g Hardware Acceleration)

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1861]
what is this sentence trying to say, in particular the bolded part, "The acceleration hardware is typically optimized for specific kinds of workloads and some form of disaggregation might be required to separate control and user plane responsibilities between generic server hardware and accelerators."

**Comment by walterkozlowski** [comment]
@sureshkrishnan, can you please create a PR to close this issues, thanks.  we are really finishing now with this release.
