### ISSUE TITLE
[RM Ch07] Corrections to RM Chapter 7

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1867]
Please renumber Figures
Please delete "Image from https://www.networkworld.com/article/2840273/sdn-security-attack-vectors-and-sdn-hardening.html Will replace with a better image when I create it in the future" from [7.7 Application Vendors responsibility](https://github.com/cntt-n/CNTT/blob/karinesevilla-patch-6/doc/ref_model/chapters/chapter07.md#77-application-vendors-responsibility)

**Comment by karinesevilla** [comment]
@pgoyal01 Thanks! It is done within PR#1864

**Comment by pgoyal01** [comment]
@karinesevilla Thanks. I approved PR #1864
