### ISSUE TITLE
[RA2 Ch4]: Soft definitions in Ch4

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1869]
RA2 Chapter 4 should define the components and to be aligned with the targets of CNTT Ch4 should select one component and one configuration parameter from the different options where the component or the parameter have affect on the software of a CNF or the deployment artefacts of a CNF. 

Current Ch4 have lots of `may`-s in places where it should have `must`-s,

**Comment by tomkivlin** [comment]
@CsatariGergely is this still relevant or can we close it?  If it needs to stay open can you provide some examples please?

**Comment by tomkivlin** [comment]
Given the large number of changes in ch4 since August I suggest we close this.  Will do in 2 days unless @CsatariGergely says otherwise.

**Comment by tomkivlin** [comment]
Closed due to age.
