### ISSUE TITLE
[Tech Steering] To what level do we go to ensure "consistency"

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#1874]
**Question for Tech Steering**: we need a decision as to whether it is ONLY the container images (i.e. the software) that must be abstracted from the infrastructure, or whether the deployment artefacts, which are often developed alongside the software by the software vendor, are also included in the scope of this abstraction.

Background
---
Within RA2, because of how tightly coupled the application lifecycle management artefacts (e.g. Helm) is to the development of the software by vendors (i.e. they release both together), a question has arisen over time as to the level to which we decide to want to avoid "options" in RA2 Chapter04 (Architecture Specification).  In particular, it comes down to:
1. Whether the container images differ (i.e. whether different container images are required for the specification provided)
1. Whether the deployment artefacts differ (i.e. whether different YAML configurations - not just variables but included options - are required for the specification provided)

I think everyone is agreed that 1. above is definitely what the RA2 specification is looking to avoid.  I'm not sure there is full agreement/acceptance of 2. above and hence the question to steering group.

e.g.

For multi-NIC networking solution, we could go through all the requirements and decide that the only metaplugin that meets them all is DANM.  We specify that in the RA2 spec, meaning all implementations (the RI, any VIs, etc.) must use DANM, and all CNFs that require multiple connection points must use DANM.  The benefits of this are that there is consistency and everyone knows what they're building for - in particular the container images _and_ deployment artefacts are the same across all implementations.  The downsides are that this then removes all the other potential solutions to providing multiple connections points - whether that be another metaplugin (e.g. Multus) or another approach entirely (e.g. CRDs/NSM), which in turn could reduce the overall benefit seen within the community (i.e. people stop using RA2 as a specification and we're back to square one).

An alternative approach is that the RA2 specifies the configurations that are needed to ensure certain standards are used - e.g. compliance with Kubernetes SIGs, that any networking solution must allow for any CNI-compliant plugin to be used, CRDs must be used, etc. and then the implementations (RI, VIs, etc.) settle on the solutions that best meet the needs of the workloads/business in question.  The benefit of this is that we don't shut out any solutions that may benefit us all in the long run - we retain some flexibility for innovative and forward-thinking options in a fast-moving industry.  The downside is that the deployment artefacts now become inconsistent between the various options that are presented.  e.g. if the RI decides to use Multus to provide multiple connection points, the deployment artefacts for a particular CNF will need Multus-specific elements.  If a VI decides to use DANM for the same purpose, a second set of deployment artefacts for that same CNF are required (even though the same container image can be used).  This adds process time and cost to the software vendors as they have to maintain two sets of deployment artefacts, and an element of optionality that was the original intent of CNTT to avoid.

**Comment by pgoyal01** [comment]
@tomkivlin Thanks for clearly defining the issue. There can also be an underlying issue whether the requirements on which we are basing our correct and complete, and in addition there is the issue of weighting the "must" versus the "should." Since, we are discussing the issue of meta-plugin, do we have requirements for such a meta-plugin?

**Comment by CsatariGergely** [comment]
In my opinion it is the main mission of CNTT to abstract both the container images and the deployment artefacts. 
If the deployment artefacts can differ for the different target infrastructures then the integration of the infrastructure and the workload is not guaranteed. 
The problem of CNI metaplugins is not the CNI specific part what is compliant with the CNI spec in all cases, but with the extensions the different plugins add. Until there is no abstract networking API is defined for Kubernetes this issue can not be solved in an abstract way.

**Comment by tomkivlin** [comment]
@cntt-n/tsc has this been raised in a TSC meeting yet?  Let me know if I need to come and present the problem and start the discussion.

**Comment by dabernie** [comment]
@CsatariGergely we are already at the level of acknowledging that Kubernetes based infrastructures will differ. Both on a public cloud implementation (ie hyperscaler native k8s) OR within Telco internal stacks.
Defining or revisiting what are the meta-plugin requirements will help highlight when a RI needs to leverage it or not. And in that sense, it might help define the limited features a meta-plugin actually needs to implement thus reducing the need to standardize on one.
This would also help define if a meta-plugin is a musth for multi-NIC support or could actually be relegated to support when dealing with multiple CNIs (ie primary CNI supporting multi-interface and secondary for SR-IOV).

**Comment by scottsteinbrueck** [comment]
@tomkivlin 

1.  Yes, we agree that RA-2 spec should avoid image differences. (along with storing images, also store artifacts that help configure the pods)
2.  Prefer the alternate approach that specifies the configuration and standards to be used.  (Scott:  Instead of the "brand name" approach)

**Comment by tomkivlin** [comment]
As per the TSC call on 16th September, here is my proposal for the rule-of-thumb approach we take:

> Where the RA2 specification is unable to comply with principle 4 in describing a standardised API for any particular capability (as we are finding for multiple interfaces today):
>- A gap must be documented in chapter06.md (and referenced in chapter04.md) - e.g. "There is no standard API schema for managing multiple connections to pods in Kubernetes today".
>- The RA2 spec (chapter04.md) must document that a specification that adheres to all principles is not possible, and refer to the underlying requirements
>- RI2 then chooses a solution based on those requirements, and RC2 defines test cases for those requirements
>    - A vendor may choose to create a VI based on one or other, or both, and if they meet the requirements that are tested by RC2, they only have to support one or the other
>    - Likewise, software vendors can choose to support one or the other, as long as their workload is able to pass the RC2 test cases
>- In the future, if a standardised method for managing that capability is released, we modify the RA2 spec to cater for that and look to cascade that change into the RI2 and RC2 workstreams

So in the example we have today:
- A gap must be documented that there is no standard way to manage multiple connections to a pod without affecting the deployment artefacts
- RA2 spec then removes all reference to Multus/DANM and leaves that as a decision for RI2/VI/CI level solution design
- RI2 chooses a multi-connection solution as part of overall solution design, that meets the requirements of RA2
- RC2 test cases look to test compliance against RA2, regardless of which solution is used

In addition to the above, I think we should document in chapter01.md of RA2 that, for this document, "workload", i.e. in principle 8 and others, refers to both the software itself (i.e. the container image) and the artefacts used to deploy that software (i.e. the Pod spec within a k8s YAML, Helm chart, etc.).  So any further gaps in achieving that end are documented and raised with the appropriate projects.

@walterkozlowski @CsatariGergely @pgoyal01 - does this cover the action as per your memories?

Thanks,
Tom

**Comment by tomkivlin** [comment]
Closing the issue as the TSC steer was to use the consensus based decision making process and deadlock-breaking process (i.e. vote on it).
