### ISSUE TITLE
[RM] Add new requirement to address networking scale

### ISSUE THREAD

**Issue by sukhdevkapur** [cntt-n/CNTT#1876]
Networking should scale across multiple clouds. There should be an ability to federate networks spanning across multiple deployments. Many cloud native deployments in 5G telecom space will be desegregated and span across multiple sites

**Comment by tomkivlin** [comment]
Changing this to target RM changes.

**Comment by wmk-admin** [comment]
@sukhdevkapur, can you raise this topic at a post-Elbrus RM meeting to clarify what in your view needs to be done?

**Comment by walterkozlowski** [comment]
RM Meeting on 30 June decided to close Issue#1876 "address networking scale" and add this a subtopic in the Multi-cloud topic
