### ISSUE TITLE
General] NEW: Use Cases for Profiles

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#188]
This Issue captures a comment collected from Paris, entered against the original RM Chapter-4 Etherpad, for comment JB-31. Use Cases have been a topic of discussion of late; proper location needs to be fixed.
- JB-31: Would be good to describe the actors that would produce and consume these profiles. Including how these would be used by the actors.

**Comment by rabi-abdel** [comment]
I do think this is supplementary materials that needs to be created. Introducing Welcome Pack!

**Comment by rabi-abdel** [comment]
No Action needed.
