### ISSUE TITLE
[TSC RTD] Make the left side menu more clear

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#1889]
Left side menu in readthedocs needs the following changes: 
- Less redundant CNTT mentions
- Show the two options of RA-s, RI-s and RC-s

**Comment by CsatariGergely** [comment]
See [2020-08-19- [CNTT - Technical Steering Committee] - Meeting Agenda and Minutes](https://wiki.lfnetworking.org/display/LN/2020-08-19-+%5BCNTT+-+Technical+Steering+Committee%5D+-+Meeting+Agenda+and+Minutes)

**Comment by scottsteinbrueck** [comment]
@CsatariGergely - I agree with your proposal.  Here is a suggested structure:

Cloud iNfrastructure Telco Taskforce (CNTT)
- Table of Contents
- Available Specifications
- Introduction
- Approach
- Use Cases
- Roadmap and Releases
- CNTT Technical Policies and Transition Plan
- Other Policies
- Relevant Technologies

Community Guidelines
- Release Information
- Version History
- Table of Contents

Reference Model
- Release Information
- Bundle/Version History
- Overall Status
- Table of Contents

Reference Architectures
- RA1 - Openstack Based
- RA2 - Kubernetes Based

Reference Implementation
- RI1 - OpenStack Based
- RI2 - Kubernetes Based

Reference Conformance (RC) Test Case Integration
- RI and RC toolchains
- Test case integration requirements
- Testing Cookbooks
- RC1 - Openstack Based
- RC2 - Kubernetes Based

Vendor Implementations
- Vendor Implementation Template
- Vendor X
- Vendor Y
- Vendor Z
