### ISSUE TITLE
[RA-1 Ch6.3.2] Update for hardening 

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#1901]
Please reflect in RA-1 changes in RM Sec 7.11.1, see PR #1892

**Comment by pgoyal01** [comment]
FYI: The requirements alignment was performed: PR #1937 (already merged)

**Comment by pgoyal01** [comment]
This Issue is to align the content of RA1 Ch 6.3.2 with the updated requirements. 

Suggest that we work on this in the next release.

**Comment by pgoyal01** [comment]
Completed in PR #1949 and so closing as per meeting on September 14, 2020.
