### ISSUE TITLE
[Glossary] Add the definition of vCPU to the glossary

### ISSUE THREAD

**Issue by EditKoselak** [cntt-n/CNTT#1909]

**Comment by pgoyal01** [comment]
Please note that in RM the following terms, some erroneously, are used in Ch04 (and may also have been used elsewhere including in copy'n'paste in RA1 and RA2) and in some cases linked with vCPUs:
1. [4.1.2.2 Exposed Performance Optimisation Capabilities](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4122-exposed-performance-optimisation-capabilities): cores and physical cores
1. [4.1.4.1 Internal Resource Capabilities](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4141-internal-resource-capabilities): CPU cores
1. [4.1.4.2 Internal SLA capabilities](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4142-internal-sla-capabilities): virtual cores
1. [4.2.5 Cloud Infrastructure Profile Capabilities Mapping](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#425-cloud-infrastructure-profile-capabilities-mapping): vCPU cores and cPU cores
