### ISSUE TITLE
[RA1][RA2]RC1][RC2] Make clear the default testing timeouts

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1914]
Here are several ways to precise the default API operation timeouts:
 - add 1 or several requirements per RA branches
 - add 1 or several requirements per RC branches (for instance in test case descriptions)
 - precise in the testing principles (on top of RC1 and RC2) that the default test framework timeouts are kept unchanged unless RAX or RCX defines other values.

**Comment by collivier** [comment]
I would suggest the third options. Both 1 and 2 could lead to lots of requirements for quite nothing.
For the time being, the testing principles is written in the Benchmarking API descriptions (both RC1 and RC2)

any thought?

**Comment by tomkivlin** [comment]
I agree - having a simple principle or requirement in chapter02.md of each of RC1/RC2 that states something like the following would be sufficient I think.

> Where external test frameworks are used, the default test framework timeouts are kept unchanged unless otherwise specified in the Reference Architecture specification.

**Comment by collivier** [comment]
@tomkivlin Thank you for your quick feedback!

**Comment by pgoyal01** [comment]
Incorporated in Issue #1915
