### ISSUE TITLE
[RM Appendix A] Duplicate Content

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1931]
[A.5 Hardware-Dependent Coding Policies](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/appendix-a.md#A.5)

and in
[CNTT Technical Policies and Transition Plan](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md#cntt-technical-policies-and-transition-plan) in section [Hardware-Dependent Coding](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md#7.1.2)

When a decision is made as to the correct source, RM Chapter 04, Table 4-17 entry for "e.cap.013
(SR-IOV over PCI-PT)" needs to be corrected. The reference to A.3 Exceptions should be deleted and instead point to Chapter 01 of the RA documents.

**Comment by walterkozlowski** [comment]
Appropriate changes in Appendix have been already made
