### ISSUE TITLE
[RA1 Ch06] Add content to 6.3.1.4 RBAC

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#1935]
per @iangardner22 PR #1910, add the following:
 point out that RBAC is somewhat limited and still requires the editing of the policy.json for each OpenStack service

**Comment by pgoyal01** [comment]
@iangardner22 do any of the following capabilities in keystone address your ask:
- All keystone APIs now use the default reader, member, and admin roles in their default policies. This means that it is now possible to create a user with finer-grained access to keystone APIs than was previously possible with the default policies. 
- All keystone APIs now support system scope as a policy target. This, for example, will allow keystone to distinguish between project-specific requests and requests that operate on an entire deployment.

**Comment by iangardner22** [comment]
> @iangardner22 do any of the following capabilities in keystone address your ask:
> 
> * All keystone APIs now use the default reader, member, and admin roles in their default policies. This means that it is now possible to create a user with finer-grained access to keystone APIs than was previously possible with the default policies.
> * All keystone APIs now support system scope as a policy target. This, for example, will allow keystone to distinguish between project-specific requests and requests that operate on an entire deployment.

Then possibly yes!    Could we check with Karine?  @karinesevilla

**Comment by pgoyal01** [comment]
@karinesevilla Can you please confirm so that we can either move this issue to backlog or close? Thanks
