### ISSUE TITLE
[RM Ch3] Write section 3.x Storage

### ISSUE THREAD

**Issue by petorre** [cntt-n/CNTT#1943]
(As per discussions on RM calls) Write section 3.x Storage similar like there is [3.5 Network](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#3.5) .

**Comment by walterkozlowski** [comment]
Hi @petorre, how are you going with this update?  Perhaps we need a call with selected people (like we had) to discuss this?  Let me now how I can help.

**Comment by petorre** [comment]
> 
> 
> Hi @petorre, how are you going with this update? Perhaps we need a call with selected people (like we had) to discuss this? Let me now how I can help.

Thanks for the offer. Just made PR #1969 , please check.
