### ISSUE TITLE
[RM Ch03] Intra networks

### ISSUE THREAD

**Issue by BernardTsai-DT** [cntt-n/CNTT#195]
**Comment from Paris Meeting: Chapter 03 Infrastructure Abstraction - GAPS (Day 1):** 

**Intra Networks**
Tenant : do we need to add intra networks?

**Comment by BernardTsai-DT** [comment]
External networks have been mentioned as one of the attributes of a tenant in the table in section 3.2.1 Tenant. The way of how to describe such an external network has to be specified in more detail, e.g.:
* name
* CIDR
* gateway
* route-target (?)
* additional attributes (?)

**Comment by pgoyal01** [comment]
@BernardTsai-DT May I suggest that to address this issue #195 and Issue #196, more clarity could be provided in 3.2.1 (maybe with the add of another Table on "External Networks" and relabel 3.2.4 as "Tenant Networks."

**Comment by bfcohen** [comment]
Bernard could you clarify how detailed you think it needs to be in Chapter 3.

**Comment by markshostak** [comment]
The RM already describes "Networks", which covers L2, as well as L3 v4 and v6 networking. What a network is used for (e.g., OA&M, inter, intra, etc.), is a function of what's attached to the network, and how said attached hosts employ the network. In other words, from a networking perspective, the subnet is agnostic to its use. Given the RM already describes the required "generic" network attributes, the question becomes, is describing the logical application of the networks within the RM's scope/purview, and if so, should it be prescriptive or informative. I do not believe it's within CNTT's purview to tell VNF suppliers how to network their VNF(C)s, hence, my recommendations are:
1) To the initial question: we don't need to add (i.e. prescribe) intra-networks, as differentiated from any other networks
2) Networking is already sufficiently described from a prescriptive perspective, so no additions/changes of prescriptive material is required
3) Some informative language on the use of/networking applications, can be added for background. However, I would consider this low priority (i.e. future dev, not Borange).
Thanks,
-Mark

**Comment by TFredberg** [comment]
Closed since intra network usage are not in scope for the Reference Model or even CNTT as agreed on the RM meeting Aug 5th 2020.
