### ISSUE TITLE
[Chapter 3] Subnets

### ISSUE THREAD

**Issue by BernardTsai-DT** [cntt-n/CNTT#196]
**Comment from Paris Meeting: Chapter 03 Infrastructure Abstraction - GAPS (Day 1):** 

**Subnets**
Network model: subnet, is it at model level?

**Comment by BernardTsai-DT** [comment]
Typically a subnet description would specify the IP family (IPv4/IPv6), the CIDR and the gateway. This information relates to IP and since all operators would probably want to communicate via IP this information would be of general value.
Therefore I would propose to keep subnet information in the model level.

**Comment by pgoyal01** [comment]
@BernardTsai-DT May I suggest that to address this issue #196 and Issue #195, more clarity could be provided in 3.2.1 (maybe with the add of another Table on "External Networks" and relabel 3.2.4 as "Tenant Networks."

**Comment by bfcohen** [comment]
Yes it belongs in the RM, because it is common to all reference architectures.
