### ISSUE TITLE
[Chapter 1] VNF/CNF

### ISSUE THREAD

**Issue by BernardTsai-DT** [cntt-n/CNTT#198]
**Comment from Paris Meeting: Chapter 03 Infrastructure Abstraction - GAPS (Day 1):** 

**VNF/CNF**

VNFs/CNFs are not managing their own resources via API-s.
VNFs and CNFs are using different abstractions.

VNFs are VMs working on an infrastructure (compute, NW, storage) abstraction, CNFs are processes working on an operating system abstraction. We must not pretend VNFs and CNFs were simply different ways of packaging software (CNFs need OS + container runtime + container orchestration on top of NFVI) --> have to keep these layers separate to ensure CNFs are abstracted from infra mgmt. and run on different NFVIs (OpenStack, VMw, AWS, ...).

Release 1 MVP is only Infra and VNFs; CNF-s will be fully supported in Release 2

    Can this be clearly stated in the document and can we remove the refernces ot CNF-s from the Release 1 branch to avoid confusion?

**Comment by pgoyal01** [comment]
@BernardTsai-DT: aren't VMs also processes running in the Hypervisor space on top of an OS (Host OS). Agree that VMs and Containers are "virtualized," organized and orchestrated differently but both VMs and Containers consume NFVI resources and services.

**Comment by xavier-grall** [comment]
NFVI hardware & software can be fully abstracted from VM perspective (unless they directly use some hardware-specific features, eg with pcipassthrough).
Container must share the NFVI nodes kernel, unless they run themselves on a VM or a dedicated Baremetal (eg, in BMaaS mode) but they must still share the kernel with other containers on the same VM/BM.
So the abstraction between VM and containers is well different, so they require different control/management functions at the NFVI level (hypervisor vs container runtime, eg kvm vs docker) and MANO level (VIM vs CISM as per ETSI NFV IFA029, eg openstack vs kubernetes).
Moreover, it should be noticed that kubernetes could also be a VNFM.
Discussions about that in 1 issue #122 and 2 pending PR #123, #193

**Comment by ulikleber** [comment]
Just to clarify a bit the terminology. 
CNF is a type of VNF. VNFs can use VMs or containers. Also VNFs usually are composed of multiple components. See definition in chapter 1.
