### ISSUE TITLE
[RA2][RC2] Implement from RA2 to RC2 security traceability

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#1984]
As far as I understand, no clear security rules are defined as mandatory yet. 
Then RC2 Security testcases only prints all failures in console without postprocessing (following benchmarking model).

RA2 and RC2 must be clear about the violation list.

**Comment by collivier** [comment]
@tomkivlin @CsatariGergely @gkunz @scottsteinbrueck @pgoyal01 + all
I think there is a couple of issues regarding kube-bench (CIS benchmark 1.5) in CNTT and CIS benchmark 1.5 and we can't go further with the existing RA2/RC2 (the test case only prints the errors and the test case status depends if the benchmark is successfully executed).

From a CNTT pov, the requirement should have been tagged as MUST rather than SHOULD.
Even so there is a couple of CIS benchmark checks I would strongly disagree because they are forcing specific deployments:
 - Ensure that the etcd data directory ownership is set to etcd:etcd (Scored)
 - Ensure that the proxy kubeconfig file permissions are set to 644 or more restrictive (Scored) 
 - Ensure that the proxy kubeconfig file ownership is set to root:root (Scored)

We can't assume that etcd is running on master node and even so it could run in a container which would fail all theses checks by design by following the best security rules. Last but not least all manual testings are incompatible with RC2 by design.

Then my recommendations would be to exclude the target controlplane (manual), policies (manual) and etcd (forced a specific design). Regarding the master and node targets, we must exclude all configuration checks which may not be generic enough (kube-proxy). **It also asks for an update of the RA2 requirements (must and 1.5 must be explicit)**

Please see https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-security-latest-kube_bench_node-run/5/console and https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-security-latest-kube_bench_master-run/5/console fro any details.

**Comment by collivier** [comment]
@tomkivlin @CsatariGergely 
Please let me know if I do open a baraque bug for "sec.std.001: The Cloud Operator **should** comply
with Center for Internet Security CIS Controls"

**Comment by tomkivlin** [comment]
@collivier all the RA2 security requirements are pulled through from the RM, so would need updating there first.

**Comment by collivier** [comment]
@tomkivlin Thank you for the clarification (RA2 is the interface for RC2 and then kube-bench).
The question is still valid. If we want precise security checks in RC1 and RC2, we do rather consider a must requirement.
The next key issue would be that we do manage exceptions per RA streams.

**Comment by tomkivlin** [comment]
> The next key issue would be to manage exceptions per RA streams.

I have been late in adding this in, but #2018 includes a structure and place where we can document such exceptions.  So, we could add in a requirement exception for RA2 where we make this a MUST rather than a SHOULD (if that's the right thing to do).

**Comment by gkunz** [comment]
So, just trying to summarize: there are basically 2 exceptions here:
- exception 1 in RA2: change SHOULD to MUST in the RA2
- exception 2 in RC2: remove selected test cases / best practices defined in CIS because the test case implementation or the CIS benchmark definition is currently not suitable -> action for later

**Comment by collivier** [comment]
Yes. We could take this points into account for the next release (Baraque +1). 
It's possibly about RA1 as well (the "should" about CIS is completed by additional specific must requirements)
