### ISSUE TITLE
[Chapter 2] VNF profiles analysis

### ISSUE THREAD

**Issue by xavier-grall** [cntt-n/CNTT#200]
In section 2.2:
- VNF requirements should only rely on their needs, and not on NFVI configuration elements (as EPA...)
- NFVI profile naming (network-intensive...) should not appear here, but only in the next section

Here is a change proposal for that purpose: 
https://github.com/xavier-grall/CNTT/commit/076d9e3737dfb6ce724d5ad2fd2faf19434ed0c4

**Comment by karinesevilla** [comment]
Agree, it would be much better to start from VNF requirements. The section2.2  is currently mixing VNFs requirements and NFVI features

**Comment by rabi-abdel** [comment]
PR Created for it: https://github.com/cntt-n/CNTT/pull/235

**Comment by rabi-abdel** [comment]
PR addressed. closing for now
