### ISSUE TITLE
[RA2][RC2] Select all e2e tests applicable to RA2 

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#2025]
Kubernetes Conformance is driven for an high level of common functionality which differs a little bit from CNTT which defines the reference architecture.

k8s_conformance currently selects about 300 singles tests out 5000 as proposed by e2e tests.
A next requirement traceability could help reaching the OpenStack ratio where more than 80 % of the tests are selected.

It may ask for updates in RA2 conforming with RA1 Chapter 5

**Comment by pgoyal01** [comment]
@collivier @taylor @CsatariGergely @tomkivlin Any progress on developing the test cases (beyond k8s conformance) needed for RA2 conformance?

**Comment by tomkivlin** [comment]
@pgoyal01 I believe this issue was about selecting the already defined tests in the e2e Kubernetes test suite. "Conformance" is a subset but there may be others already written that align to RA2 specs.

**Comment by collivier** [comment]
They are new test cases in Functest master which should be added to RA2 once testing, backporting and RA2 requirements (at least to me)  are clear
sig_network: https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-smoke-latest-sig_network-run/5/console
sig_network (basic features): https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-smoke-latest-sig_network_features-run/4/console
sig_storage (no specific driver): https://build.opnfv.org/ci/job/functest-kubernetes-opnfv-functest-kubernetes-smoke-latest-sig_storage-run/2/console

and many others on my computer ;)

**Comment by collivier** [comment]
It deserves a true deep analysis and multiple testing env. I would suggest to let it open for the next release.
