### ISSUE TITLE
VNF/CNF in Chapter 1 refer to #198

### ISSUE THREAD

**Issue by bfcohen** [cntt-n/CNTT#203]
Release 1 MVP is only Infra and VNFs; CNF-s will be partially supported in Release 2
JB - clarify position and look at best way to support/define CNF articulated. (also impacts Ch. 3)+1 (high level only in CP1)
Can this be clearly stated in the document and can we remove the refernces ot CNF-s from the Release 1 branch to avoid confusion? Overall CP1 is missing the use cases, once these are added, much of the confusion should be resolved.

**Comment by bfcohen** [comment]
Refer to #198 for the related issue.

**Comment by pgoyal01** [comment]
Also related to #139

**Comment by BernardTsai-DT** [comment]
Added following text to the Roadmap section of Chapter 1:
(in the branch: VNF/CNF-in-Chapter-1)

Release 1 of this document will focus on the network function virtualisation infrastructure and virtualised network functions which are based on virtual machines. In Release 2 there will be partial support for cloud native functions which make use of container technology.

@bfcohen, @rabi-abdel: Could you please check if the statement is correct?

**Comment by pgoyal01** [comment]
Removing Chapter03 Label for this issue as it pertains only to text in RM Chapter 01.

**Comment by bfcohen** [comment]
Added a roadmap item in Chapter 01 that explicitly demonstrates that Containerization will be started at least in Release 2.
