### ISSUE TITLE
[RA2] new tab to make the mandatory features clear

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#2030]
RA2 should offer a new tab listing all mandatory/optional Kubernetes Features for RC2 (conforming to RA1 Chapter 5).
https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter05.md#5.2

It may somehow duplicate the existing tabs mostly driven by req traceability (project management).
But it would be the best interface for RC2 and the true e2e traceability expected by users
Please see http://testresults.opnfv.org/functest/traceability/

e.g.: [sig-network]:
- Feature:Ingress
- Feature:IPv6DualStackAlphaFeature
- Feature:Federation
- Feature:kubemci
- Feature:NEG
- Feature:Networking-IPv4
- Feature:Networking-IPv6
- Feature:Networking-Performance
- Feature:NetworkPolicy
- Feature:NoSNAT
- Feature:PerformanceDNS
- Feature:SCTP
- ...

Linked to https://github.com/cntt-n/CNTT/issues/2025

**Comment by tomkivlin** [comment]
@collivier is MUST/SHOULD/MAY wording in the specification not enough to show which is mandatory/optional/allowed?

**Comment by rgstori** [comment]
two approaches recommended:

1. cleanup of ch4 tables, ensuring MUST/SHOULD/MAY verbs are present (and possibly highlighted) in each row
2. adding an extra column with a boolean if the spec is mandatory or not

shall we start with the first one?

**Comment by pgoyal01** [comment]
@rgstori I just realised that Cedric is also asking to define the mandatory and optional, for example, w.r.t. APIs also.

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by pgoyal01** [comment]
@rgstori you can assign this to Vijay
