### ISSUE TITLE
[RA1 Ch02] OPNFV ask for extra details

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2033]
OPNFV would like some additional clarification for "zero downtime" and "hitless" in the [2.3.6 Operations and LCM requirements](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md#236-operations-and-lcm): 

Ref # | sub-category | Description | Traceability
-- | -- | -- | --
req.lcm.gen.01 | General | The Architecture must support zero downtime expansion/change of physical capacity (compute hosts, storage increase/replacement). |  
req.lcm.adp.02 | Automated deployment | The Architecture must support hitless upgrades of  software provided by the cloud provider so that the availability of  running workloads is not impacted. |  

suggest  the following changes (formatting for ease):

Ref # | sub-category | Description | Traceability
-- | -- | -- | --
req.lcm.gen.01 | General | The Architecture must support zero _**workloads**_ downtime expansion/change of physical capacity (compute hosts, storage increase/replacement). |  
req.lcm.adp.02 | Automated deployment | The Architecture must support hitless _**(as in no impact to workloads)**_ upgrades of  software provided by the cloud provider so that the availability of  running workloads is not impacted. |  

@acmacm Does the new language satisfy the OPNFV ask?
@karinesevilla Any issues with the suggested change?

Once we are aligned will fix in a PR.

**Comment by karinesevilla** [comment]
@pgoyal01 I agree with your wording, even if I think that " (as in no impact to workloads)" is redundant with the end of the sentence

**Comment by acmacm** [comment]
Suggest revised wording and further CNTT discussion:

gen.01: The Architecture must support zero downtime as observed in workload functions due to expansion/change of physical capacity (compute hosts, storage increase/replacement, etc. where the workload <is/is not> operating).
          Note: CNTT stakeholders should decide on the definition of "zero downtime" they are using (does downtime exclude brief VM stalls?), and whether the observed workload occupies infrastructure resources that are expanded or changed, or occupies adjacent/un-changed resources.

.adp.02: The Architecture must support hit-less (as in no impact to observed workloads) during upgrades of software provided by the cloud provider so that the availability of running workloads is not impacted.
         Note: "hit-less" traditionally covers a per-transaction level of operation (no packets are lost) while "availability" allows small outage time but the function continues to operate without intervention.  Which of these is intended here? Hit-less is clearly more demanding on the upgrade process.

**Comment by pgoyal01** [comment]
@acmacm Thanks. Please see rewording of the requirements. Not sure what "observed workloads" means? In the adp.02 it clearly states "availability".


Ref # | sub-category | Description | Traceability
-- | -- | -- | --
req.lcm.gen.01 | General | The Architecture must support zero downtime of workloads when the number of compute hosts and/or the storage capacity is being expanded or unused capacity is being removed. |

**Comment by acmacm** [comment]
@pgoyal01 I'm sorry, I don't see where the requirements have been re-worded since your original proposal. 
In a large-scale deployment, it would be impossible to observe *all* workloads. The solution is to observe a representative set.
In adp.02,  (original wording and proposals), the phrase "must support hitless" implies a very demanding, "no observable effect" level of performance. Terms like "availability" mentioned later, and "zero downtime" imply a different requirement in terms of the response to changes.

**Comment by pgoyal01** [comment]
@acmacm when a workload is affected that is a change in its state and results in alerts. This is not about only monitoring a subset of workloads but all workloads.
gen.01 has been reworded to clarify what changes cause no affect on the workloads.
adp.02 below reworded to ensure we are speaking in terms of availability

Ref # | sub-category | Description | Traceability
-- | -- | -- | --
req.lcm.gen.01 | General | The Architecture must support zero downtime of workloads when the number of compute hosts and/or the storage capacity is being expanded or unused capacity is being removed. |  
req.lcm.adp.02 | Automated deployment | The Architecture must support upgrades of  software, provided by the cloud provider, so that the availability of running workloads is not impacted (viz., hitless upgrades). |

**Comment by acmacm** [comment]
@pgoyal01 
for gen.01: can this be stated as "running workloads" (same as .adp.02) ?  I feel the distinction is useful, but obviously not essential!
for adp.02, a strong simplification: Upgrades of cloud-provider software must not reduce the availability of running workloads.
Does CNTT have definitions (or references to definitions) of "downtime" and "availability" ?

**Comment by pgoyal01** [comment]
At the RA1 meeting of October 19, the following alternate language was agreed upon:

Ref # | Category | Current Description | Alternate Suggested Decsription
----|------|-----|------
req.lcm.gen.01 | General | The Architecture must support zero downtime expansion/change of physical capacity (compute hosts, storage increase/replacement). | The  Architecture must support zero downtime of running workloads when the  number of compute hosts and/or the storage capacity is being expanded or  unused capacity is being removed. 
req.lcm.adp.02 | Automated deployment | The  Architecture must support hitless upgrades of software provided by the  cloud provider so that the availability of running workloads is not  impacted. | The Architecture must support  upgrades of software, provided by the cloud provider, so that the  running workloads are not impacted (viz., hitless upgrades). Please note  that this means that the existing data plane services should not fail  (go down). 

Critique?
