### ISSUE TITLE
[RA1 Ch2, Ch4] T-shirt removal

### ISSUE THREAD

**Issue by EditKoselak** [cntt-n/CNTT#2038]
The T-shirt terminology is not used anymore and has been removed from the rest of the documentation.

**Comment by pgoyal01** [comment]
@EditKoselak Thanks. This issue also corrects references to the correct chapter titles, and other typo's - extra spaces, etc.

I edited the labels and milestones. Now that a PR has been opened, IMO, this issue doesn't require the "new" label.
