### ISSUE TITLE
[RA1 Ch4] Network fabric: content needed

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#2046]
Develop content for section 4.2.3

**Comment by pgoyal01** [comment]
@iangardner22 please review [4.2.3](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter04.md#423-network-fabric)  and [RM 4.3](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#43-networking)
