### ISSUE TITLE
[RA1 Ch01] RA1-terminology empty

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#2047]
Section 1.3 Do we need RA1 terminology section?

**Comment by pgoyal01** [comment]
@karinesevilla I think the decision was to include all terminology in the Common chapter and the RA-1 related stuff is in the [OpenStack terminology](https://github.com/cntt-n/CNTT/blob/master/doc/common/glossary.md#1.5) section.

**Comment by pgoyal01** [comment]
@karinesevilla Link to Terminology: https://github.com/cntt-n/CNTT/blob/master/doc/common/glossary.md
