### ISSUE TITLE
[RM Ch03] Enterprise Multi-cloud Model

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2049]
Multi/hybrid cloud  from Data Centre to Edge

**Comment by pgoyal01** [comment]
Content being developed in the wiki: [CNTT Edge and Multi-Cloud RA01Architecture Scenario](https://wiki.lfnetworking.org/display/LN/CNTT+Edge+-+RA01+%28+OpenStack+%29+Architecture+-+Scenario)
Please critique, add missing content, etc.
