### ISSUE TITLE
[Question] Add other Standards and Open Source bodies related.

### ISSUE THREAD

**Issue by bfcohen** [cntt-n/CNTT#205]
CNTT should collaborate very closely with the respective API workgroup of SDOs (ETSI, MEF, TM Forum). To collate the relevant APIs from these SDOs would require special permission since information might not be available to the public. eg. MEF LSO APIs & TM Forum OpenAPIs are accessible by members only.
JB Ch. 1 and 7. And also how CNTT community operates outside the document.
[G0]: ETSI NFV OpenAPI-s are accessible for everyone here: https://forge.etsi.org/gitlab/nfv.
OpenStack API-s: https://docs.openstack.org/stein/api/

**Comment by pgoyal01** [comment]
@bfcohen The MEF work is related to Services (collection of VNFs) and overlap in scope of NFVO and NFVM (e.g., ONAP) -- I think these are out of scope for the work here. The Distributed TMF, abstract model differs from what we have in CNTT and, thus, the APIs are different; BTW I haven't verified all of them. 

It appears to me that, in our RM document, the interfaces will be tied to the abstract model (Chapter 3), will be platform agnostic and would not be exhaustive (restricted to model concepts). In the RA OpenStack version the APIs will be drawn from OpenStack.

Critique?

**Comment by rabi-abdel** [comment]
This seems to me a generic question that we need to add to FAQ. not sure it impacts any of the documents we are writing at this stage.

**Comment by rabi-abdel** [comment]
Not sure an action needed here. closing for now
