### ISSUE TITLE
[RM Ch03/4] Hardware Infastructure Management

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2050]
Hardware Infrastructure Management: function and APIs

**Comment by CsatariGergely** [comment]
CNTT should not define an API, but only high level functional requirements. Defining an API would mean, that CNTT RM would require a specific technology or CNTT should develop a technology and none of these are in the scope of the RM,

**Comment by TFredberg** [comment]
@CsatariGergely I can agree to that the title/content description of the issue should not include RM to specify API but rather interfaces, but I think we have to have a general discussion about where / how deep RM should or could aim which likely should be different levels in different areas. 
I completely agree to that CNTT shall not by itself define API´s, but at some level within CNTT we have to point to standards defined models, interfaces and possibly API´s that enables the wanted interoperability simplification that CNTT is created for.
Complete Technology Agnostic will likely not work as the RM today takls about a number of technology specific things.
To simplify for the operators in their selection of Infrastructure components and network functions we have to be more specific than the Reference Points that ETSI and others point out.
