### ISSUE TITLE
[RM Ch03/04] HW Acceleration abstraction

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2051]
Need to define an abstract model of acceleration and map to some concrete acceleration technologies

**Comment by CsatariGergely** [comment]
This should be aligned with the similar activities of O-RAN.

**Comment by petorre** [comment]
> This should be aligned with the similar activities of O-RAN.

Could you please point me to some documents?

**Comment by petorre** [comment]
Section titles in #2115 .

**Comment by petorre** [comment]
On https://wiki.lfnetworking.org/display/LN/RM+Hardware+Acceleration+Abstraction is initial text written jointly by @TFredberg , @qabpea , @walterkozlowski and me.
Please review and comment there on the Wiki. Later I'll create PRs.

**Comment by petorre** [comment]
> Please review and comment there on the Wiki. Later I'll create PRs.

Please review/comment PRs referenced to this issues (listed above), and not on the Wiki.
