### ISSUE TITLE
[RM Ch03/4] Observability/telemetry

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2052]
Need to define model for observability/telemetry

**Comment by sukhdevkapur** [comment]
The details are described in this google doc - 
https://docs.google.com/document/d/1BjRTIPVOs7vqZvvmd65CWX0vJU3YCGcq5McVyyxdXoY/edit?usp=sharing
Once this content is reviewed, I will open a PR and push the content to appropriate section/chapter.
