### ISSUE TITLE
[RM Chxx] Infrastructure LCM Automation - Umbrella issue

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2087]
IaC - LCM
Design and build consideration (with Automation) - collaboration with RAs and RIs (RI-1 is inactive)? Principles, guidelines in RAs? Is this really focus of Anuket? Declarative approach to automation. 
Automation 
9.5.1.1. Hardware Configuration CI/CD
9.5.1.2. Networking Automation
9.5.1.3. Software Development CI/CD1.

**Comment by wmk-admin** [comment]
Automation has started in Elbrus, but closed loop automation is under discussion now, so it will not be included in Elbrus

**Comment by walterkozlowski** [comment]
To be discussed at RM in the context of Automation chapter

**Comment by CsatariGergely** [comment]
@walterkozlowski I understand form your [comment](https://github.com/cntt-n/CNTT/issues/2087#issue-737438361), that this issue is about the LCM of the **infrastructure**.  Can we add this clarification to the title of the issue?

**Comment by walterkozlowski** [comment]
Closed by PR#2851, PR#2929.

**Comment by walterkozlowski** [comment]
Closed by PR#2851, PR#2929.
