### ISSUE TITLE
[RM] Virtual compute CPU and Virtual compute resource CPU

### ISSUE THREAD

**Issue by EditKoselak** [cntt-n/CNTT#2092]
The term "virtual compute CPU" is used many times in the RM chapters. Isn't it the same as "vCPU"? Is there a difference between the two? 

We also found the term "Virtual compute resource CPU". Should we use something else instead of this as well?

**Comment by pgoyal01** [comment]
@EditKoselak Thanks for finding these errors. May I suggest a simple solution for the examples that you have provided:

virtual compute CPU --> virtual compute resource (vCPU)

Virtual compute resource CPU --> Virtual compute resource (vCPU)
