### ISSUE TITLE
RM Chxx] Load balancing

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2095]
Initial concept description

**Comment by qabpea** [comment]
Loadbalancing in Openstack and Kubernetes
L4 and L7 load balancing can in its simplest form be reduced to an virtual endpoint (address:port or URL) and a set of endpoints that offers the service. The load balancer will distribute the sessions across the service endpoints according to some type of policy.

The usage of load balancing is very different in Openstack and in Kubernetes.
In Openstack, "IaaS" infra structure and network functions such as load balancers are created by the "users/tenants" at will using an API, the endpoint set can consist of any type of entity as long as it provides the targeted service(s).
Kubernetes differs here, internal, and external load balancing, are services  that are defined and implemented by the framework it self or by the service provider. The endpoint sets are implicit, a direct match to the replicas of a POD, all the entities in the endpoint set are of the same type. Load balancing in kubernetes does in many ways not fulfill the traditional definition of load balancing, in Kubernetes it is all about service scaling. The load balancer is invisible and does not have an API available for the "normal" user.

There is a choice to make when looking at the secondary interfaces and "network orchestration" in Kubernetes. 
Is the goal to create an "IaaS" type of environment with more feature rich API and features where any type of traditional NW can be built? 
Or should it follow the pod model with scaling implicit scaling between replicas of the same type.
How should Load balancing and service chaining interact? how are physical constraints taken into account?
DO we expect an external "super" orchestrator manage and setup all service interaction or should a cluster be able to use local meta information about services, infra structure, service chain definitions and rules/policies to orchestrate this?

---------
My preference will always be to make local decisions when ever possible. System that are dependent on a external global orchestrator has a tendency to become fragile and error prone

**Comment by wmk-admin** [comment]
@qabpea, I suggest to close this issue as the relevant PR has been. created and merged, if you are OK with this.

**Comment by wmk-admin** [comment]
I have double checked and the contents has been merged so I can close this issue.
