### ISSUE TITLE
[RA2 Ch2] Review NAT requirement(s)

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#2119]
There is currently only one requirement relating to NAT, which specifies that NAT must be supported ([infra.net.cfg.003](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#523-virtual-networking)).

Do we need a requirement that states NAT-less connectivity is required?  If so, for which workloads?

Refer to previous version of network spec in RA2 (since hidden, as no requirement trace):
|`ra2.ntw.005`|NAT less connectivity|An IPVLAN CNI plugin or the [MACVLAN CNI](https://github.com/containernetworking/plugins/tree/master/plugins/main/macvlan) may be used||

What is the use-case for that requirement?  @CsatariGergely ?

**Comment by CsatariGergely** [comment]
Speed, SIP and Diameter.

**Comment by rgstori** [comment]
added in https://github.com/cntt-n/CNTT/commit/35d7742ab7dcd3e321b410caaa15ac188f119275
