### ISSUE TITLE
[RA2 Ch03] Change table 3-1 to provide example implementations

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2134]
As opposed to a comparison between multus and DANM, create a list of CNIs

**Comment by tomkivlin** [comment]
Apologies I didn't notice this issue - do the changes in https://github.com/cntt-n/CNTT/pull/2121/commits/8870ccfa07795c62b8962c0a3d5fb19e2e8cad84#diff-ab4631ec11073c6526d42593ee36076830c05a659f62ccd28541fc7c42230ae7 cover what is being asked of here?

**Comment by rgstori** [comment]
there are now even more columns in the table, shall we close this issue and leave them as is?

**Comment by tomkivlin** [comment]
@rgstori it depends - I'm happy for that table to be changed further but yes I've added more columns and changed to focus from being Multus v DANM to being a comparison of the various approaches that could be taken when needing multiple network connections.  I think the title of this Issue still stands even with the changes I've done, but I don't think we can do it this week before the change freeze.  I will move to the backlog if that's ok?

**Comment by tomkivlin** [comment]
14/01/21 leave open for now as initial risks are mitigated. Potentially add this to RI in the future, let's see how it goes.
