### ISSUE TITLE
[RM Ch03] Illogical sub chapter order 

### ISSUE THREAD

**Issue by TFredberg** [cntt-n/CNTT#2135]
The Modeled entities in Chapter 3 do not fit with the existing chapter sequence. That makes it hard to read sequentially today and very hard to write for the reader to and gain understanding sequentially.
I suggest a change to:
3.1 Model
3.2 Virtual Infratructure Layer
3.2.1 Virtual Resources 
3.2.1.1 Tenant
3.2.1.2 Virtual Compute
3.2.1.3 Virtual Storage
3.2.1.4 Virtual Network
3.2.1.4 Availability Zone
3.2.2 Virtual Infrastructure Manager
3.3 Hardware Infrastructure Layer
3.3.1 Hardware Resources
3.3.1.1 Compute
3.3.1.2 Storage
3.3.1.3 Network
3.3.2 Hardware Infrastructure Manager
3.4 Sample reference model realization

This will also imply that existing chapters 3.5 Networking and 3.6 Storage have to be split up in its HW Infrastructure Layer and Virtualization Layer relevant parts.

**Comment by walterkozlowski** [comment]
@TFredberg: Where is the current 3.8  Hardware Acceleration in this new proposed flow?
In general, I agree this is a more logical flow but i doubt that we will be able to do this for Elbrus.  We need definitely to discuss this in the RM meeting and after that do the re-editing, which I am happy to do but after Elbrus release.  Unless there are any volunteers to do this change over the Christmas and New Year break....

**Comment by TFredberg** [comment]
@walterkozlowski Agree that it is too major to change in Elbrus. Chapter 3.8 Accelerators should likely be treated as Storage and Networking that needs to be split up in beteen the descrition of the Physical HW components (in part of 3.3.1) and how they are used by the Virtualization Layer and Tenents  (in chapter 3.2.1). The existing Storage and Networking do not have a separation of these concerns.

**Comment by karinesevilla** [comment]
@TFredberg @walterkozlowski Agree with Tomas proposal, the chapter will be more easy to read
