### ISSUE TITLE
Chapter 5: Refine Scaling parameter definition

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#215]
Refer to tables 5-5 and 5-11, per wed chap review mtg.

**Comment by karinesevilla** [comment]
The initial content of the feature "horizontal scaling" in Table 5-5 Virtual networking features was:
"The VNF cluster must be able to scale horizontally and to leverage technologies such as ECMP to enable scale-outs/scale-ins, privileging Active-Active HA models, even though this may require some level of application re-design to cope with the need of sharing state between VNF instances."

Table 5-5 is dealing with Virtual networking features of NFVI SW profiles (basic, network intensive and compute intensive).
The subject of horizontal scaling when speaking of additon of nodes is more general than NFVI SW profiles. It would be better to address horizontal scaling for NFVI at a global level, may be introducing load balancing. 
Another question: Should we consider ECMP (Equal-cost multi-Path protocol) a required routing protocol on infrastructure? 
I don't think we must be so prescriptive.

**Comment by karinesevilla** [comment]
Remove from reference model document and assign to architecture document

**Comment by rabi-abdel** [comment]
@karinesevilla shall this issue be re-assigned to "Reference Architecture"?

**Comment by rabi-abdel** [comment]
Addressed in a previous PR
