### ISSUE TITLE
[RM Ch05] 5.2.3 Virtual Networking

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2186]
[5.2.3 Virtual Networking](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#523-virtual-networking)

Reference | Feature | Type | Basic | Network Intensive
-- | -- | -- | -- | --
infra.net.cfg.002 | Overlay protocol | Protocols | VXLAN, MPLSoUDP, GENEVE, other |  

The Overlay protocol should also apply to the Network Intensive profile -- this was the case in the table that was commented out because of a change that was made.

**Comment by wmk-admin** [comment]
@pgoyal01, can you fix this via linked PR, thanks?

**Comment by pgoyal01** [comment]
@walterkozlowski Done PR # 2198

@ASawwaf @sukhdevkapur Can you please review and approve? Thanks
