### ISSUE TITLE
[Chapter 1] Instance Type and Compute flavour definitions

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#220]
In section 1.2.1, the definitions of instance type and compute flavour can be confusing.
Modification proposed:
Replace 
"Instance type: specifies a set of virtualized hardware resources and capabilities used for the creation of a virtual compute on which a workload runs on; includes capability specifications such as CPU, storage, and memory." 
by 
"Instance type: specifies a set of virtualized hardware resources and capabilities used for the creation of a virtual compute on which a workload runs on;
includes capability specifications characterizing compute, storage and memory."

Replace 
"Compute flavour: defines the compute, memory, and storage capacity, and the capabilities of the physical compute server that the virtual compute resource can run on."
by 
"Compute flavour: defines the virtualised resources (compute, memory, and storage) required to run a VNF component."

**Comment by bfcohen** [comment]
Added to Chapter 01.
