### ISSUE TITLE
[RA2 ch2] Review/remove req.gen.cnt.01

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#2203]
https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter02.md#23-kubernetes-architecture-requirements

It is not likely to be usefully covered in chapter04 as it is inherent in Kubernetes architecture.

**Comment by rgstori** [comment]
suggestion to mark as void (in the description field), or to delete line completely, but keep numbering of following lines
