### ISSUE TITLE
[Chapter 01] Roadmap section and diagram

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#221]
include more details or Roadmap and a diagram

**Comment by ASawwaf** [comment]
Some points to be added in Roadmap 

-GPU/FPGA supporting 
- Cyborg project should be added
- Container infrastructure and more on cloud-native
-

**Comment by bfcohen** [comment]
Added to Chapter 01 road map.

**Comment by bfcohen** [comment]
Rolled into Chapter 01.
