### ISSUE TITLE
[RA1 Ch03/04] RM Hardware Acceleration

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2239]
RM specifies various Hardware Acceleration technologies: https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#38-hardware-acceleration-abstraction

Align RA1

Umbrella issue

**Comment by karinesevilla** [comment]
Content added to umbrella issue #2786 , issue closed
