### ISSUE TITLE
[RA2] More clarifications to acceleration (and SR-IOV)

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#2255]
From [LFN DTF 2021.02: 2021-02-04 - Anuket - RA2 what's after Elbrus?](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=50528585):

- How accelerators are handled with device plugins?
- How the activation LCM works

**Comment by petorre** [comment]
Writing this comment as I still cannot co-assign @arkadykanevsky .

**Comment by petorre** [comment]
@CsatariGergely, @rgstori : With 3 PRs merged, this issue can be closed now. Ch4 specs for Containers in VMs I'll work as issue #2464 .
