### ISSUE TITLE
[RA2] Define explicit Kubernetes version instead of a relative one

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#2258]
From [LFN DTF 2021.02: 2021-02-04 - Anuket - RA2 what's after Elbrus?](https://wiki.lfnetworking.org/pages/viewpage.action?pageId=50528585):

Now RA2 is not consistent on the Kubernetes version

**Comment by pgoyal01** [comment]
@CsatariGergely can we identify the major inconsistencies?

**Comment by rgstori** [comment]
define specific k8s release in ra2.k8s.005

may also need to add k8s version for the current release in main index readme.md page, as a one stop shop table for the subcomponent versions

**Comment by CsatariGergely** [comment]
Kubernetes releases 3 times a year while Anuket have 2 releases. As a consequence I think we should define Kubernetes version ranges for each Anuket release. 

Specifying the Kubernetes release also means that we explicitly define the version of different components depending on the Kubernetes API-s, I think we should define these components and releases explicitly. We can add the versions to a readme.md page as @rgstori suggested.
