### ISSUE TITLE
Chapter 3 + 4 outlines

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#227]
work with @pgoyal01 and @walterkozlowski Assigned to @Ian Garnder

**Comment by rabi-abdel** [comment]
@iangardner22 and @pgoyal01 to provide a proposal of Chapter 3 + Chapter 4 outlines to be discussed on next RA Meeting on 3rd September. 

Please create two Pull Requests (one for Chapter 3 outline) and (one for Chapter 4 outline).

**Comment by pgoyal01** [comment]
@rabi-abdel Issue #227  RA Chapters 03 TOC please see #312 and for RA Chapter 04 please see #313.
