### ISSUE TITLE
[RA2 Ch04] Add requirement on IPAM capability

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2275]
CH04 should include a requirement for a K8S plugin capable of IP address management

**Comment by pgoyal01** [comment]
@rgostri we have a requirement in Chapter 2.3 for cluster-wide address assignment coordination - would this issue address that?

req.inf.ntw.10 | Infrastructure | Network | The Architecture must support Cluster wide coordination of IP address assignment.
-- | -- | -- | --
