### ISSUE TITLE
[RM Ch03] Update Service Function Chaining 3.5.1

### ISSUE THREAD

**Issue by kumarsumangit** [cntt-n/CNTT#2276]
Update section 3.5.1 .. refer ra2 issue #2189

**Comment by pgoyal01** [comment]
@sukhdevkapur @walterkozlowski @TFredberg @qabpea 
Please review write-up in Issue #2189 -- I am suggesting that an abstracted version should be used to update the writeup in [RM 3.5.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#3.5.1),

Please comment here and not in 2189. Thanks

**Comment by kumarsumangit** [comment]
Introduction
By principle, SFC definition is in orchestration, devOps and SDN controller domain, but it requires support at networking requirements.
SFC can be visualized as Service function plane (consists of SFF, SFC, SF, SF proxy) over Service function overlay network. Service function chaining utilizes a service-specific overlay that creates the service topology.  The service overlay provides service function connectivity, built "on top" of the existing network topology.
In Overlay network, packets are routed based on networking principles as destination ip, next hop.
However, in service overlay network, packets are routed based on policies unlike overlay network, again defined at Orchestrator level. This requires specific support at network level such as  at CNI in CNF environment to provide such specific routing mechanism.
It means, we need to define or capture items, which will help realize SFC at CNF environment, are  
1.	SFC aware interfaces available to Pod as plugins at CNI level. 
2.	CNI need to route packets based on policy, along with networking routing principles. 
For example,
   CNI enables SFC by assigning a port/interface to Container (SFC identifier, or SFCID, to each SF and sequencing these service SFCIDs in a ordered list.  A service SFCID may be of local significance or directly reachable from anywhere in the routing domain. 
Once packets destined to undergo SFP, CNI will be getting the information encapsulated in packet to enable this forwarding to Container (SF). This information will be encoded by SFC and forwarded to CNI to act as SFF.(out of scope for RA2) 

SFC Architecture
Functional Components:- 
SFC can be visualized as made of these components which makes SFC possible. 
1.	SFC Orchestrator – High-level orchestrator for SF and link between MANO and SF.
2.	SFC components for traffic steering in Service Plane. These are SDNC, SFF, SF & SF proxy.
3.	SFC Renderer – creates and wires port for SF data path. In CNF Environment, CNI agent to wire Policy rules for SFC. It can deploy different techniques to stitch the wiring but provide the same functionality, for example l2xconn, srv6 , Segment routing etc. 
4.	VNF MANO – VNF (SF) Lifecycle Manager NFVO, VNFM, VIM .

5.	CNF MANO- CNF DevOps Components, which are responsible for as SF LCM. For example cloudify, K8S, Ansible, etc.



![SFC Architetcure-VNF ](https://user-images.githubusercontent.com/47166781/109906582-c24b0f80-7cc6-11eb-9061-e6f765f431a7.png)

![SFC Architetcure-CNF](https://user-images.githubusercontent.com/47166781/109906633-dee74780-7cc6-11eb-955a-28678625d72f.png)


Call flow- 
Service function Chaining call flow visualized logically as two steps as shown in figure below:
1.	Creation of SFs
a.	SFC orchestrator creates the SFs with help of VNF MANO or CNF MANO.
b.	Attaches the SFC aware interfaces at SFs
c.	Booting up the SF configurations
2.	Creation of SFP using the created SFs and associated interfaces.
a.	SFC orchestrator creates SFP with help of SDNC
b.	SDNC pushes the SFC traffic steering policies.
c.	SFC classifier Policy provided for SFP. Note- not shown in call flow.
![SFC call flow](https://user-images.githubusercontent.com/47166781/109906661-edcdfa00-7cc6-11eb-8842-15081f930c7e.png)

 

For example, to create the SFC in container system shown as above. After creation of container, SFC interfaces created, identified by interface Ids and attached with the container. These interface IDs ae used to render SFP for given SFC. 
Once packets received on these SFP, policy driven packet steering performed to route packets to SF for processing.  

A  Service Function Path consists of:
•	A set of ports( in VNF environment) or interfaces ( in CNF environment) , that define the sequence of service functions 
•	A set of flow classifiers that specify the classified traffic flows entering the chain.

If a SF involves a pair of ports/interfaces, the first port/interface acts as the ingress port/interface of the service function and the second port/interface acts as the egress port/interface. 
First port/interface of the first port/interface-pair is the head of the service chain. The second port/interface of the last port/interface-pair is the tail of the service chain. A bidirectional service chain would be composed of two unidirectional Port Chains.

For example, [{p1: p2}, {p3: p4}, {p5: p6}]/[{i1:i2},{i3:i4},{i5:i6}] represents:


 
![SFP chain](https://user-images.githubusercontent.com/47166781/109906705-fd4d4300-7cc6-11eb-8dba-fddd0fc1f7bd.png)









Policy for SFP Model, for example–
 
![SFP Data model](https://user-images.githubusercontent.com/47166781/109906729-08a06e80-7cc7-11eb-9bbf-22dbfe54c528.png)


Summary to RM relevance:-
Relevance to RM-
1.	Attaching SFC supporting Interfaces/Ports at Pod/vm using multi plugin/Port
2.	Architecture support for SDN controller interfaces at Network/CNI
3.	Configuring policy driven routes to steer traffic between these Ports/Interfaces via SDN controller .
Out of scope of RM :- 
Note:- these are not exhaustive list.
1.	How CNI/Network will support SFC using SRv6, mpls, NSH ?
2.	How SDN controller will interact with Network/CNI for SFC policy?
3.	How packets are classified for SFC?
4.	How SFP is created from SFC design?

**Comment by walterkozlowski** [comment]
@kumarsumangit, could you please present the contents and ask for feedback at the RM meeting this Wednesday?  I will assign 20 min Utes in the Agenda for it.  Please confirm.

**Comment by kumarsumangit** [comment]
@walterkozlowski Sure, mark it confirm  .. i will present the contents .. meanwhile i will update with some modification before meeting. Thanks

**Comment by walterkozlowski** [comment]
Thanks!

**Comment by pgoyal01** [comment]
Per @walterkozlowski suggestion to create 3 PRs, @kumarsumangit may I suggest the following PRs:
1. Introduction
2. Architecture
3. Call Flow and Summary

**Comment by walterkozlowski** [comment]
Agree with @pgoyal01. I would suggest having a good description of all abstract components of the SFC with examples relevant to RA-1 and to RA-2.  This could be part of PR on Intro.
