### ISSUE TITLE
[Chapter 8] Compliance, Verification, and Certification

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#228]
8.2 The objectives of the verification program are to deliver certified reference architecture which matches VNF-developer specifications, levering the OVP ecosystem as the vehicle for deliverying validated NFV.

8.2.1.1 Deliver certified reference architecture which matches VNF-developer specifications
 
(and other similar statements ...)

8.6.2. "NFVI Certification (Compliance): NFVI is the SUT, ensuring NFVI is compliant with specs of Ref Model and Ref Architecture accomplished with Manifest Validations (performed via Echo Tests)"

--------------------

Is there a disconnect between 8.2 and 8.6? 8.2 is referring to certify Reference Architecture as per some VNF-developer specifications? Would the latter differ by VNF vendors? 

8..6. is referring to certifying that the NFVI (implementation?) conforms to the CNTT Reference Model and Reference Architecture.

**Comment by mf4716** [comment]
Rewrote 8.2, 8.2.1.1, 8.6, and related sub-sections, to ensure consist use of terms, and alignment on verification of the implementation of RM/RA.  

Please review and confirm if this issue can be closed.

**Comment by mf4716** [comment]
@pgoyal01 - review changes and confirm if issue can be closed

**Comment by mf4716** [comment]
Closing.  No further comment/feedback.
