### ISSUE TITLE
[RA2 Ch4.3] Define profile/flavour labels for relevant Hardware Acceleration Abstraction options

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2299]
ref RM chapter 3.8 - Hardware Acceleration Abstraction

need to define (and add specs in ch4) labels for Hardware Acceleration on K8S nodes.
 
- Not all controllers for accelerators may be in scope - do we need to specify the interface if the accelerator is not part of the infrastructure?
- Likely overlap with RA1 - problem space is overlapping

**Comment by CsatariGergely** [comment]
I propose to rely on the [Device Plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) of the accelerators as in this way the resources of the accelerators can be also managed and to use [node-feature-discovery](https://kubernetes-sigs.github.io/node-feature-discovery/stable/get-started/index.html) to label the nodes based on their HW feature advertisement. 
I can start a pr on this if there are no objections to the approach.
