### ISSUE TITLE
[Chapter 08] - 8.1 Introduction needs clarity

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#230]
8.1 Introduction
This document includes process flow, logistics, and requirements which much be satisfied to ensure Virtualized Network Functions (VNFs) meet the design, feature, and capability expectations of VNF consumers to deliver NFV promoting the use and scalability of SDN capabilities. This chapter captures the core fundamentals and steps needed to certify VNFs on target NFVi frameworks and architectures which drives more work into the community, resulting in pre-certified VNFs on core capabilities ultimately reducing the amount of time and cost it takes each operator to on-board and maintain vendor provided VNFs..

--------
Suggest a rewrite of these 2 sentences.

**Comment by rabi-abdel** [comment]
@idbalabla

**Comment by mf4716** [comment]
The Intro has been re-written, and GitHub updated, as follows.  Please confirm if we can close.

8.1 Introduction
This document includes process flow, logistics, and requirements which much be satisfied to ensure Virtualized Network Functions (VNF) Infrastructure meets the design, feature, and capability expectations of VNF developers promoting both the use and scalability of Software Defined Networking (SDN) capabilities.  Upstream projects will define features/capabilities, test scenarios, and test cases which will be used to augment OVP test harnesses for infrastructure verification purposes.  Existing processes, communication mediums, and related technologies will be utilized where feasible.  Ultimately, test results of certified NFVI+VNF will reduce the amount of time and cost it takes each operator to on-board and maintain vendor provided VNFs."

**Comment by pgoyal01** [comment]
@mf4716 Thanks. May I suggest replacing "Virtualized Network Functions (VNF) Infrastructure " with Network Function Virtualisation Infrastructure (NFVI)?"

**Comment by mf4716** [comment]
Ch 8 Intro - replaced VNF with NFVI in opening paragraph, corrected typo, "requirements which must" (not much).  Closing.
