### ISSUE TITLE
[RA2 Ch6] Add Gaps for missing controller/APIs/interfaces for relevant Hardware Acceleration Abstraction options

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2300]
linked to #2299 
ref RM chapter 3.8 - Hardware Acceleration Abstraction

need to define what's missing in terms of controller/APIs/interfaces for relevant Hardware Acceleration Abstraction options.
Eg: FPGA k8s operator

**Comment by petorre** [comment]
@rgstori : Please see if PRs #2415 and #2416 close this, or if not let me know what is missing delta and I'll look into it.

**Comment by rgstori** [comment]
addressed in #2452
