### ISSUE TITLE
[RM Chapter 10] - RM Requirements Life-cycle Management (Process gap)

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#231]
As discussed on the Chapter 6 Interfaces call:

Discussion needed to address a fundamental question related to forward looking, life-cycle RM requirements changes, and the need to define a process for handle these in the RA since they may not be able to be accommodated, or implemented.  

Opening

**Comment by rabi-abdel** [comment]
PR to be created for this issue.

**Comment by rabi-abdel** [comment]
Addressed in https://github.com/cntt-n/CNTT/pull/342

**Comment by rabi-abdel** [comment]
can be closed now
