### ISSUE TITLE
[Chapter 1] Clarify the Term "VNF"

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#232]
From: CNTT TSC meeting of 28/8/2019
The purpose of this Issue is to create standard language to qualify the definition of the term "VNF", to explicitly indicate that it refers to Containers, as well as VMs. The intent is that this language will then be appended **to every instance of the term VNF** throughout the CNTT document suite, so as to ensure consistent messaging and intent is communicated when the term is referenced.

**Comment by pgoyal01** [comment]
There is also an open issue from Rabi #139

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by bfcohen** [comment]
I added it to chapter 01 to make it explicit in the introduction.
