### ISSUE TITLE
[RM Ch3] Improve text about standardized interfaces

### ISSUE THREAD

**Issue by petorre** [cntt-n/CNTT#2327]
@TFredberg and @arkadykanevsky to improve text about standardized interfaces in [3.8.2 Infrastructure and Application Level Acceleration](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#382-infrastructure-and-application-level-acceleration) .

**Comment by TFredberg** [comment]
I don´t really know what to extend the text with, with the exception of the Node-Feature-Discovery (NFD) function in K8s possibly in the CISM, where I also think Custom Resource Definitions (CRD) would be used in some way. I would though not be the person to describe how that is done and what text should describe that best. Any takers that could help with such formulations around NFD and possibly also CRD?

**Comment by petorre** [comment]
> 
> 
> I don´t really know what to extend the text with, with the exception of the Node-Feature-Discovery (NFD) function in K8s possibly in the CISM, where I also think Custom Resource Definitions (CRD) would be used in some way. I would though not be the person to describe how that is done and what text should describe that best. Any takers that could help with such formulations around NFD and possibly also CRD?

This was specifically for RM. If you don't feel there is more to add, let's close this issue?
For RA2 we already have several issues and people assigned to work it, includes NFD and CRD.

**Comment by TFredberg** [comment]
I would be interested to see where NFD and CRD should be add in the picture in this chapter, but I would like input from people of where to place them and possibly what text to add.

Would you have the correct contacts in RA2 to get that input from?

 

BR Tomas

**Comment by petorre** [comment]
>  Would you have the correct contacts in RA2 to get that input from?

@CsatariGergely , @arkadykanevsky and me assigned to work issues #2255 and #2299 .

**Comment by walterkozlowski** [comment]
Issue closed as discussed at RM Meeting on 31 March 2021 (see comments above)
