### ISSUE TITLE
[RA2 Ch3.8] Define SyncE requirement

### ISSUE THREAD

**Issue by arkadykanevsky** [cntt-n/CNTT#2328]
Some of the workloads, like open RAN (oDU, oRU, OCU) require Synchronous Ethernet for communication. Need to define a section for it as well how to map that requirement to RM1 and RM2.

**Comment by petorre** [comment]
Or more generally requirement for Timing Accuracy also incl. PTP.

**Comment by arkadykanevsky** [comment]
PTP should be a separate requirements. Tomas mentioned that it is already in the requirements list. Need to check. If not there then add another issue.

**Comment by petorre** [comment]
> 
> 
> PTP should be a separate requirements. Tomas mentioned that it is already in the requirements list. Need to check. If not there then add another issue.

OK, raised #2329 .
