### ISSUE TITLE
[RM][RA1][RA2] Streamline names of flavours

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2334]
All different names for flavours should be changed to:

- `workload flavour` if it refers to a workload/nf/application
- `node flavour` if it refers to infra/nodes

**Comment by ulikleber** [comment]
Suggest node flavour, since it refers to a single node and infrastructure sounds very general.

**Comment by rgstori** [comment]
agreed, will update #2312 accordingly

**Comment by pgoyal01** [comment]
@rgstori Can you review [RM Chapter 4: Section 4.2 Rewrite Proposal](https://wiki.anuket.io/display/HOME/RM+Chapter+4%3A+Section+4.2+Rewrite+Proposal). If it makes sense, then there may be some changes needed to RM 2.4

**Comment by pgoyal01** [comment]
@rgstori Since we are deleting pre-defined workload flavours, is this issue relevant? Or do you want to change this to incorporating all of the profile changes

**Comment by pgoyal01** [comment]
RM: Partially fixed by PR #2384

**Comment by pgoyal01** [comment]
Meeting of May 24, 2021, decided to close as no longer needed.
