### ISSUE TITLE
[RA2 Ch4] Define usage policy for Kubernetes alpha and beta API-s

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#2349]
Kubernetes have lots of non GA API-s which are not production ready and can be deprecated at any time. I think we should define an explicit policy about the usage of alfa and beta api-s. 

I would propose that: 
 - beta API-s are okey to use
 - An explicit selected list of alfa API-s are okey to use or just restrict the usage of alfa API-s

Any opinions?

**Comment by CsatariGergely** [comment]
@collivier , @rgstori

**Comment by petorre** [comment]
> I think we should define an explicit policy about the usage of alfa and beta api-s.

I agree. Defining such policy would help faster decide on some specific usage.

**Comment by collivier** [comment]
A Beta feature should be considered as enabled by default
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages).
Or most of them: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

Disabling all beta features could quickly lead to many issues.
See calico for instance (PodDisruptionBudget is GA in v1.21)
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/calico-kube-controllers created

Alpha may be quite disruptive and we could rather consider the related features as a gap which may be fulfilled once it's beta.

@CsatariGergely nit: typo in issue title ;)
