### ISSUE TITLE
[RM Common] Common - Technical Policies

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#2352]
[CNTT Technical Policies and Transition Plan](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md) needs to be updated to follow the recent and ongoing developments on acceleration technologies in RM.
An update is also needed to replace CNTT by Anuket in the all text.

**Comment by karinesevilla** [comment]
Per RM meeting, 14th of April, references to 'CNTT technical Policies and Transition Plan' are obsolete and  must be removed.
References to CNTT policies are still in chapter 4  [4.1.2.2](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4122-exposed-performance-optimisation-capabilities) for e.cap.013 to e.cap.016 notes:
"Capabilities generally require hardware-dependent drivers be injected into workloads. As such, use of these features shall be governed by the applicable CNTT policy. Consult the relevant RA specification for the usage policy relevant to any needed hardware capability of this type."

**Comment by wmk-admin** [comment]
Closed, as we do not reference this section in RM
