### ISSUE TITLE
[RM Ch03] SFC Section 3.5.1 Architecture

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2353]
@kumarsumangit Should this section include a ER diagram. For example, J. Blendin, J. Ruckert, N. Leymann, G. Schyguda, D. Hausheer, "Software-Defined Network Service Chaining",  2014 Third European Workshop on Software-Defined Networks, pp 109-114, includes the following diagram:

![GetImage](https://user-images.githubusercontent.com/52107136/114612617-97f25780-9c5f-11eb-967b-d784d3803230.png)

I suspect there may be other such models.

**Comment by wmk-admin** [comment]
Closed by PR#2276
