### ISSUE TITLE
[RM Ch02] Workload Profiles

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2354]
Define Workload profiles
- aligned with Node Profiles 
- include latency
- align with OPG requirements

**Comment by pgoyal01** [comment]
RM [Section 2.4](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter02.md#24-node-profiles--workload-profiles) defines both Node and Workload Profiles.

RM [Section 4.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter045.md#4.1) specifies the node profile features -- need to be aligned with changes in RM Section 2.4.

RM [Section 5.1)(https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#5.1) and [Section 5.2](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#5.2) define "Software Profiles". **Should these be referred to as Workload Profiles)?**

RM [Section 5.4](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#5.4) specifies the node profile features -- need to be aligned with the changes in RM Section 2.4. **Should this section be merged with Section 4.1 -- all node profile features in one place?**

**Comment by pgoyal01** [comment]
Alignment with OPG conceptual Operator Platform missing from node profile and workload profile:
- CPU Architecture
- Hypervisor
- Host OS

OPG document missing elements such as CPU Pinning.

Both documents missing, for workload profiles, affinity, non-affinity, dedicated cores

**Comment by pgoyal01** [comment]
Should we standardise use of terms such as capabilities, features, etc.

ETSI [NFV Release 4 Definition](https://docbox.etsi.org/ISG/NFV/Open/Other/ReleaseDocumentation/NFV(21)000025_NFV_Release_4_Definition_v0_3_0.pdf) defines the following terms:

Capability: ability of an item to perform an action under given internal conditions in order to meet some demand

Feature: functionality which represents added value to the system for a defined set of users
        NOTE: A user could be a network operator, service provider, VNF provider, or some other defined actor.

Function: the abstract concept of a particular piece of functionality in a device, entity or service

Functionality: sum of actions or any aspect an item can do
        NOTE: Functionality can be associated to diverse items, including devices, entities, services and/or features.

Release: a set of deliverables that specify a well-defined, stable and internally consistent set of functions
        NOTE: A Release differs from the previous Release by having added and/or improved functionality introduced as a result of standardization work.

Release Definition: the ensemble of Features of a particular Release

Release Description: the description of specification outputs delivered by the Release

**Comment by pgoyal01** [comment]
Change Network Intensive to High Performance

**Comment by wmk-admin** [comment]
Closed by PR#2450 now merged, as per Minutes of RM meeting on 2 June 2021
