### ISSUE TITLE
[RM Ch04] 4.3 Networking Section doesn't belong in Chapter 4

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2365]
Sections 4.1 and 4.2 are about exposed capabilities, Profiles and Flavours. Section 4.3 is quite different and so should be moved.

**Comment by petorre** [comment]
> Sections 4.1 and 4.2 are about exposed capabilities, Profiles and Flavours. Section 4.3 is quite different and so should be moved.

@pgoyal01 : Agree it doesn't fit there. I could move it to be new 3.5.3, so moving current .3 to .4 and current .4 to .5. Would it fit there better?

**Comment by pgoyal01** [comment]
@petorre Another alternative is to review the current Section 3.5 in its entirety and explore Options. In addition to your Option (Option 1), I think there is another option (please see below). If we go with Option 1, we would still need to rationalise some of the content in the main Section 4.3. Critique?

Option 2:
The current Section 3.5 has 3.5.2 (numbering error) as "Network Introduction"; I don't think that should be a numbered section or that the content should have a header as it can be just text under 3.5. The next Section also 3.5.2 (could become 3.5.1) is about Network Principles. 

If the above changes are made it frees up a 3.5.2 for use. This new 3.5.2 can incorporate 4.3 except that some of the content under the main 4.3 belongs together with (and some is duplicate) what is under the current 3.5.2 Network Introduction.  That is, some of the content in the main 4.3 that is related to the content of what is currently under "Network Introduction" needs to be rationalised.

**Comment by petorre** [comment]
> Option 2:
> The current Section 3.5 has 3.5.2 (numbering error) as "Network Introduction"; I don't think that should be a numbered section or that the content should have a header as it can be just text under 3.5. The next Section also 3.5.2 (could become 3.5.1) is about Network Principles.
> 
> If the above changes are made it frees up a 3.5.2 for use. This new 3.5.2 can incorporate 4.3 except that some of the content under the main 4.3 belongs together with (and some is duplicate) what is under the current 3.5.2 Network Introduction. That is, some of the content in the main 4.3 that is related to the content of what is currently under "Network Introduction" needs to be rationalised.

@pgoyal01 : Thanks for great guidance. Please see PR #2429 .
