### ISSUE TITLE
[RM Chapter 7] Sections 7.1 and 7.2

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#239]
The text included in 7.1 and 7.2 is related to chapter 8 "Compliance, verification and certification".
It's a wrong copy paste, it must be clean up

**Comment by mbustame** [comment]
I updated these sections today and will put in this week's pull request

**Comment by mbustame** [comment]
Closing issue, sections updated and reviewed during Chapter meeting
