### ISSUE TITLE
[RA Chapter 2] LCM: add horizontal scaling

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#240]
Coming from RM issue#215

RA §2.3.6 The requirement "horizontal scaling" should be added to the table 2-6
sub-category: general
description: The Architecture must support automated horizontal scaling when new nodes are added.

**Comment by pgoyal01** [comment]
@karinesevilla Would it be OK to add to "Section 2.3.3 -- VIM" as it relates to orchestration? If yes, then I am covering this under "`req.vim.09` | General | The Architecture **must** support horizontal scaling."

**Comment by karinesevilla** [comment]
@pgoyal01 Yes, I agree to add "Horizontal scaling" to 2.3.3

**Comment by pgoyal01** [comment]
@karinesevilla Since it has been added as req.vim.09, can you close this issue? Thanks
