### ISSUE TITLE
[RA2] Rewrite ra2.k8s.013

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#2451]
As discussed in RA2 meeting (badly it was merged anyway), I consider ra2.k8s.013 as false.

Anuket/CNTT selects a minimal release for each release (next will be v1.21).
I don't see the point why the infrastructure **MUST** offer the beta API whatever this deprecation.
ra2.k8s.013 simply looks like we allow the workload not to be updated according to the versions selected and forces the infrastructure to pay for this deprecation.

We could rather clarify that Anuket/CNTT could ask for beta API only if there is no GA API covering a particular Anuket/CNTT need.

BYW I would consider it more as forward compatibility rather than backward..

**Comment by CsatariGergely** [comment]
The reason is to avoid the mandatory update of CNF descriptors several times a year. Keeping the beta API-s active until they are supported by the actual Kubernetes release allows lower frequency of CNF redeployment.

**Comment by rgstori** [comment]
split into two

- one just for GA
- as backup when GA of the same version doesn't exist, beta is fine
