### ISSUE TITLE
[WS-All Chxx] Proofreading

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2466]
RM
- Ch02 BNG should Broadband Network Gateway (not Border)
- Ch07: 7.4.3 Platform ‘front-end’ access security      DDOS should be DDoS
- Ch10: 10.3.5 link in TOC
- Ch10: make Cyborg Project active link rather than have url separately listed
- All - change "Network Intensive" to "High Performance"

RA1
- Ch 2 IaaS, PaaS, SaaS: capitalisation error

RC1
- Ch02: VFNSDK -- should be VNF SDK

**Comment by karinesevilla** [comment]
RM Ch04:
- 4.2 Capital letter for Cloud Infrastructure
- Fig 4-3 Network Intensive -> High Performance
- 4.2.7.2 and 4.2.7.3 Capital letter for Cloud Infrastructure and CNTT to be replaced by Anuket

**Comment by jtwill98** [comment]
**RM - C2 S2.2  
Correct the spelling of extended in the text blow.  
	Text:  The list of use cases will be extendd in the future releases.

Add a comma after common in the text below.   	
	Text:  The requirements for user plane Local Breakout / Termination are common mandating that Value Added Services (VASs) & Any Gi-LAN applications are locally hosted at the Edge.

**Comment by pgoyal01** [comment]
RA1 2.4.2 -- a change had previously been approved and merged but this has reverted to "should not" and needs to be changed back to "may"

inf.acc.03 | Acceleration | The Architecture should not rely on SR-IOV PCI-Pass through to provide acceleration to VNFs.
-- | -- | --

**Comment by pgoyal01** [comment]
RA1 Proofreading corrections completed -- PR #2484

**Comment by wmk-admin** [comment]
Fixed
