### ISSUE TITLE
[RA1 Ch-All] Add/Change around containers as per OpenStack evolution

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2498]
Add/Change requirements and content around containers as per OpenStack evolution

**Comment by CsatariGergely** [comment]
@pgoyal01 is this about the containerization of the OpenStack services or the support of containers as a workload i nOpenStack?

**Comment by pgoyal01** [comment]
Per the decision of the RA-1 meetings this issue is being closed as the current content is sufficient for the "containerization of the OpenStack services".
