### ISSUE TITLE
[RA1 Ch02, 04] Use of OpenStack APIs for Edge, Hybrid and Multi-clouds

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2499]
Add requirements around the use of OpenStack APIs for Edge, Hybrid and Multi-clouds.

Update (Jan, 2022): Use StarlingX deployment options and existing production deployments to cover API needs for edge. The scope of hybrid and multi-cloud is still under investigation in the Reference Model.

**Comment by karinesevilla** [comment]
Content added to umbrella issue #2784, issue closed
