### ISSUE TITLE
[Chapter 4] : Update to align with Terminology

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#25]
Once terminology approved, please update 3.2 accordingly.

**Reviewers** : Mark S, Tom K

**Comment by TommyKTheDJ** [comment]
👍

**Comment by markshostak** [comment]
Placeholder PR; dependent on PG update to Chap 1 (due Monday 8/7/19)

**Comment by tomkivlin** [comment]
I'm using a new GitHub account for work related things.

**Comment by rabi-abdel** [comment]
I believe this is no longer needed?

**Comment by rabiabdel** [comment]
i don't think this is needed anymore
