### ISSUE TITLE
[RM] Add Storage intensive Profile

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#250]
There might be a need to add storage intensive profile.

**Comment by pgoyal01** [comment]
Do we need a storage profile or do we need to relook at our existing profiles and see how we can meet the needs for larger amount of storage and higher IOPS.

 For example, modify [4.2.3 Storage Extensions](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#423-storage-extensions) to remove storage size limitations and/or define other IOPS Tiers

**Comment by walterkozlowski** [comment]
Decision from RM meeting on 29 July 2020 not to create such profile but use Table 4-15 in RM.
