### ISSUE TITLE
[RA2] Update k8s release to 1.23

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2509]
Throughout RA2 (including the table in the README), update references to K8s and its subcomponents to release 1.23

**Comment by msidana** [comment]
I can work on this.

**Comment by CsatariGergely** [comment]
Based on the release cadence of Kubernetes what is 4 months between releases and the [release date of 1.21](https://kubernetes.io/releases/) what was 2021-07-14 1.23 will be released in February 2021. I think we should refer only to already released Kubernetes versions in RA2.

**Comment by rgstori** [comment]
agree, should go in rel. Lakelse+1
