### ISSUE TITLE
[RM Ch07] Add NIST reference for service mesh security

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#2540]
Per John Kimmins (GSMA FASG) comment (07/06/2021), include NIST SP 800-204B as security reference (7-10) for service mesh security. Develop on service mesh security if necessary.

**Comment by karinesevilla** [comment]
[NIST.SP.800-204B-draft.pdf](https://github.com/cntt-n/CNTT/files/7008407/NIST.SP.800-204B-draft.pdf)
The document deals with security for microservices-based applications using service mesh. It applies to RA2 architecture (Kubernetes and Istio).
RA2 chapters 3 (3.2.2) & 4(4.7) mention that application service mesh is out of scope.
Do we keep this issue and elaborate on it into RM?

**Comment by CsatariGergely** [comment]
I do not see the relevance of this at the moment.
