### ISSUE TITLE
[RM Ch10] Gap: Need Artifact to Deliver CNTT Parms

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#255]
CNTT needs a conduit to deliver VNF-specific configuration parameters such as Compute Flavor (B, N, C) to orchestration. Currently, this data cannot be captured in the VNFD, Heat template, etc., as the parser does not understand CNTT options. This will require changes to the upstream, or some alternative (e.g., CNTT pre-processor/mediation) to resolve.

**Comment by walterkozlowski** [comment]
Issue closed at RM meeting on 26 August 2020, as implementation specific.
