### ISSUE TITLE
[RA2 Ch04] RA2 README -- non-existent

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2559]
[4.3 Kubernetes](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter04.md#43-kubernetes) requirement

ra2.k8s.001 | Kubernetes Conformance | The Kubernetes distribution, product, or installer used in the implementation must be listed in the [Kubernetes Distributions and Platforms document](https://docs.google.com/spreadsheets/d/1uF9BoDzzisHSQemXHIKegMhuythuq_GL3N1mlUUK2h0/edit#gid=0) and marked (X) as conformant for the Kubernetes version defined in [README](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/README.md#required-versions) under "Required versions of most important components". | req.gen.cnt.03 | 4.3.1
-- | -- | -- | -- | --

There is no README with sections. Also, the README link has a typo:  remove "chapters"

**Comment by CsatariGergely** [comment]
I'm correcting the location of the README, but what do you mean on "There is no README with sections"?
