### ISSUE TITLE
[RM Chapter 2 - section 2.3 ] NFVI profiles figure update

### ISSUE THREAD

**Issue by xavier-grall** [cntt-n/CNTT#256]
For alignment with commited PR #235, section 2.3 figures must be updated as proposed here: 
https://github.com/xavier-grall/CNTT/commit/da7711c2fd8a00e7eae632462a330f054ae2fb17
ie, with this diagram: 
https://github.com/xavier-grall/CNTT/commit/d1b494d463bdcb69dc977a7051260288fd28bd84?short_path=7b203a6#diff-7b203a67fe864b84c1d0b7c68ffcc645
NB:Minor typos are also fixed by the way.

It should be noted that those proposals (this one and previous #200 #235) also imply some changes in chapter 4 and 5:
- basic and compute-intensive profiles only differ on resource allocation strategy (but with same hardware):
   * Basic with cpu oversubscription ratio (1:4)
   * Compute-intensive with optimized and dedicated resource (cpu pinning and hugepages)
- network-intensive profile is a compute-intensive profile enhanced with any other software or hardware specificities (DPDK, SRIOV/SmartNIC, FPGA…)

The rationale for those changes is the following:
Previously both network-intensive and compute-intensive profiles were fitting some data plane functions, while latency-sensitive control plane functions (as MME, AMF or IMS-CSCF) did not have any suitable profile.
Now, any data plane functions can be hosted on the network-intensive profile and latency-sensitive control plane functions on the compute-intensive profile.

**Comment by xavier-grall** [comment]
@pgoyal01 @ASawwaf 
The idea is to show a standardized or well-known VNF related to management plane.
I agree that BSS functions are not really NF, dispite they are telco-specific.
So we can replace it by:
- either an other management-related VNF (in addition to NMS): which one ?
 - or an other control-related VNF without specific performance requirement (in addition to PCRF): NSSF (5G core) ?

**Comment by pgoyal01** [comment]
@ASawwaf I read through Chapter 2 a bit more carefully this time. A couple of the acronyms are not defined; also within EPC Nodes, on the MME (Mobility Management Entity), EPS (Evolved Packet System) is used. 

Under Profile One, it states, "Control plane functions without specific need and management plane functions" -- I think some words are missing after "without specific"; should it state "without specific compute host software and hardware configuration needs (for example, NUMA, CPU pinning)".

Similarly, for Profile 3, the statement, "Control plane functions with specific computing needs" could be adjusted to state "Control plane functions with specific compute host software and hardware configuration needs (for example, NUMA alignment, CPU pinning) ".

@xavier-grall If we follow @ASawwaf Profle classifications then the Basic Instance Type can be used for certail control VNFs as well as management plane VNFs.  If you agree then possible choices to replace NMS (Network Management System) and BSS could include, for example, AAA and eNUM.

**Comment by xavier-grall** [comment]
@pgoyal01 @ASawwaf 
I am the author of those statements, so they are written with my wording, and my english may not be accurate enough...

At this point of the document, we should only speak of the VNF needs regarding NFVI, and not how they could be technically fullfilled, so I chose to use the following wording to distinguished 2 types of control plane function (aiming at being hosted either on basic node or on compute-intensive node) :
- w/o specific need
- w/ specific computing needs
Here the computing needs refer to the description above in the text (Computing speed and Specific processing)

For VNF examples, if we agree on VNF targeted by basic profile, ie including management plane functions, we should also have such example: ok to replace BSS, eg by  AAA, but I think we should keep NMS as a management plane function.

**Comment by pgoyal01** [comment]
@xavier-grall Thanks (BTW you may have noticed all sorts of errors in my writing including missing words/phrases).

I am OK with keeping NMS but we need to define it within Chapter 2 text (it may be there and I missed it).

**Comment by ASawwaf** [comment]
> @pgoyal01 @ASawwaf
> I am the author of those statements, so they are written with my wording, and my english may not be accurate enough...
> 
> At this point of the document, we should only speak of the VNF needs regarding NFVI, and not how they could be technically fullfilled, so I chose to use the following wording to distinguished 2 types of control plane function (aiming at being hosted either on basic node or on compute-intensive node) :
> 
> * w/o specific need
> * w/ specific computing needs
>   Here the computing needs refer to the description above in the text (Computing speed and Specific processing)
> 
> For VNF examples, if we agree on VNF targeted by basic profile, ie including management plane functions, we should also have such example: so, ok to replace BSS, eg by AAA, but I think we should keep NMS as a management plane function.

@xavier-grall sorry i got confused :(

**Comment by xavier-grall** [comment]
@pgoyal01 @ASawwaf
Here is a new change proposal for chapter 2 (considering our discussion, I hope ;-)
https://github.com/xavier-grall/CNTT/commit/fd3ed20e6a01d1ac984d260f78b33aa7153dfebd
It includes a new figure and also some text changes including a review of section 2.1.
The figure is here:
https://github.com/xavier-grall/CNTT/commit/d3e5c3b77cacd207575ac6de98b454dabc9adb3d?short_path=7b203a6#diff-7b203a67fe864b84c1d0b7c68ffcc645

Can I create the related PR ?

**Comment by rabiabdel** [comment]
@xavier-grall please go ahead and submit the PR for Thursday meeting.
Rabi

**Comment by rabi-abdel** [comment]
PR merged for issue merged.
