### ISSUE TITLE
[RA02 Ch02] Missing specification reference for req.kcm.gen.01

### ISSUE THREAD

**Issue by rihabbanday** [cntt-n/CNTT#2563]
The requirement `req.kcm.gen.01` regarding `policy driven horizontal auto-scaling of Kubernetes Cluster` needs more explanation - there is nothing linked in the "specification reference".

If this refers to "horizontal pod scaling", we could link/reference the official Kubernetes documentation here - https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/.

**Comment by rgstori** [comment]
addressed in #2710
