### ISSUE TITLE
[RM Ch08] Identify and Codify Clear Test Objectives

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#259]
Need succinct objectives and scope clearly identified at beginning of test chapter.
Should be short and sweet :-)

**Comment by mf4716** [comment]
@markshostak 

8.1 Introduction Updated to more clearly articulate the scope early on in the documentation.

Review for comments, or closure.

Added: Objective, Scope, Repeat statement, and Not In Scope comment

**Comment by markshostak** [comment]
Hi Mike, Looks like a good start. Here are a few thoughts, per your request:
1) Please provide a link to your changes. It took some digging to find them; had almost given up...
2) Need to define new terms (verification, validation, compliance, scenario, harness, compatibility, etc.)
2b) Might also want to explicitly state your intention is to align the terms w/ CVC definitions
2c) While some TLAs are expanded in Sect 8.3.1 (e.g., CVC, OVP, etc.), and some are mentioned in the synopsis, it is only to the extent that they provide "governance and tracking"; an understanding of what these entities are, what they do and how they relate to CNTT, is crucial to understanding your methodology. I would try to be more comprehensive in the synopsis. 
3) Do you want to address the security component, and/or a reference to the relevant section of the security chapter?
4) I believe you want to declare the chapter's purpose, not the document's purpose
5) You mention ONAP is not used for MANO. AFAIK, ONAP is not used, period. Yes, tools from the ONAP project are used, but that's not ONAP.
6) You can describe your methodology in the Synopsis, in a dedicated methodology section, or where ever you prefer, but I'm looking for something to help me connect the dots.
7) It's not clear to me what the "Repeat" section is. I understand what your intent, but it sounds like it's part of your methodology, not a separate section. Also, I would specify the context first, and the action second. 

After going through the edits, I'm thinking you might consider either a formal or informal review. I think it will help you collect the big picture feedback, which are much harder to encode in github comments. You could also show the material to someone not working on the project, and see what questions they come up with.

Again, this a good start, and it's very important to get all of these points down, as you have. Now you can think about the overall flow, so that when people read it, it's clear and things that are unclear are real gaps, not items that are present, but defined later in the chapter.

Thanks,
-Mark

Note to self: Link to new content: https://github.com/cntt-n/CNTT/blob/chapter08/doc/ref_model/chapters/chapter08.md

**Comment by mf4716** [comment]
Appreciate the feedback Mark S.
Will incorporate needed changes ASAP.

**Comment by mf4716** [comment]
@markshostak - please review for closure.  I have made updates, where applicable.

1.	All updates / changes are here until merged: https://github.com/cntt-n/CNTT/edit/ch08-cleanup/doc/ref_model/chapters/chapter08.md
2.	8.3.1 updated w/ new terms of verification, validation, compliance, scenario, harness, compatibility
a.	2b) 8.3 updated to explicitly state intention is to align the terms w/ CVC definitions 
b.	2c) No change made – to avoid repeating content and sections, already exists in 8.1 Introduction - Try to be more comprehensive in the synopsis.  Please edit / update section with improvements as appropriate. 
3.	No change made – 8.6.2, first paragraphs, provides a reference to the relevant security chapter.  Please edit / update section with improvements as appropriate.
4.	8.1 updated - declare the chapter's purpose, not the document's purpose
5.	8.1 not in scope updated – explicitly mention ONAP is not used, period
6.	No change made – 8.1 provides context and description to connect dots.  Please edit / update section with improvements as appropriate.
7.	8.1 updated – to clarify (and change) the use of "Repeat"

**Comment by mf4716** [comment]
@markshostak - no feedback/edits in the past 48 hours.  As such, removing self as assignee, and removing Botrange label, considering Ch 8 will be reworked post-Botrange regardless

**Comment by markshostak** [comment]
Mike, If you can speak to your objective, that's the most important thing. As discussed, probably best to discuss the objective with the group. I'd suggest you add it to the agenda for the Chapter 8 weekly mtg. We can discuss Issue assignment. Thx, -Mark

**Comment by mf4716** [comment]
@markshostak - added to Wednesday's weekly Ch 8 agenda.  Until that time, please feel free to edit/update documentation accordingly of work offline as a final PR will be done Wed, no later than Thurs this week.

**Comment by kedmison** [comment]
@mf4716 @markshostak  Is there anything we should do to conclude on this issue?

**Comment by mf4716** [comment]
@kedmison , I think this issue was addressed.  Very old/obsolete.  @markshostak any comment?  If none, then I recommend we move to cancel this Issue and move (or add) any relevant changes to one/more of the 6-7 current open RM Ch 8 issues.

**Comment by kedmison** [comment]
Thanks, @mf4716.  If I don't see any comments in the next 3 days, I'll close the issue.
