### ISSUE TITLE
[RA-1 Ch01 - Section 1.5]: Different Level of CNTT Artefacts Figure issues 

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#260]
The figure in section 1.5 of Chapter 1 in the OpenStack based Reference Architecture contains some bugs:
- The figure does not highliht the Reference Architecture part
- The figure contains redundant content in L2 and L3 sections
- The source of the figure is not available

**Comment by pgoyal01** [comment]
Changed Title of this issue to "Gen" and "different levels of CNTT Artefacts figure issue" as this figure is present in multiple artefacts (RM, RA, etc.) and changed labels accordingly
