### ISSUE TITLE
[TSC] conform with markdown rules (GSMA compatibility)

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#2603]
GSMA leverages pandoc to convert all CNTT chapters to docx.
Even if the results seem globally ok, a couple of rules would avoid a few manual processing steps.
It's worth mentioning that it obscures any git diff and then makes GSMA updates very difficult

A first set of rules we do apply as soon as possible:
- not to mix html and markdown which could be considered as fine just in GitHub but it's incorrect from a markdown pov (see anchors and images).
- to remove all manual title numberings (in markdown we do only leverage #, ## or ###)
- to remove all our TOCs (it should be rather part of pandoc processing)
- to avoid complex tables as much as possible (MD only accepts basic tabs)
- to modify images rather than applying CSS on it

**Comment by CsatariGergely** [comment]
* Images are embedded with html as markdown does not support image scaling. To overcome this we would need to manually scale all images. Are we ready to do that? 
* Anchors are used to mask the difference between the auto anchor generation of GitHub and ReadTheDocs. We use these in a very inconsistent way anyways, so I would be happy to see a generic solution. 
* If we remove the ToC-s we will need to generate them during the ReadTheDocs build. 
* On complex tabs you mean complex tables?

**Comment by CsatariGergely** [comment]
Pulling in @bfcohen and @scottsteinbrueck as acting doc ptl-s.

**Comment by collivier** [comment]
Yes my point is to scale the src image rather than leveraging html (somehow we don't have any other choice)
I could have a look if Sphinx is able to generate TOC (I would bet yet without any doubt :))

Yes complex tables :) fixing the issue messages...

**Comment by collivier** [comment]
I think we would have to remove all br, li, etc. used in cells too (see RA2) => to compact in a single line?.

**Comment by gkunz** [comment]
> 
> 
> Pulling in @bfcohen and @scottsteinbrueck as acting doc ptl-s.

Adding @ss8171 Scot Steele

**Comment by tomkivlin** [comment]
> I could have a look if Sphinx is able to generate TOC (I would bet yet without any doubt :))

Yes, it can but how it looks depends on the theme - we use Sphinx with a Material for Sphinx theme in VF and the ToC appears in a pane on the right rather than at the top of each page.

**Comment by collivier** [comment]
I would consider the theme issue as minor compared to the current numbering which is manual and even false in RC1.
And pandoc adds its own for each title.

**Comment by collivier** [comment]
+ funny issues before weekend

```
cedric@dev:~$ echo \![img]\(img1.jpg\) | pandoc -f markdown
<figure>
<img src="img1.jpg" alt="" /><figcaption>img</figcaption>
</figure>
cedric@dev:~$ echo \![img]\(img1.jpg\) | pandoc -f gfm
<p><img src="img1.jpg" alt="img" /></p>
cedric@dev:~$ 
```

**Comment by gkunz** [comment]
I have been looking into how to build the RTD documentation with the changes proposed by @collivier here and in particular in #2607. I wasn't able to determine a way of letting Sphinx generate a table of contents in markdown files. It works for rst files, though. We could use pandoc to convert from md to rst and generate a toc along the way, but pandoc is not supported by readthedocs [1].

So, in conclusion, we need to have an in-depth discussion on the requirements on our documentation, in this order:

i) What is the desired output format? Currently docx for GSMA and html for readthedocs.
ii) How can we create a consistent build process for all output formats minimizing the number of tools (and conversions)?
iii) concluding from i) and ii): What is the format we want to use for our documentation?

The latter question is particularly interesting. I know that CNTT started naturally with GFM (GitHub flavored Markdown), but this format is pretty weak. If we now want to create different outputs in a consistent and more automated manner (e.g. auto-generate TOCs), we should think about if GFM is still the right format.

[1] https://github.com/readthedocs/readthedocs.org/issues/4987

**Comment by tomkivlin** [comment]
Does the RTD SaaS allow different themes?  I think it is the themes that allow for that to happen as part of md --> html/css conversion. e.g. the Material for Sphinx theme which I use internally, I don't maintain a ToC on each page, but it appears in the rendered html pages. 

e.g. https://bashtage.github.io/sphinx-material/specimen.html you can see the local ToC as a right pane. That's how it looks for me, but our source files are GFM.  Happy to share conf.py snippets if it would help, but I suspect it's about which themes are available on the SaaS platform.

**Comment by gkunz** [comment]
Hi @tomkivlin. So, yes, the theme works nicely based on a quick check. Well, then forget my previous comment, let's go ahead with the cleanup as proposed by Cedric and instead make it a theming question (e.g., apply the Anuket color scheme to the Material theme).

**Comment by CsatariGergely** [comment]
Cool, if material for Sphinx solves the ToC and anchoring problem I also would propose to use that theme. I'm happy to work on the theme (however last time @gkunz was way more effective than myself). I would propose to update all the Anuket docs to use the same theme. 

On the cleanup work, is it okay if I start making pr-s for the removal of all the html anchors, ToC-s and heading numbers?

**Comment by tomkivlin** [comment]
> Cool, if material for Sphinx solves the ToC and anchoring problem I also would propose to use that theme. I'm happy to work on the theme (however last time @gkunz was way more effective than myself). I would propose to update all the Anuket docs to use the same theme.
> 
> On the cleanup work, is it okay if I start making pr-s for the removal of all the html anchors, ToC-s and heading numbers?

I'm more than happy to help with this, if needed.

**Comment by gkunz** [comment]
Hi, I can create a PR for everybody to test the Material Theme (using a local build) and to see what it looks like.

**Comment by gkunz** [comment]
I have created a dedicated issue (#2617) for evaluating the material theme. I have also published a preview build here:
https://gkunz.github.io/CNTT/index.html

**Comment by CsatariGergely** [comment]
Notes from the weekly meeting from 22.09.2021
- not to mix html and markdown which could be considered as fine just in GitHub but it's incorrect from a markdown pov (see anchors and images).
  - Bogo meters: they should be scaled and consistently used
  - Image captions can be used with consistent captions
  - Internal referencing
    - Header anchors should be checked with Pandoc
  - Advanced formatting inside tables (newllines, bulletlists, superscript)
    - Check how match we can remove 
- to remove all manual title numberings (in markdown we do only leverage #, ## or ###)
  - we just need to do it
- to remove all our TOCs (it should be rather part of pandoc processing)
  - Material theme for readthedocs supports this
  - We should doublecheck if @gkunz removed the title numbering in the [Material trial](ttps://gkunz.github.io/CNTT/index.html)
- to avoid complex tables as much as possible (MD only accepts basic tabs)
  - these are the tables written in raw html
  - We should try to simplify these tables
- to modify images rather than applying CSS on it

- md vs rst
  - rst is more difficult than markdown, but more powerful
  - It is supported by pandoc and readthedocs
  - It renders on GitHub 
To be continued next week.

**Comment by gkunz** [comment]
>     * to remove all our TOCs (it should be rather part of pandoc processing)
>       
>       * Material theme for readthedocs supports this
>       * We should doublecheck if @gkunz removed the title numbering in the Material trial

No, the preview build () still uses the manual header numbering since I was not able to enable header numbering the theme itself and without using rst's toctree directive.

**Comment by tomkivlin** [comment]
Do we care about the headers being numbered?  Is that a requirement from somewhere?

**Comment by pgoyal01** [comment]
@tomkivlin we use the numbering in references to those sections from other chapters, documents (e.g., RA-1 referring to RM) and even within the same chapter.

**Comment by gkunz** [comment]
rst's numref directive allows to reference numbered items. Doing this in the theme alone is hardly possible, I believe.

**Comment by gkunz** [comment]
I have updated the preview build as follows:
- conversion from md to rst using pandoc. No postprocessing.
- removed manual numbering of headers in RC1 and RC2 (NOT in the other chapters)
- applied material theme with local and global toc

Since I only touch the RC chapters, please review
- https://gkunz.github.io/CNTT/ref_cert/RC1/README.html
- https://gkunz.github.io/CNTT/ref_cert/RC2/README.html
