### ISSUE TITLE
[RA Chapter 2 - Section 2.3.1]: req.gen.cnt.01 and req.gen.cnt.03 are the same

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#261]
req.gen.cnt.01 and req.gen.cnt.03 are the same

**Comment by pgoyal01** [comment]
Gergely,

Please review the latest Pull Request (#246) – there are changes including deletion of the duplicate. Thanks.


Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by CsatariGergely** [comment]
Yes #246 fixes this issues.

**Comment by pgoyal01** [comment]
Closing this issue as per @CsatariGergely issue #261 is fixed by #246.
