### ISSUE TITLE
[TSC] Evaluate the Sphinx Material theme for read-the-docs

### ISSUE THREAD

**Issue by gkunz** [cntt-n/CNTT#2617]
The current Sphinx bootstrap theme does not use local TOCs. The Material theme does show both local and global TOCs. This issue is about testing the Material theme to determine if we should switch to this theme for the read-the-docs builds of the documentation.

**Comment by gkunz** [comment]
Preview build available here: https://gkunz.github.io/CNTT/index.html

**Comment by gkunz** [comment]
Current state:
- local and global tables of content enabled

Issues:
- header numbering
  - there is no configuration option in the theme to enable numbering of the headings
  - I can use CSS to create header numbers, but they are only valid for each local page, not globally for the entire document (i.e., each page counts from 1 to n)
  - Sphinx can do the numbering, but this seems to work only with rst files and the toctree directive. I wasn't able to apply this to markdown directly, i.e., without converting from md to rst first.
 
Proposals for solving the header numbering are welcome.

**Comment by CsatariGergely** [comment]
> 
> 
> Preview build available here: https://gkunz.github.io/CNTT/index.html

Looks good. Couple of observations, questions:
* Favicon is still OPNFV (and yes #2565 would need some additional reviews)
* Can we manually control the left side menu? I would only list the main documents there, like RM, RA1, RA2 and so on.

**Comment by CsatariGergely** [comment]
> 
> 
> Current state:
> 
>     * local and global tables of content enabled
> 
> 
> Issues:
> 
>     * header numbering
>       
>       * there is no configuration option in the theme to enable numbering of the headings
>       * I can use CSS to create header numbers, but they are only valid for each local page, not globally for the entire document (i.e., each page counts from 1 to n)
>       * Sphinx can do the numbering, but this seems to work only with rst files and the toctree directive. I wasn't able to apply this to markdown directly, i.e., without converting from md to rst first.
> 
> 
> Proposals for solving the header numbering are welcome.

I think we need consistent header numbering. We could try to build a Sphinx plugin to do it for us.

**Comment by gkunz** [comment]
>     * Can we manually control the left side menu? I would only list the main documents there, like RM, RA1, RA2 and so on.

Yes, we can set the depth of the global TOC to 1 (3 in the preview build) to only show the high-level documents. We should do that. I have updated the preview build.

**Comment by gkunz** [comment]
> > Proposals for solving the header numbering are welcome.
> 
> I think we need consistent header numbering. We could try to build a Sphinx plugin to do it for us.

I haven't developed such a plugin yet, so I cannot judge the complexity. Another option for consideration would be to switch to rst and use the native support of Sphinx.
