### ISSUE TITLE
[RM Chapter 8] Clarify if verification of VNF upgrades is in scope for test and certification

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#269]
Question was asked if CNTT verification includes validating the VNF’s ability to be upgraded.

**Comment by mf4716** [comment]
@markshostak 
- review for comment & closure (please)
- if further edits are needed, please do so directly in the Ch 8 material and update this issue accordingly

@mbustame - fyi

Section 8.1 Introduction - **Not in Scope** updated to read:

_Upgrades to VNFs, and the respective processes of verifying upgrade procedures and validating (testing) the success and compatibility of upgrades is **not** in scope._

**Comment by mbustame** [comment]
I agree that software upgrades should not be in scope other than to say the upgraded software should be verified in the same manner, and probably to the same extent, as the original software.

**Comment by mf4716** [comment]
Consensus reached.  CNTT verification does NOT include validating the VNF’s ability to be upgraded.  Closing.
