### ISSUE TITLE
[RM Ch08] Cleanup Chapter 8 content and remove duplicates

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#270]
@mf4716 there are still some cleanup needed for Chapter 8 to:

- remove duplicates (such as profile details, Terms, etc)
- remove references to SR-IOV
- move any OpenStack references to annex
- move any OPNFV/CVC/ONAP references to CNTT-RI area.
  - this need to relate to container when you read it.

**Comment by rabi-abdel** [comment]
@mf4716 @kagreenwell I am happy to have a stab at this and create a PR for this? let me know!

**Comment by mf4716** [comment]
@rabiabdel - yes, please do Rabi, this will be a great time saver and help.

**Comment by mf4716** [comment]
@rabiabdel - status?

**Comment by mf4716** [comment]
Confirmed w/ Rabi, not required for Botrange.  Removed the Botrange label.

**Comment by rabiabdel** [comment]
This can be removed as it has been addressed
