### ISSUE TITLE
[RM Ch4] 4.1.7 Acceleration/Offload API Requirements

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2720]
Section 4.1.7 Acceleration/Offload API Requirements states:

> For Accelerators and Offload functions with externally exposed **differences** in their capabilities or management functionality these **differences must be clear through** the management API either explicit for the differing functions or implicit through the use of a unique APIs.

(bolding mine)

Differences from what? Are their baselines capabilities defined?

@walterkozlowski Can we discuss this in the next RM meeting?

**Comment by TFredberg** [comment]
Not sure why you think this is a bug.
If there could be different versions of capabilities from an accelerator, that has to be visible  in some way. It is like a parameter or attribute for a Speed creating different versions of an interface of a NIC. Could maybe be 25GbE or 100GbE capabilities.

**Comment by pgoyal01** [comment]
@TFredberg The reason for stating as "bug" is to ask for clarifying what "differences" in capabilities that we are referring to.
