### ISSUE TITLE
[RM Chapter 8 Annex] Provide Clarification of Test Suites

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#277]
(From Pankaj Goyal - observations and comments)

•	SR-IOV may not be required in many flavor types
•	Numa – Each server should configure with two numa boundaries 
o	ODD CPU/Core number is assigned to numa 1                    [May I suggest: ODD numbered CPU/Cores are assigned to numa 1 ]
o	EVEN CPU/Core number is assigned to numa 0                   [May I suggest: EVEN numbered CPU/Cores are assigned to numa 0 ]
•	Hugepages may not be enabled for all flavors
•	Why is CPU Pinning, flavors etc tied to VNF interoperability validations – they can be independently validated
•	I think everything under “VNF Interoperability – validations” can be performed independently of a VNF. I found the first bullet confusing as all of the pre-requisite activities start on the second bullet.
•	I see the creation of the host-aggregates but not assigning of hosts to these host-aggregates.
•	Same for AZ’s – since hosts not assigned to AZs, how can you verify?
•	In some of the creation activities are you going to verify with admin and user roles?
•	What is an SR-IOV network?

**Comment by mf4716** [comment]
All items added/inserted into the Annex with exception of following:

"Same for AZ’s – since hosts not assigned to AZs, how can you verify?"

Collecting more info.  MK assigned and will reply.

**Comment by mk721p** [comment]
Host is assigned while you are creating a Host Aggregate. Please let me know if you still have any question.
