### ISSUE TITLE
[RM Appendix A] In A.3 add RM 7.5

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#2772]
In Section A.3, lines 63 - 65, add a reference to RM Section "[7.5 Workload Security - Vendor Responsibility](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md#75-workload-security---vendor-responsibility)".

**Comment by CsatariGergely** [comment]
I will handle this after the merger of #2746
