### ISSUE TITLE
[RA1 Umbrella] More guidance on automation

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#2776]
From Telstra's GSMA RA1 review (Dec. 2021), give more guidance on deployment automation, align with RM development on automation.

Converted to Umbrella Issue:
1. Lifecycle Automation: may need to break into smaller chunks. Include, align with RM Automation Issue #2238
2. Deployment Automation: distribute between RA and RI

**Comment by pgoyal01** [comment]
Umbrella Issues:

1. Lifecycle Automation: may need to break into smaller chunks
2. Deployment Automation: distribute between RA and RI

**Comment by karinesevilla** [comment]
PR#2971 merged
