### ISSUE TITLE
[RM Chapter 8 - section 8.6.2] VNF categories duplicated

### ISSUE THREAD

**Issue by xavier-grall** [cntt-n/CNTT#279]
The text  & figure about "VNF categories" is redundant with chapter 2, and even it is a copy that may become divergent if some changes occur.
So, it should be removed, or replaced by a reference to chapter 2.

**Comment by xavier-grall** [comment]
@mf4716 
the figure and the text until the end of the section should also be removed (there is quite the same in chapter 2)

**Comment by mf4716** [comment]
@kagreenwell - kyle, please address

**Comment by kagreenwell** [comment]
removed the vnf families and reference chapter 2.2. I left the image in because I believe it is useful to reinforce the three performance profiles within the testing chapter. We will make note that we need to ensure we are in alignment with chapter 2 changes over time.

**Comment by xavier-grall** [comment]
@kagreenwell @rabi-abdel 
Indeed, the image is already different from chapter 2, and it will probably be still more different (if my latest proposal is accepted: xavier-grall@fd3ed20).
Moreover, this chap8 image also includes elements from chapter 4 and/or 5 (throughput, cpu pinning...), so I'm afraid that it will not be possible to keep it in alignment with all those chapters over time...
I really think it should be removed (and I guess chapter 8 should not deal with such details).

**Comment by kagreenwell** [comment]
updated 8.6.2 figure to reference figure from ch2 per discussion on today's chapter call.
