### ISSUE TITLE
[RA2 Ch4] Lost Host OS Requirements

### ISSUE THREAD

**Issue by yangxu-hw** [cntt-n/CNTT#2798]
There was a clause of host OS requirements in the previous release of RA2 (e.g., https://github.com/cntt-n/CNTT/blob/Snezka/doc/ref_arch/kubernetes/chapters/chapter04.md) capturing the requirements necessary for CNF and host OS interoperability.
The clause is removed in the following releases (perhaps due to re-structing), and there are no similar requirements in the current Ch4 now.
We think the original requirements (e.g., minimum version of linux kernel) are important for CNFs to run across different container infrastructure, and therefore should be added back into the RA2 spec.

**Comment by rgstori** [comment]
- chapter 2: check that the drivers for host OS are present - what are the requirements from workloads and k8s towards the host OS?
- chapter 4: check/restore the specs for the host OS that satisfy these requirements
