### ISSUE TITLE
[RM Ch08] Multi-cloud E2E regulatory and security aspects

### ISSUE THREAD

**Issue by walterkozlowski** [cntt-n/CNTT#2804]
Hybrid multi-cloud environment creates a range of new issues related to E2E security and also to regulatory compliance.  While those aspects are to large extend jurisdiction specific, Reference Model needs to provide some guidance.

**Comment by walterkozlowski** [comment]
No gaps found in Moselle; after review of Sec 8.2.8 (Aspects of Multi-Cloud Security), and  Requirements in Sec 7, (references in RAs are from Chapter 7).  Re-review in next releases.

**Comment by wmk-admin** [comment]
Closed by PR#3246
