### ISSUE TITLE
[RM Chapter 8 - section 8.7.1] Performance profiles duplicated

### ISSUE THREAD

**Issue by xavier-grall** [cntt-n/CNTT#281]
The table about performance profiles is redundant with chapters 2 (for NFVI profiles needs/requirements) and 4 (for metrics).
So, that table should be removed or replaced by references to chapter 2 & 4.

**Comment by kagreenwell** [comment]
Tables have been removed for compute flavors and performance profiles. They have been replaced with references to chapter 2 & 4 where these items are defined.
