### ISSUE TITLE
[RM Chapter 8 Annex] Test suite selection is inappropriate (too generic and reinvent the wheel)

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#283]
I don’t think that listing single create operations which are common to all OpenStack deployment (tenant, user, vm, images, etc…) is the best approach.

It will grow exponentially depending on:
- the service list
- all possible operations (create/update/delete) and all related attributes available
- negative testing

Tempest and its plugins as integrated in Functest offer more that ~2000 functional tests to cover that tree. OPNFV Functest creates hundreds of VMs in many different ways. 

I also consider that iteration and timeout data are missing.
Thanks to all Functest runs in OPNFV or in internal labs, we know how rally_full is crucial as it iterates multiple times the same user operations (e.g. live migration).

Pragmatically, I would suggest to simple list the upstream gate coverage and not to reinvent the wheel. I would encourage the reuse of functest-smoke (functional test mostly based on tempest), functest-benchmarking (rally_full and rally_jobs) and possibly the other tiers.

We may upstream single tests or add new tempest plugins if needed.

Please find bellow few Functest artifacts:
http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-iruya-tempest_full-run-259/results/tempest_full/tempest-report.html
http://artifacts.opnfv.org/functest/functest-opnfv-functest-benchmarking-iruya-rally_full-run-169/results/rally_full/rally_full.html

**Comment by mf4716** [comment]
@collivier @xavier-grall @mk721p 

Xavier, Cedric,

We can call out a pre-requisite to run FuncTest suites as part of the validations.  Agree that the Annex is intended to be organic, and grow over time, so in our same FuncTest mention, we can be abstract and say "refer to FuncTest details for complete test case list, including Negative Testing".

Will assign to Murtuza Khan (MK) to make these changes.

Any other changes, we'll ask for a PR and your assistance.

**Comment by mf4716** [comment]
@collivier - review for closure

Annex updated.  Section 8.2 Generic includes the following now:

_The following test projects, and their respective test cases, will be executed with each RI implementation. More targeted, or specific test cases, are listed below which may be a subset of test cases run within these test suites listed._

**_FuncTest_**

_FuncTest test suites will be run as part of the validations, and as a pre-requisite with approximately 2000+ functional test cases leveraging Tempest plugins. At a minimum, FuncTest executions will include reuse of functest-smoke (functional tests), functional-benchmarking (rally_full and rally_jobs).

Additional Resources for FuncTest details:_

_

- Project Description: https://wiki.opnfv.org/display/functest/Opnfv+Functional+Testing#OpnfvFunctionalTesting-Testcases
- User Guide: https://opnfv-functest.readthedocs.io/en/stable-hunter/testing/user/userguide/index.html
- Overview of test suites: https://opnfv-functest.readthedocs.io/en/stable-hunter/testing/user/userguide/test_overview.html.
- 
**Example, or Reference, Functest Status Reporting Artifacts:**

_

_

- Rally Verification (Status): http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-iruya-tempest_full-run-259/results/tempest_full/tempest-report.html
- Rally Tasks (Status): http://artifacts.opnfv.org/functest/functest-opnfv-functest-benchmarking-iruya-rally_full-run-169/results/rally_full/rally_full.html

_

**Comment by mf4716** [comment]
Closed.  No further comments/edits received.
