### ISSUE TITLE
[RM Chapter 8]: Typos

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#287]
There are some small typos in Chapter 8 what should be corrected: 

- "reference architecture which **satisifes** infrastructure"

- "OPNFV Releases including the successful adoption and implementaiton of Installer, Feature, and Test Projects to perform release level verification, compliance, and certification." - The whole sentence is unclear. 

- "**Dovtail**"

**Comment by mf4716** [comment]
@CsatariGergely 

All items addressed.  Updated.  Closed.
