### ISSUE TITLE
[RM et al.] Fix figure captions

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#2875]
Here is a trivial example including an image.
For its part, numfig adds the numbering  (Fig. 15 VNF_cookbook in the following example)

```
.. figure:: ../figures/rc1_cookbook_vnf.png
   :alt: VNF_cookbook

   VNF_cookbook
```
They are many places across the streams where captions are falsy (+by hand)
Maybe it's due to the fact that the conversion from markdown was incorrect
_(I suggested to pick the flavor markdown and not the github one due to this particular issue)._

To illustrate the point, see RM chapter 7.
**Figure 7-1**: Reference Model Security Domains is even not considered as part of the image.

```
.. image:: ../figures/ch7_security_posture.png
   :alt: "Figure 7-1: Reference Model Security Domains"

**Figure 7-1**: Reference Model Security Domains
```
Here is the fix

 ```
.. image:: ../figures/ch7_security_posture.png
   :alt: "Reference Model Security Domains"

   Reference Model Security Domains
```

**Comment by pgoyal01** [comment]
I think this is an umbrella issue. Let us create separate PRs for each of RM, RA1, and RA2, and maybe even individual chapters. I will work with @karinesevilla to divide up RA1 changes.
