### ISSUE TITLE
[RC2 Chxx] Align RC2 with Lakelse & Mosell RA2

### ISSUE THREAD

**Issue by steelescotr** [cntt-n/CNTT#2884]

**Comment by collivier** [comment]
Yes the container list has been updated for a wile and the test case list is continuously synced (see last TSC call)
https://github.com/cntt-n/CNTT/commit/ff6979e1cff83380ed76dc53c1a9a47ec7f3d43c

**Comment by collivier** [comment]
Done Jan 6 ... byw..
