### ISSUE TITLE
[RM Chapter 8]: Testing should be OPNFV installer agnostic

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#289]
Chapter 8.5.2 should state, that CNTT testing in agnostic to the used installer and does not prescribe any of the OPNFV installers.

**Comment by kagreenwell** [comment]
Updated section 8.5.2 to read  "Installer oriented release. CNTT does not recommended any specific installer. An agnostic approach is taken that allows for an implementation to determine their own installer."
