### ISSUE TITLE
[All] Build is not working from behind a proxy

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#2890]
Pulling of intersphinx mapping is not working from behind a proxy as 
`passenv = http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY` 
is not given in the tox.ini-s

**Comment by CsatariGergely** [comment]
Would the addition of 
`passenv = http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY` 
to tox.ini hurt other users? This really blocks me from building the docs in our corporate network.

**Comment by gkunz** [comment]
Seems to work for me in a non-proxy environment.

**Comment by collivier** [comment]
yes it hurts if useless. CNTT mustn't take into account very specific company/user setup.
OpenStack has deeply leveraged on google docs which has been blocked by a few corporate proxies..
And you can rather patch it locally and route your cell phone ;)

Let me verify this point please.

**Comment by collivier** [comment]
Please see https://github.com/tox-dev/tox/pull/1500 merged on 01/16/2020

**Comment by collivier** [comment]
This issue can be safely closed.

**Comment by collivier** [comment]
verified in Katacoda https://www.katacoda.com/ollivier/courses/xtestingci/proxy
- install tox
- change base python to 3.8

Even if if direct traffic would be allowed, I well see all PYPI downloads in proxy logs

```
1648452224.219     76 172.17.0.41 TCP_TUNNEL/200 4490 CONNECT pypi.python.org:443 admin HIER_DIRECT/151.101.112.223 -
1648452225.466     74 172.17.0.41 TCP_TUNNEL/200 4493 CONNECT pypi.python.org:443 admin HIER_DIRECT/151.101.112.223 -
1648452225.587     74 172.17.0.41 TCP_TUNNEL/200 4483 CONNECT pypi.python.org:443 admin HIER_DIRECT/151.101.112.223 -
1648452226.378     73 172.17.0.41 TCP_TUNNEL/200 4485 CONNECT pypi.python.org:443 admin HIER_DIRECT/151.101.112.223 -
1648452230.666   6441 172.17.0.41 TCP_TUNNEL/200 148024 CONNECT pypi.org:443 admin HIER_DIRECT/151.101.64.223 -
1648452230.668   5745 172.17.0.41 TCP_TUNNEL/200 3314192 CONNECT files.pythonhosted.org:443 admin HIER_DIRECT/151.101.1.63 -
1648452237.662   5521 172.17.0.41 TCP_TUNNEL/200 11261 CONNECT opendev.org:443 admin HIER_DIRECT/38.108.68.124 -
1648452291.208   1048 172.17.0.41 TCP_TUNNEL/200 4219 CONNECT pypi.org:443 admin HIER_DIRECT/151.101.64.223 -
1648452291.212  56209 172.17.0.41 TCP_TUNNEL/200 536902 CONNECT pypi.org:443 admin HIER_DIRECT/151.101.64.223 -
1648452291.214  55742 172.17.0.41 TCP_TUNNEL/200 24426336 CONNECT files.pythonhosted.org:443 admin HIER_DIRECT/151.101.1.63 -
```

**Comment by CsatariGergely** [comment]
Interesting I'm on python 3.8.10 and tox 3.13.2... but okey, I can keep copying this line for myself into the `tox.ini`-s.
I could not really get the comment about Google Docs and OpenStack. @collivier can you please clarify?

**Comment by collivier** [comment]
I know a few cases where proxies block Google docs but it doesn't forbid OpenStack to deeply leverage it.
python 3.9 is more precise that python3. In our case it can be considered as overkilled (mainly sphinx deps here) but I could detail side effects if there are conditional abstract dependencies (see previous fixes in ONAP gates)

**Comment by CsatariGergely** [comment]
Hi, I'm using Python 3.8.10 and the problem still persist in my environment. 

I still do not get the OpenStack reference, as far as I know OpenStack community tries not to use Google Docs as it is not accessible for many of the community members. At least in ECG meetings we rely on etherpad and wiki instead of Google Docs. 

I see the point that using proxies can slow down the pip package installation, but `passenv = http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY` does not mandate the usage of a proxy, only if it is required anyways by the environment.
