### ISSUE TITLE
[RM Ch9] Should we flesh out the specs for infrastructure monitoring?

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2896]
In chapter 9 there's a high level description of what assurance is, what kind of areas to monitor, etc.

Barometer uses ETSI TST 008 as source for the metrics to monitor: https://www.etsi.org/deliver/etsi_gs/NFV-TST/001_099/008/03.05.01_60/gs_NFV-TST008v030501p.pdf 

This document seems to be mostly implementation agnostic - can be applied to both IaaS and CaaS.

Should we summarise the list of metrics or groups/families of metrics that should be monitored? 

The same goes for the monitoring/oss software - shall we prescribe how it's built or not?

**Comment by rgstori** [comment]
this is in order to have something to trace ra2 monitoring requirements from (ref. #2788)

**Comment by walterkozlowski** [comment]
Closed by PR#2983 approved and merged
