### ISSUE TITLE
[RM Ch08 - Annex]: Testing should be technology agnostic

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#290]
- Current description of RM Chapter 8 Annex refers to OpenStack and Kubernetes specific testing. These should not be visible in Reference Architecture level, but they should be moved to the Refernce Models. 

- Current description of RM Chapter 8 Annex refers to NUMA testing, however NUMA is not required for all profiles. The test cases and their expected result should be differentiated based on the supported profile.

**Comment by CsatariGergely** [comment]
It is okay to be technology specific, but I'm not sure if the RM is the right place for this.

**Comment by rabi-abdel** [comment]
Let us discuss this further in the technical steering meeting.

**Comment by CsatariGergely** [comment]
@rabi-abdel did we discussed this? And if yes what was the result?

**Comment by CsatariGergely** [comment]
RM Ch8 annex was deleted / moved to RC-s in the meanwhile, so I think this issue can be closed.
