### ISSUE TITLE
[RA2 Ch4] Add requirements based on the analysis of CNF Testsuite tests

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2909]
Kubernetes workloads - CNF test suite "crashes" actually means that either the liveness or readiness probe fails - this should be made explicit and the presence of probes should be made mandatory.

**Comment by CsatariGergely** [comment]
I would generalize this to "Add workload requirements based on the analyzis of CNF Testsuite tests". What do you think?

**Comment by pgoyal01** [comment]
> I would generalize this to "Add workload requirements based on the analyzis of CNF Testsuite tests". What do you think?

@CsatariGergely it is not just workloads

**Comment by CsatariGergely** [comment]
> > I would generalize this to "Add workload requirements based on the analyzis of CNF Testsuite tests". What do you think?
> 
> @CsatariGergely it is not just workloads

The primary aim of our activity to review the CNT Testsuite tests is to formulate a basic set of workload requirements. I would scope this activity to workloads in this release.

**Comment by rgstori** [comment]
ok, so far we have:
- Probes
- image sizes and boot times
- service types
