### ISSUE TITLE
[RM Ch4] Bad link in Ch4 

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#2924]
The two :ref:`chapters/chapter02:profiles, profile extensions & flavours` are: in line 486 should be changed to The two :ref:`ref_model/chapters/chapter02:profiles, profile extensions & flavours` are:

**Comment by wmk-admin** [comment]
@CsatariGergely, Fixed and tested

**Comment by wmk-admin** [comment]
Fixed this bug
