### ISSUE TITLE
[RM - Appendix A] Adding VNF Design Guidelines content

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#294]
Petar of intel has an action item to provide initial content.
https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/appendix-a.md

**Comment by pgoyal01** [comment]
@rabi-abdel As you know, ONAP has published VNF Requirements including VNF design. ONAP has to orchestrate and manage the VNFs. May I suggest that if we idnetify any gaps in their requirements That we work with ONAP to avoid inconsistencies.

Ref: https://onap.readthedocs.io/en/latest/submodules/vnfrqts/requirements.git/docs/index.html Please see Chapter 4 for VNF Design.

**Comment by petorre** [comment]
> 
> 
> @rabi-abdel As you know, ONAP has published VNF Requirements including VNF design. ONAP has to orchestrate and manage the VNFs. May I suggest that if we idnetify any gaps in their requirements That we work with ONAP to avoid inconsistencies.
> 
> Ref: https://onap.readthedocs.io/en/latest/submodules/vnfrqts/requirements.git/docs/index.html Please see Chapter 4 for VNF Design.

Yes, fully agree.
