### ISSUE TITLE
[RM Chapter 5] NUMA description, tab 5-13

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#296]
As agreed during Chapter 5 meeting (09/11), remove reference to BIOS on table 5-13 related to NUMA description
New proposal: "NUMA supported and enabled"

**Comment by rabiabdel** [comment]
PR was created: https://github.com/cntt-n/CNTT/pull/310

**Comment by karinesevilla** [comment]
Approved, modifications merged 09/17
