### ISSUE TITLE
[RA2 Ch4] continue conversion of CNCF CNF WG test cases into requirements 

### ISSUE THREAD

**Issue by rgstori** [cntt-n/CNTT#2975]
here: [https://wiki.anuket.io/display/HOME/2022/03/01/Analyzis+of+CNCF+CNF+Testsuite+tests+for+RA2](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.anuket.io%2Fdisplay%2FHOME%2F2022%2F03%2F01%2FAnalyzis%2Bof%2BCNCF%2BCNF%2BTestsuite%2Btests%2Bfor%2BRA2&data=04%7C01%7Crgs%40vodafone.com%7C7df1c6800183499a9c5a08d9fd2383aa%7C68283f3b84874c86adb3a5228f18b893%7C0%7C0%7C637819151392432529%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=F9bH57EOotcDfoAzyhtwv7G8OhSFU6q1UNyxrHhOyoQ%3D&reserved=0)
opened new issues (see link)
met on tue 29th
there is a rationales file - might explain some of the things we had questions on - [https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md](https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md#to-check-if-the-cnf-has-multiple-process-types-within-one-container-single_process_type)
ra2 to go through rationale file and update findings
got to Jaeger row

**Comment by rgstori** [comment]
@CsatariGergely shall I keep this one open for the O release or close?

**Comment by CsatariGergely** [comment]
I think we can close this.
