### ISSUE TITLE
[General] Flavor or Flavour? en_US or en_GB?

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#300]
What's the locale selected? en_US or en_GB? At least OpenStack selects flavor.
https://docs.openstack.org/nova/latest/user/flavors.html

$ grep -r flavour |wc -l
30
$ grep -r flavor |wc -l
9

**Comment by collivier** [comment]
behavior or behaviour?

**Comment by markshostak** [comment]
CNTT has standardized on en_GB. If you can provide your stdout, we can address.
Also, you may catch more fish with -i :-)

**Comment by markshostak** [comment]
Extra credit if you save us all the trouble and use sed s/...

**Comment by collivier** [comment]
Yes. Be free to send me the full list. I can easily fix them in a few sed calls. .
It's worth mentioning that flavour is quite tricky when listing OpenStack resources.

**Comment by iangardner22** [comment]
Personally I believe we should stick with "flavor" or any other US spelling when it is the default used in the commands or community.

**Comment by rabi-abdel** [comment]
@collivier please feel free to introduce a PR to resolve it. I will assign to you :)

**Comment by collivier** [comment]
mostly done
