### ISSUE TITLE
[RM Ch08] Use Markdown instead of HTML

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#301]
See 8.2.2, 8.3.1, 8.5.1, 8.5.2 etc.
https://raw.githubusercontent.com/cntt-n/CNTT/master/doc/ref_model/chapters/chapter08.md

**Comment by mf4716** [comment]
@collivier - please make the recommended edits/updates

**Comment by mf4716** [comment]
@collivier - at your convenience, please provide status.  Thanks
