### ISSUE TITLE
[References] Fix duplicated tables: Security Related References

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#3028]

**Comment by collivier** [comment]
@pgoyal01 @walterkozlowski @karinesevilla do we merge the 2 tables?

**Comment by pgoyal01** [comment]
@collivier which 2 tables in which chapters?

**Comment by pgoyal01** [comment]
@collivier GSMA expects the references to be from within the document. If we merge the references then GSMA documents will end up with references that are not within the document and would have to be manually edited.

 @walterkozlowski @karinesevilla please comment. Thanks

**Comment by pgoyal01** [comment]
@collivier Instead of replicating them can we "include" the "common/references.rst"; maybe also abbreviations, etc.

**Comment by karinesevilla** [comment]
@collivier @pgoyal01 we must keep the references tables per workstream to able to add the right references per GSMA doc.
For the initial question about the 2 sections named Security Related References, the 2 tables must be merged in one.

**Comment by collivier** [comment]
done
