### ISSUE TITLE
[General] Fix markdown errors (currently 1272 errors)

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#303]
[markdownlint](https://github.com/jorisroovers/pymarkdownlint) currently highlights 1272 markdown issues in CNTT tree.

- R1 Line exceeds max length
- R2 Line has trailing whitespace
- R3 Line contains hard tab characters

```
$ markdownlint CNTT |wc -l
1272
```

**Comment by rabi-abdel** [comment]
@collivier will it be so easy to fix them? If so, can you do that and submit a PR for the fix? I can automatically approve and merge since it is a fix and not content addition.

**Comment by collivier** [comment]
They have to be fixed for lots of technical reasons (e.g. git history).
I already published 2 commits in the PR (I do admit that I prefer Gerrit regarding the review dependencies) fixing 2 error types out of 3. Fixing the last one is quite boring but very easy.

The usual process (see [OPNFV Functest](http://testresults.opnfv.org/functest/gates/)) is first to fix them and then to enforce the automatic verification before any human review. 
I could help regarding that when all errors are fixed.

The main problem is that commits modify all chapters. I think you can't validate them by yourself even as main editor
