### ISSUE TITLE
[RM Ch04] Disaggregate the Storage Extensions Matrix

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#308]
This Issue is a child of Issue #187, specifically to address sub-issue JB-26.
**From Issue #187:**
JB-26: Storage extension can be separate from the profiles
JB-26: Currently we utilize a matrix of [performance profile x size] to specify the Storage Extension. This is sufficient for the current dimensions, but as storage options grow, and to your point, we will need to move to a discrete approach. **ACTION**: Open Futurework issue to disaggregate size and performance.

**Comment by pgoyal01** [comment]
@ASawwaf @walterkozlowski [4.2.3 Storage Extensions](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#423-storage-extensions) already defines storage extensions independent of the profiles/flavors. If nothing more is required, suggest we close.

**Comment by walterkozlowski** [comment]
I agree with @pgoyal01 and will close this issue.  We can create new issues/PRs if needed

**Comment by walterkozlowski** [comment]
Closed as already addressed in RM  Sec 4.2.3
