### ISSUE TITLE
[RM Chap8] Hybrid-Multi-cloud - Multi-Cloud Interactions Model - Catalog Management

### ISSUE THREAD

**Issue by jbhartley** [cntt-n/CNTT#3080]
Need to add "Catalog Management" as key interactions, as this is key to exposing the Multi-Cloud to the consumer.

Draft updates provided in LFN Porto Presentation: https://wiki.anuket.io/display/HOME/LFN+DDT+Porto+June+2022?preview=/27231333/27231436/LFN-Porto-multi-cloud-interaction-model-2022.pptx

**Comment by walterkozlowski** [comment]
Closed by PR#3261
