### ISSUE TITLE
[RM]: RM text is sometimes unclear

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#3096]

**Comment by walterkozlowski** [comment]
@CsatariGergely, the contributors cannot use this issue as it is too general, and hence useless.  I suggest closing it and creating concrete issues that can be actioned.  

Btw: RM has been published several times, also went through 2 editions in GSMA, where was a subject to review by many members of GSMA, and no one has raised such an issue.  I would suggest the author of the issue to attend RM meetings and raised concerns there so the RM contributors can explain the contents in case of specific difficulties.

**Comment by CsatariGergely** [comment]
Sorry, I've created this issue for a proofreading activity for RM. I'm working with technical writers on collecting the issues and we will create pr-s for them. I agree that this issue is not useful at all in its current form, so I will close it for now.
