### ISSUE TITLE
Image: ch05_ref_nfvi_sw_profiles_v1.PNG (Barak)

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#31]
Karine to provide update/PR to chap 4; input will need to be propagated to additional chapters for Storage-Intensive.
Diagram includes SDN-C; **Need to remove from diagram**

**Comment by karinesevilla** [comment]
See PR #37, new image without SDN Controller and monitoring

**Comment by rabiabdel** [comment]
Close since addressed.
