### ISSUE TITLE
[RA1 Ch01] Language Issues

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#3149]
Line 16: Current tet: "This means that the operators have existing staff with the right skill sets to support a Cloud Infrastructure (or Network Function Virtualisation Infrastructure, NFVI "
  - it is not necessary that the operators have "existing staff"

Would it be better to state:
"This means that resources with the right skill sets to support a Cloud Infrastructure (or Network Function Virtualisation Infrastructure, NFVI) are available."

++++++++++++++++++++++
Line 30: Current: "The OpenStack-based Reference Architecture will host NFV workloads, ..."
  - we now use "Reference Architecture for OpenStack based Cloud Infrastructure"
  - the architecture will not host
Would it be better to state:
"Thie Reference Architecture specifies OpenStack based cloud infrastructure for hosting NFV workloads (a.k.a. Network Functions)."

++++++++++++++++++++++
Line 64: Current text:: "**Network functions**: Network functions is a broad category but encompasses workloads that support the exchange of information (data, voice, multi-media) over a system's network."
  - why "but encompasses"

Would it be better to state:
"**Network functions**: are software components that support the exchange of information (data, voice, multi-media) over a system's network."

**Comment by karinesevilla** [comment]
@pgoyal01 Great proposal, I will include it
