### ISSUE TITLE
[RA1 Ch03] Move APIs to Ch5 and add reference (link) in ch3.

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#319]

**Comment by pgoyal01** [comment]
@rabi-abdel The APIs had been consolidated and moved to RA-1 CH 05 prior to Antwerp and there is a reference to Chapter 5 in Chapter 4 ("The APIs for these OpenStack services are listed in Chapter 5: Inetrafces and APIs."). 

Can this issue be closed?

**Comment by pgoyal01** [comment]
PR merged.
