### ISSUE TITLE
[pcac]: Fix warnings in the compilation of the Anuket landing page

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#3199]
Implemented in here: https://gerrit.opnfv.org/gerrit/c/opnfvdocs/+/73453/1

**Comment by gkunz** [comment]
Actually, the correct link is: https://gerrit.opnfv.org/gerrit/c/opnfvdocs/+/73449

**Comment by gkunz** [comment]
Changeset has been merged in Gerrit
