### ISSUE TITLE
Rabi Chap 4 PR

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#32]
Various comments recorded against PR need to be resolved.

**Comment by rabiabdel** [comment]
new PR was created to reflect this issue: https://github.com/cntt-n/CNTT/pull/38

**Comment by rabiabdel** [comment]
Resolved, New PR created for this: https://github.com/cntt-n/CNTT/pull/38

**Comment by rabiabdel** [comment]
Close Now
