### ISSUE TITLE
[RM Chap8] Multi-Cloud Interactions Model - Catalog Management - Provide/Consumer Clarifiation

### ISSUE THREAD

**Issue by jbhartley** [cntt-n/CNTT#3218]
@karinesevilla 

"The management of the catalog of services should be clarified.
The Cloud Provider exposes the catalog of services the CSP can consume but the CSP cannot manage the Cloud Provider catalog of services.
The CSP manages the services offered to the end user using the Cloud Provider services.
The Cloud provider and the CSP are responsible of the management of their own catalogues of services, it is the reason why I think 'manage catalog' in the interaction model is confusing."

Raising as issue to address with content update.

**Comment by joaoarodrigues** [comment]
Please be aware that on a MultiCLoud architecture there are different approaches to manage the service catalogue

- Differentiate between Service Inventory and Service Catalogue
- Service Catalogue Federation (one can find service catalogues in each one of the Cloud Infrastructure) - can it be handled with a service catalogue policy
