### ISSUE TITLE
[RA1 Ch03 ] Create initial content representing Levels L2.

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#323]
Currently there is no clear split between Ch03 and Ch04. we might need to stick to L2 and L3 definitions and follow them.

**Comment by pgoyal01** [comment]
Previous L2 and L3 divisions had overlaps and, hence, at least I found it difficult to present a coherent view. It also didn't have topics to cover certain relationships between components and design choices.

**Comment by pgoyal01** [comment]
[RA-1 CH03] Initial Content PR #628 merged
