### ISSUE TITLE
[RM Chapter 8] Aspects for Empirical Validation of Storage Infra

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#338]
This is a descendant of Issue #176, and addresses the following feedback items from the Paris Etherpad regarding some of the needed aspects of the empirical testing:

- JB-22: Validate IOPS for Storage Extensions
- JB-23: Read/Write ratio validations also needed

**Comment by mf4716** [comment]
@markshostak - review section 8.8.1 of the [ch 8 clean up branch](https://github.com/cntt-n/CNTT/tree-save/ch08-cleanup/doc/ref_model/chapters/chapter08.md) for details inserted into the chapter 8 to address this issue.  Please comment, or confirm to close.

**Comment by markshostak** [comment]
@mf4716 What is the PR # that resolves this issue?
Hi Mike, The 2 test areas mentioned in this Issue are now captured in 8.8.1, so I'm ok with closing it. We should think about the section this test area, and others like it, are captured in. Generally, I'm not sure I'd look for a list of test areas (aka scenarios?) in the test results section. I would first look for a summary of tests, but the important thing is the high level test areas relevant to this issue are now captured in the chapter. I expect the chapter organization will be refined w/ feedback from Antwerp. Nice job! -Mark

**Comment by mf4716** [comment]
@markshostak - PR with the change is https://github.com/cntt-n/CNTT/pull/299.  Thanks.
