### ISSUE TITLE
[RA-1 Ch04]: Unhandled comments of pr #313

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#339]
Pr #313 have some unhanded comments: 

- req.inf.ntw.10 should be reformulated to contain infrastructure requirements and not workload requirements.
- Figure_4_3_Select_host_instance_launch.png: I think this figure is irrelevant here. This chapter should describe what is running on a compute host and not how it is selected.
- 4.5 Cloud Workload Services: I think this description is irrelevant here. This chapter should describe what runs on an compute host and not how it is selected.
- 4.4.1. Hardware Considerations: This is too generic. This chapter should describe if there are different hardware profiles allowed or there is a single HW profile supported for this RA.

**Comment by rabiabdel** [comment]
Agree with all comments below. will get them addressed prior this Friday. (when we will release this out).

**Comment by pgoyal01** [comment]
@CsatariGergely 

- req.inf.ntw.10 we cannot make change to the requirement except if it is changed in Chapter 02. We can delete from Chapter 04 if there is agreement.
- 4.5 is no longer "Cloud Workload Services."

- 4.4.1. the intent is not to be prescriptive about what the operators choose w.r.t. supporting multiple profiles or a common profile; discussion on profiles is in RM Chapter 5.

**Comment by CsatariGergely** [comment]
- req.inf.ntw.10: No, let's not delete it from Chapter 4, but I have two problems now :)
  
  - My original comment applies to the requirements in Chapter 2
  - I think we should mention in Chapter 4.5.1, that these are copied from Chapter 2.3.2

- 4.5 is no longer Cloud Workload Services.", but my original comment about it still applies to the current "4.4.1 Compute Nodes Specifications"
- 4.4.1 I think this is valid only to the RM. The whole point of the RA is to specify the options instad of leaving them open

**Comment by pgoyal01** [comment]
Can we classify this as a RA-1 Ch02 issue. At this time the requirements traceability has been removed form RA-1 Chapters 3 and 4; will be completed later once content is stabilised.
