### ISSUE TITLE
[RM Ch01] Use Cases needs cleaning up

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#343]
I think there is some cleanup to use cases section. (currently doesn't flow). The content has been commented out and needs re-working.

**Comment by bfcohen** [comment]
That was the piece that I knew needed work.  Next release.

**Comment by markshostak** [comment]
@bfcohen Hi Beth, Friendly reminder. Thanks, -Mark

**Comment by ASawwaf** [comment]
@rabi-abdel , there is no use cases in RM CH01 , so what is required here 

if you mean the use cases section  5 , it is under developing for edge use cases 

so please to close this issue

**Comment by ASawwaf** [comment]
@rabiabdel , any further comments here

**Comment by kedmison** [comment]
Closing this issue, per @rabi-abdel, as the use cases have moved to the Tech chapter.
