### ISSUE TITLE
[RA2 Ch01] Initial Content for K8s Based Reference Architecture 

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#355]
Based on discussion on Antwerp, the decision was to start a PR to initiate the content for Chapter 1 to talk about the introduction and to start thinking about what is needed from platform prospectives to deliver on the cloud native definition.

**Comment by rabi-abdel** [comment]
As a greed on Antwerp, I will go a head and create the initial PR for the discussion on Tuesday next week.

**Comment by tomkivlin** [comment]
Can this be closed now @rabi-abdel ?

**Comment by rabiabdel** [comment]
Yes
