### ISSUE TITLE
[RM Ch09] More Operation and LCM Requirement

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#365]
Need to add more operation & LCM Requirements

**Comment by petorre** [comment]
I read through and current text generally looks OK.
One concern I see in [9.2](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter09.md#92-configuration-and-lifecycle-management) is "_should be made available by ... infrastructure management (VIM) components_" in "_This leads to the following table (Table 9-3) which defines the standard interfaces that should be made available by the infrastructure and infrastructure management (VIM) components to allow for successful Configuration Management._" which after looking at scope on Figure 9-1 can be understood as exposed to VNF tenant. Can we add "to NFVI administrator" or something similar clarifying?

**Comment by pgoyal01** [comment]
Typo: "Table 9-1 lists the main components and capabilities required in order to manage the configuration and lifecycle of those components."  It should refer to Table 9-2.

**Comment by pgoyal01** [comment]
9.4: "As such the requirements for Capacity Management on the infrastructure are covered by the Assurance and Configuration and Lifecycle Management sections above. The Assurance section deals with the collection of data - there is no reason to consider that this would be done by a different mechanism for Capacity Management as it is for Assurance ..."

The Assurance data collection doesn't collect data on compute node utilisation, particularly by NFVI profiles. It also doesn't capture anticipated demand. The utilisation (by NFVI profiles) and demand are important inputs into capacity planning.  Based on the utilisation of NFVI profiles and anticipated demand it may be possible to re-purpose compute nodes without supplementing capacity.

**Comment by walterkozlowski** [comment]
Closed as agreed at the RM meeting on 19 August 2020
