### ISSUE TITLE
[RA-1 Ch04] HW Acceleration Support for NFVI

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#368]
Acceleration to be used by NFVI (for example SmartNIC to offload ovs). This is not to provide acceleration to VNF. (no SR-IOV).

**Comment by liyingyjy** [comment]
I can provide solutions of OVS offload, GPU, FPGA SmartNIC and the management of acceleration resource by cyborg. I am happy to produce initial content to discuss.

**Comment by pgoyal01** [comment]
@liyingyjy Can you provide status of where you are with the content? Thanks

**Comment by liyingyjy** [comment]
Sorry I will upload the content tomorrow morning
