### ISSUE TITLE
[RA1 Ch05] initial content for API (interfaces)

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#371]
Need to create the initial content for Ch05 about APIs (with minimum ver) and interfaces (standardise on things like swift api, etc) As per Antwerp Feedback

**Comment by rabiabdel** [comment]
assigned to @pgoyal01 Thank you @pgoyal01

**Comment by rabiabdel** [comment]
@pgoyal01 please make sure you reference this issue when creating a PR.

**Comment by pgoyal01** [comment]
@rabiabdel will do. Thanks

**Comment by pgoyal01** [comment]
@rabiabdel please see https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter05.md -- initial content already exists. Are you asking for changes (adds)?

**Comment by rabiabdel** [comment]
oh i didn't realise :) i think what is needed is:

- adding the minimum required version (at the moment it doesn't say minimum).
- leave The PR open for some time to get general agreement on the content, min version, etc.

**Comment by pgoyal01** [comment]
PR #374 created. 
Modified "Baseline" to "Minimum (Baseline)" for the version Information.

**Comment by pgoyal01** [comment]
@rabiabdel Can we close this issue now?

**Comment by collivier** [comment]
It's a very good first step but I think key data are missing.
About that bug, I strongly believe that we must precise the micro versions too (nova, cinder).

I'm not clear about Ironic here. From my understanding, it's not exposed to the VNFs or more generally the clients.

Regarding the overall target, we can complete here or in other bugs (I can open new bugs if needed) the capabilities per service. Here are few examples:
  - Swapping volumes
  - Shelve
  - Encrypted volume
  - Cold migration
  - Cinder multi-backend
  - etc.

At then end, we should be able to run OPNFV Functest without any skip test:
- http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-latest-tempest_full-run-440/results/tempest_full/tempest-report.html
- http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-latest-tempest_slow-run-83/results/tempest_slow/tempest-report.html

I will publish new patches in Functest according to that first update. Thank you!

**Comment by collivier** [comment]
I could have precised that OPNFV Functest already has the logic to allow skipping tests or not.

The new containers will simply override the default configs to forbid skipping any subtests (here we do know exactly the reference as opposed to our leitmotiv: tested as much as possible)

All CNTT users could also run the classical OPNFV Functest containers to validate any optional service (Barbican?) or any optional capabilities (swapping volumes?). 

I'm overriding the default Tempest regex to avoid skipping former API tests (e.g. Keystone v2) or optional capabilities in the new CNTT-related containers.

**Comment by collivier** [comment]
\+ Neutron extensions and overlays supported:
http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-latest-neutron-tempest-plugin-api-run-497/results/neutron-tempest-plugin-api/tempest-report.html

Here are a few examples:
- qos
- l3-conntrack-helper
- bgpvpn
- sfc
- VXLAN
- etc.

It's worth mentioning that all that capabilities are exposed by the API.

**Comment by pgoyal01** [comment]
@collivier Thanks for great input and pointing to the gaps between the RA-1 and RI. Action Items - Open Issues to:
1. Update RA-1 Chapter 2 Requirements
2. Update RA-1 Chapter 3/4 (expand to include items suggested by you)
3. Update RA-1 Chapter 5.
[I will copy most of you comments onto these issues sometime today Saturday 2019-10-19]

I hope you be able to contribute content -- I can then assign the issues that you would like to work on to you. Thanks in advance.

W.r.t. Ironic, here is my half-cent. I think of RA-1 as a reference architecture supporting VNFs using OpenStack as the software that creates and manages the IaaS cloud. Till recently (allow me label it as the "Past"), OpenStack services were implemented on virtualised resources (VMs). OpenStack services, as you are well aware, typically follow design best practices including microservices architecture principles and loose coupling. Thus, increasingly nowadays ("Present"),   OpenStack services are being containerised including by OpenStack Foundation itself (e.g., OpenStack Helm - OSH) and all major vendor distributions (Canonical, Mirantis, RedHat and others), in the process making these OpenStack services resilient, evolvable, automatically deployable, etc. One of the additional benefits is that containerised OpenStack services consume less resources then their virtualised versions. It is in this context that Ironic has been listed as one of the OpenStack services.

**Comment by collivier** [comment]
@pgoyal01 Thank you for the new issues. Regarding the testing capabilities in Functest, it seems that Gnocchi (tested via Rally scenarios) and Barbican are optional (tested via the Tempest plugin and Rally scenarios).
http://artifacts.opnfv.org/functest/functest-opnfv-functest-smoke-latest-barbican-run-498/results/barbican/tempest-report.html

**Comment by karinesevilla** [comment]
Content for Chapter 5 added and already merged
PRs #374, #463, #577, #625, #627, #572, #648, #660, #733
