### ISSUE TITLE
[RA1 Ch08] Perform GAP analysis into existing technologies based on openstack

### ISSUE THREAD

**Issue by rabiabdel** [cntt-n/CNTT#372]
There is a need to document and understand where the gaps are within OpenStack projects and others.
example would be the need for standard interfaces for acceleration.

**Comment by ASawwaf** [comment]
Yes  , i believe in this, there is a lot of gaps in current NFV implementation not only for acceleration

**Comment by rabiabdel** [comment]
@sukhdevkapur since you are the lead of this WS, please identify someone (or you :) ) to create a PR to address it.

**Comment by pgoyal01** [comment]
Issue addressed in PR #688, #689 and #700
