### ISSUE TITLE
[RM Ch08] Clarify Certification in Document

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#375]
Clarify that Certification is not possible as the open source team cannot "commercialize" a product

**Comment by mf4716** [comment]
@sukhdevkapur - can I close this issue ([375](https://github.com/cntt-n/CNTT/issues/375))?

**Comment by kedmison** [comment]
@mf4716 this issue is a bit stale... but I am wondering what we should do to revive it or close it.  Can you comment further on this please?

**Comment by mf4716** [comment]
Closing.  This issue was addressed in [RC-1 Ch1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter01.md#1-introduction) recently, with removal of "Certification", replacing with "Conformance".   Recommend opening a new issue/PR against RC-1 (Ch1 most likely) for further discussion or clarification, if required.
