### ISSUE TITLE
[RM Ch08] Update Methodology with demarcation of CNTT & Community test responsibilities

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#376]
Update Methodology with clear demarcation of CNTT vs. Community/Supplier Test Responsibilities

**Comment by mf4716** [comment]
Reassigning to Kyle (ch 8 co lead)

**Comment by kedmison** [comment]
@mf4716 @kagreenwell The Methodology section seems to have moved to RC chapter.  Can this issue be closed or migrated to an RC issue?

**Comment by kedmison** [comment]
Closing as Chapter 8 content has now moved to RI and RC workstreams.
