### ISSUE TITLE
[RM Ch08] Insert Measurements Taken by External Instrumentation

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#379]
Per analysis and agreement in 2/10/2019 RMCH-4 weekly meeting, insert all measurements (currently identified as metrics), that are taken by external test instrumentation and were removed from RMCH-4 under Issue #378. Note, this is not intended to preclude the inclusion of additional measurements not originally identified in RMCH-4. These measurements are re-targeted to RMCH-8, b/c infra performance profiling is performed. See meeting minutes for further details.

**Comment by markshostak** [comment]
Per today's weekly chapter review meeting, Al Morton has taken an action to extract the relevant PMs from ETSI NFV TST009, and the team will be bringing their favorite PMs to include, as well.

**Comment by mf4716** [comment]
@markshostak - RMCH-8 PR #389  generated with changes added to CH 8 - https://github.com/cntt-n/CNTT/pull/389.  Please review/approve/comment if Issue can be closed.

**Comment by markshostak** [comment]
Fixed by PR #389 from Mike F. Closing.
