### ISSUE TITLE
[RM Appendix-A] Add VNF Monitoring Capabilities Use Case

### ISSUE THREAD

**Issue by ashokkumarprajapati** [cntt-n/CNTT#387]
We should add a UseCase for Exposed Monitoring capabilities so that we all are on same page for the same. Use Case to be added to RM VNF Design Guidelines supplement (RM Appendix-A).

**Comment by markshostak** [comment]
Arif and Ashok, Thanks for taking this on! -Mark

**Comment by pgoyal01** [comment]
Who is developing rest of the content? 

In the[ Chapter Outlines](https://github.com/VoerEirAB/CNTT/tree/ashokkumarprajapati-387/doc/ref_model) the Appendix is referred to as "VNF Design Guidelines" and in the Chapter itself as "Guidelines for VNF Vendors", the latter having a larger scope.Th outline appears not to have a section for VNF Design (things such as, The VNFs must be designed to be agnostic to the  cloud platform and should be able to operated on such platforms where the platforms may evolve continuously.  The VNF state should be decoupled form its logic (like good sw design). etc. etc.)

Why is the "VNF Monitoring Use Case" not in the main RM "Operations and LCM" chapter?

**Comment by petorre** [comment]
> 
> 
> Who is developing rest of the content?

I am.

> In the[ Chapter Outlines](https://github.com/VoerEirAB/CNTT/tree/ashokkumarprajapati-387/doc/ref_model) the Appendix is referred to as "VNF Design Guidelines" and in the Chapter itself as "Guidelines for VNF Vendors", the latter having a larger scope.Th outline appears not to have a section for VNF Design (things such as, The VNFs must be designed to be agnostic to the cloud platform and should be able to operated on such platforms where the platforms may evolve continuously. The VNF state should be decoupled form its logic (like good sw design). etc. etc.)

Yes, all coming...

> Why is the "VNF Monitoring Use Case" not in the main RM "Operations and LCM" chapter?

Agree. Is discussed in #448 .
