### ISSUE TITLE
[RM Ch07] Typo Corrections in Sect. 7.10.5

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#396]
Tables 1 and 2 in Chapter 7 are labeled as Tables 5-1 and 5-2; should be 7-1 and 7-2.
Mike, if you want me to fix this, just assign it to me. Thx, -Mark

**Comment by markshostak** [comment]
Fixed by PR #529.

**Comment by msidana** [comment]
Closing this issue as the fix #529 is merged now.
