### ISSUE TITLE
[RA2 Ch08] GAP: Operating Model

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#400]
This issue is to tackle the operating model gap exist within K8s and try to propose solutions and next steps.

**Comment by pgoyal01** [comment]
@rabi-abdel What about an alternate view. Instead of trying to make k8s what it is not, let us think of a  CIM (Containerised Infrastructure Manager) that performs functions similar to the VIM. The CIM would then consist of kubernetes plus other software components for inventory, access management etc.

**Comment by ASawwaf** [comment]
Yes, I am favour of CIM terminology, I added before in termonologies brainstorming "PR#Initial Content for K8s RA #383"

So let agree on this and start put a definition 

_As initial definition_: it is software responsible  for controlling and managing the Container infrastructure which host Container Network Function ( Cloud Native Function ) by consuming the compute resources, storage resources and networking as well, responsible for Life Cycle management in term of resources allocation, resources scheduling for best infrastructure utilization

**Comment by pgoyal01** [comment]
@ASawwaf Thanks. Let use see if we can keep it aligned with the way ETSI GS NFV 003 V1.3.1 (2018-01) defines VIM.
Virtualised Infrastructure Manager (VIM): functional block that is responsible for controlling and managing the NFVI compute, storage and network resources, usually within one operator's Infrastructure Domain (e.g. NFVI-PoP).

Containerised Infrastructure Manager (CIM): functional block that is responsible for controlling and managing the containerised NFVI compute, storage and network resources. Note CIM supports the  Life Cycle Management of conatinerised and the underlying physical resources.

Critique?

**Comment by ASawwaf** [comment]
@pgoyal01 I used to refer to it and add my touch :)

**Comment by sukhdevkapur** [comment]
This proposed terminology makes sense to me and seem consistent with other objects. 

Sukhdev

**Comment by tomkivlin** [comment]
RA2 weekly meeting 5/12/19: Needs more clarification as to whether this should be in scope of CNTT or not.
