### ISSUE TITLE
[RI1 Ch02] RI Requirement Initial Content

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#401]
Providing initial content for Ch02 which is the requirement of Reference Implementation. (based on open source, comply to reference architectures, etc)

**Comment by mf4716** [comment]
@fuqiao123 - please assign to a contributing member.

**Comment by mf4716** [comment]
Reviewed the change/PR.  No issues, or concerns.  Let's use the 10/30 recurring status call to review with the community and approve.  If we run out of time on the call to review I'll approve immediately.

**Comment by mf4716** [comment]
status?

**Comment by fuqiao123** [comment]
Suggest to close this issue since the initial contents has been developed
