### ISSUE TITLE
[RI1 Ch03] NFVI State initial content

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#402]
This is to provide initial content into Ch03 of RI 1 to identify the required state of NFVI (what configuration needed for each of provided profiles) etc.

**Comment by mf4716** [comment]
@fuqiao123 @trevgc - Trevor can you help with this issue?

**Comment by fuqiao123** [comment]
@mf4716 could you please help add jiaqiang-cmcc as assignees for this issue?

**Comment by mf4716** [comment]
@fuqiao123  - I've made the request to add jiaqiang-cmcc.  An invite will be sent to join the repo.

**Comment by jiaqiang-cmcc** [comment]
With Rabi and Mick's help. I have joined our repo.

**Comment by mf4716** [comment]
Good to have you on board @jiaqiang-cmcc
