### ISSUE TITLE
[RI1 Ch04] Lab Requirements

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#403]
This issue to start initial content for Lab Requirements (specify in details the minimum specs of hardware needed for lab - including compute nodes, network, storage - for each of the profiles. this also should specify the topology of the lab expected.

**Comment by cntt-n** [comment]
@fuqiao1@outlook.com

**Comment by mf4716** [comment]
@rrajesh70 @fuqiao123 - we have initial requirements in Chapter 4 already.  This needs to be reviewed with our Infra WG, CNTT RA, and OPNFV teams to ensure we have sufficient requirements to meet the needs of each profile and we need a topology diagram as well.  @rrajesh70 - this is closely tied to RI Labs efforts.  Please assign as needed.

**Comment by lylavoie** [comment]
@rabi-abdel and @mf4716 , I think this issue can also be closed / resolved by pull #654 .

**Comment by mf4716** [comment]
status?
