### ISSUE TITLE
[RI1 Ch05] Initial content for Installer requirement

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#404]
This issue is to start the initial content for installers requirements.

**Comment by mf4716** [comment]
@fuqiao123 - please confirm you can assign this to yourself, or Chen Liang.  If Chen Liang, then please get the GitHub ID so we can assign it accordingly.

**Comment by ChilionChan** [comment]
Hi, my GitHub ID is chilionchan

**Comment by fuqiao123** [comment]
according to the discussion on Dec. 19 RI weekly call, the initial content for installer requirement has accomplished. Therefore I suggest we close this issue

**Comment by mf4716** [comment]
@fuqiao123 - @ChilionChan - please email response from me a few minutes ago re: the Hardware Validation plug-fest discussion.  I agree with Chen, that we can add the content from that email thread as a pre-req for software install and insert the main bullets and purpose for that testing in this chapter.  See email for more details.  After that, I agree with you to close this issue and any related PRs that will be generated.

**Comment by mf4716** [comment]
status?

**Comment by fuqiao123** [comment]
Initial contents has been developed. Will close this issue and create a new issue for further improvements of the contents.
