### ISSUE TITLE
[RI1 Ch06] Current Existing Labs details

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#406]
This issue is to include what labs are available currently (community, approved lab schemes, etc)

**Comment by mf4716** [comment]
@rrajesh70 - please work with Jack Morgan, Jim Baker, and Bin Hu.  Include Mark Shostak and myself in the dialogue.  This will get the collective input of OPNFV projects and resources teams who can provide the requested lab info and it will align on the work Jim and team are already doing to assess current labs.

**Comment by rrajesh70** [comment]
Intel PODs 10 and 15 are allocated for CNTT. UNH and Spirent are also target for building and operating CNTT Community Labs. The RI Labs documentation will be updated with the details

**Comment by mf4716** [comment]
@markbeierl - here's the issue I mentioned re: Lab Topology doc (needed).  I'll add you to issue #405 as well (via comment section).

**Comment by mf4716** [comment]
status?

**Comment by markbeierl** [comment]
For the lab details, I think we are complete here.  We will need a new PR for Ch06 to document the lab operations, as outlined by @mf4716 :

**Ch06: Lab Operations**

- Define & Ensure all entry / exit criteria met
- Outline lab selection options & How to obtain assistance (LAAS, Community, Self Service)
- Release Alignment

**Comment by mf4716** [comment]
@markbeierl - I approved PR #810 .  Agree.  A new PR can/should be generated by @rrajesh70 when ready to document Lab Operations, post-Snezka.
