### ISSUE TITLE
[RI1 Ch08] Installer Integration initial content

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#407]
This issue is to start content for Installer Integration (what installer to use, what version) and map the choice to the requirement set in RI1 Core.

**Comment by mf4716** [comment]
@lei-cloud @rexlee8776 - Lei, Rex, can you please own this issue and pull in Cedric Ollivier from Orange as needed?

**Comment by lei-cloud** [comment]
OK. I'll try to contact with Rex and Cedric discussing what to do and how to deal with this issue.

**Comment by mf4716** [comment]
status?

**Comment by jayacha** [comment]
this was initial content, proposing to close this, but recommend to review the whole cookbook for Airship.
