### ISSUE TITLE
[RI1 Ch07] User Manual initial content

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#408]
This issue is to create content to explain in details (how to install NFVI) using the installer chosen. 

whoever reads this section, should know how to install Common NFVI on their own labs.

**Comment by mf4716** [comment]
@rexlee8776 @lei-cloud - please work with Cedric Ollivier at Orange to work this chapter/issue.

**Comment by mf4716** [comment]
Assistance will be needed from our AirShip installer support for POD10/15, Mr. Sridhar Rao <Sridhar.Rao@spirent.com>.  Sridhar will be receiving access to GitHub in the next day, or two.  

As discussed 11/6 during the RI/RC meeting, example scope or subheadings for the chapter will include:  

i. pre-req:  Bare-metal validations 
a) RA Requirements Gathering process
b) Infra Requirements and Selection Process
c) Access & Connectivity
d) Descriptor file &/or Manifest creation (data elements, use/implementation)
e) Deployment Installer & Install Steps
f) Deployment Validations

These will be inserted into the documentation as a placeholder, with an open PR to start the work.

**Comment by mf4716** [comment]
FYI - PR generated with initial content and placeholders for contributor support - https://github.com/cntt-n/CNTT/pull/568

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
Expanded distro.

@fuqiao123 , @opensource-tnbt , @collivier , @markbeierl -  status?

**Comment by mf4716** [comment]
Can we get an update?

@fuqiao123 , @opensource-tnbt , @collivier , @markbeierl , @ChilionChan ?

**Comment by collivier** [comment]
Deployment Validations is under review

**Comment by jayacha** [comment]
PR #568 already merged and closed this issue.
