### ISSUE TITLE
[RI1 Ch09] Initial Gap analysis 

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#409]
This issue to initiate the content around what gaps exists in the industry for installers and other tools needed to install the NFVI.

**Comment by mf4716** [comment]
@fuqiao123 - please confirm you can accept this issue and update the chapter content accordingly, or if you can co-assign it to other contributors/leads for RI Dev.

**Comment by mf4716** [comment]
status?

**Comment by jayacha** [comment]
@fuqiao123 Any further update please? can this be closed?

**Comment by fuqiao123** [comment]
> @fuqiao123 Initial content already created. Any further update please? can this be closed?

I think we already have the initial content here. I am OK to close this. And if anyone detect further gaps to add, we can open new issue

**Comment by jayacha** [comment]
Ok to close from call
