### ISSUE TITLE
[RC1 Ch02] E2E C&V NFVI Framework Req

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#410]
This issue is to create content for E2E C&V NFVI Framework requirement. (tools needed, tools specs, how many tools, output format, etc)

**Comment by mf4716** [comment]
please review - confirm if you can assist with this issue @collivier

**Comment by mf4716** [comment]
@msidana @collivier - please review/recommend changes to this proposed chapter outline.  I'll create a PR Tuesday with any input you provide.

- Methodology
- Certification Strategy & Vehicle
- Profiles Reference 
- Compliance, Verification, and Certification
- Entry & Exit Criteria
- Frameworks: e.g. Functest (StorePerf, SampleVNF, others?)

**Comment by mf4716** [comment]
@msidana - Manik, please confirm status.  Thanks

**Comment by msidana** [comment]
> @msidana - Manik, please confirm status. Thanks

PR is already WIP - https://github.com/cntt-n/CNTT/pull/788

**Comment by mf4716** [comment]
@msidana Manik, I see the "WIP" in the PR title.  Great idea.  Can we close this issue then, with an open PR?  I don't think we want to track status in 2 locations.

**Comment by msidana** [comment]
> @msidana Manik, I see the "WIP" in the PR title. Great idea. Can we close this issue then, with an open PR? I don't think we want to track status in 2 locations.

Sure we can close this. I am doing PR against a fresh issue https://github.com/cntt-n/CNTT/issues/787

**Comment by mf4716** [comment]
Duplicate issue - https://github.com/cntt-n/CNTT/issues/787

Closing
