### ISSUE TITLE
[RC1 Ch04] Traceability of NFVI Test Cases to RA Req

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#412]
This issue is to create initial content for traceability of test cases to RA Req.

**Comment by mf4716** [comment]
@ashokkumarprajapati - please review and confirm if you can assist with this issue.

**Comment by mf4716** [comment]
@xudan16 - your assistance with this issue would be appreciated - until Ashok Kumar confirms acceptance.

**Comment by xudan16** [comment]
@mf4716 - I am glad to do this. But as I am new here, so I am not clear about what should be done in this chapter. Any info or guide would be very appreciated.

**Comment by mf4716** [comment]
@xudan16 - thanks Dan.  The goals/purpose of the chapter is to outline the strategy, approach, and criteria, resulting in the traceability of NFVI/VNF test cases to the Reference Architecture (RA1 OpenStack) requirements from CNTT.  Per our RC1 call today, Rajesh from Spirent has offered to assist in this area, so I'm adding @rrajesh70 as an Assigner.  Please reach out to Rajesh directly to discuss.  Include me (@mf4716 ) and Mark Shostak please in the emails/invites @markshostak .

**Comment by ashokkumarprajapati** [comment]
@mf4716 : Ready to help. I was on holiday so couldn't reply.
