### ISSUE TITLE
[RC1 Ch05] E2E C&V VNF Framework Req

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#413]
This issue is to create content for E2E C&V VNF Framework requirement. (tools needed, tools specs, how many tools, etc)

**Comment by mf4716** [comment]
@collivier - can you assist with this issue, or help assign to another?

**Comment by mf4716** [comment]
@mkr1481 @collivier @sparayil - please see the following for a chapter outline.  Please review and recommend changes.  I will create a PR Tuesday and ask for your help to write these sections.

- Methodology
- Introduction of Golden VNFs &/or Prototype VNFs
- Certification Strategy & Vehicle
- Profiles Reference 
- Compliance, Verification, and Certification process
- Entry & Exit Criteria
- Frameworks: Functest, SampleVNF, Prototype Family/Class

**Comment by mkr1481** [comment]
I have started to document ch05 by using #721

**Comment by mf4716** [comment]
added @sparayil (thank you) after review today.  Please collaborate with Kanag and Cedric.

**Comment by sparayil** [comment]
@mf4716 @mkr1481 , I like the format @mf4716 suggested. I see Kanag has added some good content already. I was planning to generate the content in word document and get it reviewed by both of you. lets shoot for Tuesday for an initial review of my contribution internally

**Comment by mf4716** [comment]
@mkr1481 - heads up that @sparayil will reach across Sun night US to discuss moving some Ch5 content into Ch6 as it's more applicable to that chapter.  I met with Shiby the last few days, and he's created very good content in alignment with a typical 'Framework' request.  Few final touches needed to clean it up.   Heads up @fuqiao123 , @yangyanyj as I know you're authoring some content in RC1-Ch6.  The plan is to ensure you're included in the PR for both chapters.  Please be sure to review when the PRs come out on/before 12/17.

**Comment by mkr1481** [comment]
@mf4716 sure. thanks
@sparayil i saw your outlook meeting invitations for the same. let us close this issue by today. thanks.

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@sparayil - status?

**Comment by mf4716** [comment]
@sparayil @mkr1481 - status?

**Comment by mkr1481** [comment]
it is done now. #876. and can be closed.

**Comment by mf4716** [comment]
Closed - with merged PR #876
