### ISSUE TITLE
[RC1 Ch08] E2E NFVI Testing Framework Integration

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#416]
This issue is to create content for the integration of E2E Framework (choices, exact releases, etc)

**Comment by collivier** [comment]
I may split it into several smaller issues. I think it would be great to decouple the Test Frameworks (Functest, YardStick, etc.) and the way to define a common execution of them (e.g. Xtesting).

**Comment by mf4716** [comment]
Good idea.  Rather than create separate issues though, create sub-sections within the Chapter to handle decoupling.  This will allow us to keep the Frameworks, Common Execution, Choices, Release, etc, contained within the same chapter.

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - please review proposed chapter outline. Please recommend changes. I will generate a PR Tuesday based on your inputs. Your assistance will be needed in writing the material.

- Identify Framework Needs, Goals, and Dependencies
- Define Opensource Integration (OPNFV, OVP, Functest, CVC, others)
- Provide Automation Tool chain (list, topology, flow)

**Comment by mf4716** [comment]
Update @collivier ?

**Comment by mf4716** [comment]
@yangyanyj - per your email, "I am working on RC-1 VNF and can be transferred later on Ch08", what date can create a PR, and when can you add this content.  Added @opensource-tnbt (Sridhar) here too, as he's co-assignee to this material.

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - status?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - status?  There is content available, but it appears to need a peer review, and further editing.  Please comment if someone is still working on this, or believes it should be closed.

**Comment by collivier** [comment]
@rabiabdel @mf4716 the frameworks are documented for the RC and RI needs. The testing versions are also listed for the NFVI compliance containers. Do you see something missing for NFVI Compliance?

**Comment by collivier** [comment]
I closed it be free to reopen it if needed.
