### ISSUE TITLE
[RC1 Ch08] NFVI E2E Framework User Manual

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#417]
This issue is to create content for the user manual of E2E Framework for NFVI Testing. (how to install, and use).

anyone who reads this content should be able to understand exactly what is needed to run those tools and get the results out.

**Comment by mf4716** [comment]
Kanagaraj, Cedric, can you assign this issue to someone to assist, or take ownership of the issue?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - please review proposed chapter outline. Please recommend changes. I will generate a PR Tuesday based on your inputs. Your assistance will be needed in writing the material.

- Identify Framework Needs, Goals, and Dependencies
- Define Opensource Integration (OPNFV, OVP, Functest, CVC, others)
- Provide Automation Tool chain (list, topology, flow)

**Comment by mf4716** [comment]
Added authors to this item.  Is there an update?

Ch08: E2E Framework Integration: Cedric, Kanagaraj,Sridhar (question) Yan Yang (confirmed) -

**Comment by mkr1481** [comment]
@mf4716 I have updated the VNF test platform details in ch08 already

**Comment by mf4716** [comment]
There are several sections still to be written.  @yangyanyj (Yan Yang) , @opensource-tnbt (Sridar), @collivier , can you help with those missing sections?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - status?

**Comment by collivier** [comment]
@mf4716 @rabi-abdel I would consider this part as under-review. Waiting for 2 approvals.
https://github.com/cntt-n/CNTT/pull/910

**Comment by collivier** [comment]
Done (The 2 PRs were merged)
