### ISSUE TITLE
[RC1 Ch09] Available NFVI Tests and their traceability to TC Req

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#418]
This issue is to provide a list of available NFVI test cases exist in the open source communities and trace them back into TC Req set in Ch03

**Comment by ashokkumarprajapati** [comment]
@rabi-abdel : Can you explain a bit how it would be different then #415 .

**Comment by mf4716** [comment]
@collivier - please review recommend chapter outline.  Please provide feedback for changes.  I will create a PR Tuesday based on your inputs.  Your help will be needed to create the documentation.

- Define RM/RA-1 Openstack requirements
- Map Framework to Requirements

**Comment by deebhatia** [comment]
Map the test cases to test frameworks (like functest, yardstick etc) identified in #775 and #774 .

**Comment by mf4716** [comment]
Update @deebhatia and/or @collivier ?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@deebhatia @collivier - status?

**Comment by mf4716** [comment]
@deebhatia @collivier - can this be closed?  No PR open.  There is content for the chapter, which we can improve upon post-Sneka.  [RC1 Dev Ch9 - link](https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter09.md)
