### ISSUE TITLE
[RC1 Ch08] E2E VNF Testing Framework Integration

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#420]
This issue is to create content for the integration of E2E Framework (choices, exact releases, etc)

**Comment by mf4716** [comment]
Kanagaraj, Cedric, can you assign this issue to someone to assist, or take ownership of the issue?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - please review proposed chapter outline. Please recommend changes. I will generate a PR Tuesday based on your inputs. Your assistance will be needed in writing the material.

- Identify Framework Needs, Goals, and Dependencies
- Define Opensource Integration (OPNFV, OVP, Functest, CVC, others)
- Provide Automation Tool chain (list, topology, flow)

**Comment by mkr1481** [comment]
Hi Mike, I am working on this using PR #707 for aliging with ch 05 VNF Test Platform E2E. thanks

**Comment by mf4716** [comment]
Update @mkr1481 ?

**Comment by mkr1481** [comment]
@mf4716 already completed the guidelines details in ch08 for using vtp.

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@mkr1481 - status?

**Comment by mkr1481** [comment]
Its done. now #707. can be closed

**Comment by mkr1481** [comment]
Its done. now #707. can be closed
