### ISSUE TITLE
[RC1 Ch08] VNF E2E Framework User Manual

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#421]
This issue is to create content for the user manual of E2E Framework for VNF Testing. (how to install, and use).

anyone who reads this content should be able to understand exactly what is needed to run those tools and get the results out.

**Comment by mf4716** [comment]
Kanagaraj, Cedric, can you assign this issue to someone to assist, or take ownership of the issue?

**Comment by mf4716** [comment]
@collivier @mkr1481 @opensource-tnbt @yangyanyj - please review proposed chapter outline. Please recommend changes. I will generate a PR Tuesday based on your inputs. Your assistance will be needed in writing the material.

- Identify Framework Needs, Goals, and Dependencies
- Define Opensource Integration (OPNFV, OVP, Functest, CVC, others)
- Provide Automation Tool chain (list, topology, flow)

**Comment by mkr1481** [comment]
Hi Mike,
I will start document Ch 08 using PR #707

**Comment by mf4716** [comment]
Thank you Kanagaraj @mkr1481 .

**Comment by mf4716** [comment]
update @mkr1481 ?

**Comment by mkr1481** [comment]
@mf4716 Added the required documes for VNF test platform already.

**Comment by mf4716** [comment]
@mkr1481 - can this issue be closed?  Or, is further content/review needed?  Is @sparayil adding content?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@mkr1481 - status?

**Comment by mkr1481** [comment]
Its done. now #707. can be closed
