### ISSUE TITLE
[RM Ch4]: Clarifications to the attributes

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#426]
-	e.nfvi.res.cap.001, 002 and 003: I do not see a meaning in defining a minimum value for these. It is true that there is a minimum value for these but I see it more like an implementation details than an NFVI capability

**Comment by hdamker** [comment]
e.nfvi.per.met.001, 002 and 003 ... should be a seperate issue against chapter 8 then.

**Comment by CsatariGergely** [comment]
I'm happy to work on this.

**Comment by CsatariGergely** [comment]
> e.nfvi.per.met.001, 002 and 003 ... should be a seperate issue against chapter 8 then.

Agreed. I've created #428 and deleted e.nfvi.per.met.001, 002 and 003 from here.

**Comment by CsatariGergely** [comment]
Also I've created #429 and removed i.nfvi.mon.cap.005 and 006 from here.

**Comment by CsatariGergely** [comment]
#520 fixed this.
