### ISSUE TITLE
[RM Ch4]: Remove monitoring attributes added to Ch8

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#427]
#389 added several monitoring related attributes from Chapter 4 to Chapter 8. These should be deleted from Chapter 4.

**Comment by hdamker** [comment]
@markshostak @CsatariGergely Isn't that a duplicate to #378 ?

**Comment by CsatariGergely** [comment]
> 
> 
> @markshostak @CsatariGergely Isn't that a duplicate to #378 ?

Now as I read it now more carefully, yes. Let me close this then.
