### ISSUE TITLE
[RM Ch8]: Test setup clarification is needed

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#428]
e.nfvi.per.met.001, 002 and 003: TST009 defines a set of test setups on which the different benchmarks are measured. It should be stated in the definition if these are for p2p, pvp or pvvp. (And in case of containers pcp, pvcvp, pvvcp or pvcvcp).

**Comment by rabi-abdel** [comment]
@yangyanyj is WSL for this WS, but she has not accepted the GitHub invitation yet. therefore, I will assign it to you @CsatariGergely on her behalf to fix.

**Comment by CsatariGergely** [comment]
As it is discussed in #434 @xavier-grall will propose a pr for this, therefore I reassign the ticket. (I hope its okay @rabi-abdel )

**Comment by xavier-grall** [comment]
PR #464 for that issue is replaced by PR #579
