### ISSUE TITLE
[RM Ch8]: Definitions of attributes are not correct

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#429]
Definitions of i.nfvi.mon.cap.005 and 006 are not correct, and in case of i.nfvi.mon.cap.002 I do not see how „QoS enablement” is connected to „Virtual compute resource CPU usage” monitoring.

**Comment by CsatariGergely** [comment]
I'm happy to fix this.

**Comment by rabi-abdel** [comment]
@yangyanyj is WSL for this WS, but she has not accepted the GitHub invitation yet. therefore, I will assign it to you @CsatariGergely on her behalf to fix.

**Comment by markshostak** [comment]
The references cited in this bug report have been removed from the master branch. Closing...
