### ISSUE TITLE
[RM Ch07] Modifications needed for section 7.10.5

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#431]
Following discussion we had during RM chapter 4 meeting the 16th of October,
the content of section 7.10.5 needs to be modified for a better integration in the Security Chapter.
The 2 tables were initially moved from chapter 4: text must be rephrased, especially to capture what is expected at a model level.

@ASawwaf I can create a PR for that

**Comment by ASawwaf** [comment]
Yes , agreed , please do 
thx
