### ISSUE TITLE
[RA2 Ch06] Security isolation

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#433]
Following the discussion we had during RM chapter 4 meeting the 16th of October about security isolation, describe the mechanisms enabled to ensure security isolation per requirements expressed in RM Chapter 07 (section 7.10.5)

**Comment by msidana** [comment]
I'll be happy to work on this. Can I assign this to myself ?

**Comment by tomkivlin** [comment]
@msidana yes please do.  Suggest #530 needs working on first though? Will add you to an email conversation that has started around having a meeting on the subject.

**Comment by tomkivlin** [comment]
@msidana can you add yourself as a contributor here please: https://wiki.lfnetworking.org/display/LN/CNTT+Workstream+Signup#CNTTWorkstreamSignup-K8sReferenceArchitectureWorkstreams

You can join the mailing list here: https://lists.opnfv.org/g/cntt-tech-refa

**Comment by msidana** [comment]
> #530

Sure. Thanks @tomkivlin :).
I'll mark myself as an assignee for #530

**Comment by tomkivlin** [comment]
Closed as this is a subset of the content required from #530
