### ISSUE TITLE
[RM Ch5]: Virtual Storage Acceleration features

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#442]
Table 5-4: Virtual Storage Acceleration features describes nfvi.stg.acc.cfg.001 for "Storage IOPS oriented" and nfvi.stg.acc.cfg.002 for "Storage capacity oriented". Can someone please explain what are these acceleration technologies? How can I accelerate in a storage capacity oriented way?

**Comment by markshostak** [comment]
As currently written, the storage performance is implied by the element prefix of the selected storage extension, and realized through different "acceleration technologies" such as solid state media versus rotating media, rotational speed (e.g., 10K, 15K), the associated physical interfaces (e.g., SAS-1, SAS-2, PCIe, etc), logical organization, etc. Probably more to your point, as the storage extension identifier is already overloaded with the performance, it is redundant redundant to specify an additional form of "acceleration", al la carte. Therefore, I would propose we remove the IOPs indicator. 

WRT capacity, it's explicit within the storage extension identifier, therefore I'd propose we remove it.

@karinesevilla , Are you in agreement or do you have another proposal?

Thanks,
-Mark

**Comment by markshostak** [comment]
@CsatariGergely Hi Gergerly, I haven't seen any further questions from you, so I'm closing this issue. Ping me if you want to discuss further. Thanks, -Mark
