### ISSUE TITLE
[RA2 - Ch2] Requirements

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#445]
Modify req.gen.ost.01 and req.gen.ost.02 to be req.gen.k8st.01 and req.gen.k8s.02 respectively. In same PR add an initial set of other requirements.

**Comment by tomkivlin** [comment]
From 31.10 meeting: Contributors to the PR (#452) feedback to contact Pankaj with availability to have a meeting to discuss each in line.

**Comment by pgoyal01** [comment]
@tomkivlin Can we close as the issues were taken care of.

**Comment by tomkivlin** [comment]
> @tomkivlin Can we close as the issues were taken care of.

Once #452 is merged, yes - will be automatic if you used "Fixes #445" in the PR comments.
