### ISSUE TITLE
[RA2 Core]: Build a consensus about the usage of Helm and document the result

### ISSUE THREAD

**Issue by CsatariGergely** [cntt-n/CNTT#451]
In the discussions of #383 there was no consensus if Helm should be part of the Reference Architecture. The resolution of this issue shall build a consensus on it and document the result.

**Comment by msidana** [comment]
**Query:** A few months ago, [helm beta](https://helm.sh/blog/helm-v3-beta/) was released which involved removal of tiller due to security concerns as tiller requires cluster-role privileges. Is it preferable to wait for a stable HELM release or go ahead considering the beta if it is to be made a part of reference architecture ?

**Comment by CsatariGergely** [comment]
> 
> 
> **Query:** A few months ago, [helm beta](https://helm.sh/blog/helm-v3-beta/) was released which involved removal of tiller due to security concerns as tiller requires cluster-role privileges. Is it preferable to wait for a stable HELM release or go ahead considering the beta if it is to be made a part of reference architecture ?

In my opinion we should not use Tiller and have Helm 3 in the Reference Architecture.

**Comment by msidana** [comment]
> > **Query:** A few months ago, [helm beta](https://helm.sh/blog/helm-v3-beta/) was released which involved removal of tiller due to security concerns as tiller requires cluster-role privileges. Is it preferable to wait for a stable HELM release or go ahead considering the beta if it is to be made a part of reference architecture ?
> 
> In my opinion we should not use Tiller and have Helm 3 in the Reference Architecture.

Yes, I agree with you. But since Helm 3 is still beta, should it be a part of Reference Architecture ?

**Comment by tomkivlin** [comment]
Also linked to the scope discussions in #449 and #450
