### ISSUE TITLE
[RI 1 Labs]: Sridhar Rao to have a readout to CNTT RI1 members about Airship installation details and procedures on Intel POD 10 or 15

### ISSUE THREAD

**Issue by rrajesh70** [cntt-n/CNTT#459]
Sridhar has suggested having the readout on Wednesday Oct 30th

**Comment by mf4716** [comment]
@rrajesh70 - can we do this earlier in the week?

**Comment by rrajesh70** [comment]
The India based contributors are off for Diwali holiday. I will try to advance

**Comment by rrajesh70** [comment]
Sridhar Rao has completed the readout and published a powerpoint deck detailing steps
