### ISSUE TITLE
Add chapter describing workflow of compliance program

### ISSUE THREAD

**Issue by gkunz** [cntt-n/CNTT#460]
I am proposing to add a chapter describing the overall workflow of the LFN-based compliance program: testing -> result submission -> review -> granting of a compliance label.

This chapter should be based on and/or point to existing documentation of the LFN CVC where applicable.

**Comment by mf4716** [comment]
Please see RM Ch8 sections 8.5-8.7 as this was captured, albeit may need some updates/edits as you see fit.  This can be moved/inserted into existing RC chapters, sub-sections, or new RC chapter as needed.  Please review and advise.  Thanks.  [Link to RM Ch8](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter08.md).

**Comment by mf4716** [comment]
Please update with status @gkunz

**Comment by mf4716** [comment]
@gkunz  - hi, can you update status?  If finished, or NA, let's please close the issue.

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@gkunz - status?

**Comment by gkunz** [comment]
This issue can be closed as the content I proposed should be covered by RC1 Chapter 2.
