### ISSUE TITLE
[RM ch8] Updates for perf measurement (section 8.9.1.1)

### ISSUE THREAD

**Issue by xavier-grall** [cntt-n/CNTT#462]
Perf metrics has been moved from chapter 4 to chapter 8 in a new perf measurement section which requires to be updated to detail how perf metrics can ne measured.
A commit is proposed for that purpose:
https://github.com/xavier-grall/CNTT/commit/f30e9de72115e83c644842fe494c1b2f8a22d7ae

**Comment by markshostak** [comment]
Just to clarify, performance measurements that are taken with external instrumentation (e.g., Spirent, Ixia, etc.) and used to characterize the infra, were moved to RM CH-8. Performance measurements (PMs) that are generated by the infra itself on a day to day basis, remain in RM CH-4. Also, be aware that the measurements in RM CH-8 will likely move to RC NFVI.

**Comment by xavier-grall** [comment]
@markshostak 
OK thank you Mark for that clarification.

**Comment by xavier-grall** [comment]
PR #464 for that issue is replaced by PR #579

**Comment by kedmison** [comment]
The most recent PR #579 was merged, and the perf metrics moved to the RC document

@mf4716 @ASawwaf let me know if you think this issue can be closed.

**Comment by ASawwaf** [comment]
@kedmison , for the time being no issue
I preferred to have a details list of metric either in RM ( Annex ) or RA and RC refer to it

**Comment by kedmison** [comment]
closing this issue, as linked content appears to have been merged to other documents (RC) via other PRs ( #579 )
