### ISSUE TITLE
[RI 1 Dev] Add latest tempest plugins into Functest

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#483]
Functest could complete the API coverage already in place by adding the latest tempest plugins.
The tempest plugins may be prioritized in relation with the mandatory services/capabilities/extensions
https://docs.openstack.org/tempest/latest/plugin-registry.html

It's worth mentioning that the next plugins are already part of Functest:
- openstack/barbican-tempest-plugin
- openstack/neutron-tempest-plugin
- openstack/octavia-tempest-plugin
- openstack/patrole

**Comment by collivier** [comment]
3 plugins were just merged in master (they had to be backported in older releases: Hunter?)
- keystone-tempest-plugin https://gerrit.opnfv.org/gerrit/c/functest/+/68698
- cinder-tempest-plugin https://gerrit.opnfv.org/gerrit/c/functest/+/68698
- horizon-tempest-plugin https://gerrit.opnfv.org/gerrit/c/functest/+/68696

**Comment by collivier** [comment]
Additional comments:
- heat-tempest-plugin seems not working (additional upstream changes have to be considered)
- x/intel-nfv-ci-tests seemed unmaintained (pending changes from OPNFV members)

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
done
