### ISSUE TITLE
[RI 1 Dev] Port YardStick testcases to Xtesting

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#509]
Xtesting allows a smooth integration of sparsed testcases and ease building CI/CD toolchains via an Ansible role.
http://testresults.opnfv.org/functest/stockholm/

Here leveraging on Xtesting will ease building CI/CD toolchains in few commands mixing Functest and YardStick testcases. It also simplifies any validation process as it avoids extra logics per test frameworks (jenkins job templates, certification, etc.)
https://wiki.opnfv.org/pages/viewpage.action?pageId=32015004

**Comment by mf4716** [comment]
status update @collivier ?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier - status?

**Comment by collivier** [comment]
It's up to YardStick team to port it or at least to ask for help.
I won't update all OPNFV test frameworks.

**Comment by mf4716** [comment]
@collivier - reassiging back to you as you opened this in Oct.  Please assign to the proper Yardstick person/team, or list as a gap and we'll address post-Snezka

**Comment by mf4716** [comment]
status @collivier ?

**Comment by collivier** [comment]
@rabi-abdel @mf4716 I would appreciate a quick clarification about the RC1 Co-Lead scope.
From my understanding here, the issue must be assigned to StorPerf PTL or contributors, any CNTT-OPNFV liaisons or RC1 leader. On the other hand, this role raises side effects vs my Functest PTL role regarding the false RC tables introduced in OPNFV TSC meeting (and possibly in CNTT governance?).
To avoid a lots of spams as it happened in December, I would suggest to close this issue and the similar ones per OPNFV projects. Agree?

**Comment by collivier** [comment]
@fuqiao123 @rabi-abdel @acmacm : No upstream activity for a while. I closed it.
Be free to reopen it if needed.
