### ISSUE TITLE
[RI 1 Dev] Port Bottlenecks to Xtesting

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#510]
Xtesting allows a smooth integration of sparsed testcases and ease building CI/CD toolchains via an Ansible role.
http://testresults.opnfv.org/functest/stockholm/

Here leveraging on Xtesting will ease building CI/CD toolchains in few commands mixing Functest and Bottlenecks. It also simplifies any validation process as it avoids extra logics per test frameworks (jenkins job templates, certification, etc.)
https://wiki.opnfv.org/pages/viewpage.action?pageId=32015004

**Comment by mf4716** [comment]
status update @collivier ?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier - status?

**Comment by mf4716** [comment]
status @collivier ?

**Comment by collivier** [comment]
@rabi-abdel @mf4716
To avoid a lots of spams as it happened in December, I would suggest to close this issue and the similar ones per OPNFV projects. Agree?

**Comment by collivier** [comment]
@fuqiao123 @rabi-abdel @acmacm : No upstream activity for a while. I closed it.
Be free to reopen it if needed.
