### ISSUE TITLE
[RC 1 Dev] Archive all Xtesting logs/artifacts as last CI jobs

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#512]
Xtesting eases the whole verification/validation/process because it unifies the test execution and the artifacts/results publication.
It avoids a wrong model where one software decides to integrate any underlying test framework by proposing all interfaces to be part of the process (one for all or all for one).

The purpose here is to add the final step in the CI process to archive all artifacts.

It's worth mentioning that Functest is already compatible with Xtesting.
http://testresults.opnfv.org/functest/stockholm/

**Comment by collivier** [comment]
functest-smoke-cntt was just created. neutron-tempest-plugin-api is already conformed with the current API section.
https://gerrit.opnfv.org/gerrit/c/functest/+/68668

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
Done
https://build.opnfv.org/ci/job/functest-hunter-zip/3/console
http://artifacts.opnfv.org/functest/9ID39XK47PMZ.zip
