### ISSUE TITLE
[RC 1 VNF] Describe VNF onboarding and testing via Xtesting

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#515]
Xtesting eases onboarding and testing any VNF with the minimal set of requirements.
It only defines the right interface for an easy integration in the CI/CD toolchain whatever the underlying process (proprietary VNFM, opensource orchestrator, application deployment tools, etc.).

It's already in place in Functest for the next 3 VNFs:
- VyOS https://vyos.io/
- Clearwater IMS https://www.projectclearwater.org/
- OpenAirInterface https://www.openairinterface.org/

Deployed via:
- Cloudify https://cloudify.co/
- Heat https://docs.openstack.org/heat/latest/
- Juju https://jaas.ai/openstack

It's worth mentioning that the Functest scenarios buit on top of Xtesting may ease programming all the OpenStack operations. https://functest-api.readthedocs.io/en/latest/apidoc/functest.core.html

**Comment by mf4716** [comment]
Update @collivier ?

**Comment by mf4716** [comment]
Update @collivier ?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier - status?

**Comment by collivier** [comment]
done
