### ISSUE TITLE
[RM Ch05] Clarification of CPU pinning definition

### ISSUE THREAD

**Issue by karinesevilla** [cntt-n/CNTT#521]
Section 5.1.1 Virtual compute, 
nfvi.com.cfg.003, CPU pinning capability
The definition "Binding of a process to a dedicated CPU" doesn't take into account cores and SMT.
It can be changed by:
"Binding a vCPU to either a physical core or a thread of a core with SMT"

**Comment by deebhatia** [comment]
@karinesevilla I can pick this if ok. Also, Is `Binding a vCPU to a dedicated logical core of compute.` better?

**Comment by karinesevilla** [comment]
@deebhatia Following the process, we need to obtain the approval from the WSL before the PR creation. Then we'll be able to propose both definitions and request a vote to select one.

@markshostak  As WSL of RM core, can you assign this issue to Deepanshu and my self for the PR creation?

**Comment by xavier-grall** [comment]
@deebhatia @karinesevilla 
`Binding a vCPU to a dedicated logical core of compute` is a good definition but it would require to define what is a logical core (ie either a physical core on a non-SMT architecture or a thread of a core on a SMT architecture)

**Comment by markshostak** [comment]
Bonjour Karine, Didn't realize you were waiting on me. Happy to have your PR. Thx, -Mark

**Comment by deebhatia** [comment]
> @deebhatia @karinesevilla
> `Binding a vCPU to a dedicated logical core of compute` is a good definition but it would require to define what is a logical core (ie either a physical core on a non-SMT architecture or a thread of a core on a SMT architecture)

@xavier-grall Yeah. then we need to define two terms. As current document is not using `logical core` definition in any of the chapters and using the SMT based wherever required, **+1** to @karinesevilla's definition.

**Comment by karinesevilla** [comment]
@markshostak, @deebhatia @xavier-grall PR on going
