### ISSUE TITLE
[RA2 Ops] Chapter 6 initial content

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#530]
As a precursor to #433 we need some initial content.

**Comment by msidana** [comment]
Can I work on this ?
https://github.com/cntt-n/CNTT/issues/433#issuecomment-549673666

**Comment by manamsamuel** [comment]
HI @msidana i have prepared some content for this, do you mind if i create a PR for this and we can collaborate on the content? @tomkivlin can you assign this to me so i go ahead and create that PR?

**Comment by msidana** [comment]
@manamsamuel Sure.

**Comment by tomkivlin** [comment]
@samulikuusela I've assigned you to this now.

**Comment by manamsamuel** [comment]
@tomkivlin great. Thanks, will start copying the content across.
