### ISSUE TITLE
[RM Ch02] PCRF should not be classified as a 'basic' VNF

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#536]
PCRF is often required to have aggressive latency targets.  As such, a 'basic' flavour with significant overbooking (up to 4:1 possible) cannot provide the infrastructure necessary to meet those requirements.  

In the current context of profiles, the best choice for NFVI profile for PCRF is thus probably the Compute Intensive profile.  Examples and documents should be updated to reflect this.

**Comment by xavier-grall** [comment]
@kedmison 
Would you have a VNF example which can replace PCRF for basic profile ?
According to the text, it should be "Control plane functions without specific need, and management plane functions", and possible mobile network control plane functions may be the following :
    3GPP AAA: Authentication, Authorization, and Accounting
    OCS: Online Charging system
    OFCS: OFfline Charging System
    HSS: Home Subscriber Server
    DRA: Diameter Routing Agent
    HLR: Home Location Register

**Comment by pgoyal01** [comment]
@xavier-grall IMHO, HSS, HLR and DRA have significant performance requirements and may not be best suited for the Basic profile.

**Comment by kedmison** [comment]
Offline Charging System is a good candidate.  PCRF is triggered, for example, at attach or at VoLTE call setup, so the latency hit from CPU over-booking is undesirable.

**Comment by xavier-grall** [comment]
@kedmison @pgoyal01 
OK for OFCS, I can close PR #531 and create a new PR for that: opinion ?

Beyond that comment, imho, we should not consider the the entire VNF for the infra profile mapping, but rather the VNFC types. For example, the basic profile should fit to any VNFC handling the mgmt plane function of any VNF.
With such approach, we could assume that any VNF can be composed of the 3 following types of VNFC which can each be hosted on different infra profiles:
- **Managemant plane VNFC**
applicable to any VNF
=> Basic
- **Control plane VNFC** (possibly including also mgmt plane function):
applicable to any control or data plane VNF 
=> Basic or CI (depending on VNF control plane perf requirement) 
- **Data plane VNFC** (possibly including also mgmt and/or control plane function):
applicable to any data plane VNF
=> CI or NI (depending on VNF data plane perf requirement)

Opinion ?

**Comment by ASawwaf** [comment]
@xavier-grall , we have agreed before on this and we came up with General=Basic, Control=CPU intensive and Data  = Network-intensive

**Comment by xavier-grall** [comment]
@ASawwaf @kedmison @pgoyal01 
OK, here is a proposal for including that issue and replacing (my) PR #531:
https://github.com/cntt-n/CNTT/blob/xavier-grall-patch-ch02/doc/ref_model/chapters/chapter02.md
with the diff:
https://github.com/cntt-n/CNTT/compare/xavier-grall-patch-ch02
if you approve, I create the PR.

**Comment by ASawwaf** [comment]
@xavier-grall , sure, please  . the diagram should be updated ( i tried before )

**Comment by xavier-grall** [comment]
PR #555 created

**Comment by pgoyal01** [comment]
@xavier-grall One observation:
_**Network Intensive**: VNFCs that perform network and compute intensive operations with high throughput and low latency requirements.
- **Compute Intensive**: VNFCs that perform compute intensive operations.
should the latter be qualified "VNFCs that perform compute intensive operations but do not have  high network throughput and low latency requirements."

**Comment by xavier-grall** [comment]
@pgoyal01 look at this:
https://github.com/cntt-n/CNTT/blob/xavier-grall-patch-ch02/doc/ref_model/chapters/chapter02.md#2.3
ok ?

**Comment by pgoyal01** [comment]
@xavier-grall Thanks -- looks great

**Comment by xavier-grall** [comment]
PR #555 merged
