### ISSUE TITLE
[RI1 Ch04] Lab Hardware Specification

### ISSUE THREAD

**Issue by lylavoie** [cntt-n/CNTT#564]
We need to finalize the hardware roadmap and specification for RI 1, so labs can acquire and setup hardware.  To facilitate this discussion, a wiki page has been created here: https://wiki.opnfv.org/display/pharos/CNTT+RI+Lab+Infrastructure+Discussion, along with a set of proposals / agreements for the "labs release 1", i.e. what is included in the RI 1 specification materials.

**Comment by lylavoie** [comment]
@rabi-abdel Can you apply the right RI1 labels to this, I don't have write access, so I can't add labels...Thanks

**Comment by rabiabdel** [comment]
> @rabi-abdel Can you apply the right RI1 labels to this, I don't have write access, so I can't add labels...Thanks

invite to you on it's way so you can do it in the future

**Comment by mf4716** [comment]
RI Ch4 is reserved for Lab Requirements - we can tie the discussion/disposition to this chapter.  https://cntt-n.github.io/CNTT/doc/ref_impl/cntt-ri (RI)

**Comment by mf4716** [comment]
@lylavoie - can we get an update?

**Comment by lylavoie** [comment]
@mf4716 This issue should have been closed / resolved by #654, so I'm closing this.
