### ISSUE TITLE
[RM] Terminology update with RA2 terms / definitions

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#569]
Affected page: https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/glossary.md#1.1

New / duplicate terms/definitions: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter01.md#1.2

There are some terms (e.g. "container") where the definitions don't match.  I will prepare a PR to the RM Glossary to propose changes based on the definitions we've made in RA2 (these are based on Kubernetes glossary).  The PR will also include removing those same terms from the RA2 chapter (as they aren't needed again).

**Comment by ulikleber** [comment]
Started on it.
