### ISSUE TITLE
[RC 1 Dev] Add Neutron QoS and Trunk services/extensions in Compliance

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#575]
The next PR about API asks to cover Neutron QoS and Trunk in compliance (functest-smoke-cntt)
#463

Tests regex and count have to be updated to match the new Neutron extension list.
https://git.opnfv.org/functest/commit/docker/smoke-cntt/testcases.yaml?h=stable/hunter&id=610ce4634e454a2295dbb957cf10b9d7e4a1d928

**Comment by collivier** [comment]
https://gerrit.opnfv.org/gerrit/c/functest/+/68852

**Comment by mf4716** [comment]
@collivier - hi, this is quite old.  Can we get an update please?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@collivier - status?

**Comment by mf4716** [comment]
@collivier - PR #463 is closed.  Can this issue be closed?

**Comment by collivier** [comment]
done
