### ISSUE TITLE
[RM Ops ] Ch09 LCM : Define of Generic installer 

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#586]
we need to start the definition/requirements of the Generic installer that we will be defined in RM and to be used to deploy RA01 and RA02

**Comment by ASawwaf** [comment]
Just start 
1-The installer must be capable to deploy all Virtualizated, Containerized, Baremetal environment

**Comment by rabi-abdel** [comment]
Isn't this related to RI Core (Installer Requirements)?

**Comment by karinesevilla** [comment]
@ASawwaf 
In my opinion, the right place to describe installer is the RI.
We can mention installers in RA, but in a light mode without putting strong constraints or being prescriptive.

**Comment by ASawwaf** [comment]
@karinesevilla 
let work on the below approach 


from Rabi
May I propose to initiate the content for RM Chapter 09 as a new PR against the issue: https://github.com/cntt-n/CNTT/issues/365 with the requirement you have in mind.

Once that PR is created, we can decide then what to keep in RM and what to keep in  RI. 

I agree with you that requirement (from LCM prospective)  needs to stay in RM.

**Comment by walterkozlowski** [comment]
Generic installer moved to RI-1 and RI-2, so no need to discuss it in RM
