### ISSUE TITLE
[RI 1 Labs] Intel Pod-10 Status and Ongoing Works

### ISSUE THREAD

**Issue by opensource-tnbt** [cntt-n/CNTT#591]
**Outstanding**:
1. Enable SRIOV on Pod-10 and Redeploy:  Patch Submitted on Nov-9th: 
   https://gerrit.opnfv.org/gerrit/#/c/airship/+/68815/ . Once the patch is merged, redeploy will be performed.
2. Deploy script in opnfv-airship to be generic - use the same script to deploy all pods. Work in Progress.
   Patch Submitted: https://gerrit.opnfv.org/gerrit/#/c/airship/+/68816/ 
3. Manual/Automatic Validation against Requirements Specification: Waiting for requirements.
4. Pod10 Access issues - Endpoints Failures. Troubleshoot with the help of Greg Oberfield/Cedric/Kaspars 
5. Jenkins-CI failure/issue in opnfv-airship. 

Airship Treasuremap for Pod10: https://github.com/opnfv/airship/tree/master/site/intel-pod10

**Comment by mf4716** [comment]
@rrajesh70 , @opensource-tnbt (Sridhar) - can we get an update?

**Comment by mf4716** [comment]
status?

**Comment by jayacha** [comment]
@opensource-tnbt  any further status or can this issue be closed?

**Comment by jayacha** [comment]
Team Ok to close
