### ISSUE TITLE
[RC 1 Dev] Add tempest_cinder in compliance

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#593]
The new tempest_cinder regex in compliance should conform with the last CNTT updates:
https://github.com/cntt-n/CNTT/pull/577

@rabi-abdel : + testing if I can close it via gerrit merge

**Comment by collivier** [comment]
Ok It seems working. Here I think it's not autmoatically closed because it was already merged in our default Functest branch (master) but can see here all backports in Jerma and Iruya.
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

It works thanks to the OPNFV Github mirror.

**Comment by mf4716** [comment]
@collivier - are you closing, or more work to do, or documentation to be added to CNTT repos?

**Comment by rabi-abdel** [comment]
It seems to me this should be closed. @mf4716 feel free to close as I see the PR it refers to has been merged.

**Comment by mf4716** [comment]
Yes, confirmed with @collivier  that we can closed @rabi-abdel .  Closing.
