### ISSUE TITLE
[RC1 Ch01] Introduction

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#594]
Introduction content for Ref Cert 1.

Content to include, but not limited to:
- Goals and Objectives of a C&V program
- Principles which govern C&V decisions, and operations
- LCM for C&V framework for NFVI
- Establish goals to Ensure Platform Stability, Operability, & Performance for target RAs
- Definitions used for Certification

**Comment by mf4716** [comment]
Adding @arunkandappan , additional team member to assist with the creation writing of Introduction content for RC1 Ch01.

**Comment by mf4716** [comment]
PR has been issued - https://github.com/cntt-n/CNTT/pull/658.  

Pending reviews/approvals.  

This is initial content and work in progress.  Includes, but not limited to the following Ch 1 sections, with progress being made on some;

- Synopsis
- Introduction
- Principles & Guidelines
- Goals & Objectives
- Best Practices
- Verification methodologies
- Assumptions & Dependencies
- Results Collation & Presentation
- Measurements, Monitoring
- Governance
- Resources & References

**Comment by mkr1481** [comment]
Hi Rajesh,
I have approved #658

**Comment by mf4716** [comment]
@gkunz - please review, as this may be dup of [460](https://github.com/cntt-n/CNTT/issues/460)

**Comment by mf4716** [comment]
@gkunz - please review, as this may be dup of 460

**Comment by mf4716** [comment]
status?  @gkunz

**Comment by mf4716** [comment]
@rrajesh70 @gkunz @mkr1481 - status?

**Comment by mf4716** [comment]
@rrajesh70 @gkunz @mkr1481 - status?

**Comment by mf4716** [comment]
@rrajesh70 @gkunz @mkr1481 - can this be closed?  No open PR, and there is content available. [ RC Ch1 - link](https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter01.md)

**Comment by gkunz** [comment]
@mf4716 can be closed as a clean-up measure for the release.
