### ISSUE TITLE
[RM Ch07] Modifications to Section 7.10.4

### ISSUE THREAD

**Issue by glimonta** [cntt-n/CNTT#597]
After discussion on Nov 14th, we agreed to rewrite parts of this section to better describe the behaviour of the TPM when taking boot time integrity measurements.

@CsatariGergely I'll create a PR for this.

**Comment by glimonta** [comment]
I'll work on this issue.

**Comment by CsatariGergely** [comment]
#618 fixed this, I think we can close this issue.

**Comment by kedmison** [comment]
Agreed.
