### ISSUE TITLE
[RM Ch07] Add new section 7.10.5 on Runtime Integrity Measurements

### ISSUE THREAD

**Issue by glimonta** [cntt-n/CNTT#598]
After discussion on Nov 14th, we agreed to add a new subsection that addresses the runtime integrity measurements that can be taken in a platform using the TPM.

@CsatariGergely  I'll create a PR for this.

**Comment by glimonta** [comment]
I'll work on this issue.

**Comment by CsatariGergely** [comment]
#618 fixed this, I think we can close this issue.
