### ISSUE TITLE
[RA1 RA2] Describe relationship of RA2 with underlying infrastructures

### ISSUE THREAD

**Issue by peterwoerndle** [cntt-n/CNTT#600]
This is a follow up from the RA2 Core call on 2019-11-14 on issue #565 . The request was to extend the proposed text with examples which kind of functionality Kubernetes may expect from the underlying infrastructure and by what means Kubernetes can integrate directly with the infrastructure it is running on.

Examples for resources or capabilities of the underlying infrastructure consumed by Kubernetes are, but are not limited to:

- storage (ephemeral/persistent)
- connectivity
- compute

Kubernetes uses a plugin-based mechanism for integration with any type of infrastructure resource providers. Most prominently [Kubernetes Cloud Provider](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/) collect various integrations towards a particular infrastructure platform e.g. to create volumes or additional worker nodes. The [Kubernetes cluster api](https://github.com/kubernetes-sigs/cluster-api) harmonizes some of the k8s cluster management related integrations with different infrastructure platforms under a common API. With the Container Network Interface (CNI) and the Container Storage Interface (CSI) specifications Kubernetes also provides additional means to integrate with the underlying infrastructure. (Note: the use of CNIs or CSIs does not imply the use of specific platform resources.)

With regards to the relation between RA2 and any other infrastructure (including RA1) we should state as part of RA2 that the implementation of RA2 may require resources from the underlying infrastructure. RA2 can integrate directly with the infrastructure using the above mentioned mechanisms.

We could then also try to simplify the existing figure in the [RA readme](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/README.md) to reflect only the interaction mechanisms between RA2 and any underlying infrastructure including RA1.

**Comment by tomkivlin** [comment]
@peterwoerndle thanks for starting this. In general I like the way you're taking this. And definitely support your simplifying the diagram! 👍

**Comment by tomkivlin** [comment]
@peterwoerndle have you managed to create a branch and raise a PR for this?

**Comment by peterwoerndle** [comment]
@tomkivlin didn't know that I should create a PR right away. Will do that asap.
