### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **should** consist of stateless service components. However, where state is required it must be kept external to the component.

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#603]
What about, e.g., etcd?

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

The requirements reads more as one for the workloads. The internal implementation architecture does not need to follow the same principles on all layers.

_Originally posted by @hdamker in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by hdamker** [comment]
@tomkivlin: from my perspective this requirement is not needed (as it describes the internal implementation).  Therefore my proposal would be to fix it by deleting the (commented) requirement from chapter 02.

**Comment by tomkivlin** [comment]
Agreed to remove.

**Comment by tomkivlin** [comment]
Resolved in #1124
