### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **should** include industry standard hardware management systems at both HW device level (embedded) and HW platform level (external to device).

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#604]
Unclear why this is in a Kubernetes RA? Shouldn't that be abstracted from the infra (i.e. agnostic whether it runs on physical or virtual resources) and modular (i.e. allowing customers to rely on existing HW management methods, rather than prescribing these or even making them integrated)?

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by xmulligan** [comment]
Looking through the thread above, it seems the issue was resolved with `req.inf.vir.01` and `req.inf.phy.01`
@tomkivlin I think we can close this issue now

**Comment by tomkivlin** [comment]
@xmulligan agreed.  I don't think we need this one.
