### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **must** support scheduling of workloads based on Enhanced Platform Awareness (EPA) features such as CPU Pinning, huge-pages and SR-IOV.

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#609]
EPA is a marketing buzzword and a white canvas; the set of features varies depending who and when you ask. It'd be better to remove EPA and explicitly list the complete set of required features.

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by ASawwaf** [comment]
@tomkivlin 
we opened this for the same https://github.com/cntt-n/CNTT/issues/592 
so what did you think, we need to close one of them

**Comment by tomkivlin** [comment]
> @tomkivlin
> we opened this for the same #592
> so what did you think, we need to close one of them

Could do, I read #592 as a terminology / definition one (I.e. add something to the glossary). Whereas this is about the validity of the requirement wording. Have I got that right?

**Comment by ASawwaf** [comment]
@tomkivlin , may be :) , but as per my understanding that your recommendation @tomkivlin @CsatariGergely  that we did not want to have one definition for it and we leave it to the context of the clauses 

if not, let me put a generic definition to EPA to be added terminology /definition?

what do u think ?

**Comment by tomkivlin** [comment]
I think a definition in the glossary would be helpful for future conversations about EPA. However I think that the requirements chapter should list the individual "features" of EPA as separate requirements, rather than stating EPA as a whole is a requirement.  That way we can have clearer and more granular traceability for each one.  Is that ok?

**Comment by ASawwaf** [comment]
Agreed, thx

**Comment by tomkivlin** [comment]
I am going to create a PR to remove this requirement and close this issue.  There is a requirement that has been added that covers all of this:

req.gen.ref.01 | Model | The Architecture must support the Reference Model defined profiles (instance types: Basic and Network Intensive).
-- | -- | --
