### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **must** include kubernetes artefacts (e.g., images, Helm charts, etc.) repository capabilities.

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#610]
Unspecific and open-ended. If a Kubernetes platform supported VM workloads, would this also include qcow2 images? What if the platform had integrated management of the host OS, would it then also include RPMs? Raw disk images? ostrees? Kubernetes Operators?

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by xmulligan** [comment]
I think this is the same as #1108 and will be solved with #1109 
@tomkivlin can we close this issue?

**Comment by tomkivlin** [comment]
@xmulligan yes, I think it can.  Will close now.
