### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **must** support workload resiliency

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#613]
It's the responsibility of workloads to be resilient by using the primitives and behavioral contracts provided by Kubernetes.

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by tomkivlin** [comment]
GC/PW/YW: enable instead of support.
Need more info on what sort of resiliency.
Describe underlying services and how they enable workloads to be resilient.
PW: should state what the parameters of native k8s features are.
PW: preference is to describe what the infra/platform is offering. ReplicaSet parameters (container restart) - definable and testable.

**Comment by petorre** [comment]
(Sorry if this was resolved some other way and not updated here.)
"Enable workloads to be resilient" is also tricky if going beyond default Kubernetes functionality and practices mentioned in #616 . If removed there, then can also close this issue here.
