### ISSUE TITLE
[RA2 Core] Requirements: The Architecture **must** provide Control API endpoints to cloud platform core services.

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#614]
Open-ended. What is the set of core services this refers to?

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

**Comment by tomkivlin** [comment]
Tweak to make the requirement about the robustness and cleanliness of the APIs being offered.

**Comment by tomkivlin** [comment]
ALso remove reference to 'cloud platform'.

**Comment by tomkivlin** [comment]
Closed as I think this is covered by the following requirements:


```
req.gen.cnt.04 | Cloud nativeness | The Architecture must run conformant Kubernetes as defined by the CNCF.
req.int.api.02 | API | The Architecture must leverage the Kubernetes APIs to discover and declaratively manage compute (NFVI and bare metal resources), network, and storage.
```

The first ensures the Kubernetes used has a CNCF conformant API, and the second ensures all resources are managed through that API.

**Comment by tomkivlin** [comment]
Sorry, re-opened as a commented-out line needs removing from chapter02.md.

**Comment by petorre** [comment]
I don't know the full context of this but it might also mean Platform Services beyond Kubernetes, which are non-differentiating for vendors and bring fragmentation to CommSPs. There was another issue on that which I cannot find now.
