### ISSUE TITLE
[RA-1 Ch03] 3.3.4. Flavour management (i.e. T-Shirt type) | Need Content

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#635]
[RA-1 Ch03] 3.3.4. Flavour management (i.e. T-Shirt type) | Need Content

**Comment by pgoyal01** [comment]
[RA-1 Ch03] 3.3.4. Flavour management (i.e. T-Shirt type) | Need Content

**Comment by msidana** [comment]
Can I assign this to myself and work on it, if it's already not taken by anyone ?
