### ISSUE TITLE
[RA2 Core] Requirement: Architecture should support service function chaining

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#639]
[RA2 Core] Requirement: Architecture should support service function chaining -- requires a separate discussion.

**Comment by tomkivlin** [comment]
Hi @pgoyal01 - this has been open for a while with no discussion.  Do you think it is needed, or should we raise a PR to remove?  For me, the requirement is a bit ambiguous as-written and should either be decomposed into more specific requirements dealing with the individual components of "service chaining" or we remove and add in requirements if needed that aren't already dealt with by existing API, orchestration or networking requirements listed.  Sound ok?

**Comment by pgoyal01** [comment]
@tomkivlin This issue was opened during one of the requirement review sessions. This was never implemented in the RA-2 Requirements. 

At some point, "2.2.4 Instance Capabilities Mapping" was added to RA-2 and it has "nfvi.net.cfg.005 SFC Support."  The current RM [4.2.5 Instance Capabilities Mapping](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4.2.5) doesn't mention SFC but [5.1.3 Virtual Networking](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#513-virtual-networking) does.

BTW RA-2 Ch02, Section 2.2.4 has more entries than the current RM 4.2.5.

**Comment by tomkivlin** [comment]
> BTW RA-2 Ch02, Section 2.2.4 has more entries than the current RM 4.2.5.

Interesting, feels like we need a better way to manage the traceability - will include in #1137.

**Comment by tomkivlin** [comment]
> At some point, "2.2.4 Instance Capabilities Mapping" was added to RA-2 and it has "nfvi.net.cfg.005 SFC Support." The current RM [4.2.5 Instance Capabilities Mapping](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md#4.2.5) doesn't mention SFC but [5.1.3 Virtual Networking](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md#513-virtual-networking) does.

OK, understood thanks.  What I don't understand is, what are the requirements on the infrastructure to support SFC, other than the networking requirements already listed (perhaps with some new ones) and an orchestration requirement (which isn't in scope of CNTT)?

Meaning - what the capabilities needed by an architecture to support SFC?  I may be misunderstanding but SFC is the orchestration of multiple network functions to create a service.  So the SFC requirement is a layer above the infrastructure and even the workloads, isn't it? It's an NFVO requirement, I think?

**Comment by ulikleber** [comment]
Agree. I don't think this brings any additional value. Let's close.

**Comment by tomkivlin** [comment]
Agreed to close on weekly meeting.
