### ISSUE TITLE
[RA2 Core] Requirements: | req.inf.ntw.13 | Network | The Architecture should support IPv6 for Kubernetes workloads.

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#640]
> | req.inf.ntw.13 | Network | The Architecture should support IPv6 for Kubernetes workloads. |
Either to be changed to "must" or to be put into backlog

From @hdamker in https://github.com/cntt-n/CNTT/pull/452#pullrequestreview-318646455.

**Comment by xmulligan** [comment]
solved with #1010
