### ISSUE TITLE
[RA2 Core] Requirements: compliance to national and regional security requirements

### ISSUE THREAD

**Issue by kedmison** [cntt-n/CNTT#649]
There is an unresolved discussion in https://github.com/cntt-n/CNTT/pull/452 relating to security requirements.  Specifically, on the following security requirements.

| `req.sec.cmp.01` | Compliance | The Architecture **must** comply with all applicable national standards and regulations. |
| `req.sec.cmp.02` | Compliance | The Architecture **must** comply with all applicable regional standards and regulations. |

@msidana said  
[Isn't this an open-ended requirement all applicable standards and regulations. ?](https://github.com/cntt-n/CNTT/pull/452?#discussion_r344483243)

@kedmison said
[I am concerned that this is still not a testable requirement. What would the explicit list of applicable national requirements be? What would the list of applicable regional standards? Can we instead cite directly the applicable standards, as we know them, so that the validation/verification teams know which ones to test against?](https://github.com/cntt-n/CNTT/pull/452?#discussion_r346102841)

**Comment by pgoyal01** [comment]
@msidana @kedmison Is the ask that we list all security standards by all nations (200+) and regions (US States, EU, etc.)? Even within the EU, member countries have their own cyber and data security agencies rendering requirements. In the US many states (e.g., California) have laws in this area. Listing all "applicable standards" by each country would be difficult. 

Can we specify ISO 27001 as a base requirement for testing (as was previously the case), and with testing for national/regional standards being beyond the scope of the CNTT effort.  FYI, ISO 27001 is a commonly referenced standard including by the EU's ENISA.

**Comment by msidana** [comment]
@pgoyal01 Yes, we cannot do this - listing regional/national policies. I think we shouldn't be writing about ISO standards , PCI DSS etc as these are mostly driven by business and regulatory requirements. However, we can write security requirements considering below points(suggestions welcome) which are verifiable via automation/manual checks:
1. The operating system should be hardened as per STIG guidelines.
2. API communication should be secured via HTTPS, TLS etc.
3. Multi factor authentication
4. RBAC managed access
5. Credentials rotation 
6. Some means for isolation of untrusted workloads
7. Securing workloads
8. Audit logging etc.

**Comment by kedmison** [comment]
Completely agree with @msidana in that the initial requirement text was too broad, and we just couldn't actually list all the relevant national/regional standards.  What I had thought we might be able to do was to find a few relevant standards that are already written (not business-sector-based like PCI DSS, but perhaps something already exists, rather than creating, in effect, a new security standard by generating our own list of requirements.

**Comment by pgoyal01** [comment]
To specify the RA-1 Security requirements, an attempt is underway to define the RM Security requirements (RM Ch07). These requirements will be subject to everyone's review once they are add to the RM chapter 07. Once the RM security requirements are agreed upon, we can revisit the RA-1 and RA-2 requirements.

**Comment by tomkivlin** [comment]
As mentioned above, we need testable requirements, or at least requirements that can be delivered by testable architecture specifications.  Given that existing standards (e.g. CIS benchmarks) will generally already come with test specifications, I would rather a set of requirements that refer to those existing standards and then the RC2 work is to combine existing tests, not creating new ones.
I'm going to close this issue, we can open more specific and deliverable ones as needed.
