### ISSUE TITLE
[RM Ch05] Remove SR-IOV notes

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#652]
As spotted by @ASawwaf we need to remove reference to SR-IOV in the RM to remove confusion. 
e.g. 

nfvi.net.acc.cfg.002 | Support of HW offload | Yes/No | e.g. support of SR-IOV, SmartNic.
-- | -- | -- | --

and 

SR-IOV (Single-Root Input/Output Virtualisation): Configure PCIe ports to support SR-IOV.

**Comment by rabi-abdel** [comment]
happy to get this assigned to me @karinesevilla

**Comment by pgoyal01** [comment]
@rabi-abdel @ASawwaf SR-IOV has been discussed at great length in the RA-2 Ch02 discussion and has been pointed out by several folks it is a "must" requirement. 

I do not agree on the deletion of SR-IOV -- in the RM its support is optional and should remain so.

**Comment by rabi-abdel** [comment]
@pgoyal01 there is no SR-IOV support agreed on RM. our decision on RA-1 Ch02 was to let operators decide if they would allow SR-IOV but the CNTT is Clearly staying it "Should not be used" and there will be no support for it on CNTT. 

Currently, the few sentences in RM it is confusing everybody and I think this needs to be cleared out.

**Comment by pgoyal01** [comment]
@rabi-abdel I am only asking that SR-IOV should remain as an option for operators. If the language needs to be modified to make things clearer that is for good but object to "... we need to **remove reference to SR-IOV in the RM** ."

**Comment by rabi-abdel** [comment]
@pgoyal01 keeping SR-IOV reference in the RM won't solve your problem. it will just complicate it and cause confusion. keeping those reference doesn't make it optional. hence my proposal is to remove it.

**Comment by karinesevilla** [comment]
@rabi-abdel @ASawwaf @pgoyal01 
For short term deployment SR-IOV is used and required by VNF needing network acceleration. May be in the future, it will be replaced by smartNIC, but today we must keep it.
In my opinion, what is not recommended by CNTT (because coming against resources sharing  principle) is the configuration of SR-IOV with PCIe passthrough. I think that was discussed some months ago, but the notion of PCIe passthrough disappeared. When SR-IOV is used with VF, one NIC isn't dedicated to a VNF.

**Comment by rabiabdel** [comment]
> @rabi-abdel @ASawwaf @pgoyal01
> For short term deployment SR-IOV is used and required by VNF needing network acceleration. May be in the future, it will be replaced by smartNIC, but today we must keep it.
> In my opinion, what is not recommended by CNTT (because coming against resources sharing principle) is the configuration of SR-IOV with PCIe passthrough. I think that was discussed some months ago, but the notion of PCIe passthrough disappeared. When SR-IOV is used with VF, one NIC isn't dedicated to a VNF.

@karinesevilla fair enough. Will close for now.

**Comment by ASawwaf** [comment]
> > @rabi-abdel @ASawwaf @pgoyal01
> > For short term deployment SR-IOV is used and required by VNF needing network acceleration. May be in the future, it will be replaced by smartNIC, but today we must keep it.
> > In my opinion, what is not recommended by CNTT (because coming against resources sharing principle) is the configuration of SR-IOV with PCIe passthrough. I think that was discussed some months ago, but the notion of PCIe passthrough disappeared. When SR-IOV is used with VF, one NIC isn't dedicated to a VNF.
> 
> @karinesevilla fair enough. Will close for now.

@pgoyal01 it is my bad , 
@rabi-abdel ,sorry what is the conclusion ?
@rabi-abdel @kagreenwell @pgoyal01 @petorre , From my side I will push big time to avoid the SRIOV in CNTT , ( It is against of CNTT principle and targets ) the target to push on the vendor to achieve what we looking for ,   if there is doubt that we need to accept  it in RA1 , for RA2 no way to accept it , how to have CNF with SRIOV  we are contradicting ourself

**Comment by rabi-abdel** [comment]
agree @ASawwaf 100%. we must not promote it in any way. I still think we need to remove the references from RM. if you agree, I am happy to create a pull request to do this.

**Comment by ASawwaf** [comment]
@rabi-abdel Totally agreed

**Comment by kagreenwell** [comment]
I completely agree that CNTT should not push specific technology, but I don't know how you are going to square this in the RI/RC. If you want to test anything that is not GP (general performance), you are going to have to implement specific technologies and build test cases that validate those technologies. Are you suggesting pushing SRIOV/DPDK/other-technologies out of just the RM and into the RA, RI, RC, whateveR?

**Comment by ASawwaf** [comment]
@kagreenwell , Actually not all technology , Just SRIOV , we need to avoid it as much as we can , and build our RM / RAs / RI /RC without SRIOV


@pgoyal01 @karinesevilla  , if you think about it ( SRIOV ) doesn't make any sense to push the vendor to test it on our RI/RC as we know the result from now that all vendor will achieve line rate throughput on SRIOV NICs

**Comment by rabi-abdel** [comment]
@markshostak sorry, I just realised Ch05 is RM Core not RM OPs.

**Comment by rabi-abdel** [comment]
> I completely agree that CNTT should not push specific technology, but I don't know how you are going to square this in the RI/RC. If you want to test anything that is not GP (general performance), you are going to have to implement specific technologies and build test cases that validate those technologies. Are you suggesting pushing SRIOV/DPDK/other-technologies out of just the RM and into the RA, RI, RC, whateveR?

what CNTT is against is SR-IOV Pass Through. it is OK for NFVI to enumerate SR-IOV but not to pass SR-IOV VF to workload bypassing the hypervisor because that will defeat the whole point.

**Comment by xavier-grall** [comment]
I guess sriov issue is about nic-specific driver (and not only virtio) which must be implemented in vnfc, thus loosing the hardware abstraction, and that seems a quite relevant reason.
Consequently, for providing vnfc with high throughput and/or low latency, only 2 solutions are currently available: dpdk and virtio-compliant smartnic.
What should we consider for a first step ? dpdk vswitch only (very cpu & energy consumer)? virtio-compliant smartmic (quite rare) ? non-virtio smartnic with dpdk-based adaptation (quite complex) ?

**Comment by markshostak** [comment]
@rabi-abdel, @ASawwaf, all,
I think we need to clarify what we're debating, so, two points:

1) Reminder: Please be sure to include your rationale when asserting you believe something should be in or out or this or that. That way we are all debating the same explicit concerns/merits, and not the issue we _think_ everyone is else is debating.

2) Is "SR-IOV Pass Through" a PCI-SIG standard? AFAIK, there is SR-IOV and there is PCI Pass Through, but those two are mutually exclusive, so it's unclear to me if we're conflating the two, and I want to make sure I'm on the same page. Does someone have a link to this technology?

Thanks,
-Mark

**Comment by xavier-grall** [comment]
@markshostak 
The discussion is now in PR #653 
SR-IOV is a PCI-SIG specification enabling to share a single PCI device as multiple virtual PCI devices named Virtual Functions (VFs).
PCI passthrough is a way for providing a VM with direct access to a PCI device without passing by the hypervisor, it can be a physical PCI device or a virtual PCI device (ie a SR-IOV VF).
The discussion is about PCI passthrough, especially for SR-IOV VF, and "SR-IOV passthrough" is a short name for it.

**Comment by rabi-abdel** [comment]
> I completely agree that CNTT should not push specific technology, but I don't know how you are going to square this in the RI/RC. If you want to test anything that is not GP (general performance), you are going to have to implement specific technologies and build test cases that validate those technologies. Are you suggesting pushing SRIOV/DPDK/other-technologies out of just the RM and into the RA, RI, RC, whateveR?

@kagreenwell great question. here are few points:
- CNTT is not opposing to SR-IOV as a technology. it is opposing to expose hardware details (via Pass-Through) into workloads which will break the abstraction.
- Performance can be achieved by:
    - SmartNICs (by leveraging SR-IOV but still exposing virtio interfaces into workloads).
    - OVS DPDK in the host.
    - any other mechanism that doesn't break the abstraction.

**Comment by kedmison** [comment]
At the present time, I do not concur with the removal of SR-IOV.  From what I can see, it is a commonly used technology, and I don't know enough about the proposed alternative technologies to know if they are completely capable of filling the gap.  Thus, I think that VNF vendors should be able to weigh in on this.  I'll also comment in pr #653.

**Comment by markshostak** [comment]
> 
>  
> @rabi-abdel wrote: here are few points:
> 
>     * CNTT is not opposing to SR-IOV as a technology. it is opposing to expose hardware details (via Pass-Through) into workloads which will break the abstraction.
> 
>     * Performance can be achieved by:
>       
>       * SmartNICs (by leveraging SR-IOV but still exposing virtio interfaces into workloads).
>       * OVS DPDK in the host.
>       * any other mechanism that doesn't break the abstraction.

There's a business factor here, it's not purely technical. Assuming the above alternatives give us comparable performance, we also need to be sure to factor the following into our calculus:

* The comparative cost of the alternative solutions for the same performance
* Potential impact on CNTT adoption, if we summarily dismiss SRIOV

I'm still not seeing a cost-neutral alternative to the transitional approach. We may not like it, but so far it looks like the most realistic compromise.
