### ISSUE TITLE
[RM Ch 9] OM&A requirements 

### ISSUE THREAD

**Issue by ASawwaf** [cntt-n/CNTT#663]
@kedmison @trevgc , Gents as per our RM call, we need your support to define the requirements of 
OAM , Assurnace part of NFVi in terms of FM , Logging , Config mgt

**Comment by rabi-abdel** [comment]
@ASawwaf I suggest you go ahead and create a PR for it to start the content creation. the discussion can be moved to the PR which makes it simpler to merge after the discussion is concluded.

**Comment by ASawwaf** [comment]
@rabi-abdel , sure , I did it 
Update chapter09.md #674 

i hope it is the right way to create PR :)

**Comment by rabi-abdel** [comment]
@ASawwaf yes indeed. i just added a line to the PR "Fixes #663" which will automatically close this issue once merged.

**Comment by walterkozlowski** [comment]
Closed with close PR# #674
However, the review may show more contents needed
