### ISSUE TITLE
[RM Glossary] Fix some container related definitions

### ISSUE THREAD

**Issue by ulikleber** [cntt-n/CNTT#664]
Fix the following definitions based on comments to #595 by @pgoyal01:

- **Cloud native Network Function (CNF)**: The last two sentences reference "containers" but container is not previously mentioned. "... run on an application orchestration layer ..." -- do we need "application"?
Typo, last sentence, capitalize "t" in "the containers themselves ... "

- **Container**: OCI defines Conatiner as "An environment for executing processes with configurable isolation and resource limitations. For example, namespaces, resource limits, and mounts are all part of the container environment."
Can we include it as a "Note" say.

- Definition on "container runtime" needed: Something like, "Container runtime reads the configuration files for a container from a directory structure, uses that information to create a container, launches a process inside the container, and performs other lifecycle actions." (adapted from https://github.com/opencontainers/runtime-spec/blob/master/glossary.md).

- **Kubernetes Cluster**: A set of machines, called nodes, that run containerised applications managed by Kubernetes. A cluster has at least one worker node and at least one master node.
In kubernetes, a node is a "worker machine" -- see term "Kubernetes Node" below Please delete "node" from "master node" and also from similar use in "Kubernetes Master."
 
- **Kubernetes Service**: An abstract way to expose an application running on a set of Pods as a network service.
In this definition what is a "network service"? A kubernetes service can be used to expose a database cluster, for example. I believe there was previous discussion on this term including by @CsatariGergely @TamasZsiros

**Comment by rabi-abdel** [comment]
@ulikleber since The glossary file doesn't practically belong to any WS, I have assigned it to you. feel free to go ahead and prepare PR proposing the changes you would like to make.

**Comment by markshostak** [comment]
@ulikleber Hi, Did you want to create a PR for this one? Thanks, -Mark

**Comment by ulikleber** [comment]
Will work on it. Just now travelling.
