### ISSUE TITLE
[Gov Ch08] Recruiting, Engagement, & Adoption

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#680]
**Scope**
Recruit operators & suppliers  to bring diverse perspective and contributions into the community
Drive membership engagement activities to address community resource demands
Engage industry leaders with Common NFVI value proposition to drive adoption rate
Drive adoption roadmap with VNF Vendors

**Comment by jbeltranatl** [comment]
Rabi - what document is this content intended for?
