### ISSUE TITLE
[RM Ch05] Consistency between Figure 5-1 and Figure 5-3

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#682]
Figures [5-1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch05_nfvi_layers_sw_profile.PNG) and [5-3](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/RM_chap5_fig_5_3_SW_profile.png) both refer to "NFVI Software Profile" but differently.

**Comment by markshostak** [comment]
Fixed by PR #712, pending review.
