### ISSUE TITLE
[RA-1 Ch04] Support for Profiles and T-shirt instance types

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#686]
[RA-1 Ch004] Support for Profiles and T-shirt instance types: content needed on how these instance types will be supported by the Architecture

**Comment by iangardner22** [comment]
So @rabi-abdel we have 

**Basic** - suggest kernel OVS, over-committed vCPU:pCPU, 1:1 RAM?  Do we have multiple sizes within this?
**Compute Intensive** (for MVP I assume we don't need anything more than a specific vCPU / VRAM specfication)
**Network Intensive**  (we aim for DPDK but I know @pgoyal01 proposed we also do SR-IOV)

I suggest we show how using host aggregates, DPDK aware OVS and scheduler hints that this is achieved.   We should also show the threads allocated to DPDK and Hypervisor

**Comment by ASawwaf** [comment]
@iangardner22 , for SRIOV , please refer to #653 

Agree with Basic profile , 

CI : either OVS or OVS+DPDK

NI : I will go with OVS+DPDK

**Comment by pgoyal01** [comment]
PR #744
