### ISSUE TITLE
[RI 1 Dev] Enhance Functest SUT to cover Ceph

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#694]
Functest SUTs need to be compliant with CNTT API section.
They have to switched to ceph as backend and conforms with all features recently added in nova section.

**Comment by collivier** [comment]
Done. The Hunter POD is now compliant with CNTT API.
Here is the full sucess after switching to ceph.
https://build.opnfv.org/ci/view/functest/job/functest-hunter-daily/322/

@pgoyal01 @karinesevilla @rabi-abdel @rabiabdel @mf4716 @fuqiao123

**Comment by mf4716** [comment]
Great work Cedric @collivier !  

Please be sure to include this information in the appropriate RI CNTT documentation.

For convenience, here are the RC1 Dev scope and chapters:

**Scope**
- Covers installers, automation, etc.
- Integration of installers and components.
- Gap analysis with required actions for existing eco-system within LFN/OPNFV community projects

**Chapters**
- Ch07: Integration
- Ch08: Gap analysis & Development
