### ISSUE TITLE
[RM Ch 3] Update Section 3.3 NFVI Management Software

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#716]
[RM Ch 3] Update Section 3.3 NFVI Management Software to be consistent with changes made by @tomkivlin in PR #715 to RM 3.1.

**Comment by ASawwaf** [comment]
@pgoyal01 could you please the update here

**Comment by pgoyal01** [comment]
@ASawwaf I made some changes. PR #1484

Not sure why this was assigned to me.

Ch03 still uses NFVI including where the Figure has been updated to "cloud Infrastructure" but the Figure legend still uses NFVI.
