### ISSUE TITLE
[RM Ch5] How to deal with VM-specific terms and features?

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#727]
A question: including a reference to RM makes it look like everything described there is applicable for RA2. I'm wodering how to handle things like CPU pinning, vswitch optimization, security group support, etc. These things make sense in an OpenStack context, not so much in K8s...

_Originally posted by @TamasZsiros in https://github.com/cntt-n/CNTT/pull/677_

Other examples include "CPU Sockets", "CPU Cores per Socket" etc. Not applicable to containerised workloads (which are allocated CPU time across all CPUs). Feels like there are two options:
1. Re-write RM to be technology agnostic
2. Keep existing things as possible, add container-applicable entries where required

**Comment by tomkivlin** [comment]
More than happy to arrange a call with the RM Core WSLs to discuss.

**Comment by tomkivlin** [comment]
Linked to #359 and associated PR #621

**Comment by CsatariGergely** [comment]
What else is needed on top of #621 and #738 @tomkivlin , @TamasZsiros ?

**Comment by kedmison** [comment]
@tomkivlin, @TamasZsiros can you please take a look to see if anything else is needed?  If nothing is needed we could close this issue in time for the Baldy release.

**Comment by tomkivlin** [comment]
Yes, all good for me.

**Comment by kedmison** [comment]
Closing as this has been addressed through other PRs.
