### ISSUE TITLE
[RA-1 Ch04] Update Ironic writeup

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#734]
Based on Issue #733, we should include a statement in [RA-1] Ch 4 - 4.3.1.7 that "Ironic is currently not invoked directly and hence its APIs will not be specified."

**Comment by iangardner22** [comment]
agree...  if we see a T-shirt size that says "Baremetal" then we review

**Comment by iangardner22** [comment]
But in the RM we don't specify this I assume?

**Comment by pgoyal01** [comment]
PR #743 created.
