### ISSUE TITLE
[RM Glossary] Need definition of "Platform"

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#741]
[RM Glossary] Need definition of "Platform" -- platform is used in many places and it is not always clear as to what is included in the platform.

**Comment by deebhatia** [comment]
@rabi-abdel The `project-bot` is applying the `RA2 Core` project in `Backlog` automatically to all. Can you fix it? It should do a match on based on tag in title if possible.

**Comment by tomkivlin** [comment]
@pgoyal01 does the project tag in this need modifying - not sure it's RA2 Core?

**Comment by pgoyal01** [comment]
@tomkivlin Agree. Changed
