### ISSUE TITLE
[RM Ch-various] Form Principles Related to HW Abstraction and Exposure Thereof

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#746]
This Issue is in support of Issue #731.

Proposes principles to support cloud native workload development by stipulating h/w abstraction, and it's application to higher-level features such as PCI-PT, SRIOV and EPA.

**Comment by pgoyal01** [comment]
project-bot bot added this to Backlog in RA2 Core 1 hour ago -- should RM Core
