### ISSUE TITLE
[RM Ch-0xA] Create VNF Evolution Framework

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#750]
This issue creates a framework to support management of the "evolution" of the CNTT VNF operating environment. As the Infra evolves, its supporting technology will change; CNTT will want to promote adoption of newer technology and potentially deprecate or even expedite deloading of older technology.

The Evolution Framework can potentially be envisioned as a roadmap. The VNF phases, let's call them "A", "B", "C", etc., as they elapse, will synchronously promote and/or deprecate various features/functions/capabilities/etc. These features may be unrelated, except that the timing of their application will be governed by VNF Evolution roadmap. 

The elapsing Evolution phases can then be used to "clock" these features into and out of vogue, within the CNTT context, and ostensibly the CNTT-RC Certification requirements, as well. 

This Issue is an action resulting from the review of, and also supports PR #749 .

**Comment by rabi-abdel** [comment]
@markshostak I am happy to have a stab at this if you assign to me.

**Comment by ASawwaf** [comment]
@markshostak I can support in this as well

**Comment by markshostak** [comment]
@rabi-abdel @ASawwaf @mf4716 After some time to think on it, I'd propose:
- VNF Evolution phases should be identified by a number (1, 2, 3, etc.)
- VNF Evolution phases should be directly tied to CNTT releases. In other words, phases increment explicitly with each CNTT release, as opposed to incrementing based on other criteria, such as by date (i.e. quarter, month or arbitrary date)

I'm thinking the state of various features, capabilities, compromises, etc. can then be tied to the various Phases. For example, support for a given capability could be specified as optional in Phase 1, but become mandatory in Phase 3. This allows suppliers to know that a capability will be required in the future, as well as when.

As Operator upgrades are hard to mandate, I mainly see features becoming mandatory, deprecated, etc. driving the results of RC testing. For example, in the case of NEW capabilities, Capability x for NFVI is identified as optional in Phase 1, but mandatory in Phase 3:
- If an NFVI is submitted to OVP in Phase 1 without Capability x, it will PASS, but produce a "transitional" warning, indicating that Capability x will be required in Phase 3
- If an NFVI is submitted to OVP in Phase 3 without Capability x, it will FAIL

Similarly:
- If a VNF is submitted to OVP in Phase 1 that is dependent on Capability x, it will PASS, but produce a warning that it is using an optional Capability and may not be compatible with all Infra
- If a VNF is submitted to OVP in Phase 3 that is dependent on Capability x, it will simply PASS

In the case of DEPRECATED capabilities, given Capability y for NFVI is identified as tolerated in Phase 1, but prohibited in Phase 3:
- If an NFVI is submitted - there is no impact to RC results for NFVI supporting functionality that is incremental to the specification
- If a VNF is submitted in Phase 1 that is dependent on Capability y, it will PASS, but produce a "transitional" warning, indicating the VNF is using a Capability that will become prohibited in Phase 3
- If a VNF is submitted in Phase 3 that is dependent on Capability y, it will FAIL

Your thoughts?

**Comment by tomkivlin** [comment]
@markshostak does the project tag in this need modifying - not sure it's RA2 Core?

**Comment by markshostak** [comment]
@tomkivlin Hi Tom, Hmm, not the f/b I was hoping to for, but agreed. I've moved it manually. Maybe Funny-Bot was playing a joke on you? We need to check if there's an issue with a rule. @rabi-abdel How do we track this down? Thanks, -Mark

**Comment by tomkivlin** [comment]
@markshostak ha yes sorry. More relevant feedback will appear on monday :-)

It was an issue with the rules I'd created. I can add a wiki entry if it would help, I think I've fixed it now.

**Comment by jbeltranatl** [comment]
Instead of the word "compromise" couple of words most commonly used in the software world are 'exception' (if it leads to a different outcome), or 'alternative' (if it leads to the same outcome but via a different route).

**Comment by tomkivlin** [comment]
As a concept, I think we need this, glad it's happening.

I had been thinking about the wording the past few days.  I think there are a couple of concepts going on here.  

First, there is the transitions, phases, generations - which word do we want to use to describe each step? I don't have a strong opinion on that.

Secondly, there is the compromise, exceptions, etc. wording - I wonder if the terms that [TOGAF use for Architecture Compliance](https://pubs.opengroup.org/architecture/togaf8-doc/arch/chap24.html) would suffice - after all we're not looking to invent some new concept, we're just talking about the compliance status of each phase/generation.
![image](https://user-images.githubusercontent.com/52716470/70621686-107f7900-1c12-11ea-8106-5a60a4965486.png)

For example, the first two phases/generations would be classed as Consistent/Compliant/Conformant with only the final phase/generation being "Fully Conformant". None of them should be classed as Irrelevant or Non-Conformant.

**Comment by pgoyal01** [comment]
@tomkivlin We would need to tweak the TOGAF labels so as not allow, for example, "implementation of features not covered by the specification." I think we are trying to restrict VNFs/CNFs to adhere to the specifications.

We have the ideal specifications and the specifications with exceptions for practical reasons. We will also have RA evolution (e.g., choosing of a new CNTT OpenStack reference release). The "generational" concept can take care of both situations.

**Comment by tomkivlin** [comment]
@pgoyal01 yes absolutely - I hope none of us take TOGAF and adopt it verbatim :) it's there to be tweaked.

**Comment by rabi-abdel** [comment]
Great discussion everybody. I think the framework is more generic than RM and will need to be linked to proper roadmap and strategy. therefore, I suggest to remove confusion.

- focus our efforts into getting the strategy right.
- getting the elements rights and what lives where.

This is one of the items that are still pending on my plate but I started to write it down based on these discussions by @tomkivlin @pgoyal01 @markshostak in here: https://github.com/cntt-n/CNTT/pull/681

may I suggest to focus our efforts and get those right

**Comment by petorre** [comment]
(Like I wrote in other comments) In transitions will help differentiating if VNFs using Exception is optional (typically to run more cost effectively) or mandatory (typically to reach latency requirements).
