### ISSUE TITLE
[RM Ch-A] Codify SRIOV Compromise Language 

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#759]
Language is required to effect a compromise to accommodate the transition from SR-IOV to a Cloud Native technology that offers comparable throughput at a comparable price:performance ratio. 

The solution shall be built on top of the recently introduced CNTT Hardware-Dependent Coding Framework and the VNF Evolution Framework, as well as introduce minor refinements to the frameworks thereof.

**Comment by tomkivlin** [comment]
@markshostak should this be in the RM Core project instead of RA2 Core? Or should the labels be modified?

**Comment by markshostak** [comment]
@tomkivlin Funny-Bot is detecting a pattern... @rabi-abdel ??

**Comment by rabi-abdel** [comment]
> @tomkivlin Funny-Bot is detecting a pattern... @rabi-abdel ??

Yes will fix that.

**Comment by markshostak** [comment]
This issue was addressed by PR 760, which was rolled into PR 731 and merged 9/1/2020. Closing...
