### ISSUE TITLE
[RI 1 Core] CIRV Repo(s) Determination

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#761]
A request has been made to create a CIRV repo, "cirv-perftest" for the containment of artifacts, tools, etc, in support of Perf Test evaluations on POD10.

**Rationale for repo(s):**
The purpose for the repo(s) is twofold:  **First**, utilize the repo for a centralized storage of artifacts (code, tools, descriptor templates (POD, Infra, etc), topology documents, etc), which would be considered to vital to the delivery of the CIRV project and could not easily, or be feasible, to store on Confluence/GitHub/wikis.  **Second**, the repo(s) will be used for OPNFV Release Planning, for direct release consumption and delivery.  

This issue is open to facilitate conversation, and reach consensus on the following:

1. Do we agree to create, or establish CIRV repos at this time?
2. Quantity?
3. Name(s), following normalized syntax?

**Recommendation is:**

- Yes, create CIRV repos.
- Use syntax of "cirv-[purpose]"
- Start with one repo, "cirv-perftest"
- Functional results are stored in the OPNFV Test Database.  
- If we need to create/open a repo for functional, security, performance, resiliency, etc in support of storing and archiving tools, results, analysis, etc, and we're unable to leverage a common OPNFV Test Database, then subsequent repos will be requested/created using similar naming conventions (e.g. cirv-functional, cirv-performance, etc)
- Repos can contain, but not limited to:  Yaml's for Cookbooks, code for stand alone tools for testing/validation, etc

**Comment by mf4716** [comment]
Please review and weigh in: @markshostak , @collivier , @opensource-tnbt (Sridhar), @rrajesh70 

FYI, Assignees/owners: @fuqiao123 @trevgc 

My (Mike F) recommendation is in the Issue Description itself.  i.e. Yes, start with 1, call is cirv-perftest and stick to similar nomenclature in the future.  According to an offline conversation w/ Bin Hu, we understand the CIRV project is entitled to 2 repos, by default.

**Comment by tomkivlin** [comment]
Hi @mf4716 does the project tag for this Issue need changing - not sure this is RA2 Core?

**Comment by mf4716** [comment]
Corrected to RI1-Core.  Thanks @tomkivlin , for letting me know.

**Comment by markshostak** [comment]
@mf4716 
> 
> 
> _A request has been made to create a CIRV repo..._

Can you include a rationale for the requested repo? I agree with your proposal, but we should be documenting these things, not creating them just `cause, even if we all agree it should be done.

>     1. Do we agree to create, or establish CIRV repos at this time?
>      * Yes, create CIRV repos.
MXS> Yes, I support creating CIRV repo(s) at this time.

>     2. Quantity?
MXS> Quantity should be based on defendable need. BTW, who has to approve the creation of yet another repo?

>     3. Name(s), following normalized syntax?

MXS> Yes, definitely.

>     * Use syntax of "cirv-[purpose]"

MXS> Um, "cirv.", I'm good, but I'm thinking we may need another qualifier to scope the repo (see below).

>     * Start with one repo, "cirv-perftest"

I can't tell from this name, if the object under test is the VNF or the NFVI. The subject is applicable to both, but the tools in the repo would likely be much different (i.e. complementary/opposite).

So, perhaps "cirv.vnf.perftest" if the tool will exercise the candidate VNFs, and "cirv.nfvi.perftest" if the tool will exercise the NFVI. Also, this assumes the repos all pertain to the "V" in cirv. If the repo contents pertains to the "I" in cirv, "cirv.ri-_x_.[purpose]", where _x_ reflects the relevant RA.

Here's an additional question for your list: Who will be designated to administrate, or at least approve/merge updates to any given repo? My recommendation: A) person requesting repo, B) CIRV PTL, C) variable delegate.

Note: I prefer "." as the delimiter, so we can use "-x" to identify variants (e.g., RI-1, RI-2, etc.), assuming the repo platform allows these characters in repo names. 

HTH,
-Mark

**Comment by mf4716** [comment]
@markshostak - the description has been updated to include Rationale.  Regarding approval, I was informed we request approval from the OPNFV TSC, with an expectation that two(2) repos can be provided.  Additional repos, if needed, would require additional TSC review and discussion.  I'm confirming repo-name syntax (i.e. using the "." notation), and overall admin/approver.  Will revert back upon receipt of those details.

**Comment by mf4716** [comment]
@markshostak - there's no particular syntax that is required that I've been told, or can find.  See examples in https://git.opnfv.org/.   But, ONAP uses a different style https://git.onap.org/.  Unclear still who is the owner/admin of the repo, so I've asked again.  Re: repo name, it makes logical sense to go with a nomenclature of, "cirv.ri-x.[purpose]", assume we can further define the *purpose* as nfvi, or vnf.  e.g. cirv.ri-1.nfvi.perftest, or something equivalent.  Thoughts?

**Comment by mf4716** [comment]
@markshostak , I shared this in email offline, but Admin/owner of the repo is the Linux Foundation.  Creating directories, changes, file uploads/mgmt, etc, is done by contributors, reviewed by contributors including committers, and approved and merged by committers.  For CIRV, this would be @fuqiao123 (Fu Ciao), and myself.  

@trevgc Trevor, @fuqiao123 Fu Qiao, are you okay with "cirv.ri-01.perftest" as the first repo?  If not, please recommend an alternative(s).

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@lylavoie (Lincoln), per the RI/RC status call, here's the open Issue re: where to Park CIRV tools/code, and recommended syntax for folder/file names.  Please review at your next opportunity.  I'll include a link in our 1/22 meeting minutes for RI/RC.

**Comment by lylavoie** [comment]
I would propose we request the following one repo ("cirv"). Inside the repo we will separate materials via directories, as "intel-pod-10-nfiv-perfest" or "hdv-tooling", "manifest-tooling".  Folders can easily be changed, discussed, and maintained by the PTL and committers. Repo creation comes through TSC for the project, which in this case is cirv.  The request to OPNFV TSC should come from the PTL.  

@mf4716 I believe you are one of the PTLs for CIRV, can you make the ask to OPNFV TSC to approve the creation of the repo. 

The Wiki page (https://wiki.opnfv.org/pages/viewpage.action?pageId=47284396) should also be updated to list the PTL and in the OPNFV project, we should have a few more committers, responsible for review and merging, if there are trusted volunteers, you should nominate them to be put to that status.

**Comment by mf4716** [comment]
I've emailed the OPNFV TSC (1/22/2020), requesting creation of a "CIRV" repo.  Awaiting disposition.  

The CIRV project has the designated PTL listed.  

I will send an email to the list of project contributors, with a nomination of a few trusted volunteers.

**Comment by mf4716** [comment]
Closing.  Two repo's created, and documented on the [CIRV project page](https://wiki.opnfv.org/pages/viewpage.action?pageId=47284396).

1. CIRV:  https://gerrit.opnfv.org/gerrit/admin/repos/cirv - main(primary) repo
2. CIRV_Spirent: https://gerrit.opnfv.org/gerrit/admin/repos/cirv-spirent - adjunct repo, dedicated to Spirent, used for uploading/managing code contributions for RI/RC validations in direct support of CNTT
