### ISSUE TITLE
[RC1 Ch04] Define the test cases for exposed infrastructure capabilities

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#774]
This issue is to capture the tests the exposed infrastructure capabilities as defined in [RM §4.1.2](https://cntt-n.github.io/CNTT/doc/ref_model/chapters/chapter04.html#4.1.2).

**Comment by mf4716** [comment]
Ch 4 authors, can we get an update?

Ch04: NFVI TC Traceability to RA Requirements: Rajesh, Dan, Ashok,Deepanshu (confirmed)

**Comment by mf4716** [comment]
@deebhatia , @xudan16 , @ASawwaf , @rrajesh70 - hi, can we get an update please?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@deebhatia - status?

**Comment by mf4716** [comment]
@deebhatia - status?

**Comment by mf4716** [comment]
status @deebhatia ?

**Comment by fuqiao123** [comment]
Does this issue mean we should also add the requirement in RM chp4 into the test case consideration? Can this covered by requirement in RA chp 05？

**Comment by fuqiao123** [comment]
No status for this one for a while. I would have the team review this one on Apr. 1st RC call and see if we should drop it.

**Comment by fuqiao123** [comment]
close this since no PR created and no contributors
