### ISSUE TITLE
[RC1 Ch04] Define the test cases for RA 1 OpenStack Services

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#775]
This is to provide the tests for the defined Openstack Service APIs and the functionalities offered by them.

**Comment by deebhatia** [comment]
@mf4716 Happy to work on this.

**Comment by deebhatia** [comment]
As discussed with @mf4716, will use this as a roadmap item and add other issue to provide the related content in subparts referencing this issue.

**Comment by mf4716** [comment]
Ch04 authors - can we get an update?

Ch04: NFVI TC Traceability to RA Requirements: Rajesh, Dan, Ashok,Deepanshu (confirmed)

**Comment by mf4716** [comment]
@liyingyjy - same comment posted in an RA-1 Ch3 (#803 ) issue, as there was an ask to review RC-1 Ch4 in that 803 issue.

For the other authors/reviewers, (Dan, Deepanshu, Ashok), please review @liyingyjy 's comments.

Basically, agree with the approach as you're outlining Test Case requirements to Infra, RM, or API, requirements.  Please continue.  For reference, here are the requirements links/documents:
o	RM Ch5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md --> RM requirements
o	RA 2: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md --> RA NFVI/infra requirements
o	RA 5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/chapters/chapter05.md --> RA API compliance requirements

**Comment by mf4716** [comment]
@liyingyjy - hi, can we get an update please?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@deebhatia - status?

**Comment by mf4716** [comment]
@deebhatia - status?

**Comment by deebhatia** [comment]
It is already covered. Closing it.
