### ISSUE TITLE
[RC1 Ch02] Write content - E2E C&V NFVI Framework Req

### ISSUE THREAD

**Issue by msidana** [cntt-n/CNTT#787]
As the base chapter outline is merged, the actual content can be written against this issue.

**Example chapter sections**
* Methodology
* Certification Strategy & Vehicle
* Profiles Reference
* Compliance, Verification, and Certification
* Entry & Exit Criteria
Frameworks (this is the badging process, what would we badge, requirements for badging, tools we're using, etc)

**Comment by mf4716** [comment]
I updated:
* the title - E2E C&V NFVI Framework Req 
* the description to include Chapter section ideas (just ideas).
* added missing labels

FYI - this replaces https://github.com/cntt-n/CNTT/issues/410

**Comment by mf4716** [comment]
@msidana - hi, can we get an update please?

**Comment by msidana** [comment]
Section  2.1, 2.2 and 2.6 added in https://github.com/cntt-n/CNTT/pull/788
Pending Sections 2.3,2.4,2.5,2.7

**Comment by mf4716** [comment]
Great @msidana !  What's the target date for the pending sections?

**Comment by msidana** [comment]
Added Section 2.4. 
Pending Sections 2.3, 2.5, 2.7. - @collivier Can you please provide some inputs for these sections.

**Comment by msidana** [comment]
Added all sections. PR #788 is ready for review and feedback

**Comment by mf4716** [comment]
status?

**Comment by msidana** [comment]
All sections documented. Currently working on detailing of Frameworks Section.

**Comment by msidana** [comment]
All comments fixed but one - https://github.com/cntt-n/CNTT/pull/788#discussion_r360229042.

**Comment by mf4716** [comment]
@msidana - status?

**Comment by msidana** [comment]
@mf4716 Completed. Review awaited.

**Comment by mf4716** [comment]
Thanks Manik @msidana - I added my review, requested a re-review by @collivier , and have requested two additional approvals hoping we can close PR #788 and this corresponding issue (soon, today if possible.)
