### ISSUE TITLE
[RI MVP] Lab Requirements

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#794]
RI MVP work item for Snezka:  Lab Requirements

Placeholder to track status, and ask Q&A, for the creation of Lab Requirement documentation, including a topology document for the test labs (POD10 and POD15).  Write the content in the respective RI chapter(s).

Respective RI chapters:  [RI-1 Labs Ch04 -#564](https://github.com/cntt-n/CNTT/issues/564)

For convenience, requirements locations:

- RM 5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md --> RM requirements
- RA 2: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md --> RA Infra Requirements
- RA 5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/chapters/chapter05.md --> RA API requirements

**Lead**: @rrajesh70 (Rajesh R.)

**Comment by mf4716** [comment]
@fuqiao123 , @rrajesh70 - hi, can you update on status?  Also, fyi, mark.beierl@dell.com is trying to obtain, or recreate a topology document for PODs 10 and 15.  If you're able to get/create one yourself, please let us and Mark B. know.

**Comment by mf4716** [comment]
@fuqiao123 , @rrajesh70 - hi, can you update on status?  

+@markbeierl (fyi)

**Comment by rrajesh70** [comment]
Completed draft for Lab requirements and prepared slides for Prague.
[CNTT-POD-Descriptions-2.docx](https://github.com/cntt-n/CNTT/files/4033609/CNTT-POD-Descriptions-2.docx)

**Comment by rrajesh70** [comment]
[Uploading CNTT-Lab-requirements.docx…]()

**Comment by rrajesh70** [comment]
Uploaded Lab requirements document
