### ISSUE TITLE
[RI MVP] Installer Requirement 

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#795]
RI MVP work item for Snezka: Installer Requirements

Placeholder to track status, and ask Q&A, for the creation (finishing) of Installer Requirement documentation.  Write the content in the respective RI chapter(s).

Respective RI Core Chapter:  [RI Ch05 #404](https://github.com/cntt-n/CNTT/issues/404)

Lead: @ChilionChan (Chen Liang)

**Comment by mf4716** [comment]
@ChilionChan - hi, can you update on status?

**Comment by ChilionChan** [comment]
Should I commit in a new PR? @mf4716

**Comment by mf4716** [comment]
@ChilionChan - the content for this section goes into RI-1 Core Ch05, "Installers Requirements", which is also issues #404 .  **Yes**, create a new PR for the content as right now there is no PR open (you can check here too - https://github.com/cntt-n/CNTT/projects/7 - look in the PR column, which will open for RI Core).  Once the content is created, we can close issue #404 and this issue.

**Comment by mf4716** [comment]
@ChilionChan - hi, can you please provide a status?

**Comment by ChilionChan** [comment]
This issue can be closed. I prepared  a slides which have been included into MVP slides.

**Comment by mf4716** [comment]
@ChilionChan , or @fuqiao123 - did the same Installer Requirement documentation get inserted into the  [RI Core Chapter 05](https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter05.md)?  If so, please close this issue.

**Comment by mf4716** [comment]
Contents contained in Ch 5.  Closed.
