### ISSUE TITLE
[RI MVP] Cookbook

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#797]
RI MVP work item for Snezka: Cookbook

Placeholder to track status, and ask Q&A, for the creation (finishing) of the Cookbook documentation. Write the content in the respective RI chapter(s).

Lead: Mark Beierl (GitHub ID needed), adding @collivier (Cedric) and @rrajesh70 (Rajesh)

**Comment by mf4716** [comment]
@rrajesh70 , @collivier - hi, can you update on status?  I'll send to Mark B. too and request status.

**Comment by mf4716** [comment]
@markbeierl - please see / comment on issue.  To test and confirm access.

**Comment by markbeierl** [comment]
Pong!

**Comment by mf4716** [comment]
Worked!  Was able to add you as an assignee.  Any questions, let me know, and Thank you!

**Comment by markbeierl** [comment]
Chapter reference: https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter07.md

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
@mf4716 
I think my part is completed and I can be safely removed from assignee.
https://github.com/cntt-n/CNTT/pull/911
https://github.com/cntt-n/CNTT/pull/910
https://github.com/cntt-n/CNTT/issues/912

**Comment by mf4716** [comment]
@collivier 

The sections that a 3rd party team would need to complete the setup of a lab and run smoke/health/compliance (only to confirm component exposure) still need to be written.

These were (are) the areas you were going to create: 
7.7 Deployment Validations
7.8 CICD Tool Chain (use of, process, and scripts)
7.9 Jenkins Setup & Job Creation
7.10 Compliance Validation (steps, process)

Where is this information contained?  There is a link to a jenkins job page, but this is not intuitive, or descriptive.  

Reopening.
