### ISSUE TITLE
[RI MVP] PoD state and labs availabilities 

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#798]
RI MVP work item for Snezka: PoD state and labs availabilities 

Placeholder to track status, and ask Q&A, for the creation (finishing) of PoD state and labs availabilities, including Release Notes.  documentation. Write the content in the respective RI chapter(s).

Lead: @rrajesh70

**Comment by mf4716** [comment]
@rrajesh70 - hi, can you update on status?

**Comment by mf4716** [comment]
status?

**Comment by rrajesh70** [comment]
will have a draft on this by tomorrow

**Comment by rrajesh70** [comment]
Completed a draft and updated Prague slide deck

[CNTT-POD-Descriptions-2.docx](https://github.com/cntt-n/CNTT/files/4033621/CNTT-POD-Descriptions-2.docx)
