### ISSUE TITLE
[RI MVP] Initial NFVI installation using Airship 

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#799]
RI MVP work item for Snezka: Initial NFVI installation using Airship 

Placeholder to track status, and ask Q&A, for the creation (finishing) of Initial NFVI installation using Airship documentation, including items not complying with CNTT documentation right now.   Write the content in the respective RI chapter(s).

Lead: @opensource-tnbt (Sridhar), @rrajesh70 (Rajesh)

**Comment by mf4716** [comment]
@opensource-tnbt , @rrajesh70 - hi, can you update on status?

**Comment by mf4716** [comment]
status?

**Comment by rrajesh70** [comment]
@opensource-tnbt spent many hours to stand up NFVI on POD 15 and is currently encountering issue with one of the computes booting incorrectly (not using pxe boot correctly. INFRA ticket 395 raised (OPNFV Jira ticket) to resolve this issue. Trevor Cooper has asked Timothy Gresham (Intel) to investigate this failure as high priority item

**Comment by mf4716** [comment]
Install complete on target POD15 lab 1/7.  Closed.
