### ISSUE TITLE
[RC MVP] Framework Requirements

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#800]
RC MVP work item for Snezka: Framework Requirements

Placeholder to track status, and ask Q&A, for the creation (finishing) of Framework Requirements
documentation. Write the content in the respective RC chapter(s).

Lead: @msidana (Manik)

**Comment by mf4716** [comment]
@msidana - hi, can you update on status?

**Comment by msidana** [comment]
Sections 2.3, 2.7 pending in PR https://github.com/cntt-n/CNTT/pull/788/

**Comment by msidana** [comment]
Updates (12/18)
Section 2.3 is added.
Section 2.7 is pending. Need inputs from @collivier

**Comment by msidana** [comment]
Added Section 2.7. All sections are complete. PR #788 is ready for review and feedback

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
Please let me write the work already done.

**Comment by mf4716** [comment]
@collivier - Cedric, will this be ready in 1-2 days to review?

**Comment by collivier** [comment]
@mf4716 I don't see the point to hurry to create PRs if they are not reviewed quickly.
I'm first finishing Chapter 4 (API functional tests, benchmarking API, benchmarking dataplane, golden VNF, etc...). 1-2 days seem unrealistic regarding the ongoing work here and holidays. Else yes it's on time here for the release.
https://github.com/cntt-n/CNTT/pull/831
https://github.com/cntt-n/CNTT/pull/833
https://github.com/cntt-n/CNTT/pull/835
https://github.com/cntt-n/CNTT/pull/837
https://github.com/cntt-n/CNTT/pull/839
https://github.com/cntt-n/CNTT/pull/844
https://github.com/cntt-n/CNTT/pull/845

**Comment by mf4716** [comment]
@collivier - with few committers, it's easier we find to centralize changes and commits to as few PRs as possible, this way, there is complete context for what is being reviewed, and if there are any changes in the document to adjust the flow, or update section numbers, or table of contents, we can do it with 1/few PRs and merge them quickly.  I'll take a look at the other PRs to see if I can add a comment/review.

**Comment by mf4716** [comment]
@collivier - status?

**Comment by mf4716** [comment]
Frameworks created.  Additional iterations expected post-Snezka.
