### ISSUE TITLE
[RC MVP] Certification process drafted 

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#801]
RC MVP work item for Snezka: Certification process drafted

Placeholder to track status, and ask Q&A, for the creation (finishing) of Certification process drafted / documented.  Write the content in the respective RC chapter(s).

Lead: @sparayil (Shiby), @mkr1481 (Kanag)

**Comment by mf4716** [comment]
@sparayil , @mkr1481 - hi, can you update on status?

**Comment by mf4716** [comment]
status?

**Comment by mf4716** [comment]
@sparayil , @mkr1481 - hi, can you update on status?

**Comment by mf4716** [comment]
@sparayil , @mkr1481 - hi, can you update on status?

**Comment by sparayil** [comment]
> @sparayil , @mkr1481 - hi, can you update on status?

Unfortunately, Mike I have not been able to work on this at all due to some business priorties

**Comment by mkr1481** [comment]
This could be closed as https://github.com/cntt-n/CNTT/pull/807 merged already

**Comment by mf4716** [comment]
Closed - with merged PR #807
