### ISSUE TITLE
[RC MVP] Automation / Compliance / Tool chain process and status

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#802]
RC MVP work item for Snezka: Automation / Compliance / Tool chain process and status

Placeholder to track status, and ask Q&A, for the creation (finishing) of documenting the Automation / Compliance / Tool chain process and status.  Write the content in the respective RC chapter(s).

Lead:  Mark Beierl (@markbeierl), and @collivier (Cedric)

**Comment by mf4716** [comment]
@collivier - hi, can you update on status?  I'll email Mark Beierl and ask status too.

**Comment by markbeierl** [comment]
Test comment to see if my github ID shows up this way.

**Comment by mf4716** [comment]
@markbeierl - works!  Fantastic!  I updated you as an assignee!  -Mike (@mf4716 )

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
I just finished the OPNFV part. It's now on my agenda as the OPNFV/CNTT inter dependencies about Compliance are now solved.
https://git.opnfv.org/functest-xtesting/commit/xtesting?h=stable/hunter&id=e11091e94b179c67f1c57f5fdf33816a469c5feb

**Comment by mf4716** [comment]
@collivier - Cedric, what Chapter(s) in RI or RC are you adding this info to?

**Comment by mf4716** [comment]
@collivier - status?

**Comment by mf4716** [comment]
@collivier , @markbeierl - can we close?
