### ISSUE TITLE
[RC1 Ch04] Define the test cases for RA 1 Identity Service (Keystone)

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#808]
As per issue #775 , add test cases for OpenStack identity service - Keystone. Tests should also cater the requirements defined around identity management.

**Comment by mf4716** [comment]
Thank you for creating the issue.  Added you @deebhatia (Deepanshu) as the assignee.  Add others, as needed.

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
@mf4716 I think it can be closed as replaced by #832 and #833

**Comment by collivier** [comment]
@deebhatia @mf4716 I think it duplicates the upstream work and listing the ~2000 tests already executed in Functest CNTT costs lots of time for a duplication in the best cases.
The proposal #833 is straightforward regarding RA1 Chapter 5 (API) and then I don't see the point to add abstract requirements which can't me mapped neither with API nor opensource testcases.
See opnfv/functest-smoke-cntt:hunter in https://build.opnfv.org/ci/view/functest/job/functest-hunter-daily/373/

**Comment by deebhatia** [comment]
Closing this as per @collivier's comments.

**Comment by mf4716** [comment]
> @mf4716 I think it can be closed as replaced by #832 and #833

@collivier - Cedric, If this was to add TCs, then yes.  We do not duplicate tickets.  Thanks.
