### ISSUE TITLE
[RC1 Ch04] Define the test cases for RA 1 Image Service (Glance)

### ISSUE THREAD

**Issue by deebhatia** [cntt-n/CNTT#809]
As per issue #775 , add test cases for OpenStack image service - Glance. Tests should also cater the requirements defined around image management.

**Comment by mf4716** [comment]
Thank you for creating the issue.  Added you @deebhatia (Deepanshu) as the assignee.  Add others, as needed.

**Comment by mf4716** [comment]
status?

**Comment by collivier** [comment]
@mf4716 I think it can be closed as replaced by https://github.com/cntt-n/CNTT/issues/832 and https://github.com/cntt-n/CNTT/pull/833

**Comment by deebhatia** [comment]
Closing this as per @collivier's comments.

**Comment by mf4716** [comment]
> @mf4716 I think it can be closed as replaced by #832 and #833

@collivier - Cedric, If this was to add TCs, then yes.  We do not duplicate tickets.  Thanks.
