### ISSUE TITLE
[RM Ch04 & Ch05] Consistency

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#816]
Can some of the similar requirements defined in RM Ch04 and Ch05 be made consistent. For example, "i.nfvi.sla.cap.001 CPU overbooking" and "nfvi.com.cfg.001 CPU allocation ration"?

**Comment by markshostak** [comment]
@pgoyal01 Good idea. Please do. Thanks, -Mark

**Comment by pgoyal01** [comment]
Specifying some details as to what is required:

Few issues need to be addressed in RM Ch04 and Ch05. Below are just some examples.

1. Consistency in "Ref". For example, 
    - i.nfvi.mon.cap.001 Host CPU usage
    - i.nfvi.pm.001 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Host CPU usage

1. Consistent use of terms, for example "usage" and "utilisation" and others
    - i.nfvi.mon.cap.001 Host CPU usage
    - i.nfvi.pm.001 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Host CPU usage
    - i.nfvi.mon.cap.003 Host CPU utilisation
    - i.nfvi.pm.003 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Host CPU utilisation

    - e.nfvi.cap.006 &nbsp;&nbsp;&nbsp;&nbsp; CPU core pinning support
    - nfvi.com.cfg.003 &nbsp;&nbsp;&nbsp;&nbsp; CPU pinning capability
    - e.nfvi.per.cap.001 &nbsp;&nbsp;&nbsp;&nbsp; CPU pinning support

    Important to use the same terms and ratios for "CPU overbooking" and "CPU Allocation Ratio" -- the latter is the preferred term.


1. [4.1.2.1 Exposed Resource Capabilities](https://github.com/cntt-n/CNTT/blob/pgoyal01-patch-2/doc/ref_model/chapters/chapter04.md#4121-exposed-resource-capabilities): Since these requirements are all about "maximum" limits, may I suggest that the "NFVI Capability" verbiage should include "Max"

1. [4.1.5.2 Internal Availability/Reliability Measurements](https://github.com/cntt-n/CNTT/blob/pgoyal01-patch-2/doc/ref_model/chapters/chapter04.md#4152-internal-availabilityreliability-measurements): 
    - i.nfvi.pm.010 "AZ" is not defined and what constitutes an AZ failure?
    - i.nfvi.pm.011 Recovery Time of what?

1. [4.1.6 VIM Capabilities](https://github.com/cntt-n/CNTT/blob/pgoyal01-patch-2/doc/ref_model/chapters/chapter04.md#416-vim-capabilities): why is e.vim.cap.005 Images management restricted to VNFC software images? 

1. [4.1.7.1 Resources Management Measurements](https://github.com/cntt-n/CNTT/blob/pgoyal01-patch-2/doc/ref_model/chapters/chapter04.md#4171-resources-management-measurements): why are the times to create, delete, start, pause and stop for VNF rather than VNFC resources? VNFs differ in size and complexity and more importantly data that may need to be loaded.
