### ISSUE TITLE
[RI1 Dev][RC1 Dev] new RI deployment container

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#828]
The current Airship deployment scripts seem linked to OPNFV jumphosts and then can be hardly exported to the users (RI cookbook). For the time being, it works only in the OPNFV Context.

It should be considered as prerequisites before writing any RI Cookbook (or we can only focus on the testing part):
 - all Airship deployment scripts delivered via a new container
 - a new Xtesting testcase definition to export easily the whole CI toolchain (mandatory for RC). 

see: https://jira.opnfv.org/browse/AIRSHIP-25

**Comment by mf4716** [comment]
status @collivier ?

**Comment by collivier** [comment]
@fuqiao123 @rabi-abdel @acmacm : No upstream activity for a while. I closed it.
Be free to reopen it if needed.
