### ISSUE TITLE
[RC1 Dev] Clean interfaces between RC and OVP

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#829]
From my understanding, if we care about interfaces, RC should:
- define the criteria for Compliance (NFVI & VNF)
- list the existing testcases for the CNTT Compliance
- define the framework used to execute them everywhere and to dump the results for third-parties
- set the gap to improve Compliance

it's up to OVP/CVC:
- to define the way to receive the results and to review the results
- to print the Compliant NFVI and VNFs list

See as good example: CVC will maintain requirements for certification in Gouvernance
https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter01.md

There are lots of sections mixing both (Dovetail test execution in Resources & References) and I would appreciate agreements on this trivial approach before applying the deep changes

**Comment by mf4716** [comment]
@collivier - We are in agreement.  This is a duplicate issue, having already generated relevant scope/documentation for RC1 in Ch 1, and inflight framework chapters 02 for NFVI and 05 for VNF. 
 Please review those PRs, add content, and let's close this duplicate issue.  Thanks

**Comment by mf4716** [comment]
@collivier - can we close please?

**Comment by collivier** [comment]
@mf4716: From my understanding, CVC will maintain requirements for certification is false or possibly well explained (or well understood). It's up to CNTT to select the compliance test list.
I would like to change "Dependencies NFVI+VNF verification will rely upon test harnesses, test tools, and test suites provided by upstream OPNFV projects, including dovetaill, yardstick, and Bottleneck". dovetail doesn't not maintain any test. It executes a few modified test cases from Functest, YardStick and Bottleneck.

**Comment by mf4716** [comment]
> @mf4716: From my understanding, CVC will maintain requirements for certification is false or possibly wrongly understood. It's up to CNTT to select the compliance test list.
> I would like to change "Dependencies NFVI+VNF verification will rely upon test harnesses, test tools, and test suites provided by upstream OPNFV projects, including dovetaill, yardstick, and Bottleneck". dovetail doesn't not maintain any test. It executes a few modified test cases from Functest, YardStick and Bottleneck.

Agreed @collivier .  Please edit & close.

**Comment by mf4716** [comment]
status @collivier ?

**Comment by mf4716** [comment]
@prabhubalan - as discussed with Prabhu, he will confirm with Cedric if we need to make a change, and then close.  Thanks in advance Prabhu.

**Comment by fuqiao123** [comment]
I am OK with all the comments and discussion above. However no exist PR related with this. Will check with the team and see if we already acomplish this one and we can close it.
