### ISSUE TITLE
[RC1] Remove 4.3.2 Infrastructure and 4.3.3 VIM

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#858]
It's quite falsy, from a technical statepoint, to list only a few operations in the 2000 tests already executed in Functest Smoke CNTT.

It's much more covered in the next sections.

**Comment by mf4716** [comment]
FYI - Ch04 is for NFVI TC Traceability to RA Requirements.

The sections, 4.3.2 Infrastructure and 4.3.3 VIM, contain the RA Requirements, for which TCs will be tested, or used for testing.  As such we will **Not** be removing the sections.

@collivier - Please insert additional Functest/Smoke test cases to enhance this section.  

+Adding contributor authors to this conversation for any comments/input from them: @rrajesh70 (Rajesh), @xudan16 (Dan), @ashokkumarprajapati (Ashok) and @deebhatia (Deepanshu).

**Comment by collivier** [comment]
@mf4716 Could I remove this part? We could add them back when content is added.

**Comment by mf4716** [comment]
@collivier - The ask was,
 
"The sections, 4.3.2 Infrastructure and 4.3.3 VIM, contain the RA Requirements, for which TCs will be tested, or used for testing. As such we will Not be removing the sections.

Please insert additional Functest/Smoke test cases to enhance this section."

There is a need for content, so we cannot remove.

**Comment by collivier** [comment]
It looks strange to keep TOC when empty and partially duplicating other sections.
