### ISSUE TITLE
[RI 1 Dev] Port NFVbench testcases to Xtesting

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#865]
Xtesting allows a smooth integration of sparsed testcases and ease building CI/CD toolchains via an Ansible role.
http://testresults.opnfv.org/functest/stockholm/

Here leveraging on Xtesting will ease building CI/CD toolchains in few commands mixing Functest and NFVbench-based testcases. It also simplifies any validation process as it avoids extra logics per test frameworks (jenkins job templates, certification, etc.)
https://wiki.opnfv.org/pages/viewpage.action?pageId=32015004

**Comment by mf4716** [comment]
status @collivier ?

**Comment by fuqiao123** [comment]
@collivier could you please help see if we have any progress for this one, or if nothing happen in NFv bench, we probably can close this one first.

**Comment by jayacha** [comment]
@acmacm can you please confirm this is done or backlog?

**Comment by jayacha** [comment]
Cedric will close next week after adding test cases.

**Comment by collivier** [comment]
Thank you. Alec and François-Régis for the update:
https://gerrit.opnfv.org/gerrit/c/nfvbench/+/69753
