### ISSUE TITLE
[RC1] Describe Xtesting & XtestingCI capabilities for RC

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#866]
This 2 projects combined meet the CNTT requirements about verification, compliance and certification:
- smoothly assemble multiple heterogeneous test cases
- generate the Jenkins jobs in OPNFV Releng to verify CNTT RI
- deploy local CI/CD toolchains everywhere to check compliance with CNTT
- dump all test case results and logs for third-party certification review

**Comment by mf4716** [comment]
Copying comment from PR #867 ...

_Cedric @collivier , there is already an open PR for RC Ch2 - #788 (Ch02: NFVI E2E C&V Framework Requirements). Can you please add / move your content from this PR #867 to PR #788 ?

Note: Manik @msidana has put considerable work into PR 788. Please be sure the content you're adding doesn't conflict with what is already there._
