### ISSUE TITLE
[RM Ch05] 5.4.1. Compute Resources

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#875]
[RM Ch05] [5.4.1. Compute Resources](https://github.com/cntt-n/CNTT/blob/0e4a3d6720ab021b83e3b5f94711c469c479b477/doc/ref_model/chapters/chapter05.md#541-compute-resources)

Reference | Feature | Description | Basic Type | Network Intensive | Compute Intensive
-- | -- | -- | -- | -- | --
nfvi.hw.cpu.cfg.002 | Number of Cores per CPU | This determines the number of cores needed per each CPU. | 20 | 20 | 20

Should these be minimum number of cores per CPU? This impacts PR #738 

I think, "needed" and "each" should be deleted.

**Comment by pgoyal01** [comment]
This also affects RI [4.2.1 Physical Server Requirements](https://github.com/markbeierl/CNTT/blob/patch-2/doc/ref_impl/cntt-ri/chapters/chapter04.md#421-physical-server-requirements) where 24 core CPUs are specified for use; non-compliant with nfvi.hw.cpu.cfg.002

**Comment by markshostak** [comment]
Good catch, @pgoyal01 ! All yours.

**Comment by kedmison** [comment]
RI1 is currently internally inconsistent; it has 20 cores (same as RM) in the [RI1 Chapter03 section 3.4](https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter03.md#34-nfvi-hardware-profile) but it has 24 cores in [RI1 Chapter 4 section 4.2.1](https://github.com/cntt-n/CNTT/blob/master/doc/ref_impl/cntt-ri/chapters/chapter04.md#421-physical-server-requirements).

Given that the RI has this to resolve, this issue will focus on the grammar and not on changing the intent of the core count metric or the name.
