### ISSUE TITLE
[RC1] Change "[RC1 Ch03] - NFVI test case requirements" or possibly revert it

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#891]
It's written that NFVI test cases *must* support either proxied Internet connectivity or an offline mode if additional container or virtual machine images need to be downloaded at runtime.

I disagree to forbid testcases when it could be considered out of NFV (enterprise proxies?) or at least up to Operator to setup mirrors. I would de facto remove VNF testing and possibly raise side effect in RI (it leverages on external DNS).

3.9.1 Functional (API) test cases falsy duplicates chapter04 https://github.com/cntt-n/CNTT/blob/master/doc/ref_cert/lfn/chapters/chapter04.md

If Chapter 3.9 is a better place, we do copy the right content from Chapter 4 to Chapter 3.

**Comment by gkunz** [comment]
Let me clarify the requirement. The intention of this requirement is to ensure that there is "some way" to run a test case in a enterprise internal lab environment. Typically, such labs do not allow direct Internet access, but require proxies and internal DNS servers, etc. This is fundamentally different from the rather open OPNFV environment.

By "some way to run" a test case, I am not implying that every test case must natively support enterprise proxies. Instead, it would also be fine to have a description of how to provide local mirrors / repositories, etc. to allow a test case to run in a private lab environment.

This is often a practical reality of lab environments. From an adoption perspective, I believe this should be considered. However, I am happy to receive feedback from other organizations (vendors, organizations, 3rd party labs) if this is a problem for them as well or not. Let's take a practical perspective on this issue.

Regarding Ch 3.9 vs Ch 4: I think it makes most sense to keep the content in Chapter 4 and refer to it from 3.

**Comment by collivier** [comment]
@gkunz Sorry for the conflict between Chapter3 and Chapter 4 which sometimes occurs in a collaborative process. At least they seems equal, only the details differ.
+1 to rephrase the proxy part as proposed here.
Thank you in advance for the next PR.

**Comment by gkunz** [comment]
Hi @collivier. Would you agree to list of all test cases selected by the compliance test suite in chapter 4, that is, also the performance, resilience and bare-metal validation test cases - once defined - in addition to the functional tests you have already covered? If so, I would just move the empty headings from 3.9 to 4 in the next patch.

**Comment by gkunz** [comment]
@collivier I moved the headings in #909 . Let me know if you prefer to undo this.

**Comment by collivier** [comment]
@gkunz Performance could have been removed as they are already few section about API benchmarking and dataplace benchmarking.
