### ISSUE TITLE
[RA-2 Ch06] 6.1 Images

### ISSUE THREAD

**Issue by pgoyal01** [cntt-n/CNTT#898]
[RA-2 Ch06] 6.1 Images

" Image registries must be monitored to automatically block or replace images with known vulnerabilites, while also ensuring policies are used to gate what can be deployed and who can deploy from the registry."

It should be mandatory that "images with vulnerabilities" are blocked from being loaded into the registries. 
Typo: "vulnerabilities"

"The following functionalities are recommended for securing kubernetes platform;"
Typo ":" instead of ";"

Modify "Image SIgning" to "Image Certification (Scanning for vulnerabilities, basic operations, ..) and Signing"

**Comment by CsatariGergely** [comment]
@pgoyal01 Google tells me that "vulnerabilities" is correct. Can you please comment what kind of spelling should I use here?
"basic operations" are not clear for me what do you mean on this?
