### ISSUE TITLE
[RA-2 Ch06] 6.1

### ISSUE THREAD

**Issue by samulikuusela** [cntt-n/CNTT#899]
“A fully integrated security testing should be baked into the CI/CD pipeline.”
Suggest to modify to:
“A fully integrated security testing should be baked into the CI/CD pipeline, both in the vendors and operators pipelines.”

In the bullet list:
“Kubernetes Cluster Multi-tenancy security”
could be changed to eg:
“How to overcome the lack of true Kubernetes Cluster Multi-tenancy”

**Comment by tomkivlin** [comment]
@CsatariGergely to split into separate issues/PRs or not.

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely to split into separate issues/PRs or not.

Nope, these are small enough to keep them in one.
