### ISSUE TITLE
[RA2 Ch06] Security patches

### ISSUE THREAD

**Issue by samulikuusela** [cntt-n/CNTT#901]
“new security features and patches are added in every quarterly update”:
Unclear if this means vendor (SW development) or operator (SW deployment). Suggest anyway to remove the "every quarterly", because open src and commercial SW are released in various cycles which can be longer or shorter than every quarter.

Could add what does this mean for vendor and operator, something like;
- the vendor aspect: the trend is for more frequent releases or ‘continuous’.
- the operator aspect: up to ‘network LCM strategy’ how often updates are made. The ultimate CD would be like with the popular example of Netflix, but probably not realistic quite yet.

**Comment by tomkivlin** [comment]
PR to be created after #1492 is complete.

**Comment by karinesevilla** [comment]
Security patches management must be better specified, "quarterly update" is not relevant
