### ISSUE TITLE
[RC1] Remove 7.8, 7.9 and 7.10

### ISSUE THREAD

**Issue by collivier** [cntt-n/CNTT#912]
They are empty and already treated from my understanding
https://github.com/cntt-n/CNTT/pull/910
https://github.com/cntt-n/CNTT/pull/911

The only place to grow would be to dive into Jenkins job builder but it's already very well documented inline and we are not so many to master it even in OPNFV (see Releng contributors).

**Comment by collivier** [comment]
@fuqiao123 @mf4716 Please let me now if do create the PR.

**Comment by mf4716** [comment]
These sections need to be written.  We need to delete/cancel this issue.

**Comment by collivier** [comment]
Your choice.
