### ISSUE TITLE
[RM Ch-08-Annex] Purge Annex

### ISSUE THREAD

**Issue by markshostak** [cntt-n/CNTT#915]
@mf4716 Mike, Is there any purpose in having an annex to RM Ch8 anymore? Please take a look and let me know if you've got all the material in RC, so I can delete it. Thanks, -Mark

**Comment by mf4716** [comment]
@markshostak - there is some good content needed for RC-1.  I'll review / retrieve info, then revert back when done.  For convenience, link to material:  [RM Ch8 Annex](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter08-annex.md)

**Comment by deebhatia** [comment]
@mf4716 I think you can use this patch. :)
[Annexture_8_movement_in_RC_1.patch.zip](https://github.com/cntt-n/CNTT/files/4046753/Annexture_8_movement_in_RC_1.patch.zip)

**Comment by markshostak** [comment]
> 
> 
> @mf4716 I think you can use this patch. :)
> [Annexture_8_movement_in_RC_1.patch.zip](https://github.com/cntt-n/CNTT/files/4046753/Annexture_8_movement_in_RC_1.patch.zip)

That's cute.

**Comment by mf4716** [comment]
@markshostak - Good to purge.  We have what we need.  Thanks.
