### ISSUE TITLE
[TSC] - sync WSLs to CODEOWNERS

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#925]
At the moment, the [CODEOWNERS](../blob/master/CODEOWNERS) contains a subset of the workstream leads and coleads for each chapter. 
E.g. for all RA2 Core chapters could we add @CsatariGergely and the other co-leads?

```
# Reference Architectures 2 Core
/doc/ref_arch/kubernetes/chapters/chapter01.md        @rabiabdel @tomkivlin
/doc/ref_arch/kubernetes/chapters/chapter02.md        @rabiabdel @tomkivlin
/doc/ref_arch/kubernetes/chapters/chapter03.md        @rabiabdel @tomkivlin
/doc/ref_arch/kubernetes/chapters/chapter04.md        @rabiabdel @tomkivlin 
```

**Comment by rabi-abdel** [comment]
Part of this is due to limitation in GitHub that doest allow for (or).
