### ISSUE TITLE
[RC1 Ch9 - Snezka F2F] RC Cookbook Enhancements

### ISSUE THREAD

**Issue by mf4716** [cntt-n/CNTT#945]
As a follow up to Sneka F2F, enhance the RC Cookbook in [RC1 Ch9](https://github.com/cntt-n/CNTT/tree/master/doc/ref_cert/lfn/chapters) to include:

**User-Execution**
- Common Failure codes, description, and resolutions
- Test Framework Clean-Up Utility, Process, and Support Expectations

**Process / Version Mgmt**
- Process for version control
- Process for bug fixes and patches
- Containers Tagged
- Playbooks grab the tagged version

**Comment by mf4716** [comment]
@lylavoie , @markbeierl , @markshostak - please update description w/ missing enhancements needed for RC1 Cookbook.

**Comment by mf4716** [comment]
@lylavoie , @markbeierl , @markshostak - any volunteers to assist?

**Comment by collivier** [comment]
I don't see why the cookbook should explain all possible errors and then the possible fixes. It's just an infinite work which seems out of a cookbook.

**Comment by mf4716** [comment]
"Common Failure codes, description, and resolutions"

The feedback in Prague was to include some helpful information for self-troubleshooting.  Not exhaustive, but common.  Airship deployment guides include troubleshooting information.  The plan was to start with that info, and expand over time - e.g. CICD Toolchain common setup issues, etc

**Comment by mf4716** [comment]
@prabhubalan - per conversation w/ Prabhu on 3/20, Prabhu will assume ownership and work with the other assigners to review what is needed to complete this issue. Prabhu to setup a call, or discuss at the next RIRC meeting, or email.

**Comment by fuqiao123** [comment]
According to discussion on Apr. 8 RC call, I suggest we close this issue for now and reopen it once we find necessity for adding troubleshooting
