### ISSUE TITLE
[RA 2] making the Artefact Repository consistent across the documentation

### ISSUE THREAD

**Issue by xmulligan** [cntt-n/CNTT#946]
In reference to the conversation in  #943 
Yes I like that. And probably a new issue to clarify and make the documentation consistent around artefact repos. - @tomkivlin 

We need to understand which RM requirements address the requirement for an artefact repository. As a more generic requirement for Kubernetes architecture it makes sense, but in the context of an architecture that is about standardizing on the infrastructure capabilities consumed by workloads, it should be reexamined.

This issue needs to address and make the artefact repository consistent across the documentation including
#610
https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter01.html Figure 1-1 
https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter03.html 3.2.4
https://cntt-n.github.io/CNTT/doc/ref_arch/kubernetes/chapters/chapter04.html Figure 4-1

The suggest language may be pulled from 4.8? "The reference architecture must support the usage of a Kubernetes Application package manager using the Kubernetes API-s, like Helm v3."

**Comment by xmulligan** [comment]
Section 4.1.6 VIM Capabilities at https://cntt-n.github.io/CNTT/doc/ref_model/chapters/chapter04.html includes image management as e.vim.cap.005

**Comment by tomkivlin** [comment]
From deep dive in Prague:
Container Registries
Need to work out what, if anything, the registry does to help a CNF pass the RC tests [and then modify the chapter]

**Comment by tomkivlin** [comment]
@xmulligan is there a PR to raise here?
