### ISSUE TITLE
[TSC] Need for New RI-2 WS Proposal

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#954]
**We need a proposal for the new WS RI-2 based on RA-2 Specs** 
This should follow the process defined in https://github.com/cntt-n/CNTT/blob/master/doc/gov/chapters/chapter03.md#34-new-work-streams-policy

Put the proposal to etherpad (https://etherpad.opnfv.org/p/RI2) or any other online editing tool or write directly here, but should contain:

- What Opensource projects we can use to create/install the K8s based reference implementation. what are the tools available, etc.

**Comment by pgoyal01** [comment]
Is RA-2 ready for RI-2 and RC-2?

**Comment by rabi-abdel** [comment]
-Scott to be added.
-Rihab to be added.

**Comment by rabi-abdel** [comment]
Aim for a month to have a draft to be reviewed.

**Comment by SaadUllahSheikh** [comment]
Hi @rabi-abdel  the RA2 2.3 is not even scopes completely . E.g use of SDN , networking and VIM capabilities , i think we need put some more details before jumping to RI-2 , secondly for tools we can just refer to CNCF test bed as to start .

**Comment by gkunz** [comment]
Hi @SaadUllahSheikh. While RA2 is certainly not yet fully fleshed out, one benefit of starting with RI2 now is that it can feedback information into RA2 regarding some of the choices you mentioned above. Moreover, I consider the early RI2 efforts more as a prototyping activity than an implementation strictly following an existing reference spec.

**Comment by gkunz** [comment]
Hi all. I have added more content to the etherpad. Please review and extend: https://etherpad.opnfv.org/p/RI2

**Comment by rabi-abdel** [comment]
- add your name please to contributor interst's lit (as a lead or as a contributor)

**Comment by rabi-abdel** [comment]
@CsatariGergely since you are the CNCF TUG officer, do you mind please communicating to CNCF TUG (via email) & Slack to gather their interest to become contributors in this WS? we agreed in last meeting with TUG to document the Requirement part of the RI. (we need to create the WS to be able to do that).

**Comment by SaadUllahSheikh** [comment]
> Hi @SaadUllahSheikh. While RA2 is certainly not yet fully fleshed out, one benefit of starting with RI2 now is that it can feedback information into RA2 regarding some of the choices you mentioned above. Moreover, I consider the early RI2 efforts more as a prototyping activity than an implementation strictly following an existing reference spec.

**Comment by SaadUllahSheikh** [comment]
@gkunz clear on this

**Comment by tomkivlin** [comment]
I've added a section which will capture the information required for the CNTT proposal as per the CNTT governance docs. I don't think lab location and specific tools to use are required at this stage (that's not to say we stop thinking about it, but let's focus on getting the workstream approved with the info required, given the wording in the document @rabi-abdel provided.

===========Info required by CNTT for a new workstream proposal:============

Please add any info you think would be relevant.
