### ISSUE TITLE
[TSC] we need a proposal for RC-2 new WS

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#955]
We need a proposal for the new WS RC-2.

This should follow the process defined in https://github.com/cntt-n/CNTT/blob/master/doc/gov/chapters/chapter03.md#34-new-work-streams-policy

Put the proposal to etherpad or any other online editing tool or write directly here.
https://etherpad.opnfv.org/p/RC2

**Comment by rabi-abdel** [comment]
Here is more details of how RC-2 will fit within OVP Ph2 program.
https://wiki.lfnetworking.org/display/LN/OVP+2.0+Boot+Strap

**Comment by collivier** [comment]
@rabi-abdel : The key part is to reuse the common part as already defined in RC1 (test case integration and verification, cookbooks, etc).

**Comment by xmulligan** [comment]
I've updated the etherpad, but we still need additional people committed to the workstream
