### ISSUE TITLE
[RM CH04] Table 4-24

### ISSUE THREAD

**Issue by jonnewton** [cntt-n/CNTT#957]
Fix the inconsistency between the references in table 4-24 and the references in table 4-1

**Comment by CsatariGergely** [comment]
In this case we do not know where is table 4-24.
@jonnewton can you please clarify what kind of inconsistencies are you referring to?

**Comment by pgoyal01** [comment]
@ASawwaf @walterkozlowski can we close as this has been open for a very long time and since the Table 4-24 doesn't exist this issue is invalid
