### ISSUE TITLE
[RM CH04] Table 4-24 does not map to the acceleration extensions

### ISSUE THREAD

**Issue by jonnewton** [cntt-n/CNTT#962]
Capabilities such as In line IPSec Acceleration and Look Aside Crypto are  requested using the acceleration extensions rather than on by default (but table 4-24 does not identify this).   Suggest an additional column is added for the cases where the capability has to be requested by Acceleration Extension (and identify the Extension in this column).

**Comment by pgoyal01** [comment]
@jonnewton while working on Ch 4 can you ensure consistency. Examples, CPU core pinning support and CPU pinning support; Host CPU usage and HOST CPU utilisation; e.nfvi.cap.013 refers to both SR-IOV over PCI-PT and Monitoring of L2-L7 data; etc.

There also different terms used in Ch 4 and Ch 5 for the same concept. Example, CPU overbooking and CPU allocation ratio; etc.

**Comment by CsatariGergely** [comment]
There is no Table 4-24, but Table 4-16 mentions IPSec and Look Aside accelerations.
@jonnewton can you please explain what is missing from this table?

**Comment by walterkozlowski** [comment]
Exceptions have been removed to RA-1 and RA-2
