### ISSUE TITLE
[CNTT Technical Steering] Officers assignments:

### ISSUE THREAD

**Issue by rabi-abdel** [cntt-n/CNTT#974]
- Release Technical Manager
- Chief Technical Editor.
- ONAP Technical Coordinator.
- OPNFV Technical Coordinator.
- CNCF Technical Coordinator.
- CVC Technical Coordinator.
- Automation and Tooling

**Comment by rabi-abdel** [comment]
Discussed during CNTT:

- Release Technical Manager: @collivier 
- Chief Technical Editor: @bfcohen  
- ONAP Technical Coordinator:   <TBA>
- OPNFV Technical Coordinator: **Owner:** @fuqiao123 helers: @mf4716 
- CNCF Technical Coordinator:   @CsatariGergely 
- CVC Technical Coordinator:     @rabi-abdel 
- Automation and Tooling:           **Owner**: Scott, help from:  @CsatariGergely, @collivier

@rabi-abdel to Update Wiki with the newly assigned names.

**Comment by rabiabdel** [comment]
Completed and logged in wiki
