### ISSUE TITLE
[RA2] Survey of Kubernetes usage

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#975]
Comments by @kedmison in Prague:
KE: Is it worth doing a matrix survey of who is doing K8S now, and who will be doing it at EoY, vs who is using it for network functions, and who is doing it for IT-type workloads (or network-adjacent tasks like management, operations)
KE: CNTT defined its mandate as wanting to provide an environment for network, IT, and ML workloads.  If the survey shows that K8S is happening this year for management & operations, then perhaps more urgency should be placed RA-2 work.

**Comment by xmulligan** [comment]
@tomkivlin is this still something we are looking at doing this release? I would be interested in helping out if so

**Comment by tomkivlin** [comment]
I think N it would be useful yes, to inform the requirements we need to meet. I think the stuff Trevor presented a couple of weeks back from OVP analysis would be a great start! You've been assigned Bill.

**Comment by xmulligan** [comment]
I've started the document below. Please feel free to add comments or additional questions

https://docs.google.com/document/d/1TpDyfg_Qyk7eWUuI78OX-QCRE-nhEKYsBzmUsvsUmqw/edit

**Comment by xmulligan** [comment]
https://forms.gle/wwyyam8aPGNYRTv79 the survey is now live

**Comment by xmulligan** [comment]
Survey was presented at the June 2020 Developer forum
