### ISSUE TITLE
[RA2] Ch3 - track SR-IOV exception for RA2

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#981]
From deep dive in Prague:
3.2.1 Raise an issue to track SR-IOV exception for RA-2

**Comment by CsatariGergely** [comment]
I would need to know how to "track" an exception. @rabi-abdel do we already have the way to propose and track exceptions?

**Comment by rabi-abdel** [comment]
Yes, I have created the exception list in RM (https://github.com/cntt-n/CNTT/pull/1265). I would expect RA-2 to have a similar table in Appendix-A stating what RA-2 Exceptions has been used to fulfil RM exceptions but also if there are expcetions within RA-2 that also can be tracked and worked towards getting rid of. something like: 

| Ref         	| Type       	| Name  	| RM Exception if any 	| Details                                                                                                                                	|
|-------------	|------------	|-------	|---------------------	|----------------------------------------------------------------------------------------------------------------------------------------	|
| ra2.exc.001 	| Technology 	| SRIOV 	| rm.exc.001          	| This exception allows workloads (VNF/CNF) to use SR-IOV Pass-Through. RA-2 architectures allows plugins such as CNI-SRIOV to be used.  	|
| ra2.exc.002 	| API        	| TBD   	| NA                  	| Allowing temporary API versions.                                                                                                       	|
| ra2.exc.003 	| Technology 	| TBD   	| NA                  	|                                                                                                                                        	|

Let me know if this makes sense
