### ISSUE TITLE
[RA2] Ch6 - check if 6.2.4 exists any more

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#986]
From deep dive in Prague:
8.2.4 This gap may not be existing anymore. Check if it relates to 8.2.5. Issue to be opened.

**Comment by xmulligan** [comment]
8.2.4 Multiple network interfaces on Pods
with the updated chapter structure, this now refers to 6.2.4 and 6.2.5

**Comment by rgstori** [comment]
yes, checked and existing as of now: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter06.md#624-multiple-network-interfaces-on-pods
