### ISSUE TITLE
[RA2] Ch5 - runtime security

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#994]
From deep dive in Prague:
Runtime Security
More guidance for operator-choice tooling
Maybe move to TUG whitepapers over time

**Comment by rgstori** [comment]
@tomkivlin do you reckon this is addressed in https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter05.md#511--run-time-security ? Can this be closed? Thanks

**Comment by tomkivlin** [comment]
For me, yes - I think that is enough guidance for Anuket to provide.

**Comment by rgstori** [comment]
perfect, thank you! closing
