### ISSUE TITLE
[RA2] Ch6 - container registries

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#996]
From deep dive in Prague:
Container Registries
Need to work out what, if anything, the registry does to help a CNF pass the RC tests [and then modify the chapter]

**Comment by xmulligan** [comment]
Is this any different than #946 ?
Are we looking for a generic Artefact Repository or a more specific container registry?

**Comment by tomkivlin** [comment]
@xmulligan - no, I think the Issue you've started covers it - sorry, I did a very simple import of Prague notes with no deduplication on my end 🙃.  I'll close this and add the notes to #946
