### ISSUE TITLE
[RA2] Ch6 - capitalise Kubernetes

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#997]
From deep dive in Prague:
6.14
Capitalise kubernetes -> Kubernetes

**Comment by CsatariGergely** [comment]
Will work on this with @EditKoselak.

**Comment by EditKoselak** [comment]
We didn't find anything to correct in RA2 Ch6, but we checked the rest of the chapters and found several instances in the appendix.
#2292 corrects the following in the Appendix:
kubernetes -> Kubernetes
Kubernetes cluster -> Kubernetes Cluster
Kubernetes namespace -> Kubernetes Namespace

**Comment by EditKoselak** [comment]
#2292 
+ Kubernetes corrected in RA2 Ch4
