### ISSUE TITLE
[RA2] Ch6 - Add in NIST specs

### ISSUE THREAD

**Issue by tomkivlin** [cntt-n/CNTT#998]
From deep dive in Prague:
6.14
Add in NIST (800-190) specifications

**Comment by pgoyal01** [comment]
@tomkivlin Are the non-US companies OK with incorporating NIST requirements? I have been working with some others on creating the RM Security Ch07 requirements and hence the ask.

**Comment by tomkivlin** [comment]
> @tomkivlin Are the non-US companies OK with incorporating NIST requirements? I have been working with some others on creating the RM Security Ch07 requirements and hence the ask.

When it was discussed in the deep dive there was no concern raised and plenty of non-US firms were there - European, Asian - so I'd consider that a low risk.  I think the key is to incorporate the requirements from NIST / CIS / whomever else that work and not create a hard link to that particular standards body unless there is widespread agreement to do so.
